-- Staging-only controlled-import contract tests. All fixture records roll back.
begin;
select set_config('request.jwt.claim.sub','b6ee4db2-0f37-4b3e-a3ee-fa804ec5e6cd',true);
do $$
declare c uuid; c2 uuid; blocked uuid; baseline uuid; published uuid; req uuid:=gen_random_uuid();
 pdf text:=encode(convert_to('%PDF-1.7 QA ONLY controlled import rollback fixture','UTF8'),'base64');
 rows jsonb; v jsonb; decisions jsonb; revision integer; events integer; h1 uuid; h2 uuid; h3 uuid; denied boolean;
begin
 c:=public.payroll_holiday_candidate_capture(2097,'qa:synthetic','QA ONLY rollback baseline','qa.pdf',pdf,req,true);
 if public.payroll_holiday_candidate_capture(2097,'qa:synthetic','QA ONLY rollback baseline','qa.pdf',pdf,req,true)<>c then raise exception 'capture retry failed'; end if;
 if (select count(*) from public.payroll_holiday_import_events where candidate_id=c)<>1 then raise exception 'duplicate capture event'; end if;
 if (select source_sha256 from public.payroll_holiday_import_candidates where id=c)<>encode(extensions.digest(decode(pdf,'base64'),'sha256'),'hex') then raise exception 'server hash mismatch'; end if;
 denied:=false;
 begin perform public.payroll_holiday_candidate_capture(2097,'qa:synthetic','QA ONLY changed payload','qa.pdf',pdf,req,true); exception when others then denied:=true; end;
 if not denied then raise exception 'changed retry accepted'; end if;
 denied:=false;
 begin perform public.payroll_holiday_candidate_capture(2097,'https://unofficial.example/calendar','Unverified','qa.pdf',pdf,gen_random_uuid(),false); exception when others then denied:=true; end;
 if not denied then raise exception 'unofficial authority accepted'; end if;
 rows:='[{"date":"2097-01-10","name":"QA ONLY National","scope":"national","source_locator":"page 1 row 1"},{"date":"2097-01-11","name":"QA ONLY Perak","scope":"state","state_code":"MY-08","source_locator":"page 1 row 2"},{"date":"2097-01-12","name":"QA ONLY Selangor","scope":"state","state_code":"MY-10","source_locator":"page 1 row 3"}]';
 perform public.payroll_holiday_candidate_parse(c,rows);
 select ic.revision, (select jsonb_object_agg(value->>'key',jsonb_build_object('action','accept')) from jsonb_array_elements(ic.rows)) into revision,decisions from public.payroll_holiday_import_candidates ic where id=c;
 if (select count(*) from jsonb_array_elements((select ic.rows from public.payroll_holiday_import_candidates ic where id=c)) r where r->>'state'='new' and r->'row'->>'kind'='gazetted')<>3 then raise exception 'normalization/required inference failed'; end if;
 perform public.payroll_holiday_candidate_review(c,revision,decisions,true);
 select ic.revision into revision from public.payroll_holiday_import_candidates ic where id=c;
 baseline:=public.payroll_holiday_candidate_publish(c,revision);
 if public.payroll_holiday_candidate_publish(c,revision)<>baseline then raise exception 'publish retry failed'; end if;
 if (select count(*) from public.payroll_holiday_import_events where candidate_id=c and event_type='published')<>1 then raise exception 'duplicate publish'; end if;
 select (entries->0->>'holiday_id')::uuid,(entries->1->>'holiday_id')::uuid,(entries->2->>'holiday_id')::uuid into h1,h2,h3 from public.payroll_holiday_calendar_versions where id=baseline;
 c2:=public.payroll_holiday_candidate_capture(2097,'qa:synthetic','QA ONLY correction','qa.pdf',pdf,gen_random_uuid(),true);
 rows:=jsonb_build_array(jsonb_build_object('date','2097-01-10','name','QA ONLY National','scope','national','source_locator','page 1'),jsonb_build_object('date','2097-01-13','name','QA ONLY Perak','scope','state','state_code','MY-08','previous_holiday_id',h2,'source_locator','page 2'),jsonb_build_object('date','2097-01-14','name','QA ONLY New','scope','national','source_locator','page 3'));
 perform public.payroll_holiday_candidate_parse(c2,rows);
 select ic.rows,ic.revision into v,revision from public.payroll_holiday_import_candidates ic where id=c2;
 if (select count(distinct value->>'state') from jsonb_array_elements(v))<>4 then raise exception 'expected matched/changed/new/missing'; end if;
 decisions:='{"2":{"action":"accept","remark":"QA source correction"},"3":{"action":"accept"},"4":{"action":"retain"}}';
 denied:=false;
 begin perform public.payroll_holiday_candidate_review(c2,revision-1,decisions,true); exception when serialization_failure then denied:=true; end;
 if not denied then raise exception 'stale review accepted'; end if;
 perform public.payroll_holiday_candidate_review(c2,revision,decisions,true);
 select ic.revision into revision from public.payroll_holiday_import_candidates ic where id=c2;
 published:=public.payroll_holiday_candidate_publish(c2,revision);
 if not exists(select 1 from jsonb_array_elements((select entries from public.payroll_holiday_calendar_versions where id=published)) r where r->>'holiday_id'=h3::text) then raise exception 'missing previous record deleted'; end if;
 if (select jsonb_array_length(entries) from public.payroll_holiday_calendar_versions where id=baseline)<>3 then raise exception 'original calendar changed'; end if;
 blocked:=public.payroll_holiday_candidate_capture(2097,'qa:synthetic','QA ONLY uncertainty','qa.pdf',pdf,gen_random_uuid(),true);
 perform public.payroll_holiday_candidate_parse(blocked,'[{"date":"2097-03-01","name":"Uncertain","scope":"state","state_code":"UNKNOWN","kind":"required","source_locator":"p1"}]');
 select ic.revision into revision from public.payroll_holiday_import_candidates ic where id=blocked;
 denied:=false;
 begin perform public.payroll_holiday_candidate_review(blocked,revision,'{}',true); exception when others then denied:=true; end;
 if not denied then raise exception 'blocked import approved'; end if;
 if exists(select 1 from jsonb_array_elements(public.payroll_holiday_candidate_read(2097,false)) r where r->>'id'=c::text) then raise exception 'QA leaked into operational read'; end if;
 if has_table_privilege('authenticated','public.payroll_holiday_import_candidates','SELECT') or has_table_privilege('authenticated','public.payroll_holiday_import_candidates','UPDATE') or has_function_privilege('anon','public.payroll_holiday_candidate_publish(uuid,integer)','EXECUTE') then raise exception 'public/direct authority leak'; end if;
 perform set_config('request.jwt.claim.sub','',true);
 denied:=false;
 begin perform public.payroll_holiday_candidate_read(2097,true); exception when others then denied:=true; end;
 if not denied then raise exception 'anonymous read accepted'; end if;
 raise notice 'CONTROLLED IMPORT CONTRACTS PASS';
end $$;
rollback;
