// Uses the production renderer; fixture-only outputs under /private/tmp.
import { createRequire } from 'node:module';
import { writeFile, readFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
import { renderPayslip } from '../../supabase/functions/payroll-payslips/render.js';
import { loadPayslipFonts, requiredFontShards } from '../../supabase/functions/payroll-payslips/fonts/load.js';
const require = createRequire('/private/tmp/feedx-payroll-pdf-test/package.json');
const { PDFDocument, StandardFonts, rgb } = require('pdf-lib');
const fontkit = require('@pdf-lib/fontkit');
const base = { identity:{employer:'QA ONLY FeedX Payslip Design',registration:'QA-P5-20260927',employee_name:'QA ONLY Phase 5 Monthly',employee_code:'QA-P5-1',position:'Restaurant Supervisor',workplace:'QA ONLY Phase 5 Workplace'},pay_basis:'monthly',period_start:'2026-06-01',period_end:'2026-06-30',finalized_at:'2026-09-27T08:07:47.180031+00:00',earnings:[{label:'Basic Salary',amount:3250},{label:'Transport Allowance',amount:100}],deductions:[],reimbursements:[],gross_earnings:3350,net_pay:2918.25,statutory:[{scheme:'epf',applicable:true,amount:359,employer_amount:424},{scheme:'socso',applicable:true,amount:16.25,employer_amount:56.85},{scheme:'eis',applicable:true,amount:6.5,employer_amount:6.5},{scheme:'pcb',applicable:true,amount:50}]};
base.identity.employer_address='QA ONLY · 12 Jalan Contoh, 30000 Ipoh, Perak, Malaysia';
base.identity.ic_passport='900101-08-1234';
const api={PDFDocument,StandardFonts,rgb,fontkit};
const fonts = manifest => loadPayslipFonts(manifest, async path => new Blob([await readFile(new URL(`../../supabase/functions/payroll-payslips/fonts/prepared/${path.split('/').at(-1)}`,import.meta.url))]));
const render = async manifest => renderPayslip(manifest,{...api,unicodeFonts:await fonts(manifest)});
const monthly=await render(base);
assert.deepEqual(monthly,await render(base),'Deterministic retry bytes');
const hourly={...base,pay_basis:'hourly',identity:{...base.identity,employee_name:'QA ONLY Phase 5 Hourly',employee_code:'QA-P5-2'},earnings:[{label:'Regular Hourly Pay',amount:75,minutes:450,rate:10}],gross_earnings:75,net_pay:65.4,statutory:[{scheme:'epf',applicable:true,amount:9},{scheme:'socso',applicable:true,amount:.4},{scheme:'eis',applicable:true,amount:.2},{scheme:'pcb',applicable:false,amount:0}]};
await writeFile('/private/tmp/feedx-phase5-monthly.pdf',monthly);
await writeFile('/private/tmp/feedx-phase5-hourly.pdf',await render(hourly));
await writeFile('/private/tmp/feedx-phase5-draft.pdf',await render({...base,draft:true}));
const unicode={...base,draft:true,identity:{...base.identity,employer:'QA ONLY 冷启动有限公司',employee_name:'QA ONLY 陈伟明 · 长名称测试'},earnings:Array.from({length:40},(_,i)=>({label:`津贴 ${i} · Long financial line wrapping verification`,amount:1}))};
const started=performance.now();
const bytes=await render(unicode);
assert.deepEqual(bytes,await render(unicode));
assert.ok(bytes.length<1000000,'Expanded Unicode identity PDF comfortably below 5 MiB');
assert.throws(()=>requiredFontShards({...base,identity:{...base.identity,employee_name:'Unsupported 🦄'}}),/not supported/,'Never silently drop unsupported source-font glyphs');
assert.ok((await PDFDocument.load(bytes)).getPageCount()>1,'Long statement pagination');
await writeFile('/private/tmp/feedx-phase5-unicode.pdf',bytes);
console.log(`Monthly/Hourly A4, deterministic retry and Unicode pagination PASS: ${bytes.length} bytes; two Unicode renders ${Math.round(performance.now()-started)} ms`);
