-- Read-only legal pricing -> shared Draft/Final renderer manifest contract.
with context as(select jsonb_build_object('date','2026-09-16','period_start','2026-09-01','period_end','2026-09-30','employee_age_verified',true,'preceding_employer_verified',true,
 'paid_holiday',jsonb_build_object('outlet_state_code','MY-08'),'compensation',jsonb_build_object('id','qa-ph-hourly','pay_basis','hourly'),
 'source',jsonb_build_object('source_fingerprint','QA'),'time',jsonb_build_object('id','qa-time','status','approved_manual','classification','public_holiday','source_fingerprint','QA','approved_minutes',480,'approved_extra_minutes',60),
 'company_policy',null,'rules',(select jsonb_agg(to_jsonb(v)) from payroll_pay_rule_versions v where formula_version='my_ph_2023_v1' and pay_basis='hourly')) c),
 priced as(select payroll_ph_statutory_price(c,'{"coverage":"full_time","schedule_category":"general","schedule_monthly_wages":2600,"normal_minutes":480,"holiday_eligibility":"eligible","preceding_period_start":"2026-08-01","preceding_period_end":"2026-08-31","preceding_qualifying_wages":1600,"preceding_worked_days":20}') p from context),
 calc as(select jsonb_build_object('pay_basis','hourly','gross_earnings',(select sum((x->>'amount')::numeric)*2 from jsonb_array_elements(p->'lines') x)+90,'non_statutory_deductions',0,
 'lines',(p->'lines')||(p->'lines')||'[{"kind":"earning","code":"regular","minutes":300,"rate_per_minute":0.15,"multiplier":1,"amount":45,"source":{"compensation_version_id":"qa-regular","rule_version_id":"qa-regular"}},{"kind":"earning","code":"regular","minutes":300,"rate_per_minute":0.15,"multiplier":1,"amount":45,"source":{"compensation_version_id":"qa-regular","rule_version_id":"qa-regular"}}]'::jsonb) c from priced)
select jsonb_build_object('draft',payroll_payslip_document('{"employer":"QA ONLY","employee_name":"QA ONLY PH 陈"}','2026-09-01','2026-09-30',null,c,jsonb_build_object('net_pay',(c->>'gross_earnings')::numeric,'lines','[]'::jsonb),true),
 'final',payroll_payslip_document('{"employer":"QA ONLY","employee_name":"QA ONLY PH 陈"}','2026-09-01','2026-09-30','2026-10-04T00:00:00Z',c,jsonb_build_object('net_pay',(c->>'gross_earnings')::numeric,'lines','[]'::jsonb),false)) manifest from calc;
