-- Disposable/local or rollback-only Staging contract verification. No durable fixtures.
begin;
create function pg_temp.assert(ok boolean, message text) returns void language plpgsql as $$ begin if ok is distinct from true then raise exception '%',message; end if; end $$;
do $$
declare opening uuid:=gen_random_uuid(); config uuid:=gen_random_uuid(); applicant uuid:=gen_random_uuid(); application uuid:=gen_random_uuid(); invitation uuid:=gen_random_uuid(); attempt uuid:=gen_random_uuid(); actor uuid:=gen_random_uuid(); client uuid:=gen_random_uuid(); unit uuid:=gen_random_uuid(); lost uuid:=gen_random_uuid(); token text:=repeat('a',64); result jsonb; first_result jsonb; request_one uuid:=gen_random_uuid(); request_two uuid:=gen_random_uuid(); gap_count integer; deadline timestamptz;
begin
  -- Canonical master references are placeholders ONLY inside this rolled-back fixture.
  set local session_replication_role=replica;
  insert into employees(id,full_name) values(actor,'Synthetic rollback QA');
  insert into recruitment_openings(id,title,position_id,workplace,legal_entity_id,status,created_by,updated_by) values(opening,'QA Phase 2 rollback',gen_random_uuid(),'Management',gen_random_uuid(),'open',actor,actor);
  insert into recruitment_interview_configs(id,opening_id,version,required_topics,scenario_briefs,target_minutes,max_minutes,created_by) values(config,opening,1,'["Customer service evidence"]','["Handle a missing order"]',5,5,actor);
  insert into recruitment_applicants(id,full_name,contact,created_by) values(applicant,'Synthetic QA','00000',actor);
  insert into recruitment_applications(id,applicant_id,opening_id,opening_title_snapshot,opening_description_snapshot,position_snapshot,workplace_snapshot,legal_entity_snapshot,created_by) values(application,applicant,opening,'QA','','QA','Management','QA',actor);
  insert into recruitment_invitations(id,application_id,token_hash,expires_at,issued_by) values(invitation,application,encode(extensions.digest(token,'sha256'),'hex'),clock_timestamp()+interval '1 hour',actor);
  insert into recruitment_interview_attempts(id,invitation_id,application_id,opening_id,config_version_id,status) values(attempt,invitation,application,opening,config,'ready');
  insert into recruitment_consents(attempt_id,application_id,copy_version,copy_snapshot,accepted_purposes) values(attempt,application,'qa','{}','{}');
  set local session_replication_role=origin;
  result:=recruitment_recovery_state(token,client);
  perform pg_temp.assert(result->>'state'='RECOVERY_REQUIRED','Ready bootstrap not recoverable');
  first_result:=recruitment_recovery_begin(token,client,request_one,null);
  result:=recruitment_recovery_begin(token,client,request_one,null);
  perform pg_temp.assert(result=first_result,'Resume request retry changed result');
  perform pg_temp.assert((select recovery_id=request_one from recruitment_interview_attempts where id=attempt),'Recovery owner not stored');
  perform recruitment_recording_access(token,client,'open',jsonb_build_object('unit_id',unit,'recovery_id',request_one));
  result:=recruitment_recovery_context(token,client,request_one);
  perform recruitment_recovery_connected(token,client,request_one,1);
  perform recruitment_public_transcript_turn(token,client,1,1,'candidate-item','candidate','I handled café orders and checked missing meals.',0,1000);
  perform recruitment_apply_coverage(token,client,'{"topics":[{"index":0,"turn_number":1}],"scenarios":[]}');
  perform recruitment_recovery_pause(token,client,request_one,'media_track_muted');
  perform recruitment_recovery_pause(token,client,request_one,'page_backgrounded');
  perform pg_temp.assert((select count(*)=1 from recruitment_events where attempt_id=attempt and action='recording_gap'),'Repeated pause duplicates gap');
  update recruitment_interview_attempts set paused_at=clock_timestamp()-interval '20 minutes',max_ends_at=clock_timestamp()-interval '15 minutes',lease_expires_at=clock_timestamp()-interval '19 minutes' where id=attempt;
  result:=recruitment_recovery_state(token,client);
  perform pg_temp.assert((result->>'remaining_seconds')::integer between 299 and 301,'Cold state lost paused remaining duration');
  result:=recruitment_recovery_begin(token,client,request_two,request_one);
  perform pg_temp.assert((result->>'max_ends_at')::timestamptz>clock_timestamp()+interval '4 minutes 55 seconds','Cold resume failed to restore active budget');
  deadline:=(result->>'max_ends_at')::timestamptz;
  perform pg_temp.assert((select count(*)=1 from recruitment_transcript_turns where attempt_id=attempt),'Cold resume lost transcript');
  perform pg_temp.assert((select state='covered' from recruitment_topic_coverage where attempt_id=attempt),'Cold resume lost coverage');
  select count(*) into gap_count from recruitment_events where attempt_id=attempt and action='recording_gap';
  perform recruitment_recovery_begin(token,client,request_two,request_one);
  perform pg_temp.assert((select count(*)=gap_count from recruitment_events where attempt_id=attempt and action='recording_gap'),'Duplicate resume generated gap');
  perform pg_temp.assert((select max_ends_at=deadline from recruitment_interview_attempts where id=attempt),'Duplicate resume extended budget');
  begin perform recruitment_recovery_begin(token,client,request_one,null); raise exception 'Late old resume accepted'; exception when serialization_failure then null; end;
  perform recruitment_recovery_pause(token,client,request_one,'late_close');
  perform pg_temp.assert((select paused_at is null from recruitment_interview_attempts where id=attempt),'Late old pause stopped new recovery');
  begin perform recruitment_recording_access(token,client,'open',jsonb_build_object('unit_id',gen_random_uuid(),'recovery_id',request_one)); raise exception 'Late old recording accepted'; exception when serialization_failure then null; end;
  begin perform recruitment_recovery_context(token,client,request_one); raise exception 'Late old provider accepted'; exception when serialization_failure then null; end;
  begin perform recruitment_recovery_connected(token,client,request_one,1); raise exception 'Late old connection accepted'; exception when serialization_failure then null; end;
  perform recruitment_recording_access(token,client,'open',jsonb_build_object('unit_id',lost,'recovery_id',request_two));
  perform pg_temp.assert((select count(*)=1 from recruitment_recording_units where attempt_id=attempt and status='capturing'),'Competing recorder ownership');
  perform pg_temp.assert((select status='interrupted' from recruitment_recording_units where id=unit),'Old recording was not truthfully interrupted');
  result:=recruitment_recovery_context(token,client,request_two);
  perform pg_temp.assert(result->>'generation'='2','Fresh recovery generation missing');
  perform pg_temp.assert(jsonb_array_length(result->'established_facts')=1,'Durable established facts missing');
  perform recruitment_recovery_connected(token,client,request_two,2);
  perform recruitment_recovery_observe(token,client,'bootstrap-test','{"type":"recovery.bootstrap","state":"RECOVERY_REQUIRED","stage":"server state"}');
  perform recruitment_recovery_observe(token,client,'bootstrap-test','{"type":"recovery.bootstrap","state":"RECOVERY_REQUIRED","stage":"server state"}');
  perform pg_temp.assert((select count(*)=1 from recruitment_realtime_traces where attempt_id=attempt),'Recovery trace retry not idempotent');
  begin perform recruitment_recovery_observe(token,client,'bad','{"type":"recovery.error","token":"secret"}'); raise exception 'Credentials allowed in diagnostics'; exception when invalid_parameter_value then null; end;
  perform pg_temp.assert(not has_function_privilege('anon','recruitment_recovery_context(text,uuid,uuid)','execute'),'Provider authority exposed');
  perform pg_temp.assert(not has_function_privilege('anon','recruitment_recording_access_before_recovery(text,uuid,text,jsonb)','execute'),'Old private recording helper exposed');
  perform pg_temp.assert(not has_table_privilege('anon','recruitment_realtime_traces','select'),'Raw trace data exposed');
  update recruitment_invitations set revoked_at=clock_timestamp() where id=invitation;
  result:=recruitment_recovery_state(token,client);
  perform pg_temp.assert(result->>'state'='TERMINAL','Revocation did not produce terminal explanation');
  raise notice 'Cold bootstrap, active time, same attempt, idempotent resume, stale ownership fencing and recovery diagnostics passed';
end $$;
rollback;
