-- Staging-only synthetic contract verification; all fixtures roll back.
begin;
create function pg_temp.assert(ok boolean,message text) returns void language plpgsql as $$begin if ok is distinct from true then raise exception '%',message;end if;end$$;
do $$
declare actor uuid; identity uuid; profile recruitment_interview_profiles%rowtype; revised uuid; op uuid; cfg uuid; payload jsonb; app uuid; token text; attempt uuid; client uuid:=gen_random_uuid(); person uuid; result jsonb; tid bigint; ai bigint; v1 uuid; entity uuid; position uuid; scoped uuid; i integer;
begin
 select e.id,e.auth_user_id into actor,identity from employees e join roles r on r.id=e.role_id where r.name='owner' and e.is_active and e.enable_system_login and e.access_state='active' limit 1;
 if actor is null then raise exception 'Existing authorized Staging actor required';end if;
 perform set_config('request.jwt.claim.sub',identity::text,true);
 select * into profile from recruitment_interview_profiles where profile_key='service_crew' order by version desc limit 1;
 perform recruitment_validate_profile(profile.definition);
 begin update recruitment_interview_profiles set name='changed' where id=profile.id;raise exception 'Immutable profile changed';exception when object_not_in_prerequisite_state then null;end;
 begin perform recruitment_publish_profile(profile.definition||'{"completion_criteria":{"Core":"unresolved","Important":"partial","Optional":"unresolved"}}',profile.version);raise exception 'Invalid Core completion accepted';exception when invalid_parameter_value then null;end;
 revised:=recruitment_publish_profile(profile.definition||'{"role_context":"Revised Service Crew context for rollback QA only"}',profile.version);
 begin perform recruitment_publish_profile(profile.definition,profile.version);raise exception 'Concurrent stale publication accepted';exception when serialization_failure then null;end;
 select id into entity from legal_entities where is_active limit 1;
 select id into position from job_positions where status='active' limit 1;
 payload:=jsonb_build_object('title','QA Profile rollback','position_id',position,'workplace','Management','legal_entity_id',entity,'status','open','config',jsonb_build_object('interview_profile_id',profile.id,'opening_requirements',jsonb_build_object('weekend_required',true,'closing_shift','11pm','preferred_start','Within two weeks'),'required_topics','["Client invented topic"]'::jsonb,'scenario_briefs','[]'::jsonb,'target_minutes',5,'max_minutes',5));
 op:=recruitment_save_opening(payload);
 select id into cfg from recruitment_interview_configs where opening_id=op and version=1;
 perform pg_temp.assert((select interview_profile_id=profile.id and required_topics->>0='Customer Handling' and max_minutes=(profile.definition->>'max_minutes')::integer from recruitment_interview_configs where id=cfg),'Server did not derive pinned profile');
 app:=recruitment_register_application(op,jsonb_build_object('full_name','QA Profile Candidate','contact','QA-'||op),null);
 token:=recruitment_issue_invitation(app,clock_timestamp()+interval '1 day');
 select id into attempt from recruitment_public_attempt(token);
 perform recruitment_save_opening(payload||jsonb_build_object('id',op,'config',jsonb_build_object('interview_profile_id',revised,'opening_requirements','{}'::jsonb)));
 perform pg_temp.assert((select config_version_id=cfg from recruitment_interview_attempts where id=attempt),'Opening edit rewrote invited configuration');
 perform pg_temp.assert((select definition->>'role_context'=profile.definition->>'role_context' from recruitment_interview_profiles where id=profile.id),'Opening requirements mutated profile');
 update recruitment_interview_attempts set status='interviewing',lease_owner=client,lease_expires_at=clock_timestamp()+interval '45 seconds',interview_started_at=clock_timestamp(),max_ends_at=clock_timestamp()+interval '15 minutes' where id=attempt;
 insert into recruitment_topic_coverage(attempt_id,topic_index,topic) select attempt,ordinality-1,value#>>'{}' from jsonb_array_elements((select required_topics from recruitment_interview_configs where id=cfg)) with ordinality;
 insert into recruitment_scenario_progress(attempt_id,scenario_index,brief) select attempt,ordinality-1,value#>>'{}' from jsonb_array_elements((select scenario_briefs from recruitment_interview_configs where id=cfg)) with ordinality;
 insert into recruitment_transcript_turns(attempt_id,provider_generation,provider_item_id,speaker,transcript,turn_number,elapsed_end_ms) values(attempt,1,'candidate-1','candidate','I have some customer experience.',1,1000) returning id into tid;
 result:=recruitment_apply_coverage(token,client,'{"topics":[{"index":0,"state":"partial","turn_number":1,"reason":"Relevant experience, no concrete customer example yet"}],"scenarios":[]}');
 perform pg_temp.assert((select state='partial' and evidence_turn_id=tid from recruitment_topic_coverage where attempt_id=attempt and topic_index=0),'Partial citation not durable');
 perform pg_temp.assert(not (result->>'can_finish')::boolean,'Partial Core allowed completion');
 begin perform recruitment_public_finish(token,client,'coverage');raise exception 'Partial completion bypassed';exception when object_not_in_prerequisite_state then null;end;
 result:=recruitment_apply_coverage(token,client,'{"topics":[{"index":0,"state":"covered","turn_number":999,"reason":"Missing citation"}],"scenarios":[]}');
 perform pg_temp.assert((select state='partial' from recruitment_topic_coverage where attempt_id=attempt and topic_index=0),'Missing citation advanced coverage');
 insert into recruitment_transcript_turns(attempt_id,provider_generation,provider_item_id,speaker,transcript,turn_number,elapsed_end_ms) values(attempt,1,'ai-2','ai','A customer complains food is taking too long. What would you do?',2,2000) returning id into ai;
 result:=recruitment_apply_coverage(token,client,'{"topics":[{"index":0,"state":"covered","turn_number":2,"reason":"AI is not candidate evidence"}],"scenarios":[{"index":0,"state":"answered","turn_number":1}]}');
 perform pg_temp.assert((select state='partial' from recruitment_topic_coverage where attempt_id=attempt and topic_index=0),'AI citation advanced coverage');
 perform pg_temp.assert((select state='pending' from recruitment_scenario_progress where attempt_id=attempt and scenario_index=0),'Unasked scenario completed');
 insert into recruitment_transcript_turns(attempt_id,provider_generation,provider_item_id,speaker,transcript,turn_number,elapsed_end_ms) values(attempt,1,'candidate-3','candidate','I listened to a complaint, checked with kitchen and gave an honest update. I can start 15 October, work weekends and close at 11pm. I helped a teammate carry orders.',3,3000) returning id into tid;
 perform recruitment_apply_coverage(token,client,'{"topics":[{"index":0,"state":"partial","turn_number":3,"reason":"Newer supporting example"}],"scenarios":[]}');
 perform pg_temp.assert((select state='partial' and evidence_turn_id=tid from recruitment_topic_coverage where attempt_id=attempt and topic_index=0),'Same-state newer citation did not refresh continuation facts');
 perform recruitment_apply_coverage(token,client,'{"topics":[{"index":0,"state":"partial","turn_number":1,"reason":"Earlier evidence must not replace current facts"}],"scenarios":[]}');
 perform pg_temp.assert((select state='partial' and evidence_turn_id=tid from recruitment_topic_coverage where attempt_id=attempt and topic_index=0),'Older same-state citation replaced current facts');
 result:=recruitment_apply_coverage(token,client,'{"topics":[{"index":0,"state":"covered","turn_number":3,"reason":"Concrete complaint handling"},{"index":1,"state":"covered","turn_number":3,"reason":"Specific start date"},{"index":2,"state":"covered","turn_number":3,"reason":"Weekend and closing availability"},{"index":3,"state":"partial","turn_number":3,"reason":"Transferable experience without detailed responsibilities"},{"index":4,"state":"partial","turn_number":3,"reason":"Relevant teamwork example, limited detail"}],"scenarios":[{"index":0,"state":"asked","turn_number":2},{"index":0,"state":"answered","turn_number":3}]}');
 perform pg_temp.assert((result->>'coverage_complete')::boolean,'Core Covered / Important Partial + scenario did not satisfy profile criteria');
 perform recruitment_apply_coverage(token,client,'{"topics":[{"index":0,"state":"partial","turn_number":1,"reason":"Earlier incomplete example"}],"scenarios":[]}');
 perform pg_temp.assert((select state='covered' and evidence_turn_id=tid from recruitment_topic_coverage where attempt_id=attempt and topic_index=0),'Coverage regressed');
 perform pg_temp.assert((select count(*)>=6 from recruitment_coverage_findings where attempt_id=attempt),'Material findings not retained');
 begin update recruitment_coverage_findings set reason='changed' where attempt_id=attempt;raise exception 'Finding changed';exception when object_not_in_prerequisite_state then null;end;
 result:=recruitment_assessment_context(token,client);
 perform pg_temp.assert(result->'interview_profile'->>'version'=profile.version::text and result->'opening_requirements'->>'closing_shift'='11pm','Runtime context lost pinned plan/requirements');
 result:=recruitment_workspace(op,'all',1,true);
 perform pg_temp.assert((result->>'applications_total')::integer=1 and result->'applications'->0->>'stage'='interviewing','Opening workspace pagination/stage incorrect');
 perform pg_temp.assert(not exists(select 1 from jsonb_array_elements(recruitment_workspace()->'openings') where value->>'id'=op::text),'Default view exposes QA opening');
 result:=recruitment_admin_evidence(app,attempt);
 perform pg_temp.assert(jsonb_array_length(result->'coverage_findings')>=6 and result->'interview_profile'->>'version'=profile.version::text,'Manager evidence lost citations/profile');
 perform recruitment_public_finish(token,client,'coverage');
 perform pg_temp.assert((select status='finalizing' from recruitment_interview_attempts where id=attempt),'Completion failed');
 -- Check immutable report consumer still captures canonical config and Partial state without report/hiring mutations.
 update recruitment_interview_attempts set status='partial',recording_state='partial' where id=attempt;
 result:=recruitment_report_source(attempt);
 perform pg_temp.assert(result->'config'->>'interview_profile_id'=profile.id::text,'Report source lost profile version');
 perform pg_temp.assert(exists(select 1 from jsonb_array_elements(result->'topics') where value->>'state'='partial'),'Report source lost Partial evidence');
 -- Counts and pagination are over the complete opening pipeline, not the current page.
 for i in 1..21 loop perform recruitment_register_application(op,jsonb_build_object('full_name','QA Page '||i,'contact','QA-'||left(op::text,16)||'-'||i),null); end loop;
 result:=recruitment_workspace(op,'all',2,true);
 perform pg_temp.assert((result->>'applications_total')::integer=22 and jsonb_array_length(result->'applications')=2,'Opening pagination counts only a page');
 result:=recruitment_workspace(op,'needs_review',1,true);
 perform pg_temp.assert((result->>'applications_total')::integer=1 and result->'applications'->0->>'id'=app::text,'Stage filter not server-owned');
 select e.auth_user_id into scoped from employees e join roles r on r.id=e.role_id where r.name='manager' and e.enable_system_login and e.access_state='active' and e.is_active limit 1;
 if scoped is null then raise exception 'Existing permission-denied Staging actor required';end if;
 perform set_config('request.jwt.claim.sub',scoped::text,true);
 perform pg_temp.assert(not current_user_has_permission('recruitment.manage') and not current_user_has_permission('recruitment.view'),'Expected restricted actor');
 begin perform recruitment_workspace(op,'all',1,true);raise exception 'Unauthorized workspace read';exception when insufficient_privilege then null;end;
 begin perform recruitment_publish_profile(profile.definition,profile.version);raise exception 'Unauthorized profile publish';exception when insufficient_privilege then null;end;
 select e.auth_user_id into scoped from employees e join roles r on r.id=e.role_id where r.name='factory_read_only_test' and e.enable_system_login and e.access_state='active' and e.is_active limit 1;
 if scoped is null then raise exception 'Existing scoped Staging actor required';end if;
 perform set_config('request.jwt.claim.sub',scoped::text,true);
 perform pg_temp.assert(exists(select 1 from outlets where not recruitment_opening_in_scope(id)),'Scoped actor unexpectedly sees all outlets');
 perform set_config('request.jwt.claim.sub','',true);
 begin perform recruitment_workspace();raise exception 'Anonymous read accepted';exception when insufficient_privilege then null;end;
 begin perform recruitment_publish_profile(profile.definition,profile.version);raise exception 'Anonymous publication accepted';exception when insufficient_privilege then null;end;
 perform pg_temp.assert(not has_function_privilege('anon','recruitment_workspace(uuid,text,integer,boolean)','EXECUTE'),'Anonymous workspace grant');
 perform pg_temp.assert(not has_table_privilege('authenticated','recruitment_interview_profiles','INSERT'),'Direct profile writes allowed');
 perform pg_temp.assert(not has_table_privilege('authenticated','recruitment_coverage_findings','UPDATE'),'Direct evidence updates allowed');
 raise notice 'Profile pinning/publication/concurrency, Partial citations, completion authority, workspace and evidence compatibility PASS';
end$$;
rollback;
