begin;
create function pg_temp.assert(ok boolean,message text) returns void language plpgsql as $$begin if ok is distinct from true then raise exception '%',message; end if; end$$;
do $$
declare actor uuid; identity uuid; op uuid:=gen_random_uuid(); position_id uuid:=gen_random_uuid(); entity uuid:=gen_random_uuid(); person uuid:=gen_random_uuid(); app uuid:=gen_random_uuid(); app2 uuid:=gen_random_uuid(); op2 uuid:=gen_random_uuid(); invitation uuid:=gen_random_uuid(); attempt uuid:=gen_random_uuid(); config uuid:=gen_random_uuid(); report uuid; report2 uuid; request uuid:=gen_random_uuid(); result jsonb; claim jsonb; payload jsonb; employee uuid; anonymous_denied boolean:=false;
begin
 select e.id,e.auth_user_id into actor,identity from employees e join roles r on r.id=e.role_id where r.name='owner' and e.enable_system_login and e.access_state='active' and e.is_active limit 1;
 if actor is null then raise exception 'Existing authorized test actor required.'; end if;
 perform set_config('request.jwt.claim.sub',identity::text,true);
 perform set_config('request.jwt.claims',jsonb_build_object('sub',identity,'role','authenticated')::text,true);
 insert into job_positions(id,name,department) values(position_id,'QA Phase3 rollback '||op,'QA');
 insert into legal_entities(id,legal_company_name,company_registration_no,registered_address,created_by_employee_id,updated_by_employee_id) values(entity,'QA Phase3 rollback',op::text,'QA ONLY',actor,actor);
 insert into recruitment_openings(id,title,position_id,workplace,legal_entity_id,status,created_by,updated_by) values(op,'QA Phase3 rollback',position_id,'Management',entity,'open',actor,actor);
 insert into recruitment_interview_configs(id,opening_id,version,required_topics,scenario_briefs,target_minutes,max_minutes,created_by) values(config,op,1,'["Experience"]','[]',5,5,actor);
 insert into recruitment_applicants(id,full_name,contact,created_by) values(person,'QA Phase3 '||person,'QA-'||person,actor);
 insert into recruitment_applications(id,applicant_id,opening_id,opening_title_snapshot,opening_description_snapshot,position_snapshot,workplace_snapshot,legal_entity_snapshot,created_by) values(app,person,op,'QA','','QA','Management','QA',actor);
 insert into recruitment_invitations(id,application_id,token_hash,expires_at,issued_by) values(invitation,app,encode(extensions.digest(repeat(replace(op::text,'-',''),2),'sha256'),'hex'),clock_timestamp()+interval '1 hour',actor);
 insert into recruitment_interview_attempts(id,invitation_id,application_id,opening_id,config_version_id,status,recording_state) values(attempt,invitation,app,op,config,'partial','partial');
 insert into recruitment_transcript_turns(attempt_id,provider_generation,provider_item_id,speaker,transcript,turn_number,elapsed_end_ms) values(attempt,1,'qa-item','candidate','I worked in a café.',1,1000);
 -- Service finalization must enqueue the pinned report atomically, even for failed recording.
 update recruitment_interview_attempts set status='finalizing',lease_owner=request,lease_expires_at=clock_timestamp()+interval '45 seconds',interview_started_at=clock_timestamp()-interval '5 seconds',interview_ended_at=clock_timestamp(),completion_reason='candidate_stop' where id=attempt;
 result:=recruitment_finalize(repeat(replace(op::text,'-',''),2),request);
 report:=(result->>'report_id')::uuid;
 perform pg_temp.assert(result->>'status'='failed' and report is not null,'Finalization did not enqueue report');
 perform pg_temp.assert((select source_snapshot->'attempt'->>'status'='failed' and status='queued' from recruitment_reports where id=report),'Report did not pin finalized evidence');
 perform pg_temp.assert(report=recruitment_report_prepare(app,request),'Manager recovery duplicated auto-enqueued report');
 perform pg_temp.assert(report=recruitment_report_prepare(app,gen_random_uuid()),'Automatic report replaced existing version');
 claim:=recruitment_report_claim(report);
 perform pg_temp.assert(recruitment_report_claim(report)->>'status'='generating','Concurrent generation obtained lease');
 update recruitment_reports set lease_until=clock_timestamp()-interval '1 second' where id=report;
 payload:=recruitment_report_claim(report);
 begin perform recruitment_report_finish(report,(claim->>'generation_id')::uuid,'{}',null,null); raise exception 'Expired worker published'; exception when serialization_failure then null; end;
 claim:=payload;
 perform recruitment_report_finish(report,(claim->>'generation_id')::uuid,'{"candidate_snapshot":[]}',null,null);
 perform recruitment_report_review(report);
 begin update recruitment_reports set body='{}' where id=report; raise exception 'Reviewed report changed'; exception when object_not_in_prerequisite_state then null; end;
 report2:=recruitment_report_prepare(app,gen_random_uuid(),true);
 perform pg_temp.assert((select version=2 and source_hash=(select source_hash from recruitment_reports where id=report) from recruitment_reports where id=report2),'New report lost reproducible source');
 begin perform recruitment_decide(app,gen_random_uuid(),'review','hired');raise exception 'Direct Hire skipped shortlist';exception when object_not_in_prerequisite_state then null;end;
 result:=recruitment_decide(app,gen_random_uuid(),'review','shortlisted','',null,report);
 perform pg_temp.assert(result->>'state'='shortlisted','Partial evidence blocked shortlist');
 payload:=jsonb_build_object('full_name','QA Phase3 Hired '||person,'contact','QA-'||person,'nationality','QA','employment_type','probation','joined_date',timezone('Asia/Kuala_Lumpur',clock_timestamp())::date);
 request:=gen_random_uuid();
 result:=recruitment_decide(app,request,'shortlisted','hired','QA only',payload,report);employee:=(result->>'employee_id')::uuid;
 perform pg_temp.assert(recruitment_decide(app,request,'shortlisted','hired','QA only',payload,report)=result,'Identical Hire retry changed result');
 perform pg_temp.assert((select count(*)=1 from employee_employment_assignment_revisions where employee_id=employee and source_kind='new_employee'),'Hire missed canonical People baseline');
 perform pg_temp.assert((select legal_entity_id=entity and workplace='Management' and not enable_system_login and auth_user_id is null and role_id is null and access_state='no_access' from employees where id=employee),'Hire created access or wrong assignment');
 begin perform recruitment_decide(app,request,'shortlisted','hired','Changed',payload,report);raise exception 'Changed Hire retry accepted';exception when invalid_parameter_value then null;end;
 begin perform recruitment_issue_invitation(app,clock_timestamp()+interval '1 hour');raise exception 'Hired applicant invited again';exception when raise_exception then if sqlerrm='Hired applicant invited again' then raise;end if;end;
 insert into recruitment_openings(id,title,position_id,workplace,legal_entity_id,status,created_by,updated_by) values(op2,'QA Phase3 second',position_id,'Management',entity,'open',actor,actor);
 insert into recruitment_applications(id,applicant_id,opening_id,opening_title_snapshot,opening_description_snapshot,position_snapshot,workplace_snapshot,legal_entity_snapshot,created_by) values(app2,person,op2,'QA','','QA','Management','QA',actor);
 begin perform recruitment_decide(app2,gen_random_uuid(),'review','shortlisted','',null,report);raise exception 'Foreign report attached to decision';exception when raise_exception then if sqlerrm='Foreign report attached to decision' then raise;end if;end;
 perform recruitment_decide(app2,gen_random_uuid(),'review','shortlisted');
 begin perform recruitment_decide(app2,gen_random_uuid(),'shortlisted','hired','',payload);raise exception 'Second application duplicated person';exception when unique_violation then null;end;
 perform recruitment_decide(app2,gen_random_uuid(),'shortlisted','final_interview');
 perform recruitment_decide(app2,gen_random_uuid(),'final_interview','rejected','QA rejection');
 begin perform recruitment_decide(app2,gen_random_uuid(),'rejected','shortlisted');raise exception 'Terminal rejection reopened';exception when object_not_in_prerequisite_state then null;end;
 perform set_config('request.jwt.claim.sub','',true);perform set_config('request.jwt.claims','{}',true);
 begin perform recruitment_decide(app,gen_random_uuid(),'hired','rejected');exception when insufficient_privilege then anonymous_denied:=true;end;
 perform pg_temp.assert(anonymous_denied,'Anonymous manager decision accepted');
 perform pg_temp.assert(not has_function_privilege('anon','public.recruitment_decide(uuid,uuid,text,text,text,jsonb,uuid)','EXECUTE'),'Anonymous decision RPC exposed');
 perform pg_temp.assert(not has_function_privilege('authenticated','public.recruitment_report_finish(uuid,uuid,jsonb,text,text)','EXECUTE'),'Client can publish AI report');
 raise notice 'Phase3 report immutability/versions, all decisions, exact-once canonical Hire and denied anonymous mutations passed';
end$$;
rollback;
