-- Staging only; caller must BEGIN/ROLLBACK. All cash/settings/session fixtures roll back.
do $$ declare outlet uuid; admin_id uuid; manager uuid; c uuid; past uuid:=gen_random_uuid(); value jsonb; first_snapshot jsonb; evidence jsonb; denied boolean; tok text:=encode(extensions.gen_random_bytes(32),'hex');
 original_denominations jsonb:='{"100":7,"10":4,"1":6}';
begin
 select id into outlet from public.outlets where name='QA Demo — Reporting Posters';
 select e.auth_user_id into admin_id from public.employees e join public.roles r on r.id=e.role_id where e.enable_system_login and e.access_state='active' and e.is_active and lower(r.name)='owner' limit 1;
 select e.id into manager from public.employees e join public.crew_access ca on ca.employee_id=e.id where lower(btrim(e.workplace))='management' and ca.access_state='active' and e.is_active and outlet=any(public.crew_authorized_outlet_ids(e.id)) limit 1;
 assert outlet is not null and admin_id is not null and manager is not null;
 assert not exists(select 1 from public.crew_cash_checkouts where outlet_id=outlet and business_date=timezone('Asia/Kuala_Lumpur',now())::date),'Do not collide with a real checkout';
 perform set_config('request.jwt.claim.sub',admin_id::text,true);
 perform public.crew_cash_save_settings(outlet,'{"allow_authorized_management_checkout":true,"variance_tolerance":0,"require_manager_review_over_tolerance":true}');
 perform public.crew_cash_save_settings(outlet,jsonb_build_object('floating_cash',300,'effective_date',timezone('Asia/Kuala_Lumpur',now())::date,'reason','Rollback Return workflow verification'));
 insert into public.crew_sessions(employee_id,token_hash,expires_at) values(manager,encode(extensions.digest(tok,'sha256'),'hex'),now()+interval '5 minutes');
 perform set_config('request.jwt.claim.sub','',true);
 value:=public.crew_management_cash_save_checkout(tok,outlet,'reconcile',jsonb_build_object('denomination_counts',original_denominations,'pos_expected_cash',700,'carry_forward',0));
 c:=(value#>>'{checkout,id}')::uuid;
 value:=public.crew_management_cash_save_checkout(tok,outlet,'submit',jsonb_build_object('checkout_id',c,'variance_reason','Original cash discrepancy'));
 select snapshot into first_snapshot from public.crew_cash_checkout_review_events where checkout_id=c and event='submitted';
 assert (first_snapshot->>'counted_cash')::numeric=746,'Submission snapshot';
 denied:=false; begin perform public.crew_management_cash_save_checkout(tok,outlet,'draft',jsonb_build_object('checkout_id',c,'pos_expected_cash',746)); exception when invalid_parameter_value then denied:=true; end; assert denied,'Submitted is read-only';
 perform set_config('request.jwt.claim.sub',admin_id::text,true);
 execute 'set local role authenticated';
 denied:=false; begin perform public.crew_cash_review_checkout(c,'reject',''); exception when invalid_parameter_value then denied:=true; end; assert denied,'Reason required';
 value:=public.crew_cash_review_checkout(c,'reject','Recheck the POS amount');
 assert value->>'id'=c::text and value->'denomination_counts'=original_denominations and (value->>'pos_expected_cash')::numeric=700,'Return preserves same submitted working evidence';
 execute 'reset role';
 perform set_config('request.jwt.claim.sub','',true);
 value:=public.crew_management_cash_mobile(tok,outlet,timezone('Asia/Kuala_Lumpur',now())::date);
 assert value#>>'{checkout,is_returned}'='true' and value#>>'{checkout,return_reason}'='Recheck the POS amount','Action Required readback';
 assert jsonb_array_length(value->'action_required_checkouts')=1,'Responsible actor correction queue';
 perform public.crew_management_cash_save_checkout(tok,outlet,'draft',jsonb_build_object('checkout_id',c,'pos_expected_cash',746));
 perform public.crew_management_cash_save_checkout(tok,outlet,'reconcile',jsonb_build_object('checkout_id',c));
 denied:=false; begin perform public.crew_management_cash_save_checkout(tok,outlet,'complete',jsonb_build_object('checkout_id',c)); exception when invalid_parameter_value then denied:=true; end; assert denied,'A balanced returned checkout still needs Manager approval';
 value:=public.crew_management_cash_save_checkout(tok,outlet,'submit',jsonb_build_object('checkout_id',c));
 assert (value#>>'{checkout,variance}')::numeric=0 and value#>>'{checkout,review_status}'='pending' and value#>>'{checkout,status}'='submitted','Balanced resubmission remains Needs Review';
 perform set_config('request.jwt.claim.sub',admin_id::text,true);
 perform public.crew_cash_review_checkout(c,'reject','Keep RM46 for the next day');
 perform set_config('request.jwt.claim.sub','',true);
 perform public.crew_management_cash_save_checkout(tok,outlet,'reconcile',jsonb_build_object('checkout_id',c,'carry_forward',46));
 perform public.crew_management_cash_save_checkout(tok,outlet,'submit',jsonb_build_object('checkout_id',c));
 perform set_config('request.jwt.claim.sub',admin_id::text,true);
 value:=public.crew_cash_review_checkout(c,'approve','Reviewed and approved');
 assert value->>'status'='completed' and (value->>'amount_for_deposit')::numeric=400 and (value->>'carry_forward')::numeric=46 and (value->>'variance')::numeric=0;
 assert (select count(*)=1 from public.crew_cash_checkouts where id=c),'Same checkout throughout';
 assert (select count(*)=1 and sum(signed_amount)=400 from public.crew_cash_ledger_entries where checkout_id=c),'Only final completion posts ledger';
 assert (select array_agg(event order by id)=array['submitted','returned','resubmitted','returned','resubmitted','approved'] from public.crew_cash_checkout_review_events where checkout_id=c),'Complete repeated Return history';
 assert (select snapshot=first_snapshot from public.crew_cash_checkout_review_events where checkout_id=c and event='submitted'),'Original submission immutable';
 assert (select count(*)=2 from public.crew_cash_checkout_review_events where checkout_id=c and event='returned' and actor_user_id=admin_id),'Actual return actor';
 denied:=false; begin update public.crew_cash_checkout_review_events set reason='rewrite' where checkout_id=c; exception when invalid_parameter_value then denied:=true; end; assert denied,'Audit append-only';
 denied:=false; begin perform public.crew_cash_review_checkout(c,'approve','Duplicate'); exception when invalid_parameter_value then denied:=true; end; assert denied,'Duplicate approval denied';
 assert not has_table_privilege('authenticated','public.crew_cash_checkout_review_events','INSERT'),'No direct audit write';
 assert not has_function_privilege('anon','public.crew_cash_checkout_review_projection(uuid)','EXECUTE'),'Private audit projector';
 value:=public.crew_cash_admin_page(outlet,timezone('Asia/Kuala_Lumpur',now())::date,timezone('Asia/Kuala_Lumpur',now())::date);
 assert jsonb_array_length(value#>'{rows,0,review_history}')=6,'Admin history canonical';
-- A returned prior-day run is resumed by ID; the submitting employee/outlet remains enforced.
 insert into public.crew_cash_checkouts(id,outlet_id,business_date,checked_out_by_employee_id,status,review_required,review_status,floating_cash,expected_opening_cash,denomination_counts,counted_cash,pos_expected_cash,variance,carry_forward,amount_for_deposit,submitted_at)
 values(past,outlet,timezone('Asia/Kuala_Lumpur',now())::date-1,manager,'submitted',true,'pending',300,300,original_denominations,746,700,46,0,446,now()-interval '1 day');
 perform public.crew_cash_review_checkout(past,'reject','Correct the previous day checkout');
 perform set_config('request.jwt.claim.sub','',true);
 value:=public.crew_management_cash_save_checkout(tok,outlet,'reconcile',jsonb_build_object('checkout_id',past,'pos_expected_cash',746));
 assert value#>>'{checkout,id}'=past::text and (value#>>'{checkout,business_date}')::date=timezone('Asia/Kuala_Lumpur',now())::date-1,'Prior-day correction stays on same run/date';
 perform public.crew_management_cash_save_checkout(tok,outlet,'submit',jsonb_build_object('checkout_id',past));
 assert (select count(*)=2 from public.crew_cash_checkouts where outlet_id=outlet and id in (c,past)),'No duplicate runs';
end $$;
select 'PASS: Submit -> Return -> balanced correction -> Resubmit -> Return -> Resubmit -> Approve; same ID, immutable submissions, actual actors, one ledger' result;
