import { BarChart3, CircleAlert, TrendingDown, TrendingUp } from "lucide-react";
import { money, periodLabel, statusLabel } from "./reportingFormatters.js";

function Metric({ label, metric, emphasis = false }) {
  return <div className={`rounded-2xl border p-3 ${emphasis ? "border-emerald-200 bg-emerald-50/80" : "border-slate-200 bg-white/70"}`}><div className="text-[10px] font-bold uppercase tracking-[0.14em] text-slate-500">{label}</div><div className={`mt-1 text-lg font-bold tracking-tight ${emphasis ? "text-emerald-800" : "text-slate-900"}`}>{money(metric)}</div>{metric?.presence !== "present" ? <div className="mt-1 text-[10px] font-semibold text-amber-700">Missing record</div> : null}</div>;
}

function ProductList({ title, icon: Icon, rows = [], emptyMessage }) {
  return <section className="min-w-0 rounded-2xl border border-slate-200 bg-white/75 p-3"><div className="flex items-center gap-2"><span className="grid h-7 w-7 place-items-center rounded-lg bg-slate-900 text-white"><Icon size={14} /></span><div><h3 className="text-xs font-bold text-slate-900">{title}</h3><p className="text-[10px] text-slate-500">Sales revenue</p></div></div>{rows.length ? <ol className="mt-3 space-y-1.5">{rows.map((product, index) => { const category = product.category_name ?? product.category; return <li key={`${category ?? ""}-${product.product_name ?? product.productName ?? "product"}-${index}`} className="flex min-w-0 items-center justify-between gap-2 text-[11px]"><span className="min-w-0 truncate text-slate-700"><b className="mr-1 text-slate-400">{index + 1}.</b>{product.product_name ?? product.productName ?? "Unnamed product"}{category ? <em className="ml-1 not-italic text-slate-400">· {category}</em> : null}</span><strong className="shrink-0 text-slate-900">{money({ amount: product.sales_revenue ?? product.salesRevenue, presence: "present" })}</strong></li>; })}</ol> : <div className="mt-4 rounded-xl bg-slate-50 p-3 text-[11px] leading-4 text-slate-500">{emptyMessage}</div>}</section>;
}

export default function MonthlyProfitPoster({ dataset }) {
  const unavailable = dataset.productDataStatus !== "available";
  return <article className="aspect-[4/5] w-full overflow-hidden rounded-[28px] bg-[radial-gradient(circle_at_top_right,_rgba(16,185,129,0.22),_transparent_38%),linear-gradient(145deg,_#f8fafc,_#ecfdf5)] p-4 text-slate-900 shadow-[0_25px_70px_rgba(15,23,42,0.16)] sm:p-6" aria-label="Monthly Profit Report poster">
    <div className="flex items-start justify-between gap-3 border-b border-slate-200/80 pb-4"><div><div className="text-[10px] font-extrabold uppercase tracking-[0.2em] text-emerald-700">FeedX · Monthly Profit</div><h2 className="mt-2 text-xl font-black tracking-tight sm:text-2xl">{dataset.outlet?.name ?? "Outlet"}</h2><p className="mt-1 text-xs font-medium text-slate-500">{periodLabel(dataset.period)}</p></div><span className={`rounded-full border px-2.5 py-1 text-[10px] font-bold uppercase tracking-wide ${dataset.financialCompleteness === "complete" ? "border-emerald-200 bg-emerald-100 text-emerald-800" : "border-amber-200 bg-amber-100 text-amber-800"}`}>{statusLabel(dataset.financialCompleteness)}</span></div>
    <div className="mt-4 grid grid-cols-2 gap-2"><Metric label="Revenue" metric={dataset.financials.revenue} /><Metric label="COGS · purchase-based" metric={dataset.financials.purchaseBasedCogs} /><Metric label="OpEx" metric={dataset.financials.opex} /><Metric label="Net Profit" metric={dataset.financials.netProfit} emphasis /></div>
    {dataset.financialCompleteness !== "complete" ? <div className="mt-3 flex gap-2 rounded-xl border border-amber-200 bg-amber-50 px-3 py-2 text-[11px] leading-4 text-amber-800"><CircleAlert className="mt-0.5 shrink-0" size={14} />Incomplete means one or more financial source records are missing; “—” is not RM0.</div> : null}
    <div className="mt-4 flex items-center justify-between"><div><div className="text-xs font-bold text-slate-900">Product performance</div><div className="text-[10px] text-slate-500">Completed Product Analytics report</div></div><BarChart3 size={17} className="text-emerald-700" /></div>
    {unavailable ? <div className="mt-3 rounded-2xl border border-dashed border-slate-300 bg-white/60 p-4 text-center text-xs text-slate-500">Product sales data is unavailable for this period. Financial reporting remains available.</div> : <div className="mt-3 grid grid-cols-2 gap-2"><ProductList title="Top 10" icon={TrendingUp} rows={dataset.topProducts} emptyMessage="No ranked products." /><ProductList title="Lowest 10" icon={TrendingDown} rows={dataset.lowestProducts} emptyMessage="No products above zero sales revenue." /></div>}
  </article>;
}
