import { CircleAlert, TrendingUp } from "lucide-react";
import { compactMonth, money, statusLabel } from "./reportingFormatters.js";

function Metric({ label, metric, primary = false }) { return <div className={`rounded-xl border p-2.5 ${primary ? "border-emerald-200 bg-emerald-50" : "border-slate-200 bg-white/75"}`}><div className="text-[9px] font-bold uppercase tracking-[0.12em] text-slate-500">{label}</div><strong className={`mt-1 block text-sm tracking-tight ${primary ? "text-emerald-800" : "text-slate-900"}`}>{money(metric)}</strong></div>; }

function seriesPoints(months, field) {
  const values = months.map((month) => month.financials[field]?.presence === "present" ? Number(month.financials[field].amount) : null);
  const max = Math.max(...values.filter((value) => value !== null).map((value) => Math.abs(value)), 1);
  return values.map((value, index) => value === null ? null : `${8 + index * 24},${52 - ((value / max) * 38)}`).filter(Boolean).join(" ");
}

export default function YearlyPnlPoster({ dataset }) {
  const periodTitle = dataset.periodMode === "ytd" ? `${dataset.year} YTD` : `${dataset.year} Yearly P&L`;
  return <article className="aspect-[4/5] w-full overflow-hidden rounded-[28px] bg-[radial-gradient(circle_at_90%_0,_rgba(59,130,246,0.2),_transparent_36%),linear-gradient(145deg,_#f8fafc,_#eef2ff)] p-4 text-slate-900 shadow-[0_25px_70px_rgba(15,23,42,0.16)] sm:p-6" aria-label="Yearly P&L Report poster">
    <div className="flex items-start justify-between gap-3 border-b border-slate-200 pb-4"><div><div className="text-[10px] font-extrabold uppercase tracking-[0.2em] text-indigo-700">FeedX · Financial Performance</div><h2 className="mt-2 text-xl font-black tracking-tight sm:text-2xl">{dataset.outlet?.name ?? "Outlet"}</h2><p className="mt-1 text-xs font-medium text-slate-500">{periodTitle}</p></div><span className={`rounded-full border px-2.5 py-1 text-[10px] font-bold uppercase tracking-wide ${dataset.completeness === "complete" ? "border-emerald-200 bg-emerald-100 text-emerald-800" : "border-amber-200 bg-amber-100 text-amber-800"}`}>{statusLabel(dataset.completeness, dataset.periodMode)}</span></div>
    <div className="mt-4 grid grid-cols-2 gap-2"><Metric label="Revenue" metric={dataset.totals.revenue} /><Metric label="COGS · purchase-based" metric={dataset.totals.purchaseBasedCogs} /><Metric label="OpEx" metric={dataset.totals.opex} /><Metric label="Net Profit" metric={dataset.totals.netProfit} primary /></div>
    {dataset.completeness !== "complete" ? <div className="mt-3 flex gap-2 rounded-xl border border-amber-200 bg-amber-50 px-3 py-2 text-[10px] leading-4 text-amber-800"><CircleAlert className="mt-0.5 shrink-0" size={13} />YTD / Incomplete — missing and future months display as “—”, never RM0.</div> : null}
    <section className="mt-4 rounded-2xl border border-slate-200 bg-white/70 p-3"><div className="flex items-center justify-between"><div><h3 className="text-xs font-bold">Revenue & Net Profit trend</h3><p className="text-[10px] text-slate-500">Present months only</p></div><TrendingUp size={16} className="text-indigo-600" /></div><svg className="mt-2 h-16 w-full" viewBox="0 0 280 60" role="img" aria-label="Monthly revenue and net profit trend"><path d="M 8 52 H 272" stroke="#cbd5e1" strokeWidth="1" /><polyline points={seriesPoints(dataset.months, "revenue")} fill="none" stroke="#4f46e5" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" /><polyline points={seriesPoints(dataset.months, "netProfit")} fill="none" stroke="#059669" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" /></svg><div className="mt-1 grid grid-cols-12 text-center text-[8px] font-semibold text-slate-400">{dataset.months.map((month) => <span key={month.month}>{compactMonth(month.month).slice(0, 1)}</span>)}</div></section>
    <section className="mt-3 overflow-hidden rounded-2xl border border-slate-200 bg-white/80"><div className="grid grid-cols-[34px_repeat(4,minmax(0,1fr))] gap-1 border-b border-slate-200 bg-slate-50 px-2 py-2 text-[8px] font-bold uppercase tracking-wide text-slate-500"><span>Month</span><span className="text-right">Revenue</span><span className="text-right">COGS</span><span className="text-right">OpEx</span><span className="text-right">Net</span></div>{dataset.months.map((month) => <div key={month.month} className="grid grid-cols-[34px_repeat(4,minmax(0,1fr))] gap-1 border-b border-slate-100 px-2 py-1 text-[8px] last:border-0"><span className="font-bold text-slate-500">{compactMonth(month.month)}</span><span className="truncate text-right">{money(month.financials.revenue)}</span><span className="truncate text-right">{money(month.financials.purchaseBasedCogs)}</span><span className="truncate text-right">{money(month.financials.opex)}</span><strong className="truncate text-right text-emerald-800">{money(month.financials.netProfit)}</strong></div>)}</section>
  </article>;
}
