import {render,screen,fireEvent,waitFor,cleanup} from '@testing-library/react';
import {afterEach,beforeEach,describe,it,expect,vi} from 'vitest';
import PayrollPhStatutory from '../PayrollPhStatutory.jsx';
const service=vi.hoisted(()=>({readPhStatutory:vi.fn(),confirmPhStatutory:vi.fn(),previewPhTreatment:vi.fn()}));
vi.mock('../../../../services/payrollService.js',()=>({payrollService:service}));
const row={date:'2026-09-16',context_fingerprint:'server-current',issues:['ph_occurrence_review_required'],profile:{status:'review_required'},context:{compensation:{pay_basis:'hourly',hourly_rate:8},time:{id:'time',status:'approved_manual',classification:'public_holiday',approved_minutes:480,scheduled_minutes:480},source:{leave_type:null},company_policy:null},review:null};
const quote={quote_fingerprint:'quoted-amount',context_fingerprint:'server-current',context:{time:{approved_minutes:480}},statutory_available:true,statutory_amount:156,issues:[],warnings:[]};
beforeEach(()=>{vi.clearAllMocks();service.readPhStatutory.mockResolvedValue([row]);service.previewPhTreatment.mockResolvedValue(quote);service.confirmPhStatutory.mockResolvedValue({review_id:'verified'});});
afterEach(cleanup);
async function open(){render(<PayrollPhStatutory runId="run" employeeId="employee" canManage/>);fireEvent.click(await screen.findByRole('button',{name:'Review Holiday'}));await screen.findByText(/Calculated Public Holiday Allowance/);}
async function choose(name){fireEvent.click(screen.getByRole('button',{name:/Select PH pay treatment|Apply Statutory PH Pay|Custom PH Allowance|No Additional PH Pay/}));fireEvent.click(screen.getByRole('button',{name,exact:true}));}
const reason=()=>fireEvent.change(screen.getByLabelText('Decision / correction reason'),{target:{value:'Reviewed explicit day treatment'}});
describe('PH operational treatment',()=>{
 it('one-step statutory confirmation uses the server quote without a required profile form',async()=>{await open();expect(screen.queryByLabelText('First Schedule coverage')).toBeNull();expect(screen.queryByRole('button',{name:'Setup PH Pay Profile'})).toBeNull();expect(screen.getByText(/RM.*156/)).toBeTruthy();await choose('Apply Statutory PH Pay');reason();await waitFor(()=>expect(screen.getByRole('button',{name:'Confirm PH Treatment'}).disabled).toBe(false));fireEvent.click(screen.getByRole('button',{name:'Confirm PH Treatment'}));await waitFor(()=>expect(service.confirmPhStatutory).toHaveBeenCalled());expect(service.confirmPhStatutory.mock.calls[0][0]).toMatchObject({treatment:'statutory',decision:'keep_approved',context_fingerprint:'server-current'});expect(service.confirmPhStatutory.mock.calls[0][0].evidence).toBeUndefined();});
 it('custom amount resolves unavailable statutory pricing with a reason and acknowledged warning',async()=>{service.previewPhTreatment.mockResolvedValue({...quote,statutory_available:false,statutory_amount:null});render(<PayrollPhStatutory runId="run" employeeId="employee" canManage/>);fireEvent.click(await screen.findByRole('button',{name:'Review Holiday'}));await screen.findByText('Statutory amount cannot be determined automatically.');await choose('Custom PH Allowance');fireEvent.change(screen.getByLabelText('Public Holiday Allowance (RM)'),{target:{value:'125.50'}});reason();expect(screen.getByRole('button',{name:'Confirm PH Treatment'}).disabled).toBe(true);fireEvent.click(screen.getByRole('checkbox',{name:'I acknowledge this compliance warning.'}));await waitFor(()=>expect(screen.getByRole('button',{name:'Confirm PH Treatment'}).disabled).toBe(false));fireEvent.click(screen.getByRole('button',{name:'Confirm PH Treatment'}));await waitFor(()=>expect(service.confirmPhStatutory).toHaveBeenCalled());expect(service.confirmPhStatutory.mock.calls[0][0]).toMatchObject({treatment:'custom',amount:'125.50',acknowledge_warning:true});});
 it('zero additional pay is explicitly warned and never labelled statutory compliance',async()=>{await open();await choose('No Additional PH Pay');expect(screen.getByRole('note').textContent).toContain('Statutory entitlement may still be due');reason();fireEvent.click(screen.getByRole('checkbox'));await waitFor(()=>expect(screen.getByRole('button',{name:'Confirm PH Treatment'}).disabled).toBe(false));fireEvent.click(screen.getByRole('button',{name:'Confirm PH Treatment'}));await waitFor(()=>expect(service.confirmPhStatutory).toHaveBeenCalled());expect(service.confirmPhStatutory.mock.calls[0][0].treatment).toBe('none');});
 it('separates PH OT override from ordinary allowance',async()=>{service.previewPhTreatment.mockResolvedValue({...quote,context:{time:{approved_minutes:480,approved_extra_minutes:60}}});await open();await choose('Custom PH Allowance');expect(await screen.findByLabelText('PH overtime allowance (RM)')).toBeTruthy();});
 it('retains server errors and the same date; stale responses never enable save',async()=>{await open();await choose('Apply Statutory PH Pay');reason();service.confirmPhStatutory.mockRejectedValue(new Error('PH evidence changed. Reopen and review the current evidence.'));await waitFor(()=>expect(screen.getByRole('button',{name:'Confirm PH Treatment'}).disabled).toBe(false));fireEvent.click(screen.getByRole('button',{name:'Confirm PH Treatment'}));expect(await screen.findByRole('alert')).toHaveProperty('textContent','PH evidence changed. Reopen and review the current evidence.');expect(screen.getByText('PH Pay Treatment · 2026-09-16')).toBeTruthy();});
 it('offers correction and history while finalized rows remain read-only',async()=>{service.readPhStatutory.mockResolvedValue([{...row,issues:[],review:{id:'r',evidence:{workflow:'pay_treatment_v1',intent:{treatment:'custom'}},reason:'Original decision'},history:[{id:'r',evidence:{intent:{treatment:'custom'}},reason:'Original decision'}]}]);render(<PayrollPhStatutory runId="run" employeeId="employee" canManage={false}/>);expect(await screen.findByText('Confirmed')).toBeTruthy();expect(screen.queryByRole('button',{name:'Correct PH Treatment'})).toBeNull();expect(screen.getByText(/Original decision/)).toBeTruthy();});
});
