import {render,screen,fireEvent,waitFor,cleanup,within} from '@testing-library/react';
import {afterEach,beforeEach,describe,it,expect,vi} from 'vitest';
import PayrollPhStatutory from '../PayrollPhStatutory.jsx';
const service=vi.hoisted(()=>({readPhStatutory:vi.fn(),confirmPhStatutory:vi.fn(),previewPhTreatment:vi.fn()}));
vi.mock('../../../../services/payrollService.js',()=>({payrollService:service}));
const row={date:'2026-09-16',context_fingerprint:'server-current',issues:['ph_occurrence_review_required'],profile:{status:'review_required'},context:{compensation:{pay_basis:'hourly',hourly_rate:8},time:{id:'time',status:'approved_manual',classification:'public_holiday',approved_minutes:300,scheduled_minutes:300},source:{leave_type:null},company_policy:null},review:null};
const base={quote_fingerprint:'quoted-amount',context_fingerprint:'server-current',context:{time:{approved_minutes:300}},statutory_available:true,statutory_amount:156,issues:[],warnings:[]};
function respond(input,extra={}){return {...base,...extra,pay_preview:{determinate:Boolean(input.treatment),regular_pay:0,public_holiday_allowance:input.treatment==='none'?0:156,ph_ot:0,company_ph_benefit:0,total_day_additions:input.treatment==='none'?0:156,previous_day_additions:0,payroll_change:input.treatment==='none'?0:156,...extra.pay_preview}};}
beforeEach(()=>{vi.clearAllMocks();service.readPhStatutory.mockResolvedValue([row]);service.previewPhTreatment.mockImplementation(async input=>respond(input));service.confirmPhStatutory.mockResolvedValue({review_id:'verified'});});
afterEach(cleanup);
async function open(){render(<PayrollPhStatutory runId="run" employeeId="employee" canManage/>);fireEvent.click(await screen.findByRole('button',{name:'Review Holiday'}));await waitFor(()=>expect(service.previewPhTreatment).toHaveBeenCalled());}
async function choose(name){fireEvent.click(screen.getByRole('button',{name:'PH Pay Treatment',exact:true}));fireEvent.click(screen.getByRole('option',{name,exact:true}));}
const reason=()=>fireEvent.change(screen.getByLabelText('Decision / correction reason'),{target:{value:'Reviewed explicit day treatment'}});
const confirm=()=>screen.getByRole('button',{name:'Confirm PH Treatment'});
const preview=()=>within(screen.getByRole('region',{name:'Pay Preview'}));
async function enabled(){await waitFor(()=>expect(confirm().disabled).toBe(false));}
describe('PH decision safety and financial preview',()=>{
 it('shows canonical day effect before statutory confirmation, with confirmed time as evidence',async()=>{await open();expect(screen.getByText('Payable Time ✓ Confirmed · 5.00h')).toBeTruthy();expect(screen.queryByText('Day decision')).toBeNull();expect(screen.queryByLabelText('First Schedule coverage')).toBeNull();await choose('Statutory PH Pay');await screen.findByText(/This decision adds.*156/);expect(preview().getByText('Public Holiday Allowance')).toBeTruthy();await enabled();fireEvent.click(confirm());await waitFor(()=>expect(service.confirmPhStatutory).toHaveBeenCalled());expect(service.confirmPhStatutory.mock.calls[0][0]).toMatchObject({treatment:'statutory',decision:'keep_approved',quote_fingerprint:'quoted-amount'});});
 it('blocks unavailable statutory selection before confirmation and offers clear recovery',async()=>{service.previewPhTreatment.mockImplementation(async input=>respond(input,{statutory_available:false,statutory_amount:null,pay_preview:{determinate:false}}));await open();await screen.findByText(/Statutory PH Pay unavailable — required evidence is incomplete/);fireEvent.click(screen.getByRole('button',{name:'PH Pay Treatment'}));expect(screen.getByRole('option',{name:'Statutory PH Pay'}).disabled).toBe(true);expect(confirm().disabled).toBe(true);expect(screen.queryByRole('button',{name:'Complete Statutory Evidence'})).toBeNull();expect(screen.queryByText('Advanced compliance evidence')).toBeNull();});
 it('uses the server result for custom preview instead of pricing the typed value in the UI',async()=>{service.previewPhTreatment.mockImplementation(async input=>respond(input,{statutory_available:false,pay_preview:{determinate:input.amount==='125.50',public_holiday_allowance:73.41,total_day_additions:73.41,payroll_change:73.41}}));await open();await screen.findByText(/Statutory PH Pay unavailable — required evidence is incomplete/);await choose('Custom PH Allowance');fireEvent.change(screen.getByLabelText('Public Holiday Allowance (RM)'),{target:{value:'125.50'}});await screen.findByText(/This decision adds.*73.41/);reason();expect(screen.queryByRole('checkbox')).toBeNull();await enabled();fireEvent.click(confirm());await waitFor(()=>expect(service.confirmPhStatutory).toHaveBeenCalled());expect(service.confirmPhStatutory.mock.calls[0][0]).toMatchObject({amount:'125.50',treatment_model:'unified_v1'});});
 it('shows explicit zero allowance and retains compliance warning',async()=>{await open();await choose('No Additional PH Pay');await screen.findByText(/This decision adds.*0.00/);expect(preview().getByText('Public Holiday Allowance')).toBeTruthy();expect(preview().getAllByText(/RM.*0.00/).length).toBeGreaterThan(0);expect(screen.getAllByRole('note').some(x=>x.textContent.includes('Statutory entitlement may still be due'))).toBe(true);reason();await enabled();});
 it('shows separate canonical PH OT without a layered company control',async()=>{service.readPhStatutory.mockResolvedValue([{...row,context:{...row.context,company_policy:{id:'policy'},time:{...row.context.time,approved_extra_minutes:60}}}]);service.previewPhTreatment.mockImplementation(async input=>respond(input,{context:{time:{approved_minutes:300,approved_extra_minutes:60}},pay_preview:{ph_ot:17,company_ph_benefit:14,total_day_additions:187,payroll_change:187}}));await open();await choose('Custom PH Allowance');expect(await screen.findByLabelText('PH overtime allowance (RM)')).toBeTruthy();fireEvent.change(screen.getByLabelText('Public Holiday Allowance (RM)'),{target:{value:'156'}});fireEvent.change(screen.getByLabelText('PH overtime allowance (RM)'),{target:{value:'17'}});await screen.findByText(/This decision adds.*187/);expect(preview().getByText('PH OT')).toBeTruthy();expect(screen.queryByText('Separate company PH benefit')).toBeNull();expect(preview().queryByText('Company PH benefit')).toBeNull();});
 it('omits unconfigured benefit and only exposes payable-time changes on request',async()=>{await open();expect(screen.queryByText('Separate company PH benefit')).toBeNull();fireEvent.click(screen.getByRole('button',{name:'Edit Payable Time'}));expect(screen.getByText('Day decision')).toBeTruthy();});
 it('explains monthly Basic inclusion without inventing an extra daily Basic amount',async()=>{service.readPhStatutory.mockResolvedValue([{...row,context:{...row.context,compensation:{pay_basis:'monthly',basic_salary:2600}}}]);service.previewPhTreatment.mockImplementation(async input=>respond(input,{pay_preview:{monthly_basic_included:true,public_holiday_allowance:0,total_day_additions:0,payroll_change:0}}));await open();await choose('Statutory PH Pay');await screen.findByText('Included in Basic Salary');expect(screen.getByText('Total additional earnings for this day')).toBeTruthy();});
 it('displays correction delta and retains server errors in the same day',async()=>{service.readPhStatutory.mockResolvedValue([{...row,review:{id:'prior',evidence:{intent:{treatment:'custom',amount:100}},reason:'Original decision'}}]);service.previewPhTreatment.mockImplementation(async input=>respond(input,{pay_preview:{previous_day_additions:100,payroll_change:-25,total_day_additions:75,public_holiday_allowance:75}}));render(<PayrollPhStatutory runId="run" employeeId="employee" canManage/>);fireEvent.click(await screen.findByRole('button',{name:'Correct PH Treatment'}));await screen.findByText(/This decision reduces Payroll by.*25/);expect(screen.getByText(/Replaces the previous day addition/)).toBeTruthy();reason();await enabled();service.confirmPhStatutory.mockRejectedValue(new Error('PH quote changed. Review the current allowance before confirming.'));fireEvent.click(confirm());expect(await screen.findByRole('alert')).toHaveProperty('textContent','PH quote changed. Review the current allowance before confirming.');expect(screen.getByText('PH Pay Treatment · 2026-09-16')).toBeTruthy();});
 it('immediately disables confirmation and ignores obsolete quotes when an amount changes',async()=>{await open();await choose('Custom PH Allowance');fireEvent.change(screen.getByLabelText('Public Holiday Allowance (RM)'),{target:{value:'120'}});reason();await enabled();let finish;service.previewPhTreatment.mockImplementation(()=>new Promise(resolve=>{finish=resolve;}));fireEvent.change(screen.getByLabelText('Public Holiday Allowance (RM)'),{target:{value:'130'}});expect(confirm().disabled).toBe(true);expect(screen.getByText('Updating Pay Preview…')).toBeTruthy();await waitFor(()=>expect(finish).toBeTruthy());finish(respond({treatment:'custom'},{pay_preview:{public_holiday_allowance:130,total_day_additions:130,payroll_change:130}}));await screen.findByText(/This decision adds.*130/);expect(confirm().disabled).toBe(false);});
 it('keeps finalized rows read-only and preserves visible history',async()=>{service.readPhStatutory.mockResolvedValue([{...row,issues:[],review:{id:'r',evidence:{workflow:'pay_treatment_v1',intent:{treatment:'custom'}},reason:'Original decision'},history:[{id:'r',evidence:{intent:{treatment:'custom'}},reason:'Original decision'}]}]);render(<PayrollPhStatutory runId="run" employeeId="employee" canManage={false}/>);expect(await screen.findByText('Confirmed')).toBeTruthy();expect(screen.queryByRole('button',{name:'Correct PH Treatment'})).toBeNull();expect(screen.getByText(/Original decision/)).toBeTruthy();});
});

it('preselects the date-effective company default without a separate benefit or acknowledgement workflow',async()=>{service.readPhStatutory.mockResolvedValue([{...row,preview:{default_treatment:'company'}}]);service.previewPhTreatment.mockImplementation(async input=>respond(input,{company_available:true,pay_preview:{regular_pay:40,public_holiday_allowance:40,total_day_additions:80,payroll_change:80}}));await open();expect(screen.getByText('Company PH Allowance')).toBeTruthy();await screen.findByText(/This decision adds.*80/);expect(screen.queryByRole('checkbox')).toBeNull();expect(screen.queryByLabelText('Decision / correction reason')).toBeNull();await enabled();fireEvent.click(confirm());await waitFor(()=>expect(service.confirmPhStatutory).toHaveBeenCalled());expect(service.confirmPhStatutory.mock.calls[0][0]).toMatchObject({treatment:'company',treatment_model:'unified_v1'});});

it('shows a resolved Monthly Company amount while separate PH OT remains blocked',async()=>{
 service.readPhStatutory.mockResolvedValue([{...row,preview:{default_treatment:'company'},context:{...row.context,compensation:{pay_basis:'monthly',basic_salary:1800},time:{...row.context.time,approved_minutes:510,approved_extra_minutes:30}}}]);
 service.previewPhTreatment.mockImplementation(async input=>respond(input,{company_available:true,statutory_available:false,context:{compensation:{pay_basis:'monthly',basic_salary:1800},time:{approved_minutes:510,approved_extra_minutes:30}},issues:['ph_ot_statutory_evidence_required'],warnings:['ph_company_allowance_not_statutory_compliance'],pay_preview:{determinate:false,allowance_determinate:true,allowance_basis:{source:{formula_version:'company_ph_v1'}},public_holiday_allowance:69.23,ph_ot:null,total_day_additions:null,payroll_change:null}}));
 await open();await screen.findByText(/1,800.00.*÷ 26.*69.23/);
 expect(preview().getByText('Public Holiday Allowance')).toBeTruthy();expect(preview().getByText('Review Required')).toBeTruthy();
 expect(preview().getByText('Pending PH OT review')).toBeTruthy();expect(confirm().disabled).toBe(true);
 expect(screen.getAllByRole('note').some(x=>x.textContent.includes('does not confirm statutory compliance'))).toBe(true);
 expect(screen.queryByText(/This decision adds/)).toBeNull();
});
it('does not invent an allowance or a total when canonical time itself is unresolved',async()=>{
 service.readPhStatutory.mockResolvedValue([{...row,preview:{default_treatment:'company'}}]);
 service.previewPhTreatment.mockImplementation(async input=>respond(input,{company_available:true,issues:['ph_approved_time_required'],pay_preview:{determinate:false,allowance_determinate:false,public_holiday_allowance:null}}));
 await open();await screen.findByText('Complete the treatment and required payable-time decision to resolve the financial effect.');
 expect(preview().queryByText('Public Holiday Allowance')).toBeNull();expect(confirm().disabled).toBe(true);
});
