import { useState } from "react";
import Modal from "../../../../components/feedback/Modal.jsx";
import SelectField from "../../../../components/forms/SelectField.jsx";

function Field({ label, value, onChange, type = "text", placeholder }) { return <label className="block"><div className="mb-1 type-caption font-semibold text-text-secondary">{label}</div><input className="control h-9 w-full text-[13px]" type={type} min={type === "number" ? 0 : undefined} value={value ?? ""} placeholder={placeholder} onChange={(event) => onChange(event.target.value)} /></label>; }
function TextArea({ label, value, onChange }) { return <label className="block"><div className="mb-1 type-caption font-semibold text-text-secondary">{label}</div><textarea className="control min-h-20 w-full resize-none text-[13px]" value={value ?? ""} onChange={(event) => onChange(event.target.value)} /></label>; }

export default function InventoryManualMovementModal({ outlets, items, movements = [], movement, canonical, isActiveInventoryItem, todayInput, makeId, parseNonNegativeNumber, onClose, onSave }) {
  const isEdit = Boolean(movement?.id); const key = canonical(movement?.movementType || movement?.type || ""); const isTransferEdit = key.includes("transfer");
  const paired = isTransferEdit ? movements.find((entry) => entry.id !== movement.id && entry.reference && movement.reference && entry.reference === movement.reference && canonical(entry.movementType || entry.type || "").includes("transfer")) : null;
  const outgoing = isTransferEdit && key === "transfer_in" ? paired : movement; const incoming = isTransferEdit && key === "transfer_out" ? paired : movement; const initialType = isTransferEdit ? "transfer" : key === "waste" ? "waste" : key === "purchase" ? "purchase" : "adjustment"; const selectable = items.filter(isActiveInventoryItem);
  const [form, setForm] = useState({ id: isTransferEdit ? outgoing?.id || movement?.id || "" : movement?.id || "", pairMovementId: isTransferEdit ? incoming?.id || "" : "", date: movement?.date || todayInput(), itemId: movement?.itemId || selectable[0]?.id || "", type: initialType, direction: Number(movement?.quantity || 0) < 0 ? "decrease" : "increase", quantity: movement?.quantity ? Math.abs(Number(movement.quantity)) : "", outletId: movement?.outletId || outlets[0]?.id || "", fromOutletId: isTransferEdit ? outgoing?.outletId || "" : movement?.outletId || "", toOutletId: isTransferEdit ? incoming?.outletId || "" : "", user: "Current User", reference: movement?.reference || "", referenceType: movement?.referenceType || (isEdit ? "manual" : ""), referenceId: movement?.referenceId || "", notes: movement?.notes || "" });
  const [isSaving, setIsSaving] = useState(false); const item = items.find((entry) => entry.id === form.itemId); const isTransfer = form.type === "transfer"; const quantity = Number(form.quantity || 0); const canSave = form.itemId && quantity > 0 && (isTransfer ? form.fromOutletId && form.toOutletId && form.fromOutletId !== form.toOutletId : form.outletId);
  const update = (field, value) => setForm((current) => field === "type" ? { ...current, type: value, direction: value === "waste" ? "decrease" : current.direction, outletId: current.outletId || current.fromOutletId || outlets[0]?.id || "", fromOutletId: current.fromOutletId || current.outletId || outlets[0]?.id || "", toOutletId: current.toOutletId || "" } : { ...current, [field]: value });
  const save = async () => { if (isSaving) return; setIsSaving(true); try { if (isTransfer) return await onSave({ transfer: true, pairMovementId: form.pairMovementId, id: form.id, itemId: form.itemId, quantity, unit: item?.unit || "", fromOutletId: form.fromOutletId, toOutletId: form.toOutletId, reference: form.reference || `TRF-${Date.now().toString().slice(-8)}`, referenceType: "transfer", notes: form.notes }); const signed = form.type === "waste" || (form.type === "adjustment" && form.direction === "decrease") ? -Math.abs(quantity) : Math.abs(quantity); await onSave({ ...form, quantity: signed, unit: item?.unit || "", movementType: form.type, id: form.id || makeId("move"), referenceType: form.referenceType || "manual" }); } finally { setIsSaving(false); } };
  const types = [{ value: "purchase", label: "Purchase" }, { value: "waste", label: "Waste" }, { value: "transfer", label: "Transfer" }, { value: "adjustment", label: "Adjustment" }].filter((option) => !isEdit || option.value !== "purchase");
  return <Modal title={isEdit ? "Edit Inventory Movement" : "Record Inventory Movement"} description="Every stock movement should create an operational audit trail." onClose={onClose} footer={<><button className="btn-secondary" type="button" disabled={isSaving} onClick={onClose}>Cancel</button><button className="btn-primary" type="button" disabled={isSaving || !canSave} onClick={save}>{isSaving ? "Saving…" : isEdit ? "Update Movement" : "Save Movement"}</button></>}><div className="grid gap-3">{isTransfer ? <div className="grid gap-3 md:grid-cols-2"><SelectField label="From Outlet" value={form.fromOutletId} options={outlets.map((outlet) => ({ value: outlet.id, label: outlet.name }))} onChange={(value) => update("fromOutletId", value)} searchable /><SelectField label="To Outlet" value={form.toOutletId} options={outlets.map((outlet) => ({ value: outlet.id, label: outlet.name }))} onChange={(value) => update("toOutletId", value)} searchable /></div> : <SelectField label="Outlet" value={form.outletId} options={outlets.map((outlet) => ({ value: outlet.id, label: outlet.name }))} onChange={(value) => update("outletId", value)} searchable />}<SelectField label="Item" value={form.itemId} options={selectable.map((entry) => ({ value: entry.id, label: `${entry.name}${entry.sku ? ` · ${entry.sku}` : ""}` }))} onChange={(value) => update("itemId", value)} searchable /><SelectField label="Movement Type" value={form.type} options={types} onChange={(value) => update("type", value)} />{form.type === "adjustment" ? <SelectField label="Adjustment Direction" value={form.direction} options={[{ value: "increase", label: "Increase" }, { value: "decrease", label: "Decrease" }]} onChange={(value) => update("direction", value)} /> : null}<Field label={`Quantity${item?.unit ? ` (${item.unit})` : ""}`} type="number" value={form.quantity} placeholder="Enter quantity" onChange={(value) => update("quantity", parseNonNegativeNumber(value))} /><Field label="Reference" value={form.reference} onChange={(value) => update("reference", value)} /><TextArea label="Notes" value={form.notes} onChange={(value) => update("notes", value)} />{form.type === "purchase" ? <div className="rounded-2xl border border-emerald-200 bg-emerald-50 px-3 py-2 type-caption font-semibold text-emerald-800">Purchase movements are saved as positive quantities. PO receiving records remain read-only after creation.</div> : null}{form.type === "waste" ? <div className="rounded-2xl border border-amber-200 bg-amber-50 px-3 py-2 type-caption font-semibold text-amber-800">Waste movements are saved as negative quantities because they reduce stock.</div> : null}{form.type === "transfer" && form.fromOutletId === form.toOutletId ? <div className="rounded-2xl border border-rose-200 bg-rose-50 px-3 py-2 type-caption font-semibold text-rose-700">From Outlet and To Outlet must be different.</div> : null}</div></Modal>;
}
