import { useState } from "react";
import { PackagePlus, Trash2, Truck, Warehouse } from "lucide-react";
import MetricCard from "../../../../components/ui/MetricCard.jsx";
import SelectField from "../../../../components/forms/SelectField.jsx";
import DatePickerField from "../../../../components/forms/DatePickerField.jsx";
import EmptyState from "../../../../components/feedback/EmptyState.jsx";
import FactoryPagination, { useFactoryClientPagination } from "../../../factory/components/FactoryPagination.jsx";

export default function InventoryMovementsPage({ movements, itemById, outletById, outletOptions, actorNameByAnyId, formatDateTimeCompact, canonical, toTitle, canEditMovement, canRecordMovement, onEditMovement, onOpenReference }) {
  const [filters, setFilters] = useState({ outletId: "all", movementType: "all", search: "", from: "", to: "" });
  const updateFilter = (key, value) => setFilters((current) => ({ ...current, [key]: value }));
  const movementTypes = [...new Set(movements.map((movement) => movement.movementType || movement.type).filter(Boolean))];
  const typeKey = (movement) => canonical(movement.movementType || movement.type || "");
  const typeClass = (movement) => ({ purchase: "border-emerald-200 bg-emerald-50 text-emerald-700", transfer_in: "border-blue-200 bg-blue-50 text-blue-700", transfer_out: "border-purple-200 bg-purple-50 text-purple-700", waste: "border-orange-200 bg-orange-50 text-orange-700", adjustment: "border-slate-200 bg-slate-50 text-text-secondary" }[typeKey(movement)] || "border-slate-200 bg-slate-50 text-text-secondary");
  const quantityClass = (movement) => { const key = typeKey(movement); if (key === "purchase") return "text-emerald-700"; if (key === "waste") return "text-amber-700"; if (key.includes("transfer")) return "text-blue-700"; if (key === "adjustment") return "text-purple-700"; return "text-text-primary"; };
  const typeLabel = (movement) => { const key = typeKey(movement); if (key === "transfer_in") return "Transfer In"; if (key === "transfer_out") return "Transfer Out"; return toTitle(movement.movementType || movement.type || "movement"); };
  const filtered = movements.filter((movement) => { const item = itemById.get(movement.itemId); const date = String(movement.dateTime || movement.date || "").slice(0, 10); const search = `${item?.name || ""} ${movement.reference || ""} ${movement.notes || ""} ${movement.movementType || movement.type || ""}`.toLowerCase(); return (filters.outletId === "all" || movement.outletId === filters.outletId) && (filters.movementType === "all" || typeKey(movement) === canonical(filters.movementType)) && (!filters.search.trim() || search.includes(filters.search.trim().toLowerCase())) && (!filters.from || !date || date >= filters.from) && (!filters.to || !date || date <= filters.to); });
  const pagination = useFactoryClientPagination("restaurant.inventory-movements", filtered.length, 20, Object.values(filters).join("|"));
  const paginatedMovements = filtered.slice(pagination.from, pagination.to);
  const summary = filtered.reduce((value, movement) => { const key = typeKey(movement); if (key === "purchase") value.purchase += 1; else if (key.includes("transfer")) value.transfer += 1; else if (key === "waste") value.waste += 1; else if (key === "adjustment") value.adjustment += 1; return value; }, { purchase: 0, transfer: 0, waste: 0, adjustment: 0 });
  return <div className="space-y-4">
    <div className="card p-4"><div className="mb-3"><div className="type-section-title font-bold text-text-primary">Filters</div><div className="type-body-sm text-text-secondary">Filter movement records by outlet, type, date range and item/reference search.</div></div><div className="grid gap-3 lg:grid-cols-5"><SelectField label="Outlet" value={filters.outletId} options={outletOptions} onChange={(value) => updateFilter("outletId", value)} searchable /><SelectField label="Movement Type" value={filters.movementType} options={[{ value: "all", label: "All Types" }, ...movementTypes.map((type) => ({ value: type, label: toTitle(type) }))]} onChange={(value) => updateFilter("movementType", value)} /><DatePickerField label="From" value={filters.from} onChange={(value) => updateFilter("from", value)} /><DatePickerField label="To" value={filters.to} onChange={(value) => updateFilter("to", value)} /><label><div className="mb-1 type-caption font-semibold text-text-secondary">Search Item / Reference</div><input className="control h-9 w-full text-[13px]" value={filters.search} onChange={(event) => updateFilter("search", event.target.value)} placeholder="Search item, PO no, notes" /></label></div></div>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><MetricCard icon={PackagePlus} label="Purchase In" value={summary.purchase} helper="Received inventory records" tone="success" size="compact" /><MetricCard icon={Truck} label="Transfer" value={summary.transfer} helper="Transfer in/out records" tone="info" size="compact" /><MetricCard icon={Trash2} label="Waste" value={summary.waste} helper="Waste movement records" tone="warning" size="compact" /><MetricCard icon={Warehouse} label="Adjustments" value={summary.adjustment} helper="Manual correction records" tone="neutral" size="compact" /></div>
    <div className="card p-4"><div className="mb-3"><div className="type-section-title font-bold text-text-primary">Movement Records</div><div className="type-body-sm text-text-secondary">Showing {filtered.length} record{filtered.length === 1 ? "" : "s"}</div></div>{filtered.length ? <><div className="overflow-x-auto"><table className="w-full min-w-[1080px] text-left"><thead className="text-[11px] uppercase tracking-wide text-text-muted"><tr className="border-b border-border"><th className="py-2">Date & Time</th><th>Outlet</th><th>Item</th><th>Movement Type</th><th>Qty / UOM</th><th>Reference No.</th><th>Notes</th><th>Created By</th><th className="text-right">Actions</th></tr></thead><tbody className="divide-y divide-border text-[13px]">{paginatedMovements.map((movement) => { const item = itemById.get(movement.itemId); const quantity = Number(movement.quantity || 0); const unit = movement.unit || item?.unit || ""; const hasReference = Boolean(movement.reference || movement.referenceId); return <tr key={movement.id}><td className="py-3">{formatDateTimeCompact(movement.dateTime || movement.date)}</td><td>{outletById.get(movement.outletId)?.name ?? "Unknown outlet"}</td><td className="font-bold text-text-primary">{item?.name ?? "Inventory item"}</td><td><span className={`inline-flex rounded-full border px-2 py-0.5 type-caption font-semibold ${typeClass(movement)}`}>{typeLabel(movement)}</span></td><td className={`font-semibold ${quantityClass(movement)}`}>{quantity > 0 ? "+" : ""}{quantity}{unit ? ` ${unit}` : ""}</td><td>{hasReference ? <button className="type-caption font-black text-primary underline-offset-2 hover:underline" type="button" onClick={() => onOpenReference(movement)}>{movement.reference || "Open reference"}</button> : "-"}</td><td>{movement.notes || "-"}</td><td>{actorNameByAnyId(movement.user || movement.createdBy)}</td><td className="text-right">{canEditMovement(movement) && canRecordMovement ? <button className="btn-secondary h-8 px-2.5 text-xs" type="button" onClick={() => onEditMovement(movement)}>Edit</button> : <span className="type-caption font-semibold text-text-muted">Read-only</span>}</td></tr>; })}</tbody></table></div><FactoryPagination page={pagination.page} pageSize={pagination.pageSize} total={filtered.length} onPageChange={pagination.setPage} onPageSizeChange={pagination.setPageSize} /></> : <EmptyState title="No inventory movements found." description={movements.length ? "Adjust filters to see more movement records." : "Purchase receiving and manual movements will appear here after they are saved to Supabase."} />}</div>
  </div>;
}
