import { cleanup, fireEvent, render, screen, waitFor, within } from "@testing-library/react";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { FactoryPermissionsProvider } from "../../context/FactoryPermissionsContext.jsx";
import FactoryMestiWasteDisposalPage from "../FactoryMestiWasteDisposalPage.jsx";
import { factoryService } from "../../../../services/factoryService.js";

vi.mock("../../../../services/factoryService.js", () => ({ factoryService: { getMestiWasteDisposalDaily: vi.fn(), listMestiWasteDisposalMonthly: vi.fn(), listMestiWasteDisposalRequirements: vi.fn(), listMestiWasteDisposalLocations: vi.fn(), saveMestiWasteDisposalRequirement: vi.fn(), recordMestiWasteDisposal: vi.fn(), submitMestiWasteDisposal: vi.fn(), verifyMestiWasteDisposal: vi.fn() } }));
const permissions = ["factory_mesti_waste_disposal.view", "factory_mesti_waste_disposal.manage", "factory_mesti_waste_disposal.record", "factory_mesti_waste_disposal.submit", "factory_mesti_waste_disposal.verify"];
const daily = { session: { id: "s1", status: "draft" }, locations: [{ location_id: "inside", location_name: "Inside Factory", required_count: 2, completed_count: 3, events: [{ id: "e1", disposed_at: "2026-09-04T02:20:00Z", completed_by_name: "Ahmad", remarks: "First" }, { id: "e2", disposed_at: "2026-09-04T04:35:00Z", completed_by_name: "Mei Ling" }, { id: "e3", disposed_at: "2026-09-04T08:00:00Z", completed_by_name: "Ahmad" }] }, { location_id: "outside", location_name: "Outside Factory", required_count: 1, completed_count: 0, events: [] }] };
const monthly = [{ location_id: "inside", location_name: "Inside Factory", days: { "2026-09-04": { required_count: 2, completed_count: 3, state: "verified_compliant", session_status: "verified", events: daily.locations[0].events, submitted_by_name: "Ahmad", verified_by_name: "Mei Ling" } } }];
function renderPage() { return render(<FactoryPermissionsProvider permissionSet={permissions} can={(permission) => permissions.includes(permission)}><FactoryMestiWasteDisposalPage auth={{ profile: { id: "employee-1" }}} onNotify={vi.fn()} /></FactoryPermissionsProvider>); }
beforeEach(() => { vi.clearAllMocks(); factoryService.getMestiWasteDisposalDaily.mockResolvedValue(daily); factoryService.listMestiWasteDisposalMonthly.mockResolvedValue(monthly); factoryService.listMestiWasteDisposalRequirements.mockResolvedValue([]); factoryService.listMestiWasteDisposalLocations.mockResolvedValue([{ id: "inside", location_name: "Inside Factory", status: "active" }]); factoryService.recordMestiWasteDisposal.mockResolvedValue({}); factoryService.submitMestiWasteDisposal.mockResolvedValue({}); factoryService.verifyMestiWasteDisposal.mockRejectedValue(new Error("Self-verification is not allowed.")); });
afterEach(cleanup);
describe("Factory MeSTI Waste Disposal", () => {
  it("shows count-based daily completion and records multiple events", async () => { renderPage(); expect(await screen.findByText("3 / 2 Completed")).not.toBeNull(); fireEvent.click(screen.getAllByRole("button", { name: "Record Disposal" })[0]); fireEvent.click(within(screen.getByRole("dialog", { name: "Record Disposal" })).getByRole("button", { name: "Record Disposal", exact: true })); await waitFor(() => expect(factoryService.recordMestiWasteDisposal).toHaveBeenCalledWith(expect.any(String), expect.objectContaining({ location_id: "inside" }))); });
  it("renders a Location-centric monthly matrix and audit drawer", async () => { renderPage(); fireEvent.click(screen.getByRole("tab", { name: "monthly" })); expect(await screen.findByText("Inside Factory")).not.toBeNull(); fireEvent.click(screen.getByRole("button", { name: "3/2" })); const dialog = await screen.findByRole("dialog", { name: /Inside Factory disposal evidence/ }); expect(within(dialog).getByText("Ahmad")).not.toBeNull(); expect(within(dialog).getByText("Mei Ling")).not.toBeNull(); });
  it("submits the daily session and surfaces the server self-verification block", async () => { renderPage(); fireEvent.click(await screen.findByRole("button", { name: "Submit Daily Record" })); await waitFor(() => expect(factoryService.submitMestiWasteDisposal).toHaveBeenCalled()); });
});
