import { cleanup, fireEvent, render, screen, waitFor, within } from "@testing-library/react";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { FactoryPermissionsProvider } from "../../context/FactoryPermissionsContext.jsx";
import FactoryMestiWasteDisposalPage from "../FactoryMestiWasteDisposalPage.jsx";
import { factoryService } from "../../../../services/factoryService.js";

vi.mock("../../../../services/factoryService.js", () => ({ factoryService: { getMestiWasteDisposalDaily: vi.fn(), listMestiWasteDisposalMonthly: vi.fn(), listMestiWasteDisposalRequirements: vi.fn(), listMestiWasteDisposalLocations: vi.fn(), saveMestiWasteDisposalRequirement: vi.fn(), recordMestiWasteDisposal: vi.fn(), submitMestiWasteDisposal: vi.fn(), verifyMestiWasteDisposal: vi.fn() } }));
const permissions = ["factory_mesti_waste_disposal.view", "factory_mesti_waste_disposal.manage", "factory_mesti_waste_disposal.record", "factory_mesti_waste_disposal.submit", "factory_mesti_waste_disposal.verify"];
const daily = { session: { id: "s1", status: "draft" }, locations: [{ location_id: "inside", location_name: "Inside Factory", required_count: 2, completed_count: 3, events: [{ id: "e1", disposed_at: "2026-09-04T02:20:00Z", completed_by_name: "Ahmad", remarks: "First" }, { id: "e2", disposed_at: "2026-09-04T04:35:00Z", completed_by_name: "Mei Ling" }, { id: "e3", disposed_at: "2026-09-04T08:00:00Z", completed_by_name: "Ahmad" }] }, { location_id: "outside", location_name: "Outside Factory", required_count: 1, completed_count: 0, events: [] }] };
const monthly = [{ logical_requirement_id: "waste-inside", location_id: "inside", location_name: "Inside Factory", frequency: "weekly", recurrence_weekdays: [5], days: { "2026-09-04": { disposal_date: "2026-09-04", required_count: 2, completed_count: 3, session_status: "verified", events: daily.locations[0].events, submitted_by_name: "Ahmad", verified_by_name: "Mei Ling" } } }];
function renderPage() { return render(<FactoryPermissionsProvider permissionSet={permissions} can={(permission) => permissions.includes(permission)}><FactoryMestiWasteDisposalPage auth={{ profile: { id: "employee-1" }}} onNotify={vi.fn()} /></FactoryPermissionsProvider>); }
beforeEach(() => { vi.clearAllMocks(); factoryService.getMestiWasteDisposalDaily.mockResolvedValue(daily); factoryService.listMestiWasteDisposalMonthly.mockResolvedValue(monthly); factoryService.listMestiWasteDisposalRequirements.mockResolvedValue([]); factoryService.listMestiWasteDisposalLocations.mockResolvedValue([{ id: "inside", location_name: "Inside Factory", status: "active" }]); factoryService.recordMestiWasteDisposal.mockResolvedValue({}); factoryService.submitMestiWasteDisposal.mockResolvedValue({}); factoryService.verifyMestiWasteDisposal.mockRejectedValue(new Error("Self-verification is not allowed.")); });
afterEach(cleanup);
describe("Factory MeSTI Waste Disposal", () => {
  it("shows count-based daily completion and records multiple events", async () => { renderPage(); expect(await screen.findByText("3 / 2 completed")).not.toBeNull(); const record = screen.getAllByRole("button", { name: "Record Disposal" })[0]; expect(record.className).toContain("btn-primary"); expect(screen.getByRole("button", { name: "View Inside Factory details" })).not.toBeNull(); fireEvent.click(record); fireEvent.click(within(screen.getByRole("dialog", { name: "Record Disposal" })).getByRole("button", { name: "Record Disposal", exact: true })); await waitFor(() => expect(factoryService.recordMestiWasteDisposal).toHaveBeenCalledWith(expect.any(String), expect.objectContaining({ location_id: "inside" }))); });
  it("renders scheduled Monthly cells with inline lifecycle actions and evidence", async () => { renderPage(); fireEvent.click(screen.getByRole("tab", { name: "Monthly" })); expect(await screen.findByText("Inside Factory")).not.toBeNull(); expect(screen.getByText("Weekly · Fri")).not.toBeNull(); expect(screen.queryByRole("button", { name: "Inside Factory: 0/2" })).toBeNull(); fireEvent.click(screen.getByRole("button", { name: "Inside Factory: 3/2" })); expect(await screen.findByLabelText("Waste disposal monthly actions")).not.toBeNull(); fireEvent.click(screen.getByRole("button", { name: "View Inside Factory disposal evidence" })); const dialog = await screen.findByRole("dialog", { name: /Inside Factory disposal evidence/ }); expect(within(dialog).getByText("Ahmad")).not.toBeNull(); expect(within(dialog).getByText("Mei Ling")).not.toBeNull(); });
  it("uses the canonical Monthly submit and verify transitions", async () => { factoryService.listMestiWasteDisposalMonthly.mockResolvedValue([{ ...monthly[0], days: { "2026-09-04": { ...monthly[0].days["2026-09-04"], session_status: "draft" } } }]); renderPage(); fireEvent.click(screen.getByRole("tab", { name: "Monthly" })); fireEvent.click(await screen.findByRole("button", { name: "Inside Factory: 3/2" })); fireEvent.click(screen.getByRole("button", { name: "Submit" })); await waitFor(() => expect(factoryService.submitMestiWasteDisposal).toHaveBeenCalledWith("2026-09-04")); cleanup(); factoryService.listMestiWasteDisposalMonthly.mockResolvedValue([{ ...monthly[0], days: { "2026-09-04": { ...monthly[0].days["2026-09-04"], session_status: "submitted" } } }]); factoryService.verifyMestiWasteDisposal.mockResolvedValue({}); renderPage(); fireEvent.click(screen.getByRole("tab", { name: "Monthly" })); fireEvent.click(await screen.findByRole("button", { name: "Inside Factory: 3/2" })); fireEvent.click(screen.getByRole("button", { name: "Verify" })); await waitFor(() => expect(factoryService.verifyMestiWasteDisposal).toHaveBeenCalledWith("2026-09-04")); });
  it("submits the daily session and surfaces the server self-verification block", async () => { renderPage(); fireEvent.click(await screen.findByRole("button", { name: "Submit Daily Record" })); await waitFor(() => expect(factoryService.submitMestiWasteDisposal).toHaveBeenCalled()); });
  it("configures weekly Waste requirements with explicit weekdays", async () => { renderPage(); fireEvent.click(screen.getByRole("tab", { name: "Setup" })); fireEvent.click(await screen.findByRole("button", { name: "Create Requirement" })); const dialog = screen.getByRole("dialog", { name: "New Waste Disposal Requirement" }); fireEvent.click(within(dialog).getByText("Daily", { exact: true })); fireEvent.click(await screen.findByRole("button", { name: "Weekly" })); fireEvent.click(within(dialog).getByLabelText("Wed")); fireEvent.click(within(dialog).getByRole("button", { name: "Save Requirement" })); await waitFor(() => expect(factoryService.saveMestiWasteDisposalRequirement).toHaveBeenCalledWith(expect.objectContaining({ frequency: "weekly", recurrence_weekdays: expect.arrayContaining([1, 3]) }))); });
});
