import { cleanup, fireEvent, render, screen, waitFor, within } from "@testing-library/react";
import { afterEach, describe, expect, it, vi } from "vitest";
import { factoryService } from "../../../../services/factoryService.js";
import FactoryWorkspacePage from "../FactoryWorkspacePage.jsx";

const raw = { id: "raw-check", check_no: "RSC-1", status: "submitted", check_date: "2026-08-09", items: [{ id: "r1", raw_material_id: "rm-1", raw_material_name: "Chili", system_qty: 5, physical_qty: 4, uom: "kg", count_status: "counted", variance_reason: "count" }] };
const product = { id: "product-check", check_no: "PSC-1", status: "submitted", check_date: "2026-08-09", items: [{ id: "p1", finished_good_id: "sku-1", product_name: "Sambal", system_qty: 5, physical_qty: 4, count_status: "counted", variance_reason: "count", batch_allocations: [{ batch_balance_id: "fg-batch", quantity: 1 }] }] };
const perms = ["factory_raw_stock_check.view", "factory_raw_stock_check.create", "factory_raw_stock_check.edit", "factory_raw_stock_check.submit", "factory_raw_stock_check.approve", "factory_raw_stock_check.delete", "factory_product_stock_check.view", "factory_product_stock_check.create", "factory_product_stock_check.edit", "factory_product_stock_check.submit", "factory_product_stock_check.approve"];
const auth = { permissions: perms, hasPermission: (key) => perms.includes(key), profile: { id: "employee-1", nickname: "Isaac" } };
function data(check, type) { return { jobOrders: [], rawMaterials: [{ id: "rm-1", name: "Chili", name_en: "Chili", uom: "kg", status: "active", category_id: "cat-1", current_balance: 5 }], rawMaterialCategories: [{ id: "cat-1", name: "Spices", status: "active" }], rawMaterialMovements: [], receivings: [], receivingBatches: [], factorySuppliers: [], factoryCustomers: [], storageLocations: [{ id: "fg-loc", location_name: "FG", location_type: "Finished Goods Area", status: "active" }], productions: [], finishedGoods: [{ id: "sku-1", product_name: "Sambal", status: "active", category_id: "fg-cat", current_balance: 5, storage_location_id: "fg-loc", storage_location_ref: { status: "active", location_type: "Finished Goods Area" } }], finishedGoodCategories: [{ id: "fg-cat", name: "Packaging", status: "active" }], productFamilies: [], productMovements: [], finishedGoodDispatches: [], rawStockChecks: type === "raw" ? [check] : [], productStockChecks: type === "product" ? [check] : [], recipes: [], sops: [], qcChecklistTemplates: [], auditLogs: [], accessIssues: [] }; }
function mount(type, check, ui = { notify: vi.fn(), confirm: vi.fn().mockResolvedValue(true) }, testAuth = auth) { vi.spyOn(factoryService, "listFactoryData").mockResolvedValue(data(check, type)); const listing = vi.spyOn(factoryService, "listFactoryListingPage").mockResolvedValue({ rows: [check], summary: { submitted: 1, checks: 1 }, totalCount: 1, page: 1, pageSize: 20 }); vi.spyOn(factoryService, "getStockCheckNoPreview").mockResolvedValue(type === "raw" ? "RSC-NEW" : "PSC-NEW"); vi.spyOn(factoryService, "getFinishedGoodInventoryReconciliation").mockResolvedValue([{ finished_good_id: "sku-1", reconciliation_status: "ok" }]); return { listing, ui, ...render(<FactoryWorkspacePage initialTab={type === "raw" ? "raw-stock-check" : "product-stock-check"} auth={testAuth} ui={ui} />) }; }
function checkRow(reference) { return screen.getAllByText(reference).map((node) => node.closest("tr")).find(Boolean); }
afterEach(() => { cleanup(); vi.restoreAllMocks(); });
describe("Factory Stock Check mounted lifecycle", () => {
  it.each([["raw", raw], ["product", product]])("approves submitted %s checks once, updates the row, and refreshes listing plus Factory data", async (type, check) => { const { listing } = mount(type, check); const approve = vi.spyOn(factoryService, "approveStockCheck").mockResolvedValue(); await screen.findAllByText(check.check_no); fireEvent.click(within(checkRow(check.check_no)).getByRole("button", { name: "Approve" })); await waitFor(() => expect(approve).toHaveBeenCalledWith(type, check, "employee-1")); expect(approve).toHaveBeenCalledTimes(1); await waitFor(() => expect(listing).toHaveBeenCalledTimes(2)); await waitFor(() => expect(factoryService.listFactoryData).toHaveBeenCalledTimes(2)); });
  it.each([["raw", raw], ["product", product]])("does not mark %s checks approved or refresh after rejection, then permits a successful retry", async (type, check) => { const notify = vi.fn(); const { listing } = mount(type, check, { notify, confirm: vi.fn().mockResolvedValue(true) }); const approve = vi.spyOn(factoryService, "approveStockCheck").mockRejectedValueOnce(new Error("reject")).mockResolvedValueOnce(); await screen.findAllByText(check.check_no); const approveButton = within(checkRow(check.check_no)).getByRole("button", { name: "Approve" }); fireEvent.click(approveButton); await waitFor(() => expect(approve).toHaveBeenCalledTimes(1)); expect(listing).toHaveBeenCalledTimes(1); expect(factoryService.listFactoryData).toHaveBeenCalledTimes(1); expect(notify).toHaveBeenCalledWith(expect.objectContaining({ title: "Unable to approve Stock Check.", tone: "error" })); fireEvent.click(approveButton); await waitFor(() => expect(approve).toHaveBeenCalledTimes(2)); await waitFor(() => expect(listing).toHaveBeenCalledTimes(2)); await waitFor(() => expect(factoryService.listFactoryData).toHaveBeenCalledTimes(2)); });
  it.each([["raw", raw, "Spices"], ["product", product, "Packaging"]])("saves a new %s stock-check draft through the mounted modal", async (type, check, category) => { const { listing } = mount(type, check); const save = vi.spyOn(factoryService, "saveStockCheck").mockResolvedValue({ ...check, id: `new-${type}`, status: "draft" }); fireEvent.click(await screen.findByRole("button", { name: "New Stock Check" })); fireEvent.click(screen.getByRole("button", { name: type === "raw" ? "Category *" : "Category" })); fireEvent.click(await screen.findByText(category)); await waitFor(() => expect(screen.getAllByRole("spinbutton").length).toBeGreaterThan(0)); fireEvent.change(screen.getAllByRole("spinbutton")[0], { target: { value: "5" } }); fireEvent.click(screen.getByRole("button", { name: "Save Draft" })); await waitFor(() => expect(save).toHaveBeenCalledTimes(1)); expect(save).toHaveBeenCalledWith(type, expect.objectContaining({ status: "draft", check_date: expect.any(String), items: [expect.objectContaining({ [type === "raw" ? "raw_material_id" : "finished_good_id"]: type === "raw" ? "rm-1" : "sku-1", physical_qty: "5" })] }), "employee-1"); await waitFor(() => expect(listing).toHaveBeenCalledTimes(2)); expect(factoryService.listFactoryData).toHaveBeenCalledTimes(1); });
  it.each([["raw", raw], ["product", product]])("deduplicates rapid %s approval while the first approval is pending", async (type, check) => { let resolve; const pending = new Promise((done) => { resolve = done; }); const { listing } = mount(type, check); const approve = vi.spyOn(factoryService, "approveStockCheck").mockReturnValue(pending); await screen.findAllByText(check.check_no); const button = within(checkRow(check.check_no)).getByRole("button", { name: "Approve" }); fireEvent.click(button); fireEvent.click(button); await waitFor(() => expect(approve).toHaveBeenCalledTimes(1)); resolve(); await waitFor(() => expect(listing).toHaveBeenCalledTimes(2)); });
  it.each([["raw", { ...raw, status: "draft" }], ["product", { ...product, status: "draft" }]])("keeps draft mutation actions in the row overflow and deletes eligible %s checks once", async (type, check) => { const { listing } = mount(type, check); const remove = vi.spyOn(factoryService, "deleteStockCheck").mockResolvedValue(); await screen.findAllByText(check.check_no); const row = checkRow(check.check_no); expect(within(row).queryByRole("button", { name: "Delete" })).toBeNull(); fireEvent.click(within(row).getByRole("button", { name: "More row actions" })); fireEvent.click(await screen.findByRole("button", { name: "Delete" })); await waitFor(() => expect(remove).toHaveBeenCalledWith(type, check)); await waitFor(() => expect(listing).toHaveBeenCalledTimes(2)); await waitFor(() => expect(factoryService.listFactoryData).toHaveBeenCalledTimes(2)); });
  it.each([["raw", raw, "factory_raw_stock_check"], ["product", product, "factory_product_stock_check"]])("hides %s create and approval actions without the current permission, and keeps submitted rows non-editable", async (type, check, permissionPrefix) => { const viewOnly = { permissions: [`${permissionPrefix}.view`], hasPermission: (key) => key === `${permissionPrefix}.view`, profile: { id: "employee-1" } }; mount(type, check, undefined, viewOnly); await screen.findAllByText(check.check_no); expect(screen.queryByRole("button", { name: "New Stock Check" })).toBeNull(); expect(screen.queryByRole("button", { name: "Approve" })).toBeNull(); expect(screen.queryByRole("button", { name: "Edit" })).toBeNull(); expect(screen.queryByRole("button", { name: "Delete" })).toBeNull(); });
});
