import { useEffect, useMemo, useState } from "react";
import AdminFormField from "../../../components/forms/AdminFormField.jsx";
import DatePickerField from "../../../components/forms/DatePickerField.jsx";
import Modal from "../../../components/feedback/Modal.jsx";
import { employmentContractTemplateService, employmentDocumentService } from "../../../services/employmentDocumentService.js";

const malaysiaToday = () => new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Kuala_Lumpur", year: "numeric", month: "2-digit", day: "2-digit" }).format(new Date());
const defaultsFor = (employee) => ({
  employee_context: { position: employee?.position || "", workplace: employee?.workplace || "", employment_type: employee?.employment_type || "", commencement_date: employee?.joined_date || malaysiaToday() },
  currency: "MYR", basic_salary: "", salary_payment_period: "monthly", allowances: [], probation_months: "0", working_days_per_week: "5", working_days_description: "", normal_hours_per_day: "8", normal_hours_description: "", rest_days: [], notice_period_value: "1", notice_period_unit: "months", additional_terms: "", effective_date: malaysiaToday(),
});

function TermsForm({ terms, patch }) {
  const context = terms.employee_context;
  const patchContext = (key, value) => patch("employee_context", { ...context, [key]: value });
  const patchAllowance = (index, key, value) => patch("allowances", terms.allowances.map((allowance, allowanceIndex) => allowanceIndex === index ? { ...allowance, [key]: value } : allowance));
  return <div className="grid gap-4 md:grid-cols-2">
    <div className="md:col-span-2 rounded-xl border border-amber-200 bg-amber-50 px-3 py-2.5 text-sm text-amber-950"><strong>Contract-only context</strong><p className="mt-0.5 text-xs">These confirmed values are snapshotted into this contract and do not update Employee, Payroll or Roster records.</p></div>
    <AdminFormField label="Position" required><input className="control" value={context.position} onChange={(event) => patchContext("position", event.target.value)} /></AdminFormField>
    <AdminFormField label="Workplace" required><input className="control" value={context.workplace} onChange={(event) => patchContext("workplace", event.target.value)} /></AdminFormField>
    <AdminFormField label="Employment Type" required><input className="control" value={context.employment_type} onChange={(event) => patchContext("employment_type", event.target.value)} /></AdminFormField>
    <DatePickerField label="Commencement Date" required value={context.commencement_date} onChange={(value) => patchContext("commencement_date", value)} />
    <AdminFormField label="Basic Salary (MYR)" required><input className="control" inputMode="decimal" min="0" type="number" value={terms.basic_salary} onChange={(event) => patch("basic_salary", event.target.value)} /></AdminFormField>
    <AdminFormField label="Salary Payment Period" required><select className="control" value={terms.salary_payment_period} onChange={(event) => patch("salary_payment_period", event.target.value)}><option value="monthly">Monthly</option><option value="daily">Daily</option><option value="hourly">Hourly</option></select></AdminFormField>
    <AdminFormField label="Probation" required><select className="control" value={terms.probation_months} onChange={(event) => patch("probation_months", event.target.value)}><option value="0">No probation</option>{[1, 2, 3, 6, 12, 24].map((month) => <option key={month} value={month}>{month} month{month > 1 ? "s" : ""}</option>)}</select></AdminFormField>
    <AdminFormField label="Working Days per Week" required><input className="control" min="1" max="7" type="number" value={terms.working_days_per_week} onChange={(event) => patch("working_days_per_week", event.target.value)} /></AdminFormField>
    <AdminFormField label="Normal Working Hours per Day" required><input className="control" min="0.25" max="24" step="0.25" type="number" value={terms.normal_hours_per_day} onChange={(event) => patch("normal_hours_per_day", event.target.value)} /></AdminFormField>
    <AdminFormField label="Rest Day(s)" required helper="Separate days with commas."><input className="control" value={terms.rest_days.join(", ")} onChange={(event) => patch("rest_days", event.target.value.split(",").map((value) => value.trim()).filter(Boolean))} /></AdminFormField>
    <div className="grid grid-cols-[1fr_1fr] gap-2"><AdminFormField label="Notice Period" required><input className="control" min="1" max="120" type="number" value={terms.notice_period_value} onChange={(event) => patch("notice_period_value", event.target.value)} /></AdminFormField><AdminFormField label="Unit" required><select className="control" value={terms.notice_period_unit} onChange={(event) => patch("notice_period_unit", event.target.value)}><option value="days">Days</option><option value="weeks">Weeks</option><option value="months">Months</option></select></AdminFormField></div>
    <AdminFormField label="Working Days Description" helper="Optional" className="md:col-span-2"><textarea className="control min-h-20 py-3" value={terms.working_days_description} onChange={(event) => patch("working_days_description", event.target.value)} /></AdminFormField>
    <AdminFormField label="Normal Working Hours Description" helper="Optional" className="md:col-span-2"><textarea className="control min-h-20 py-3" value={terms.normal_hours_description} onChange={(event) => patch("normal_hours_description", event.target.value)} /></AdminFormField>
    <section className="md:col-span-2 rounded-xl border border-border p-3"><div className="flex items-center justify-between gap-3"><div><strong className="text-sm">Allowances</strong><p className="text-xs text-text-muted">Optional contract terms. Maximum 12 entries.</p></div><button className="btn-secondary px-3 py-2 text-xs" disabled={terms.allowances.length >= 12} type="button" onClick={() => patch("allowances", [...terms.allowances, { name: "", amount: "" }])}>+ Add allowance</button></div>{terms.allowances.map((allowance, index) => <div className="mt-2 grid grid-cols-[1fr_130px_auto] gap-2" key={index}><input aria-label={`Allowance ${index + 1} name`} className="control" placeholder="Allowance name" value={allowance.name} onChange={(event) => patchAllowance(index, "name", event.target.value)} /><input aria-label={`Allowance ${index + 1} amount`} className="control" inputMode="decimal" min="0" placeholder="MYR" type="number" value={allowance.amount} onChange={(event) => patchAllowance(index, "amount", event.target.value)} /><button className="text-xs font-semibold text-rose-700" type="button" onClick={() => patch("allowances", terms.allowances.filter((_, allowanceIndex) => allowanceIndex !== index))}>Remove</button></div>)}</section>
    <AdminFormField label="Additional Terms" helper="Optional · Contract-only text" className="md:col-span-2"><textarea className="control min-h-28 py-3" maxLength={4000} value={terms.additional_terms} onChange={(event) => patch("additional_terms", event.target.value)} /></AdminFormField>
  </div>;
}

export default function EmploymentContractBuilderModal({ employee, employer, supersedesDocumentId, onClose, onSaved, ui }) {
  const [step, setStep] = useState(0);
  const [templates, setTemplates] = useState([]);
  const [templateVersionId, setTemplateVersionId] = useState("");
  const [terms, setTerms] = useState(() => defaultsFor(employee));
  const [title, setTitle] = useState("Employment Contract");
  const [documentId, setDocumentId] = useState(null);
  const [preview, setPreview] = useState(null);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const template = useMemo(() => templates.find((item) => item.current_published_version?.id === templateVersionId), [templates, templateVersionId]);
  useEffect(() => { if (!employer?.id) return; employmentContractTemplateService.list(employer.id).then((items) => { const available = items.filter((item) => item.is_active && item.current_published_version); setTemplates(available); const preferred = available.find((item) => item.is_default) || available[0]; if (preferred) setTemplateVersionId(preferred.current_published_version.id); }).catch((cause) => setError(cause.message || "Unable to load published contract templates.")); }, [employer?.id]);
  function patch(key, value) { setTerms((current) => ({ ...current, [key]: value })); setPreview(null); }
  const termsComplete = templateVersionId && title.trim() && terms.employee_context.position.trim() && terms.employee_context.workplace.trim() && terms.employee_context.employment_type.trim() && terms.employee_context.commencement_date && terms.effective_date && terms.basic_salary !== "" && terms.rest_days.length && terms.allowances.every((allowance) => allowance.name.trim() && allowance.amount !== "");
  async function saveDraft() {
    const saved = await employmentDocumentService.saveTemplateDraft({ documentId, employeeId: employee.id, title, effectiveDate: terms.effective_date, templateVersionId, terms: { ...terms, basic_salary: Number(terms.basic_salary), probation_months: Number(terms.probation_months), working_days_per_week: Number(terms.working_days_per_week), normal_hours_per_day: Number(terms.normal_hours_per_day), notice_period_value: Number(terms.notice_period_value), allowances: terms.allowances.map((allowance) => ({ ...allowance, amount: Number(allowance.amount) })) }, requestId: documentId ? crypto.randomUUID() : crypto.randomUUID(), supersedesDocumentId });
    setDocumentId(saved.id); return saved;
  }
  async function generatePreview() { setBusy(true); setError(""); try { const saved = await saveDraft(); const result = await employmentDocumentService.previewTemplateContract(saved.id); setPreview(result); setStep(2); } catch (cause) { setError(cause.message || "Unable to generate the exact contract preview."); } finally { setBusy(false); } }
  async function send() { if (!documentId) return; setBusy(true); setError(""); try { await employmentDocumentService.send(documentId); ui?.notify?.({ title: "Employment contract sent." }); await onSaved(); onClose(); } catch (cause) { setError(cause.message || "Unable to send employment contract."); } finally { setBusy(false); } }
  const footer = <><button className="btn-secondary" disabled={busy} type="button" onClick={onClose}>Cancel</button>{step > 0 ? <button className="btn-secondary" disabled={busy} type="button" onClick={() => setStep(step - 1)}>Back</button> : null}{step === 0 ? <button className="btn-primary" disabled={!templateVersionId || busy} type="button" onClick={() => setStep(1)}>Continue to Terms</button> : null}{step === 1 ? <button className="btn-primary" disabled={!termsComplete || busy} type="button" onClick={generatePreview}>{busy ? "Generating..." : "Generate Exact Preview"}</button> : null}{step === 2 ? <button className="btn-primary" disabled={busy || !preview?.document_url} type="button" onClick={send}>{busy ? "Sending..." : "Send to Employee"}</button> : null}</>;
  return <Modal size="xl" title={supersedesDocumentId ? "Supersede with Template Contract" : "Create Employment Contract"} description="Template → confirmed terms → exact server-generated PDF → existing Employment Documents acknowledgement lifecycle." onClose={onClose} footer={footer}>
    <div className="mb-5 flex gap-2 text-xs font-bold uppercase tracking-wide text-text-muted">{["Template", "Terms", "Preview & Send"].map((label, index) => <span className={index === step ? "text-emerald-800" : ""} key={label}>{index + 1}. {label}</span>)}</div>
    {!employer?.is_active ? <div className="rounded-xl border border-amber-200 bg-amber-50 p-3 text-sm text-amber-950">Assign an active Legal Employer before creating a contract.</div> : null}
    {step === 0 ? <div className="space-y-4"><div className="rounded-xl border border-border bg-slate-50 p-3 text-sm"><strong>Legal Employer</strong><p className="mt-1">{employer?.display_name || employer?.legal_company_name || "Not assigned"}{employer?.company_registration_no ? ` · ${employer.company_registration_no}` : ""}</p></div><AdminFormField label="Published Template" required><select className="control" value={templateVersionId} onChange={(event) => { setTemplateVersionId(event.target.value); setPreview(null); }}><option value="">Select a published template</option>{templates.map((item) => <option key={item.current_published_version.id} value={item.current_published_version.id}>{item.title} · {item.contract_kind === "full_time" ? "Full-Time" : "Part-Time"}{item.is_default ? " · Default" : ""}</option>)}</select></AdminFormField>{!templates.length ? <p className="rounded-xl border border-dashed border-border p-3 text-sm text-text-muted">No published contract template is available for this Legal Employer. Create and publish one under Legal Entities first.</p> : null}{template ? <div className="rounded-xl border border-border p-3 text-sm"><strong>{template.title}</strong><p className="mt-1 text-text-muted">Version {template.current_published_version.version_number} · {template.current_published_version.sections.length} approved clause sections</p></div> : null}</div> : null}
    {step === 1 ? <div className="space-y-4"><AdminFormField label="Document Title" required><input className="control" value={title} onChange={(event) => { setTitle(event.target.value); setPreview(null); }} /></AdminFormField><DatePickerField label="Effective Date" required value={terms.effective_date} onChange={(value) => patch("effective_date", value)} /><TermsForm terms={terms} patch={patch} /></div> : null}
    {step === 2 ? <div className="space-y-4"><div className="rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-950"><strong>Exact PDF preview</strong><p className="mt-1">This server-generated PDF and SHA-256 will be pinned unchanged when sent. Editing terms or changing the template requires a new preview.</p></div>{preview?.document_url ? <iframe className="h-[520px] w-full rounded-xl border border-border" title="Employment contract preview" src={preview.document_url} /> : null}{preview?.document_sha256 ? <p className="break-all text-xs text-text-muted">SHA-256 {preview.document_sha256}</p> : null}</div> : null}
    {error ? <div className="mt-4 rounded-xl border border-rose-200 bg-rose-50 px-3 py-2 text-sm font-semibold text-rose-700" role="alert">{error}</div> : null}
  </Modal>;
}
