import { useEffect, useMemo, useState } from "react";
import { CalendarDays, Check, Clock3, Search, X } from "lucide-react";
import PageHeader from "../../../components/layout/PageHeader.jsx";
import Card from "../../../components/ui/Card.jsx";
import Badge from "../../../components/ui/Badge.jsx";
import DataTable from "../../../components/tables/DataTable.jsx";
import Modal from "../../../components/feedback/Modal.jsx";
import { crewService } from "../../../services/crewService.js";

const typeLabel = { annual: "Annual Leave", medical: "Medical Leave / MC", unpaid: "Unpaid Leave", other: "Other Leave" };
const statusTone = { pending: "warning", approved: "success", rejected: "danger", cancelled: "neutral" };
const formatDate = (value) => value ? new Date(`${String(value).slice(0, 10)}T00:00:00`).toLocaleDateString("en-MY", { day: "numeric", month: "short", year: "numeric" }) : "—";
const rosterLabel = (schedule) => !schedule || schedule === "null" ? "No published roster" : schedule.entry_type === "working" ? `${String(schedule.start_time).slice(0, 5)} – ${String(schedule.end_time).slice(0, 5)}` : schedule.template_name || schedule.entry_type;

export default function CrewLeaveAdminPage({ auth, store, ui }) {
  const outlets = (store?.outlets || []).filter((outlet) => auth.canAccessOutlet?.(outlet.id) ?? true);
  const [outletId, setOutletId] = useState(outlets[0]?.id || "");
  const [data, setData] = useState({ requests: [] });
  const [loading, setLoading] = useState(true);
  const [filters, setFilters] = useState({ search: "", type: "all", status: "all" });
  const [review, setReview] = useState(null);
  const [saving, setSaving] = useState(false);
  const canReview = auth.hasPermission("crew_leave.review");
  const load = async () => { if (!outletId) return; setLoading(true); try { setData(await crewService.leaveAdminData(outletId)); } catch (cause) { ui.notify({ title: "Unable to load leave requests", message: cause.message, tone: "error" }); } finally { setLoading(false); } };
  useEffect(() => { load(); }, [outletId]);
  const rows = useMemo(() => data.requests.filter((row) => (filters.type === "all" || row.leave_type === filters.type) && (filters.status === "all" || row.status === filters.status) && (!filters.search || `${row.employee?.name} ${row.employee?.position}`.toLowerCase().includes(filters.search.toLowerCase()))), [data, filters]);
  const decide = async (decision, reason = null) => { setSaving(true); try { await crewService.reviewLeave(review.id, decision, reason); ui.notify({ title: decision === "approve" ? "Leave approved" : "Leave rejected", message: decision === "approve" ? "The approved leave is now projected into Duty Roster." : "The employee can see the safe rejection reason.", tone: "success" }); setReview(null); await load(); } catch (cause) { ui.notify({ title: "Unable to review leave", message: cause.message, tone: "error" }); } finally { setSaving(false); } };

  return <div className="space-y-4">
    <PageHeader section="Crew · Workforce" title="Leave Requests" description="Review employee leave with published and draft roster context before making a decision." actions={<label className="field min-w-56"><span>Outlet</span><select value={outletId} onChange={(event) => setOutletId(event.target.value)}>{outlets.map((outlet) => <option key={outlet.id} value={outlet.id}>{outlet.name}</option>)}</select></label>} />
    <Card><div className="grid gap-3 md:grid-cols-[minmax(240px,1fr)_200px_200px]"><label className="field"><span>Search Employee</span><div className="relative"><Search className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-text-muted" size={16} /><input className="w-full pl-9" value={filters.search} onChange={(event) => setFilters((current) => ({ ...current, search: event.target.value }))} placeholder="Name or position" /></div></label><label className="field"><span>Leave Type</span><select value={filters.type} onChange={(event) => setFilters((current) => ({ ...current, type: event.target.value }))}><option value="all">All</option>{Object.entries(typeLabel).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="field"><span>Status</span><select value={filters.status} onChange={(event) => setFilters((current) => ({ ...current, status: event.target.value }))}><option value="all">All</option>{["pending", "approved", "rejected", "cancelled"].map((value) => <option key={value} value={value}>{value[0].toUpperCase() + value.slice(1)}</option>)}</select></label></div></Card>
    <Card title="Leave Requests" description="Approved leave is employee-level evidence. Duty Roster is a controlled projection, not the source of truth.">{loading ? <div className="p-8 text-sm font-semibold text-text-secondary">Loading leave requests…</div> : <DataTable tableClassName="min-w-[1120px]" rows={rows} getRowKey={(row) => row.id} columns={[
      { key: "employee", header: "Employee", render: (row) => <div><div className="font-bold">{row.employee?.name}</div><div className="text-xs text-text-secondary">{row.employee?.position || "Crew"}</div></div> },
      { key: "type", header: "Leave Type", render: (row) => typeLabel[row.leave_type] },
      { key: "dates", header: "Dates", render: (row) => <div><div className="font-semibold">{formatDate(row.start_date)}{row.start_date !== row.end_date ? ` – ${formatDate(row.end_date)}` : ""}</div><div className="text-xs text-text-secondary">{row.requested_days} day{Number(row.requested_days) === 1 ? "" : "s"}{row.duration_type === "half_day" ? ` · ${row.half_day_period.toUpperCase()}` : ""}</div></div> },
      { key: "submitted", header: "Submitted", render: (row) => new Date(row.submitted_at).toLocaleDateString("en-MY") },
      { key: "conflict", header: "Roster Conflict", render: (row) => { const working = row.roster_context?.filter((day) => day.schedule?.entry_type === "working") || []; return <Badge tone={working.length ? "warning" : "neutral"}>{working.length ? `${working.length} scheduled` : "None"}</Badge>; } },
      { key: "status", header: "Status", render: (row) => <Badge tone={statusTone[row.status]}>{row.status[0].toUpperCase() + row.status.slice(1)}</Badge> },
      { key: "action", header: "Action", align: "right", render: (row) => <button className="btn-secondary" type="button" onClick={() => setReview(row)}>{row.status === "pending" && canReview ? "Review" : "View"}</button> },
    ]} />}</Card>
    {review && <LeaveReview request={review} canReview={canReview} saving={saving} onClose={() => setReview(null)} onDecide={decide} />}
  </div>;
}

function LeaveReview({ request, canReview, saving, onClose, onDecide }) {
  const [mode, setMode] = useState("review"); const [reason, setReason] = useState("");
  const working = request.roster_context?.filter((item) => item.schedule?.entry_type === "working") || [];
  return <Modal size="xl" title="Leave Request" description={`${request.employee?.name} · ${request.employee?.position || "Crew"} · ${request.outlet?.name}`} onClose={onClose} footer={mode === "reject" ? <><button className="btn-secondary" type="button" onClick={() => setMode("review")}>Back</button><button className="btn-danger" type="button" disabled={saving || reason.trim().length < 2} onClick={() => onDecide("reject", reason)}>Confirm Rejection</button></> : mode === "approve" ? <><button className="btn-secondary" type="button" onClick={() => setMode("review")}>Back</button><button className="btn-primary" type="button" disabled={saving} onClick={() => onDecide("approve")}><Check size={16} /> Approve Leave</button></> : <><button className="btn-secondary" type="button" onClick={onClose}>Close</button>{request.status === "pending" && canReview && <><button className="btn-danger" type="button" onClick={() => setMode("reject")}><X size={16} /> Reject</button><button className="btn-primary" type="button" onClick={() => setMode("approve")}><Check size={16} /> Approve</button></>}</>}>
    <div className="grid gap-4 lg:grid-cols-[minmax(0,1fr)_minmax(320px,.9fr)]"><section className="space-y-3"><div className="rounded-xl bg-slate-50 p-4"><div className="grid gap-3 sm:grid-cols-2"><Detail label="Leave Type" value={typeLabel[request.leave_type]} /><Detail label="Dates" value={`${formatDate(request.start_date)}${request.start_date !== request.end_date ? ` – ${formatDate(request.end_date)}` : ""}`} /><Detail label="Duration" value={`${request.requested_days} day${Number(request.requested_days) === 1 ? "" : "s"}`} /><Detail label="Status" value={request.status[0].toUpperCase() + request.status.slice(1)} /></div></div><div><h3 className="font-bold text-text-primary">Reason</h3><p className="mt-2 whitespace-pre-wrap text-sm text-text-secondary">{request.reason}</p></div>{request.document_status === "not_uploaded" && <div className="rounded-xl border border-amber-200 bg-amber-50 p-3 text-sm text-amber-800">Supporting document not uploaded.</div>}{mode === "reject" && <label className="field"><span>Rejection Reason *</span><textarea rows="4" maxLength="1000" value={reason} onChange={(event) => setReason(event.target.value)} placeholder="Explain the decision in language safe to show the employee" /></label>}{mode === "approve" && <div className="rounded-xl border border-emerald-200 bg-emerald-50 p-4"><div className="font-bold text-emerald-800">Approve {typeLabel[request.leave_type]}?</div><p className="mt-1 text-sm text-emerald-700">Approval creates a formal Leave Record and projects it into the roster. Historical published revisions remain unchanged.</p></div>}</section><section><div className="mb-3 flex items-center gap-2"><CalendarDays size={18} className="text-primary" /><h3 className="font-bold text-text-primary">Roster Context</h3></div><div className="divide-y divide-border rounded-xl border border-border">{request.roster_context?.map((item) => <div className="flex items-center justify-between gap-4 p-3" key={item.date}><span><strong className="block text-sm">{formatDate(item.date)}</strong><small className="text-text-secondary">{item.schedule?.outlet_name || request.outlet?.name}</small></span><Badge tone={item.schedule?.entry_type === "working" ? "warning" : "neutral"}>{rosterLabel(item.schedule)}</Badge></div>)}</div>{working.length > 0 && <div className="mt-3 rounded-xl border border-amber-200 bg-amber-50 p-3 text-sm text-amber-800"><strong>This employee is currently scheduled on {working.length} requested date{working.length === 1 ? "" : "s"}.</strong><p className="mt-1">Approval supersedes the working projection while retaining its audit snapshot.</p></div>}</section></div>
  </Modal>;
}
function Detail({ label, value }) { return <div><div className="text-xs font-semibold text-text-muted">{label}</div><div className="mt-1 text-sm font-bold text-text-primary">{value}</div></div>; }
