import { useEffect, useState } from "react";
import { AlertTriangle, Calculator, CheckCircle2, ChevronRight, Gift, PiggyBank, Wallet } from "lucide-react";
import PageHeader from "../../../components/layout/PageHeader.jsx";
import Modal from "../../../components/feedback/Modal.jsx";
import Badge from "../../../components/ui/Badge.jsx";
import SelectField from "../../../components/forms/SelectField.jsx";
import DataTable from "../../../components/tables/DataTable.jsx";
import { crewService } from "../../../services/crewService.js";
import { outletService } from "../../../services/outletService.js";

const currentPeriod = () => `${new Date().toISOString().slice(0, 7)}-01`;
const money = (value) => `RM ${Number(value || 0).toLocaleString("en-MY", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
const percent = (value) => `${(Number(value || 0) * 100).toFixed(1)}%`;
const cycleStatus = (value) => ({ draft: "Draft", review: "Review", finalized: "Finalized", paid: "Paid" }[value] || value);
const entryStatus = (value) => ({ awaiting_performance: "Awaiting Performance", not_eligible: "Not Eligible", qualified: "Qualified", finalized: "Finalized", paid: "Paid" }[value] || value);
const statusTone = (value) => value === "paid" || value === "finalized" || value === "qualified" ? "success" : value === "review" || value === "awaiting_performance" ? "warning" : "neutral";

export default function CrewRewardAdminPage({ auth, ui, store, initialTab = "overview" }) {
  const [outlets, setOutlets] = useState([]); const [outletId, setOutletId] = useState(""); const [period, setPeriod] = useState(currentPeriod());
  const [data, setData] = useState({ cycles: [], cycle: null, entries: [], adjustments: [] }); const [loading, setLoading] = useState(true);
  const [createOpen, setCreateOpen] = useState(false); const [detailOpen, setDetailOpen] = useState(false); const [adjusting, setAdjusting] = useState(null);
  const canManage = auth.hasPermission("crew_reward.manage"); const canFinalize = auth.hasPermission("crew_reward.finalize"); const canPaid = auth.hasPermission("crew_reward.mark_paid");
  useEffect(() => { let active = true; (async () => { try { const rows = store?.outlets?.length ? store.outlets : await outletService.listActiveOutlets(); if (active) setOutlets((rows || []).filter((row) => row.is_active !== false)); } catch (cause) { ui.notify({ title: "Unable to load outlets", message: cause.message, tone: "error" }); } })(); return () => { active = false; }; }, [store?.outlets, ui]);
  useEffect(() => { if (!outletId && outlets.length) setOutletId(outlets[0].id); }, [outletId, outlets]);
  async function refresh(cycleId = null) { if (!outletId) return; setLoading(true); try { setData(await crewService.rewardAdminData(outletId, period, cycleId)); } catch (cause) { ui.notify({ title: "Unable to load Rewards", message: cause.message, tone: "error" }); } finally { setLoading(false); } }
  useEffect(() => { refresh(); }, [outletId, period]);
  async function createCycle(values) { const id = await crewService.createRewardCycle({ outletId, period, ...values }); setCreateOpen(false); await refresh(id); setDetailOpen(true); ui.notify({ title: "Reward cycle created", message: "The Draft cycle is ready to calculate." }); }
  async function calculate() { await crewService.calculateRewardCycle(data.cycle.id); await refresh(data.cycle.id); ui.notify({ title: "Reward calculated", message: "The server created the review breakdown from finalized evidence." }); }
  async function finalize() { await crewService.finalizeRewardCycle(data.cycle.id); await refresh(data.cycle.id); ui.notify({ title: "Reward finalized", message: "The monthly payout snapshot is now immutable." }); }
  async function markPaid() { await crewService.markRewardCyclePaid(data.cycle.id); await refresh(data.cycle.id); ui.notify({ title: "Reward marked paid", message: "Crew can now see the paid status in Reward History." }); }
  async function adjust(values) { await crewService.adjustRewardEntry(values.entryId, values.amount, values.reason); setAdjusting(null); await refresh(data.cycle.id); ui.notify({ title: "Adjustment saved", message: "The audited reason and amount were retained." }); }
  async function openCycle(row) { setPeriod(row.period_start); const next = await crewService.rewardAdminData(outletId, row.period_start, row.id); setData(next); setDetailOpen(true); }
  const outlet = outlets.find((row) => row.id === outletId);
  return <div className="crew-reward-page"><PageHeader section="Crew · Reward" title={initialTab === "cycles" ? "Reward Cycles" : "Reward Overview"} description="Transparent monthly Reward Pools from finalized Performance and completed attendance evidence." actions={<><SelectField label="Outlet" value={outletId} onChange={setOutletId} options={outlets.map((row) => ({ value: row.id, label: row.name }))} /><label className="crew-performance-period">Period<input className="control" type="month" value={period.slice(0, 7)} onChange={(event) => setPeriod(`${event.target.value}-01`)} /></label>{canManage && !data.cycle ? <button className="btn-primary" onClick={() => setCreateOpen(true)}>New Reward Cycle</button> : null}</>} />
    {loading ? <div className="crew-growth-skeleton"><span /><span /><span /><p>Loading Reward evidence…</p></div> : initialTab === "cycles" ? <CycleLibrary rows={data.cycles} onOpen={openCycle} /> : <RewardOverview data={data} onOpen={() => setDetailOpen(true)} onAdjust={setAdjusting} />}
    {detailOpen && data.cycle ? <CycleDetail data={data} canManage={canManage} canFinalize={canFinalize} canPaid={canPaid} onClose={() => setDetailOpen(false)} onCalculate={calculate} onFinalize={finalize} onPaid={markPaid} onAdjust={setAdjusting} /> : null}
    {createOpen ? <CreateCycle outlet={outlet} period={period} onClose={() => setCreateOpen(false)} onSubmit={createCycle} /> : null}
    {adjusting ? <Adjustment entry={adjusting} onClose={() => setAdjusting(null)} onSubmit={adjust} /> : null}
  </div>;
}

function RewardOverview({ data, onOpen, onAdjust }) {
  const cycle = data.cycle;
  if (!cycle) return <section className="crew-reward-empty"><Gift size={28} /><h2>No Reward cycle for this month</h2><p>Create a Draft cycle to configure the pool and calculate eligible Crew.</p></section>;
  const eligible = data.entries.filter((row) => ["qualified", "finalized", "paid"].includes(row.status)).length;
  return <div className="crew-growth-stack"><section className="crew-growth-metrics"><Metric icon={PiggyBank} label="Configured Pool" value={money(cycle.configured_pool)} detail="Monthly budget" /><Metric icon={CheckCircle2} label="Unlocked" value={money(cycle.unlocked_pool)} detail={`${percent(cycle.pool_unlock_rate)} team unlock`} tone="success" /><Metric icon={Wallet} label="Estimated Payout" value={money(cycle.actual_payout)} detail={cycleStatus(cycle.status)} /><Metric icon={Gift} label="Unused" value={money(cycle.unused_amount)} detail={`${eligible} / ${data.entries.length} eligible`} tone="warning" /></section><RewardTable rows={data.entries} cycle={cycle} onAdjust={onAdjust} /><button className="crew-reward-cycle-link" type="button" onClick={onOpen}>View complete Reward cycle <ChevronRight size={16} /></button></div>;
}

function RewardTable({ rows, cycle, onAdjust }) { return <section className="crew-growth-table"><DataTable rows={rows} getRowKey={(row) => row.id} tableClassName="min-w-[1040px]" columns={[
  { key: "employee", header: "Employee", render: (row) => <span className="crew-growth-name"><span className="crew-growth-avatar">{row.employee_name.split(/\s+/).slice(0, 2).map((part) => part[0]).join("")}</span><span><strong>{row.employee_name}</strong><small>{row.position || "Crew"}</small></span></span> },
  { key: "hours", header: "Hours", render: (row) => `${Number(row.eligible_hours).toFixed(1)}h` }, { key: "performance", header: "Performance", render: (row) => row.performance_score == null ? "—" : Math.round(row.performance_score) },
  { key: "contribution", header: "Contribution", render: (row) => row.status === "awaiting_performance" ? "—" : percent(row.contribution_share) }, { key: "factor", header: "Reward Factor", render: (row) => percent(row.performance_factor) },
  { key: "reward", header: "Estimated Reward", render: (row) => <strong>{money(row.final_payout)}</strong> }, { key: "status", header: "Status", render: (row) => <Badge tone={statusTone(row.status)}>{entryStatus(row.status)}</Badge> },
  { key: "action", header: "", align: "right", render: (row) => cycle.status === "review" && ["qualified", "finalized"].includes(row.status) ? <button className="btn-secondary" onClick={() => onAdjust(row)}>Adjust</button> : null },
]} /></section>; }

function CycleLibrary({ rows, onOpen }) { return <section className="crew-growth-table"><DataTable rows={rows} getRowKey={(row) => row.id} onRowClick={onOpen} columns={[
  { key: "month", header: "Month", render: (row) => new Date(row.period_start).toLocaleDateString("en-MY", { month: "long", year: "numeric" }) }, { key: "configured", header: "Configured Pool", render: (row) => money(row.configured_pool) },
  { key: "unlocked", header: "Unlocked", render: (row) => money(row.unlocked_pool) }, { key: "payout", header: "Actual Payout", render: (row) => money(row.actual_payout) }, { key: "unused", header: "Unused", render: (row) => money(row.unused_amount) },
  { key: "version", header: "Calculation", render: (row) => row.calculation_version }, { key: "status", header: "Status", render: (row) => <Badge tone={statusTone(row.status)}>{cycleStatus(row.status)}</Badge> }, { key: "open", header: "", align: "right", render: () => <ChevronRight size={16} /> },
]} /></section>; }

function CycleDetail({ data, canManage, canFinalize, canPaid, onClose, onCalculate, onFinalize, onPaid, onAdjust }) { const c = data.cycle; return <Modal title={`${new Date(c.period_start).toLocaleDateString("en-MY", { month: "long", year: "numeric" })} Reward`} description={`${cycleStatus(c.status)} · ${c.calculation_version}`} size="xl" onClose={onClose} footer={<><button className="btn-secondary" onClick={onClose}>Close</button>{c.status === "draft" && canManage ? <button className="btn-primary" onClick={onCalculate}>Calculate Reward</button> : null}{c.status === "review" && canFinalize ? <button className="btn-primary" onClick={onFinalize}>Finalize Reward</button> : null}{c.status === "finalized" && canPaid ? <button className="btn-primary" onClick={onPaid}>Mark Paid</button> : null}</>}><div className="crew-reward-detail"><section className="crew-reward-pool"><div><small>Configured Pool</small><strong>{money(c.configured_pool)}</strong></div><div><small>Unlocked Pool</small><strong>{money(c.unlocked_pool)}</strong></div><div><small>Actual Payout</small><strong>{money(c.actual_payout)}</strong></div><div><small>Unused</small><strong>{money(c.unused_amount)}</strong></div></section>{c.status === "draft" ? <section className="crew-reward-draft-note"><Calculator size={21} /><div><strong>Ready to calculate</strong><p>The server will snapshot finalized Performance, completed eligible hours and reward-v1 factors.</p></div></section> : <RewardTable rows={data.entries} cycle={c} onAdjust={onAdjust} />}{data.adjustments.length ? <section className="crew-reward-audit"><h3>Adjustment History</h3>{data.adjustments.map((row) => <div key={row.id}><span>{row.reason}</span><strong>{Number(row.adjustment_amount) > 0 ? "+" : ""}{money(row.adjustment_amount)}</strong></div>)}</section> : null}</div></Modal>; }

function CreateCycle({ outlet, period, onClose, onSubmit }) { const [pool, setPool] = useState("500"); const [minimum, setMinimum] = useState("60"); const [saving, setSaving] = useState(false); async function submit() { setSaving(true); try { await onSubmit({ configuredPool: Number(pool), minimumPerformance: Number(minimum) }); } finally { setSaving(false); } } return <Modal title="Create Reward Cycle" description={`${outlet?.name || "Outlet"} · ${new Date(period).toLocaleDateString("en-MY", { month: "long", year: "numeric" })}`} onClose={onClose} footer={<><button className="btn-secondary" onClick={onClose}>Cancel</button><button className="btn-primary" disabled={saving || Number(pool) < 0} onClick={submit}>{saving ? "Creating…" : "Create Draft"}</button></>}><div className="crew-reward-form"><label>Reward Pool (RM)<input className="control" type="number" min="0" step="0.01" value={pool} onChange={(event) => setPool(event.target.value)} /></label><label>Minimum Performance<input className="control" type="number" min="0" max="100" value={minimum} onChange={(event) => setMinimum(event.target.value)} /></label><section><strong>Team Unlock Rule · reward-v1</strong><p>Average below 60: 0% · 60–69: 50% · 70–79: 75% · 80+: 100%</p></section></div></Modal>; }

function Adjustment({ entry, onClose, onSubmit }) { const [amount, setAmount] = useState(""); const [reason, setReason] = useState(""); return <Modal title="Adjust Reward" description={`${entry.employee_name} · Current ${money(entry.final_payout)}`} onClose={onClose} footer={<><button className="btn-secondary" onClick={onClose}>Cancel</button><button className="btn-primary" disabled={!Number(amount) || reason.trim().length < 5} onClick={() => onSubmit({ entryId: entry.id, amount: Number(amount), reason })}>Save Adjustment</button></>}><div className="crew-reward-form"><label>Adjustment amount<input className="control" type="number" step="0.01" value={amount} onChange={(event) => setAmount(event.target.value)} placeholder="Example: 10 or -5" /></label><label>Reason<textarea className="control" value={reason} maxLength={500} onChange={(event) => setReason(event.target.value)} placeholder="Required audit reason" /></label><p><AlertTriangle size={15} /> The server rejects negative payouts and any total above the unlocked pool.</p></div></Modal>; }
function Metric({ icon: Icon, label, value, detail, tone = "neutral" }) { return <article className={`crew-growth-metric is-${tone}`}><div className="crew-growth-metric-icon"><Icon size={16} /></div><span><small>{label}</small><strong>{value}</strong><em>{detail}</em></span></article>; }
