import { useEffect, useMemo, useState } from "react";
import { Check, Search, X } from "lucide-react";
import PageHeader from "../../../components/layout/PageHeader.jsx";
import Card from "../../../components/ui/Card.jsx";
import Badge from "../../../components/ui/Badge.jsx";
import DataTable from "../../../components/tables/DataTable.jsx";
import Modal from "../../../components/feedback/Modal.jsx";
import { crewService } from "../../../services/crewService.js";

const tones = { pending_crew: "warning", pending_manager: "warning", approved: "success", rejected: "danger", cancelled: "neutral", expired: "neutral" };
const fmtDate = (value) => new Date(`${value}T00:00:00`).toLocaleDateString("en-MY", { day: "numeric", month: "short", year: "numeric" });
const fmtTime = (value) => String(value || "").slice(0, 5);

export default function CrewShiftRequestsAdminPage({ auth, store, ui }) {
  const outlets = (store?.outlets || []).filter((outlet) => auth.canAccessOutlet?.(outlet.id) ?? true);
  const [outletId, setOutletId] = useState(outlets[0]?.id || "");
  const [data, setData] = useState({ requests: [] });
  const [loading, setLoading] = useState(true);
  const [filters, setFilters] = useState({ search: "", status: "all", from: "", to: "" });
  const [review, setReview] = useState(null);
  const [saving, setSaving] = useState(false);
  const load = async () => { if (!outletId) return; setLoading(true); try { setData(await crewService.shiftRequestsAdmin(outletId, filters.from || null, filters.to || null)); } catch (cause) { ui.notify({ title: "Unable to load shift requests", message: cause.message, tone: "error" }); } finally { setLoading(false); } };
  useEffect(() => { load(); }, [outletId, filters.from, filters.to]);
  const rows = useMemo(() => (data.requests || []).filter((row) => (filters.status === "all" || row.status === filters.status) && (!filters.search || `${row.requester?.name} ${row.replacement?.name || ""}`.toLowerCase().includes(filters.search.toLowerCase()))), [data, filters]);
  const decide = async (decision, reason) => { setSaving(true); try { await crewService.reviewShiftRequest(review.id, decision, reason); ui.notify({ title: decision === "approve" ? "Shift swap approved" : "Shift request rejected", message: decision === "approve" ? "A new immutable roster revision is now live." : "The employee can see the safe rejection reason.", tone: "success" }); setReview(null); await load(); } catch (cause) { ui.notify({ title: "Unable to review shift request", message: cause.message, tone: "error" }); } finally { setSaving(false); } };
  return <div className="space-y-4"><PageHeader section="Crew · Workforce" title="Shift Requests" description="Review specific swaps and open-cover requests before publishing a roster revision." actions={<label className="field min-w-56"><span>Outlet</span><select value={outletId} onChange={(event) => setOutletId(event.target.value)}>{outlets.map((outlet) => <option key={outlet.id} value={outlet.id}>{outlet.name}</option>)}</select></label>} /><Card><div className="grid gap-3 md:grid-cols-[minmax(220px,1fr)_170px_170px_190px]"><label className="field"><span>Employee</span><div className="relative"><Search className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-text-muted" size={16} /><input className="w-full pl-9" value={filters.search} onChange={(event) => setFilters((row) => ({ ...row, search: event.target.value }))} placeholder="Requester or replacement" /></div></label><label className="field"><span>From</span><input type="date" value={filters.from} onChange={(event) => setFilters((row) => ({ ...row, from: event.target.value }))} /></label><label className="field"><span>To</span><input type="date" value={filters.to} onChange={(event) => setFilters((row) => ({ ...row, to: event.target.value }))} /></label><label className="field"><span>Status</span><select value={filters.status} onChange={(event) => setFilters((row) => ({ ...row, status: event.target.value }))}><option value="all">All</option>{Object.keys(tones).map((status) => <option value={status} key={status}>{status.replaceAll("_", " ")}</option>)}</select></label></div></Card><Card title="Shift Requests" description="Crew acceptance never changes the roster. Manager approval publishes the next immutable revision.">{loading ? <div className="p-8 text-sm font-semibold text-text-secondary">Loading shift requests…</div> : <DataTable tableClassName="min-w-[1100px]" rows={rows} getRowKey={(row) => row.id} columns={[
    { key: "requester", header: "Requested By", render: (row) => <div><strong>{row.requester?.name}</strong><small className="block text-text-secondary">{row.requester?.position}</small></div> },
    { key: "shift", header: "Original Shift", render: (row) => <div><strong>{fmtDate(row.date)}</strong><small className="block text-text-secondary">{fmtTime(row.start_time)} – {fmtTime(row.end_time)}</small></div> },
    { key: "replacement", header: "Replacement", render: (row) => row.replacement?.name || (row.coverage_mode === "open" ? "Open for cover" : "Awaiting Crew") },
    { key: "reason", header: "Reason", render: (row) => row.reason_code?.replaceAll("_", " ") },
    { key: "status", header: "Status", render: (row) => <Badge tone={tones[row.status]}>{row.status.replaceAll("_", " ")}</Badge> },
    { key: "requested", header: "Requested", render: (row) => new Date(row.submitted_at).toLocaleDateString("en-MY") },
    { key: "action", header: "Action", align: "right", render: (row) => <button className="btn-secondary" type="button" onClick={() => setReview(row)}>{row.status === "pending_manager" && auth.hasPermission("crew_shift_requests.review") ? "Review" : "View"}</button> },
  ]} />}</Card>{review && <ShiftReview row={review} canReview={auth.hasPermission("crew_shift_requests.review")} saving={saving} onClose={() => setReview(null)} onDecide={decide} />}</div>;
}

function ShiftReview({ row, canReview, saving, onClose, onDecide }) {
  const [decision, setDecision] = useState(""); const [reason, setReason] = useState(""); const eligibility = row.eligibility || {};
  const checks = [["Same position / compatible", eligibility.same_position], ["No roster conflict", !eligibility.roster_conflict], ["No approved leave", !eligibility.leave_conflict], ["Availability compatible", eligibility.availability?.compatible], ["Outlet scope valid", true]];
  const reasonRequired = decision === "reject" || (decision === "approve" && row.availability_conflict);
  return <Modal size="xl" title="Shift Request" description={`${row.requester?.name} · ${fmtDate(row.date)} · ${fmtTime(row.start_time)}–${fmtTime(row.end_time)}`} onClose={onClose} footer={<><button className="btn-secondary" type="button" onClick={onClose}>Close</button>{row.status === "pending_manager" && canReview && <>{decision !== "reject" && <button className="btn-danger" type="button" onClick={() => setDecision("reject")}><X size={16} /> Reject</button>}<button className="btn-primary" type="button" disabled={saving || (reasonRequired && reason.trim().length < 2)} onClick={() => decision ? onDecide(decision, reason) : setDecision("approve")}><Check size={16} /> {decision === "approve" ? "Confirm Approval" : "Approve"}</button></>}</>}><div className="grid gap-5 md:grid-cols-2"><section className="space-y-3"><Detail label="Original Crew" value={row.requester?.name} /><Detail label="Replacement" value={row.replacement?.name || "Not selected"} /><Detail label="Shift" value={`${fmtDate(row.date)} · ${fmtTime(row.start_time)}–${fmtTime(row.end_time)}`} /><Detail label="Reason" value={`${row.reason_code?.replaceAll("_", " ")}${row.reason ? ` · ${row.reason}` : ""}`} /></section><section className="divide-y divide-border rounded-xl border border-border">{checks.map(([label, okay]) => <div className="flex items-center justify-between p-3" key={label}><span className="text-sm font-semibold">{label}</span><Badge tone={okay ? "success" : "warning"}>{okay ? "Verified" : "Attention"}</Badge></div>)}</section></div>{decision && <label className="field mt-4"><span>{decision === "reject" ? "Rejection Reason *" : row.availability_conflict ? "Availability Override Reason *" : "Approval Note"}</span><textarea rows="3" value={reason} onChange={(event) => setReason(event.target.value)} placeholder={reasonRequired ? "Required for this decision" : "Optional audit note"} /></label>}<p className="mt-4 text-sm text-text-secondary">Approval creates a new published roster revision. The previous revision and request history remain immutable.</p></Modal>;
}
function Detail({ label, value }) { return <div><small className="font-semibold text-text-muted">{label}</small><strong className="mt-1 block text-sm text-text-primary">{value || "—"}</strong></div>; }
