import { useEffect, useMemo, useRef, useState } from "react";
import { AlertTriangle, BarChart3, CheckCircle2, ChevronRight, CircleHelp, ClipboardCheck, FileText, MessageSquareText, RotateCcw, Search, UserRoundPen } from "lucide-react";
import PageHeader from "../../../components/layout/PageHeader.jsx";
import Modal from "../../../components/feedback/Modal.jsx";
import EmptyState from "../../../components/feedback/EmptyState.jsx";
import Badge from "../../../components/ui/Badge.jsx";
import SelectField from "../../../components/forms/SelectField.jsx";
import DataTable from "../../../components/tables/DataTable.jsx";
import { crewService } from "../../../services/crewService.js";
import CrewAdminToolbar, { CrewAdminOutletField } from "../components/CrewAdminToolbar.jsx";
import { useCrewAdminOutlet } from "../context/CrewAdminOutletContext.jsx";

const serviceCriteria = [
  ["welcome_greeting", "Welcome / Greeting"], ["thank_you_goodbye", "Thank You / Goodbye"], ["grooming", "Grooming"],
  ["work_area_cleanliness", "Work Area Cleanliness"], ["initiative", "Initiative"], ["guest_interaction", "Guest Interaction"],
];
const conductCriteria = [["professional_conduct", "Professional Conduct"], ["teamwork", "Teamwork"], ["responsibility", "Responsibility"], ["communication", "Communication"], ["policy_compliance", "Policy Compliance"]];
const ratings = [{ value: "meets_standard", label: "Meets Standard" }, { value: "needs_improvement", label: "Needs Improvement" }, { value: "not_observed", label: "Not Observed" }];
const periodValue = () => new Date().toISOString().slice(0, 7) + "-01";
const score = (value, max) => value == null ? `— / ${max}` : `${Math.round(Number(value))} / ${max}`;
const statusLabel = (value) => ({ draft: "Draft", review_required: "Review Required", finalized: "Finalized" }[value] || value);
const statusTone = (value) => value === "finalized" ? "success" : value === "review_required" ? "warning" : "neutral";
const formatDate = (value) => value ? new Date(value).toLocaleDateString("en-MY", { day: "numeric", month: "short", year: "numeric" }) : "—";
const formatDateTime = (value) => value ? new Date(value).toLocaleString("en-MY", { day: "numeric", month: "short", year: "numeric", hour: "numeric", minute: "2-digit" }) : "—";

export default function CrewPerformanceAdminPage({ auth, ui, store, initialTab = "overview" }) {
  const { outlets, outletId, setOutletId } = useCrewAdminOutlet(store?.outlets || []); const [period, setPeriod] = useState(periodValue());
  const [data, setData] = useState({ summary: {}, crew: [], reviews: [], feedback: [] }); const [loading, setLoading] = useState(true);
  const [error, setError] = useState(""); const requestSequence = useRef(0);
  const [filters, setFilters] = useState({ query: "", position: "all", status: "all" });
  const [detail, setDetail] = useState(null); const [review, setReview] = useState(null); const [moderation, setModeration] = useState(null); const [feedbackDetail, setFeedbackDetail] = useState(null); const [attribution, setAttribution] = useState(null);
  const canReview = auth.hasPermission("crew_performance.review"); const canFinalize = auth.hasPermission("crew_performance.finalize"); const canModerate = auth.hasPermission("crew_feedback.moderate"); const canCorrectAttribution = auth.hasPermission("crew_feedback.correct_attribution");
  async function refresh() { if (!outletId) return; const sequence = ++requestSequence.current; setLoading(true); setError(""); try { const next = await crewService.performanceAdminData(outletId, period); if (sequence === requestSequence.current) setData(next); } catch (cause) { if (sequence === requestSequence.current) { setError(cause.message || "Performance evidence could not be loaded."); ui.notify({ title: "Unable to load Performance", message: cause.message, tone: "error" }); } } finally { if (sequence === requestSequence.current) setLoading(false); } }
  useEffect(() => { refresh(); }, [outletId, period]);
  async function submitReview(values) { await crewService.submitPerformanceReview(values); setReview(null); await refresh(); ui.notify({ title: "Review submitted", message: "The server recalculated this performance component." }); }
  async function finalize(employeeId) { await crewService.finalizePerformance(employeeId, period); setDetail(null); await refresh(); ui.notify({ title: "Performance finalized", message: "This monthly result is now immutable." }); }
  async function moderate(values) { await crewService.moderateFeedback(values.id, values.exclude, values.reason); setModeration(null); await refresh(); ui.notify({ title: values.exclude ? "Feedback excluded" : "Feedback restored to scoring", message: "The moderation history was retained." }); }
  async function correctAttribution(values) { await crewService.correctFeedbackAttribution(values.id, values.employeeId, values.reason); setAttribution(null); await refresh(); ui.notify({ title: "Crew attribution corrected", message: "The prior attribution and correction reason were retained." }); }
  const isFeedback = initialTab === "feedback";
  const positions = useMemo(() => [...new Set((data.crew || []).map((row) => row.employee.position).filter(Boolean))].sort(), [data.crew]);
  const meta = isFeedback ? ["Customer Feedback", "Understand guest sentiment without deleting unfavorable feedback."] : ["Performance Overview", "Explainable monthly performance from Attendance, Reviews, Feedback and Learning evidence."];
  return <div className="crew-performance-page"><PageHeader section="Crew · Performance" title={meta[0]} description={meta[1]} />
    <PerformanceToolbar outlets={outlets} outletId={outletId} setOutletId={setOutletId} period={period} setPeriod={setPeriod} filters={filters} setFilters={setFilters} positions={positions} feedbackOnly={isFeedback} />
    {loading ? <div className="crew-growth-skeleton"><span /><span /><span /><p>Loading performance evidence…</p></div> : error ? <PerformanceError message={error} onRetry={refresh} /> : isFeedback ? <FeedbackAdmin data={data.feedback} summary={data.feedback_summary} onModerate={setModeration} onDetail={setFeedbackDetail} onCorrectAttribution={setAttribution} canModerate={canModerate} canCorrectAttribution={canCorrectAttribution} /> : <PerformanceOverview data={data} filters={filters} onFiltersChange={setFilters} onOpen={setDetail} onReview={setReview} canReview={canReview} />}
    {detail ? <PerformanceDetail item={detail} canFinalize={canFinalize} onClose={() => setDetail(null)} onFinalize={() => finalize(detail.employee.id)} /> : null}
    {review ? <PerformanceReview item={review} period={period} onClose={() => setReview(null)} onSubmit={submitReview} /> : null}
    {moderation ? <ModerationDialog item={moderation} onClose={() => setModeration(null)} onSubmit={moderate} /> : null}
    {attribution ? <AttributionDialog item={attribution} employees={data.feedback_crew || []} onClose={() => setAttribution(null)} onSubmit={correctAttribution} /> : null}
    {feedbackDetail ? <FeedbackDetail item={feedbackDetail} onClose={() => setFeedbackDetail(null)} /> : null}
  </div>;
}

function PerformanceToolbar({ outlets, outletId, setOutletId, period, setPeriod, filters, setFilters, positions, feedbackOnly }) {
  const active = !feedbackOnly && (filters.query || filters.position !== "all" || filters.status !== "all");
  return <CrewAdminToolbar ariaLabel="Performance filters" outlet={<CrewAdminOutletField />} time={<label className="crew-performance-period">Period<input className="control" type="month" value={period.slice(0, 7)} onChange={(event) => setPeriod(`${event.target.value}-01`)} /></label>} search={!feedbackOnly ? <label className="crew-growth-search"><span>Search Crew</span><div><Search size={15} /><input value={filters.query} onChange={(event) => setFilters((current) => ({ ...current, query: event.target.value }))} placeholder="Name or employee code" /></div></label> : null} filters={!feedbackOnly ? <><SelectField label="Position" value={filters.position} onChange={(value) => setFilters((current) => ({ ...current, position: value }))} options={[{ value: "all", label: "All" }, ...positions.map((value) => ({ value, label: value }))]} /><SelectField label="Status" value={filters.status} onChange={(value) => setFilters((current) => ({ ...current, status: value }))} options={[{ value: "all", label: "All" }, { value: "awaiting", label: "Awaiting Review" }, { value: "reviewed", label: "Reviewed" }, { value: "attention", label: "Needs Attention" }, { value: "finalized", label: "Finalized" }]} /></> : null} secondary={active ? <button type="button" className="btn-secondary crew-performance-clear" onClick={() => setFilters({ query: "", position: "all", status: "all" })}><RotateCcw size={14} /> Clear</button> : null} />;
}

function reviewDone(row, component) { const value = row.result.components?.[component]; return value?.status === "reviewed" || value?.score != null; }
function rowReviewStatus(row) { return reviewDone(row, "service") && reviewDone(row, "conduct") ? "reviewed" : "awaiting"; }
function matchesPerformanceFilters(row, filters) {
  const haystack = `${row.employee.full_name} ${row.employee.employee_code || ""} ${row.employee.position || ""}`.toLowerCase();
  if (filters.query && !haystack.includes(filters.query.toLowerCase())) return false;
  if (filters.position !== "all" && row.employee.position !== filters.position) return false;
  if (filters.status === "awaiting" && rowReviewStatus(row) !== "awaiting") return false;
  if (filters.status === "reviewed" && rowReviewStatus(row) !== "reviewed") return false;
  if (filters.status === "attention" && !(row.result.total_score != null && Number(row.result.total_score) < 70)) return false;
  if (filters.status === "finalized" && row.result.status !== "finalized") return false;
  return true;
}

function PerformanceOverview({ data, filters, onFiltersChange, onOpen, onReview, canReview }) {
  const s = data.summary || {}; const rows = data.crew || [];
  const reviewed = rows.filter((row) => rowReviewStatus(row) === "reviewed").length; const awaiting = rows.length - reviewed;
  const filteredRows = rows.filter((row) => matchesPerformanceFilters(row, filters));
  const reviewRows = [...filteredRows].sort((a, b) => Number(rowReviewStatus(a) === "reviewed") - Number(rowReviewStatus(b) === "reviewed") || a.employee.full_name.localeCompare(b.employee.full_name));
  const attentionRows = filteredRows.filter((row) => row.result.total_score != null && Number(row.result.total_score) < 70).sort((a, b) => Number(a.result.total_score) - Number(b.result.total_score));
  const framework = performanceFramework(rows);
  return <div className="crew-performance-overview"><section className="crew-growth-metrics"><Metric icon={BarChart3} label="Average Score" value={s.average_score == null ? "—" : `${Math.round(s.average_score)} / 100`} detail={`${rows.length} Crew this period`} /><Metric icon={CheckCircle2} label="Reviewed" value={`${reviewed} / ${rows.length}`} detail="Service and Conduct complete" tone="success" /><button type="button" className="crew-performance-metric-action" onClick={() => onFiltersChange((current) => ({ ...current, status: "awaiting" }))}><Metric icon={ClipboardCheck} label="Awaiting Review" value={awaiting} detail="Service or Conduct pending" tone="warning" /></button><button type="button" className="crew-performance-metric-action" onClick={() => onFiltersChange((current) => ({ ...current, status: "attention" }))}><Metric icon={AlertTriangle} label="Needs Attention" value={s.needs_attention || 0} detail="Calculated score below 70" tone="danger" /></button></section>
    <PerformanceSection title="Review Queue" description="Complete Service Standards and Conduct reviews before finalization."><ReviewQueue rows={reviewRows} onReview={onReview} canReview={canReview} /></PerformanceSection>
    <PerformanceSection title="Team Performance" description={`${filteredRows.length} of ${rows.length} Crew shown for this period.`}>{filteredRows.length ? <section className="crew-growth-table is-embedded"><DataTable rows={filteredRows} getRowKey={(row) => row.employee.id} onRowClick={onOpen} tableClassName="min-w-[960px]" columns={[
      { key: "employee", header: "Employee", render: (row) => <NameCell row={row.employee} /> },
      { key: "performance", header: "Performance", render: (row) => <strong>{row.result.total_score == null ? "—" : Math.round(row.result.total_score)}</strong> },
      { key: "attendance", header: "Attendance", render: (row) => score(row.result.attendance_score, 30) }, { key: "service", header: "Service", render: (row) => score(row.result.service_score, 30) },
      { key: "customer", header: "Customer", render: (row) => score(row.result.customer_score, 15) }, { key: "knowledge", header: "Knowledge", render: (row) => score(row.result.knowledge_score, 15) }, { key: "conduct", header: "Conduct", render: (row) => score(row.result.conduct_score, 10) },
      { key: "status", header: "Status", render: (row) => <Badge tone={statusTone(row.result.status)}>{statusLabel(row.result.status)}</Badge> }, { key: "open", header: "", align: "right", render: () => <ChevronRight size={15} /> },
    ]} /></section> : <EmptyState title={rows.length ? "No Crew match these filters" : "No performance records yet"} description={rows.length ? "Clear or adjust the filters to review the full team." : "Performance records will appear after monthly evidence is available."} />}</PerformanceSection>
    <div className="crew-performance-lower"><PerformanceSection title="Needs Attention" description={attentionRows.length ? `${attentionRows.length} Crew may need manager support.` : "No Crew currently fall below the attention threshold."}><NeedsAttention rows={attentionRows} onOpen={onOpen} /></PerformanceSection><PerformanceSection title="Performance Framework · 100 pts" description="Server-derived component weights used by performance-v1."><PerformanceFramework items={framework} /></PerformanceSection></div>
  </div>;
}

function ReviewQueue({ rows, onReview, canReview }) {
  if (!rows?.length) return <EmptyState title="No reviews match these filters" description="Clear or adjust the filters to see the manager review queue." />;
  return <section className="crew-growth-table is-embedded"><DataTable rows={rows} getRowKey={(row) => row.employee.id} tableClassName="min-w-[850px]" columns={[
    { key: "employee", header: "Employee", render: (row) => <NameCell row={row.employee} /> },
    { key: "service", header: "Service Standards", render: (row) => <ReviewCell row={row} component="service" onReview={onReview} canReview={canReview} /> },
    { key: "conduct", header: "Conduct", render: (row) => <ReviewCell row={row} component="conduct" onReview={onReview} canReview={canReview} /> },
    { key: "status", header: "Review Status", render: (row) => <Badge tone={rowReviewStatus(row) === "reviewed" ? "success" : "warning"}>{rowReviewStatus(row) === "reviewed" ? "Reviewed" : "Review Required"}</Badge> },
  ]} /></section>;
}

function ReviewCell({ row, component, onReview, canReview }) { const done = reviewDone(row, component); return <span className="crew-performance-review-cell"><Badge tone={done ? "success" : "warning"}>{done ? "Completed" : "Pending"}</Badge><button type="button" className={done ? "btn-secondary" : "btn-primary"} disabled={!canReview} onClick={() => onReview({ ...row, component })}>{done ? "Review again" : "Review"}</button></span>; }
function PerformanceSection({ title, description, children }) { return <section className="crew-performance-section"><header><div><h2>{title}</h2><p>{description}</p></div></header>{children}</section>; }
function PerformanceError({ message, onRetry }) { return <section className="crew-performance-error"><AlertTriangle size={22} /><strong>Unable to load Performance</strong><p>{message}</p><button type="button" className="btn-secondary" onClick={onRetry}>Retry</button></section>; }

function NeedsAttention({ rows, onOpen }) {
  if (!rows.length) return <div className="crew-performance-positive"><CheckCircle2 size={18} /><span><strong>No Crew need immediate attention</strong><small>Scores and review evidence are within the current threshold.</small></span></div>;
  return <div className="crew-performance-attention-list">{rows.map((row) => { const weak = [["service_score", "Service", 30], ["customer_score", "Customer", 15], ["knowledge_score", "Knowledge", 15], ["conduct_score", "Conduct", 10]].filter(([key,,max]) => row.result[key] != null && Number(row.result[key]) / max < .7).slice(0, 3); return <button type="button" key={row.employee.id} onClick={() => onOpen(row)}><span><strong>{row.employee.full_name}</strong><small>{row.employee.position || "Crew"} · Score {Math.round(Number(row.result.total_score))}</small></span><em>{weak.map(([key, label, max]) => <span key={key}>{label}<b>{score(row.result[key], max)}</b></span>)}</em><ChevronRight size={16} /></button>; })}</div>;
}

function performanceFramework(rows) { const first = rows.find((row) => row.result.components); const definitions = [["attendance", "Attendance", 30], ["service", "Service", 30], ["customer", "Customer", 15], ["knowledge", "Knowledge", 15], ["conduct", "Conduct", 10]]; return definitions.map(([key, label, fallback]) => ({ key, label, points: Number(first?.result.components?.[key]?.max_score ?? fallback) })); }
function PerformanceFramework({ items }) { return <div className="crew-performance-framework">{items.map((item) => <div key={item.key}><span>{item.label}</span><strong>{item.points} pts</strong></div>)}<aside><CircleHelp size={15} /><span>Attendance, Feedback and Learning evidence are calculated by the server. Service and Conduct require manager reviews.</span></aside></div>; }

function FeedbackAdmin({ data, summary, onModerate, onDetail, onCorrectAttribution, canModerate, canCorrectAttribution }) {
  const [query, setQuery] = useState(""); const [experience, setExperience] = useState("all"); const [status, setStatus] = useState("all");
  const rows = (data || []).filter((row) => {
    const haystack = `${row.employee_name} ${row.comment || ""} ${(row.positive_tags || []).join(" ")} ${(row.improvement_tags || []).join(" ")}`.toLowerCase();
    return (experience === "all" || row.experience === experience) && (status === "all" || row.scoring_status === status) && haystack.includes(query.toLowerCase());
  });
  const totals = summary || {}; const included = Number(totals.included_feedback || 0); const positive = Number(totals.positive_feedback || 0);
  return <div className="crew-growth-stack"><section className="crew-growth-metrics"><Metric icon={MessageSquareText} label="Total Feedback" value={Number(totals.total_feedback || 0)} detail="All submissions this period" /><Metric icon={CheckCircle2} label="Positive Ratio" value={included ? `${Math.round(positive * 100 / included)}%` : "—"} detail="Included feedback only" tone="success" /><Metric icon={AlertTriangle} label="Needs Improvement" value={Number(totals.needs_improvement_feedback || 0)} detail="Included feedback only" tone="warning" /><Metric icon={FileText} label="Excluded" value={Number(totals.excluded_feedback || 0)} detail="Retained in evidence history" /></section><section className="crew-growth-filterbar"><label className="crew-growth-search"><span>Search</span><div><Search size={15} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search Crew, comment or tag" /></div></label><SelectField label="Experience" ariaLabel="Feedback experience" value={experience} onChange={setExperience} options={[{ value: "all", label: "All" }, { value: "great", label: "Great" }, { value: "okay", label: "Okay" }, { value: "needs_improvement", label: "Needs Improvement" }]} /><SelectField label="Scoring" ariaLabel="Feedback scoring" value={status} onChange={setStatus} options={[{ value: "all", label: "All" }, { value: "included", label: "Included" }, { value: "excluded", label: "Excluded" }]} /></section><section className="crew-growth-table"><DataTable rows={rows} getRowKey={(row) => row.id} tableClassName="min-w-[1040px]" columns={[
    { key: "date", header: "Date", render: (row) => formatDate(row.submitted_at) }, { key: "crew", header: "Crew", render: (row) => <span><strong>{row.employee_name}</strong>{row.employee_position ? <small className="block text-text-secondary">{row.employee_position}</small> : null}</span> }, { key: "experience", header: "Experience", render: (row) => <Badge tone={row.experience === "great" ? "success" : row.experience === "needs_improvement" ? "warning" : "neutral"}>{row.experience.replaceAll("_", " ")}</Badge> },
    { key: "tags", header: "Tags", render: (row) => <FeedbackTags row={row} compact /> }, { key: "comment", header: "Comment", render: (row) => <span className="block max-w-56 truncate">{row.comment || "—"}</span> }, { key: "scoring", header: "Scoring", render: (row) => <span><Badge tone={row.scoring_status === "included" ? "info" : "neutral"}>{row.scoring_status}</Badge>{row.scoring_status === "excluded" ? <small className="mt-1 block max-w-40 truncate text-text-secondary" title={row.exclusion_reason || ""}>{row.exclusion_reason || "Reason retained"}</small> : null}</span> },
    { key: "action", header: "Action", align: "right", render: (row) => <span className="flex justify-end gap-2"><button type="button" className="icon-btn" aria-label={`View feedback details for ${row.employee_name}`} title="Feedback details" onClick={() => onDetail(row)}><FileText size={15} /></button>{canCorrectAttribution ? <button type="button" className="icon-btn" aria-label={`Correct Crew attribution for ${row.employee_name}`} title="Correct Crew attribution" onClick={() => onCorrectAttribution(row)}><UserRoundPen size={15} /></button> : null}{canModerate ? <button type="button" className="btn-secondary" onClick={() => onModerate({ ...row, exclude: row.scoring_status === "included" })}>{row.scoring_status === "included" ? "Exclude" : "Restore"}</button> : null}</span> },
  ]} /></section></div>;
}

function FeedbackTags({ row, compact = false }) {
  const positive = row.positive_tags || []; const improvement = row.improvement_tags || [];
  if (!positive.length && !improvement.length) return "—";
  return <div className={compact ? "space-y-1 text-xs" : "space-y-2"}>{positive.length ? <div><small className="mr-1 text-text-secondary">Positive</small>{positive.map((tag) => <Badge key={tag} tone="success">{tag}</Badge>)}</div> : null}{improvement.length ? <div><small className="mr-1 text-text-secondary">Improve</small>{improvement.map((tag) => <Badge key={tag} tone="warning">{tag}</Badge>)}</div> : null}</div>;
}

function PerformanceDetail({ item, canFinalize, onClose, onFinalize }) {
  const r = item.result; const components = [["attendance", "Attendance", 30], ["service", "Service Standards", 30], ["customer", "Customer Experience", 15], ["knowledge", "Knowledge & SOP", 15], ["conduct", "Conduct", 10]];
  return <Modal title={`${item.employee.full_name} · Performance`} description={`${new Date(r.period_start).toLocaleDateString("en-MY", { month: "long", year: "numeric" })} · ${statusLabel(r.status)}`} size="xl" onClose={onClose} footer={<><button className="btn-secondary" onClick={onClose}>Close</button>{canFinalize && r.status !== "finalized" ? <button className="btn-primary" disabled={r.service_score == null || r.conduct_score == null} onClick={onFinalize}>Finalize Performance</button> : null}</>}><div className="crew-performance-detail"><section className="crew-performance-score"><span>Overall Score</span><strong>{r.total_score == null ? "—" : Math.round(r.total_score)}</strong><small>out of 100 · {r.calculation_version}</small></section><div className="crew-performance-breakdown">{components.map(([key, label, max]) => { const value = r.components?.[key]; return <article key={key}><header><strong>{label}</strong><span>{score(value?.score, max)}</span></header><div className="crew-performance-bar"><i style={{ width: `${value?.score == null ? 0 : Number(value.score) * 100 / max}%` }} /></div><p>{value?.explanation || (value?.status === "review_required" ? "Manager review required." : "Evidence is being calculated.")}</p></article>; })}</div></div></Modal>;
}

function PerformanceReview({ item, period, onClose, onSubmit }) {
  const definitions = item.component === "service" ? serviceCriteria : conductCriteria; const existing = item.result.components?.[item.component]?.criteria || [];
  const [criteria, setCriteria] = useState(() => definitions.map(([key, label]) => ({ key, label, rating: existing.find((row) => row.key === key)?.rating || "not_observed" }))); const [note, setNote] = useState(""); const [saving, setSaving] = useState(false);
  async function submit() { setSaving(true); try { await onSubmit({ employeeId: item.employee.id, period, component: item.component, criteria, note }); } finally { setSaving(false); } }
  return <Modal title={item.component === "service" ? "Service Standards Review" : "Conduct Review"} description={`${item.employee.full_name} · ${new Date(period).toLocaleDateString("en-MY", { month: "long", year: "numeric" })}`} size="xl" onClose={onClose} footer={<><button className="btn-secondary" onClick={onClose}>Cancel</button><button className="btn-primary" disabled={saving || criteria.every((row) => row.rating === "not_observed")} onClick={submit}>{saving ? "Submitting…" : "Submit Review"}</button></>}><div className="crew-performance-review">{criteria.map((row, index) => <article key={row.key}><strong>{row.label}</strong><div role="group" aria-label={`${row.label} rating`}>{ratings.map((rating) => <button type="button" key={rating.value} className={row.rating === rating.value ? "is-active" : ""} aria-pressed={row.rating === rating.value} onClick={() => setCriteria((current) => current.map((entry, i) => i === index ? { ...entry, rating: rating.value } : entry))}>{rating.label}</button>)}</div></article>)}<label>Manager note<textarea className="control" maxLength={1000} value={note} onChange={(event) => setNote(event.target.value)} placeholder="Optional coaching context. This is never shown to Crew." /></label></div></Modal>;
}

function ModerationDialog({ item, onClose, onSubmit }) { const [reason, setReason] = useState(""); const exclude = item.exclude !== false; return <Modal title={exclude ? "Exclude From Scoring" : "Restore To Scoring"} description={exclude ? "The feedback remains visible and the reason is audited." : "This returns the existing feedback to Performance scoring and records the reason."} onClose={onClose} footer={<><button className="btn-secondary" onClick={onClose}>Cancel</button><button className={exclude ? "btn-danger" : "btn-primary"} disabled={reason.trim().length < 5} onClick={() => onSubmit({ id: item.id, exclude, reason })}>{exclude ? "Exclude" : "Restore To Scoring"}</button></>}><label className="crew-performance-moderation">Reason<textarea className="control" value={reason} onChange={(event) => setReason(event.target.value)} placeholder={exclude ? "Explain why this submission should not affect scoring" : "Explain why this feedback should return to scoring"} /></label></Modal>; }

function AttributionDialog({ item, employees, onClose, onSubmit }) {
  const [query, setQuery] = useState(""); const [employeeId, setEmployeeId] = useState(item.employee_id); const [reason, setReason] = useState("");
  const choices = employees.filter((employee) => `${employee.name} ${employee.position || ""}`.toLowerCase().includes(query.toLowerCase()));
  return <Modal title="Correct Crew Attribution" description={`Currently attributed to ${item.employee_name}. The original feedback stays unchanged and this correction is audited.`} size="lg" onClose={onClose} footer={<><button className="btn-secondary" onClick={onClose}>Cancel</button><button className="btn-primary" disabled={employeeId === item.employee_id || reason.trim().length < 5} onClick={() => onSubmit({ id: item.id, employeeId, reason })}>Save Correction</button></>}><div className="space-y-4"><label>Find Crew<input className="control mt-1 w-full" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search Crew name or position" /></label><fieldset><legend className="field-label mb-2">Replacement Crew</legend><div className="max-h-56 space-y-2 overflow-y-auto">{choices.map((employee) => <label key={employee.id} className="flex cursor-pointer items-center gap-3 rounded-lg border border-border bg-white p-3 text-sm"><input type="radio" name="feedback-attribution" checked={employeeId === employee.id} onChange={() => setEmployeeId(employee.id)} /><span><strong className="block">{employee.name}</strong><small className="text-text-secondary">{[employee.position, employee.availability === "historical" ? "Historical outlet evidence" : "Active Crew"].filter(Boolean).join(" · ")}</small></span></label>)}{choices.length === 0 ? <p className="text-sm text-text-secondary">No Crew match this search.</p> : null}</div></fieldset><label>Correction reason<textarea className="control mt-1 min-h-24 w-full" value={reason} onChange={(event) => setReason(event.target.value)} placeholder="Explain why this feedback belongs to a different Crew member" /></label></div></Modal>;
}

function FeedbackDetail({ item, onClose }) {
  const moderation = item.moderation_history || []; const attribution = item.attribution_history || [];
  return <Modal title="Feedback Detail" description="Original guest evidence is retained separately from scoring decisions." size="xl" onClose={onClose} footer={<button className="btn-secondary" onClick={onClose}>Close</button>}><div className="space-y-5 text-sm"><dl className="grid gap-4 sm:grid-cols-2"><DetailItem label="Submitted" value={formatDateTime(item.submitted_at)} /><DetailItem label="Crew" value={item.employee_name} /><DetailItem label="Experience" value={item.experience.replaceAll("_", " ")} /><DetailItem label="Scoring" value={<Badge tone={item.scoring_status === "included" ? "info" : "neutral"}>{item.scoring_status}</Badge>} /></dl><section><h3 className="mb-2 font-semibold">Tags</h3><FeedbackTags row={item} /></section><section><h3 className="mb-2 font-semibold">Comment</h3><p className="whitespace-pre-wrap rounded-lg border border-border bg-surface px-3 py-2 text-text-secondary">{item.comment || "No comment provided."}</p></section>{item.scoring_status === "excluded" ? <section><h3 className="mb-2 font-semibold">Current Exclusion</h3><dl className="grid gap-3 rounded-lg border border-border bg-surface p-3 sm:grid-cols-3"><DetailItem label="Reason" value={item.exclusion_reason || "—"} /><DetailItem label="Excluded by" value={item.excluded_by_name || "—"} /><DetailItem label="Excluded at" value={formatDateTime(item.excluded_at)} /></dl></section> : null}<EvidenceHistory title="Scoring moderation" empty="No scoring moderation has been recorded." entries={moderation} render={(entry) => <><strong>{entry.previous_status} to {entry.next_status}</strong><span>{entry.reason}</span><small>{entry.changed_by || "Admin"} · {formatDateTime(entry.changed_at)}</small></>} /><EvidenceHistory title="Attribution corrections" empty="No attribution correction has been recorded." entries={attribution} render={(entry) => <><strong>{entry.previous_employee_name} to {entry.next_employee_name}</strong><span>{entry.reason}</span><small>{entry.changed_by || "Admin"} · {formatDateTime(entry.changed_at)}</small></>} /></div></Modal>;
}

function DetailItem({ label, value }) { return <div><dt className="text-xs text-text-secondary">{label}</dt><dd className="mt-1 font-medium capitalize">{value}</dd></div>; }
function EvidenceHistory({ title, empty, entries, render }) { return <section><h3 className="mb-2 font-semibold">{title}</h3>{entries.length ? <div className="space-y-2">{entries.map((entry) => <article key={entry.id} className="grid gap-1 rounded-lg border border-border bg-surface p-3">{render(entry)}</article>)}</div> : <p className="text-text-secondary">{empty}</p>}</section>; }
function Metric({ icon: Icon, label, value, detail, tone = "neutral" }) { return <article className={`crew-growth-metric is-${tone}`}><div className="crew-growth-metric-icon"><Icon size={16} /></div><span><small>{label}</small><strong>{value}</strong><em>{detail}</em></span></article>; }
function NameCell({ row }) { return <span className="crew-growth-name"><span className="crew-growth-avatar">{row.full_name.split(/\s+/).slice(0, 2).map((part) => part[0]).join("")}</span><span><strong>{row.full_name}</strong><small>{[row.position, row.employee_code].filter(Boolean).join(" · ") || "Crew"}</small></span></span>; }
