import { useEffect, useRef, useState } from "react";
import { CalendarDays, ChevronLeft, ChevronRight } from "lucide-react";
import FloatingLayer from "../../../../components/ui/FloatingLayer.jsx";
import { factoryMonthLabel, malaysiaBusinessMonthInput } from "../../utils/factoryDates.js";

export default function FactoryDashboardMonthPicker({ value, onChange }) {
  const [open, setOpen] = useState(false); const [visibleYear, setVisibleYear] = useState(() => Number(String(value || malaysiaBusinessMonthInput()).slice(0, 4))); const anchorRef = useRef(null);
  const selectedYear = Number(String(value || "").slice(0, 4)); const selectedMonth = Number(String(value || "").slice(5, 7));
  const months = Array.from({ length: 12 }, (_, index) => ({ value: index + 1, label: new Intl.DateTimeFormat("en-MY", { month: "short", timeZone: "UTC" }).format(new Date(Date.UTC(2026, index, 1))) }));
  useEffect(() => { if (open && Number.isFinite(selectedYear)) setVisibleYear(selectedYear); }, [open, selectedYear]);
  return <div><button ref={anchorRef} className="flex h-10 min-w-[176px] items-center justify-between gap-3 border-x border-border px-3 text-sm font-bold text-text-primary outline-none transition hover:bg-slate-50 focus:bg-primary/5 focus:ring-2 focus:ring-inset focus:ring-primary/20" type="button" aria-label="Select dashboard month" aria-haspopup="dialog" aria-expanded={open} onClick={() => setOpen((current) => !current)}><span>{factoryMonthLabel(value)}</span><CalendarDays size={15} className="text-text-muted" /></button><FloatingLayer open={open} onOpenChange={setOpen} anchorRef={anchorRef} align="center" minWidth={304} estimatedHeight={260} placement="auto" focusOnOpen className="p-3"><div role="dialog" aria-label="Choose dashboard month and year"><div className="flex items-center justify-between gap-3 border-b border-border pb-3"><button className="btn-secondary h-8 w-8 justify-center p-0" type="button" aria-label="Previous year" onClick={() => setVisibleYear((year) => year - 1)}><ChevronLeft size={15} /></button><div className="text-sm font-black text-text-primary">{visibleYear}</div><button className="btn-secondary h-8 w-8 justify-center p-0" type="button" aria-label="Next year" onClick={() => setVisibleYear((year) => year + 1)}><ChevronRight size={15} /></button></div><div className="mt-3 grid grid-cols-3 gap-2">{months.map((month) => { const active = selectedYear === visibleYear && selectedMonth === month.value; return <button key={month.value} className={`rounded-lg px-3 py-2 text-sm font-bold outline-none transition focus:ring-2 focus:ring-primary/20 ${active ? "bg-primary text-white" : "bg-slate-50 text-text-primary hover:bg-primary/10 hover:text-primary"}`} type="button" aria-pressed={active} onClick={() => { onChange(`${visibleYear}-${String(month.value).padStart(2, "0")}`); setOpen(false); }}>{month.label}</button>; })}</div></div></FloatingLayer></div>;
}
