import { useEffect, useMemo, useRef, useState } from "react";
import { ArrowLeft, ArrowRight, Camera, ChevronRight, ClipboardCheck, History, ImagePlus, MapPin, PackagePlus, PackageSearch, Pencil, SlidersHorizontal, Trash2 } from "lucide-react";
import { crewService } from "../../../services/crewService.js";
import { ASSET_CREATE_UNIT_OPTIONS, assetCreateErrorMessage, buildCrewAssetCreatePayload, validateAssetCreateValues } from "../../sales-purchase/utils/assetCreationContract.js";
import CrewBottomSheet from "./CrewBottomSheet.jsx";
import CrewChoicePicker from "./CrewChoicePicker.jsx";
import CrewMobileDetailHeader from "./CrewMobileDetailHeader.jsx";
import { CrewEmptyState, CrewSearchBar, CrewStatusBadge } from "./CrewMobileUI.jsx";
import AssetPhotoCropper from "../../../components/media/AssetPhotoCropper.jsx";
import CrewQuantityStepper from "./CrewQuantityStepper.jsx";
import CrewEvidencePhotoPicker from "./CrewEvidencePhotoPicker.jsx";
import CrewImageViewer from "./CrewImageViewer.jsx";
import { formatCrewOperationalDateTime } from "../utils/crewI18n.js";
import "./CrewAssetsMobile.css";
import "../../../components/media/AssetPhotoCropper.css";

const conditions = ["healthy", "needs_attention", "low_quantity", "damaged", "missing"];
const conditionLabels = { healthy: "Healthy", needs_attention: "Needs attention", low_quantity: "Low quantity", damaged: "Damaged", missing: "Missing" };
const adjustmentOptions = [{ value: "correction", label: "Set exact quantity" }, { value: "add", label: "Add quantity" }, { value: "reduce", label: "Reduce quantity" }];
const reasonOptions = [{ value: "stock_count", label: "Stock count" }, { value: "received", label: "Received" }, { value: "used", label: "Used / consumed" }, { value: "damaged", label: "Damaged" }, { value: "missing", label: "Missing" }, { value: "other", label: "Other" }];
const tone = (value) => value === "healthy" ? "success" : value === "low_quantity" || value === "needs_attention" ? "warning" : "danger";
const requestId = () => globalThis.crypto?.randomUUID?.() || `${Date.now()}-${Math.random()}`;
const pluralize = (quantity, unit) => `${quantity} ${Number(quantity) === 1 ? unit : `${unit}s`}`;
const formatDate = (value, options = { day: "numeric", month: "short", year: "numeric" }) => value ? new Intl.DateTimeFormat(undefined, options).format(new Date(value)) : "Not recorded";
const formatDateTime = formatCrewOperationalDateTime;
const signedQuantity = (value) => `${Number(value) > 0 ? "+" : ""}${value}`;

function State({ loading, error, retry, children }) {
  if (loading) return <section className="crew-v2-state" role="status"><span className="crew-v2-spinner" /><strong>Loading Assets…</strong></section>;
  if (error) return <section className="crew-v2-state"><strong>Assets unavailable</strong><p>{error}</p><button className="crew-mobile-primary" onClick={retry}>Try again</button></section>;
  return children;
}

function activityProjection(data, assetId) {
  // Inspection corrections are represented by the richer inspection evidence below.
  const movements = (data?.movement_history || []).filter((item) => item.reason !== "inspection" && (!assetId || item.asset_id === assetId)).map((item) => ({ ...item, kind: "adjustment", at: item.created_at || item.movement_date }));
  const inspections = (data?.inspection_history || []).filter((item) => !assetId || item.asset_ids?.includes(assetId)).map((item) => ({ ...item, kind: "inspection", at: item.created_at || item.inspection_date }));
  return [...movements, ...inspections].sort((a, b) => new Date(b.at) - new Date(a.at));
}

function AssetMasterImage({ asset, alt = "", className = "" }) {
  const sources = [...new Set([asset.thumbnail_url, asset.image_url, asset.original_image_url].filter(Boolean))];
  const [sourceIndex, setSourceIndex] = useState(0);
  useEffect(() => setSourceIndex(0), [asset.id, sources.join("|")]);
  const source = sources[sourceIndex];
  return source ? <img className={className} src={source} alt={alt} onError={() => setSourceIndex((current) => current + 1)} /> : null;
}

export default function CrewAssetsMobile({ token, onBack }) {
  const [data, setData] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const [query, setQuery] = useState(""); const [category, setCategory] = useState("all"); const [asset, setAsset] = useState(null);
  const [adjusting, setAdjusting] = useState(false); const [adding, setAdding] = useState(false); const [inspection, setInspection] = useState(null); const [activity, setActivity] = useState(false); const [notice, setNotice] = useState("");
  async function load(assetId) { setLoading(true); setError(""); try { const next = await crewService.assetsMobile(token, assetId); setData(next); return next; } catch (cause) { setError(cause.message || "Unable to load Assets."); return null; } finally { setLoading(false); } }
  useEffect(() => { void load(); }, [token]);
  const visible = useMemo(() => (data?.assets || []).filter((item) => (category === "all" || item.category_id === category) && `${item.name} ${item.asset_code || ""} ${item.location || ""}`.toLowerCase().includes(query.toLowerCase())), [data, query, category]);
  const categories = useMemo(() => [{ value: "all", label: "All" }, ...(data?.categories || []).filter((item) => item.is_active !== false).map((item) => ({ value: item.id, label: item.name }))], [data]);
  if (inspection) return <InspectionFlow token={token} data={data} initial={inspection} onBack={() => setInspection(null)} onSaved={async (result, status) => { const refreshed = await load(); const updates = new Map((result?.asset_updates || []).map((item) => [item.id, item])); if (updates.size) setData((previous) => previous ? { ...previous, assets: previous.assets.map((item) => ({ ...item, ...(updates.get(item.id) || {}) })) } : previous); if (asset) { const latest = refreshed?.assets?.find((item) => item.id === asset.id) || asset; setAsset({ ...latest, ...(updates.get(asset.id) || {}) }); } setNotice(status === "in_progress" ? "Draft saved" : "Inspection completed"); setInspection(null); }} />;
  if (asset) return <><AssetDetail asset={asset} data={data} onBack={() => setAsset(null)} onAdjust={() => setAdjusting(true)} onInspect={() => setInspection({ scope: "specific", assets: [asset] })} onActivity={() => setActivity({ assetId: asset.id, title: asset.name })} onEdit={() => setAdding("edit")} />
    {adjusting ? <AdjustSheet token={token} asset={asset} onClose={() => setAdjusting(false)} onSaved={async () => { const refreshed = await load(); setAsset(refreshed?.assets?.find((item) => item.id === asset.id) || null); setAdjusting(false); }} /> : null}
    {adding === "edit" ? <EditAssetDetailsSheet token={token} asset={asset} onClose={() => setAdding(false)} onSaved={async () => { const refreshed = await load(asset.id); setAsset(refreshed?.assets?.find((item) => item.id === asset.id) || asset); setAdding(false); }} /> : null}
    {activity ? <ActivitySheet data={data} assetId={activity.assetId} title={activity.title} onClose={() => setActivity(false)} /> : null}
  </>;
  return <section className="crew-assets-page"><CrewMobileDetailHeader title="Assets" onBack={onBack} /><State loading={loading} error={error} retry={load}><>
    <header className="crew-assets-intro"><div><strong>{data?.outlet?.name}</strong><span>{data?.assets?.length || 0} active assets</span></div><span className="crew-assets-header-actions"><button type="button" onClick={() => setActivity({ title: "Asset activity" })}><History size={19} /><span>Activity</span></button></span></header>
    <CrewSearchBar value={query} onChange={setQuery} placeholder="Search assets" />
    {notice ? <p className="crew-assets-notice" role="status">{notice}</p> : null}
    {data?.inspection_drafts?.map((draft) => <button className="crew-assets-resume" type="button" key={draft.id} onClick={() => setInspection({ draft })}><span><strong>Resume inspection</strong><small>{draft.completion_percentage || 0}% complete · saved {formatDateTime(draft.updated_at)}</small></span><ChevronRight size={18} /></button>)}
    {(data?.can_add_assets || data?.can_perform_asset_inspections) ? <div className={`crew-assets-operational-actions${data?.can_add_assets && data?.can_perform_asset_inspections ? "" : " is-single"}`}>{data?.can_add_assets ? <button className="crew-mobile-secondary" type="button" onClick={() => setAdding(true)}><PackagePlus size={18} />Add Asset</button> : null}{data?.can_perform_asset_inspections ? <button className="crew-mobile-primary" type="button" onClick={() => setInspection({ scope: "all", assets: data.assets })}><ClipboardCheck size={18} />Inspection</button> : null}</div> : null}
    <div className="crew-assets-filters crew-v2-chips" role="group" aria-label="Asset categories">{categories.map((item) => <button type="button" key={item.value} className={category === item.value ? "active" : ""} aria-pressed={category === item.value} onClick={() => setCategory(item.value)}>{item.label}</button>)}</div>
    <div className="crew-assets-list">{visible.map((item) => <button type="button" key={item.id} onClick={() => setAsset(item)}><span className="crew-assets-thumb">{item.thumbnail_url || item.image_url || item.original_image_url ? <AssetMasterImage asset={item} /> : <PackageSearch size={22} />}</span><span><strong>{item.name}</strong><small>{item.category_name}{item.location ? ` · ${item.location}` : ""}</small><em>{pluralize(item.current_quantity, item.unit)}</em></span><CrewStatusBadge tone={tone(item.condition)}>{conditionLabels[item.condition] || item.condition}</CrewStatusBadge><ChevronRight size={18} /></button>)}{!visible.length ? <CrewEmptyState title="No assets found" body="Try another search or category." /> : null}</div>
    {adding ? <AddAssetSheet token={token} categories={data?.categories || []} onClose={() => setAdding(false)} onSaved={async (assetId) => { const refreshed = await load(assetId); setAdding(false); setAsset(refreshed?.assets?.find((item) => item.id === assetId) || null); }} /> : null}{activity ? <ActivitySheet data={data} title={activity.title} onClose={() => setActivity(false)} /> : null}
  </></State></section>;
}

function AssetDetail({ asset, data, onBack, onAdjust, onInspect, onActivity, onEdit }) {
  const activity = activityProjection(data, asset.id).slice(0, 4); const movement = activity.find((item) => item.kind === "adjustment"); const inspection = activity.find((item) => item.kind === "inspection");
  const [viewer, setViewer] = useState(false); const display = asset.image_url || asset.original_image_url || "";
  return <section className="crew-assets-page"><CrewMobileDetailHeader title="Asset Detail" onBack={onBack} action={data?.can_manage_asset_details ? <button className="crew-mobile-header-text-action crew-assets-edit-action" type="button" onClick={onEdit}><Pencil size={17} />Edit</button> : null} /><article className="crew-asset-detail">
    <div className="crew-asset-detail-lead"><button className="crew-asset-detail-image" type="button" disabled={!display} onClick={() => setViewer(true)} aria-label={display ? "View asset photo" : undefined}>{display ? <AssetMasterImage asset={{ ...asset, thumbnail_url: "" }} /> : <PackageSearch size={30} />}</button><header><span><small>{asset.asset_code || asset.category_name}</small><h1>{asset.name}</h1>{asset.location ? <em><MapPin size={14} />{asset.location}</em> : null}</span><CrewStatusBadge tone={tone(asset.condition)}>{conditionLabels[asset.condition] || asset.condition}</CrewStatusBadge></header></div>
    {asset.description ? <p>{asset.description}</p> : data?.can_manage_asset_details ? <button className="crew-asset-detail-add-description" type="button" onClick={onEdit}>Add description</button> : null}<dl><div><dt>Quantity</dt><dd>{pluralize(asset.current_quantity, asset.unit)}</dd></div>{asset.location ? <div><dt>Location</dt><dd>{asset.location}</dd></div> : null}<div><dt>Last movement</dt><dd>{movement ? formatDateTime(movement.at) : "No movements"}</dd></div><div><dt>Last inspection</dt><dd>{inspection ? formatDateTime(inspection.at) : formatDateTime(asset.last_inspection_at)}</dd></div></dl>
    {asset.maintenance?.length ? <section className="crew-asset-maintenance"><strong>Maintenance</strong>{asset.maintenance.map((item, index) => <p key={index}>{item.status === "in_progress" ? "In progress" : "Scheduled"}{item.issue ? ` · ${item.issue}` : ""}{item.scheduled_date ? ` · ${formatDate(item.scheduled_date)}` : ""}</p>)}</section> : null}
    <section className="crew-asset-activity"><header><strong>Recent activity</strong>{activity.length ? <button type="button" onClick={onActivity}>View all activity</button> : null}</header>{activity.length ? activity.map((item) => <ActivityRow key={`${item.kind}-${item.id}`} item={item} concise />) : <p>No recent activity for this asset.</p>}</section>
    <footer>{data?.can_adjust_assets ? <button className="crew-mobile-secondary" onClick={onAdjust}><SlidersHorizontal size={18} />Adjust Quantity</button> : null}{data?.can_perform_asset_inspections ? <button className="crew-mobile-primary" onClick={onInspect}><ClipboardCheck size={18} />Inspect Asset</button> : null}</footer>
  </article>{viewer ? <CrewImageViewer src={display} alt={asset.name} onClose={() => setViewer(false)} /> : null}</section>;
}

function AdjustSheet({ token, asset, onClose, onSaved }) {
  const [type, setType] = useState("correction"); const [quantity, setQuantity] = useState(String(asset.current_quantity)); const [reason, setReason] = useState("stock_count"); const [note, setNote] = useState("");
  const [confirming, setConfirming] = useState(false); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  const entered = Number(quantity); const current = Number(asset.current_quantity); const next = Number.isFinite(entered) ? type === "add" ? current + entered : type === "reduce" ? current - entered : entered : current; const difference = next - current; const requiresConfirmation = Math.abs(difference) >= Math.max(10, current * 0.25);
  async function save() { setSaving(true); setError(""); try { await crewService.adjustAsset(token, { requestId: requestId(), assetId: asset.id, adjustmentType: type, quantity, reason, note }); await onSaved(); } catch (cause) { setError(cause.message || "Unable to adjust quantity."); } finally { setSaving(false); } }
  const footer = <><button className="crew-mobile-ghost" onClick={confirming ? () => setConfirming(false) : onClose} disabled={saving}>{confirming ? "Back" : "Cancel"}</button><button className="crew-mobile-primary" disabled={saving || !quantity || !reason || next < 0} onClick={() => confirming ? void save() : requiresConfirmation ? setConfirming(true) : void save()}>{saving ? "Saving…" : confirming ? "Confirm adjustment" : "Save adjustment"}</button></>;
  return <CrewBottomSheet title={confirming ? "Confirm large adjustment" : "Adjust Quantity"} description={asset.name} onClose={onClose} closeDisabled={saving} footer={footer}>{confirming ? <div className="crew-assets-confirm"><p>This changes stock by <strong>{signedQuantity(difference)} {asset.unit}</strong>.</p><div className="crew-assets-impact"><span><small>Current</small><strong>{pluralize(current, asset.unit)}</strong></span><ChevronRight size={18} /><span><small>New quantity</small><strong>{pluralize(next, asset.unit)}</strong></span></div><p>Confirm only after checking the physical count.</p></div> : <div className="crew-assets-form">
    <CrewChoicePicker label="Adjustment" value={type} options={adjustmentOptions} onChange={setType} /><label>Quantity<input inputMode="decimal" enterKeyHint="next" type="number" min="0" step="any" value={quantity} onChange={(event) => setQuantity(event.target.value)} /></label><div className="crew-assets-impact"><span><small>Current quantity</small><strong>{pluralize(current, asset.unit)}</strong></span><ChevronRight size={18} /><span><small>New quantity</small><strong>{pluralize(next, asset.unit)}</strong></span><em>{signedQuantity(difference)} {asset.unit}</em></div><CrewChoicePicker label="Reason" value={reason} options={reasonOptions} onChange={setReason} /><label>Note {reason !== "other" ? <small>Optional</small> : null}<textarea enterKeyHint="done" value={note} onChange={(event) => setNote(event.target.value)} placeholder="Add operational context" /></label>{error ? <p className="crew-v2-error" role="alert">{error}</p> : null}
  </div>}</CrewBottomSheet>;
}

function AddAssetSheet({ token, categories, onClose, onSaved }) {
  const [name, setName] = useState(""); const [category, setCategory] = useState(""); const [quantity, setQuantity] = useState(""); const [unit, setUnit] = useState("unit"); const [code, setCode] = useState(""); const [location, setLocation] = useState(""); const [description, setDescription] = useState(""); const [photo, setPhoto] = useState(null); const [preparingPhoto, setPreparingPhoto] = useState(false); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  const createRequestId = useRef(requestId());
  const categoryOptions = [{ value: "", label: "Choose category" }, ...categories.map((item) => ({ value: item.id, label: item.name }))];
  const draft = { name, category_id: category, initial_quantity: quantity, unit, asset_code: code, location, description };
  const validationError = validateAssetCreateValues(draft, categories.map((item) => item.id));
  useEffect(() => () => { if (photo?.previewUrl) URL.revokeObjectURL?.(photo.previewUrl); if (photo?.sourceUrl) URL.revokeObjectURL?.(photo.sourceUrl); }, [photo?.previewUrl, photo?.sourceUrl]);
  async function choosePhoto(file) {
    if (!file) return;
    setPreparingPhoto(true); setError("");
    try { const prepared = await crewService.prepareAssetMasterPhoto(file); setPhoto({ ...prepared, crop: { zoom: 1, x: 0, y: 0 }, sourceUrl: URL.createObjectURL(file) }); } catch (cause) { setError(cause.message || "That photo could not be prepared. Try another image."); } finally { setPreparingPhoto(false); }
  }
  function removePhoto() { setPhoto(null); createRequestId.current = requestId(); }
  async function save() {
    setSaving(true); setError("");
    try {
      const assetPayload = buildCrewAssetCreatePayload(draft);
      const result = photo
        ? await crewService.createAssetWithPhoto(token, { requestId: createRequestId.current, asset: assetPayload, preparedPhoto: await crewService.prepareAssetMasterPhoto(photo.file, photo.crop) })
        : await crewService.createAsset(token, { requestId: createRequestId.current, asset: assetPayload });
      const assetId = result?.asset?.id || "";
      if (!assetId) throw new Error("Asset creation returned no identifier.");
      await onSaved(assetId);
    } catch (cause) { setError(assetCreateErrorMessage("create", cause)); } finally { setSaving(false); }
  }
  return <CrewBottomSheet title="Add Asset" description="Creates a new active Asset for this outlet." onClose={onClose} closeDisabled={saving} footer={<><button className="crew-mobile-ghost" type="button" onClick={onClose} disabled={saving}>Cancel</button><button className="crew-mobile-primary" type="button" disabled={Boolean(validationError) || saving || preparingPhoto} onClick={() => void save()}>{saving ? "Creating…" : "Create Asset"}</button></>}><div className="crew-assets-form"><label>Asset name<input enterKeyHint="next" value={name} onChange={(event) => setName(event.target.value)} autoComplete="off" /></label><CrewChoicePicker label="Category" value={category} options={categoryOptions} onChange={setCategory} /><div className="crew-assets-inline-fields"><label>Initial quantity<input type="number" inputMode="decimal" enterKeyHint="next" min="0" step="any" value={quantity} onChange={(event) => setQuantity(event.target.value)} /></label><CrewChoicePicker label="Unit" value={unit} options={ASSET_CREATE_UNIT_OPTIONS} onChange={setUnit} /></div><label>Asset code <small>Optional</small><input enterKeyHint="next" value={code} onChange={(event) => setCode(event.target.value)} autoComplete="off" /></label><label>Location <small>Optional</small><input enterKeyHint="next" value={location} onChange={(event) => setLocation(event.target.value)} /></label><fieldset className="crew-assets-photo-field"><legend>Photo <small>Optional</small></legend>{photo ? <div className="crew-assets-photo-preview"><AssetPhotoCropper src={photo.sourceUrl} crop={photo.crop} onChange={(crop) => setPhoto((current) => ({ ...current, crop }))} /><div><label><Camera size={17} />Replace<input type="file" accept="image/jpeg,image/png,image/webp,image/heic,image/heif" capture="environment" onChange={(event) => void choosePhoto(event.target.files?.[0])} /></label><button type="button" onClick={removePhoto}><Trash2 size={17} />Remove</button></div></div> : <div className="crew-assets-photo-actions"><label><Camera size={18} />Take Photo<input type="file" accept="image/jpeg,image/png,image/webp,image/heic,image/heif" capture="environment" onChange={(event) => void choosePhoto(event.target.files?.[0])} /></label><label><ImagePlus size={18} />Choose from Library<input type="file" accept="image/jpeg,image/png,image/webp,image/heic,image/heif" onChange={(event) => void choosePhoto(event.target.files?.[0])} /></label></div>}{preparingPhoto ? <small role="status">Preparing 4:3 preview…</small> : null}</fieldset><label>Description <small>Optional</small><textarea enterKeyHint="done" value={description} onChange={(event) => setDescription(event.target.value)} /></label>{error ? <p className="crew-v2-error" role="alert">{error}</p> : null}</div></CrewBottomSheet>;
}

function EditAssetDetailsSheet({ token, asset, onClose, onSaved }) {
  const [name, setName] = useState(asset.name || ""); const [description, setDescription] = useState(asset.description || ""); const [location, setLocation] = useState(asset.location || "");
  const [photo, setPhoto] = useState(null); const [removePhoto, setRemovePhoto] = useState(false); const [preparingPhoto, setPreparingPhoto] = useState(false); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  useEffect(() => () => { if (photo?.sourceUrl) URL.revokeObjectURL?.(photo.sourceUrl); }, [photo?.sourceUrl]);
  async function choosePhoto(file) { if (!file) return; setPreparingPhoto(true); setError(""); try { const prepared = await crewService.prepareAssetMasterPhoto(file); setPhoto({ ...prepared, crop: { zoom: 1, x: 0, y: 0 }, sourceUrl: URL.createObjectURL(file) }); setRemovePhoto(false); } catch (cause) { setError(cause.message || "That photo could not be prepared. Try another image."); } finally { setPreparingPhoto(false); } }
  async function save() { setSaving(true); setError(""); try { await crewService.updateAssetDetails(token, { requestId: requestId(), assetId: asset.id, details: { name, description, location, remove_photo: removePhoto }, preparedPhoto: photo ? await crewService.prepareAssetMasterPhoto(photo.file, photo.crop) : null }); await onSaved(); } catch (cause) { setError(assetCreateErrorMessage("update", cause)); } finally { setSaving(false); } }
  const hasExistingPhoto = Boolean(asset.image_url || asset.original_image_url);
  return <CrewBottomSheet title="Edit Asset Details" description="Update the Asset presentation details." onClose={onClose} closeDisabled={saving} footer={<><button className="crew-mobile-ghost" type="button" disabled={saving} onClick={onClose}>Cancel</button><button className="crew-mobile-primary" type="button" disabled={saving || preparingPhoto || !name.trim()} onClick={() => void save()}>{saving ? "Saving…" : "Save changes"}</button></>}><div className="crew-assets-form"><label>Asset name<input value={name} autoComplete="off" enterKeyHint="next" onChange={(event) => setName(event.target.value)} /></label><label>Location <small>Optional</small><input value={location} enterKeyHint="next" onChange={(event) => setLocation(event.target.value)} /></label><fieldset className="crew-assets-photo-field"><legend>Photo <small>Optional</small></legend>{photo ? <div className="crew-assets-photo-preview"><AssetPhotoCropper src={photo.sourceUrl} crop={photo.crop} onChange={(crop) => setPhoto((current) => ({ ...current, crop }))} /><div><label><Camera size={17} />Replace<input type="file" accept="image/jpeg,image/png,image/webp,image/heic,image/heif" capture="environment" onChange={(event) => void choosePhoto(event.target.files?.[0])} /></label><button type="button" onClick={() => { setPhoto(null); setRemovePhoto(true); }}><Trash2 size={17} />Remove</button></div></div> : removePhoto || !hasExistingPhoto ? <div className="crew-assets-photo-actions"><label><Camera size={18} />Take Photo<input type="file" accept="image/jpeg,image/png,image/webp,image/heic,image/heif" capture="environment" onChange={(event) => void choosePhoto(event.target.files?.[0])} /></label><label><ImagePlus size={18} />Choose from Library<input type="file" accept="image/jpeg,image/png,image/webp,image/heic,image/heif" onChange={(event) => void choosePhoto(event.target.files?.[0])} /></label></div> : <div className="crew-assets-photo-preview"><AssetMasterImage asset={{ ...asset, thumbnail_url: "" }} /><div><label><Camera size={17} />Replace<input type="file" accept="image/jpeg,image/png,image/webp,image/heic,image/heif" capture="environment" onChange={(event) => void choosePhoto(event.target.files?.[0])} /></label><button type="button" onClick={() => setRemovePhoto(true)}><Trash2 size={17} />Remove</button></div></div>}{preparingPhoto ? <small role="status">Preparing 4:3 preview…</small> : null}</fieldset><label>Description <small>Optional</small><textarea value={description} enterKeyHint="done" onChange={(event) => setDescription(event.target.value)} /></label>{error ? <p className="crew-v2-error" role="alert">{error}</p> : null}</div></CrewBottomSheet>;
}

function ActivitySheet({ data, assetId, title, onClose }) {
  const [filter, setFilter] = useState("all"); const events = activityProjection(data, assetId).filter((item) => filter === "all" || item.kind === filter);
  return <CrewBottomSheet title={title || "Asset activity"} description={assetId ? "Latest activity for this asset" : "Quantity movements and completed inspections"} onClose={onClose}><div className="crew-assets-activity-filter" role="group" aria-label="Activity filter">{[{ value: "all", label: "All" }, { value: "adjustment", label: "Adjustments" }, { value: "inspection", label: "Inspections" }].map((item) => <button type="button" key={item.value} className={filter === item.value ? "active" : ""} onClick={() => setFilter(item.value)}>{item.label}</button>)}</div><div className="crew-assets-history">{events.map((item) => <ActivityRow key={`${item.kind}-${item.id}`} item={item} />)}{!events.length ? <CrewEmptyState title="No activity yet" body="Asset movements and completed inspections appear here." /> : null}</div></CrewBottomSheet>;
}

function ActivityRow({ item, concise = false }) {
  if (item.kind === "adjustment") return <article className="crew-assets-activity-row"><span><strong>Quantity adjusted{concise ? "" : ` · ${item.asset_name}`}</strong><small>{item.quantity_before} → {item.quantity_after} units · {signedQuantity(item.quantity_change)}</small><em>{item.reason?.replaceAll("_", " ")} · {formatDateTime(item.at)} · by {item.actor_name || "Admin"}</em></span><CrewStatusBadge tone="neutral">Adjustment</CrewStatusBadge></article>;
  const count = item.summary?.checked_assets || item.asset_ids?.length || 0; const inspected = item.items?.[0];
  return <article className="crew-assets-activity-row"><span><strong>Inspection completed{!concise && inspected?.asset_name ? ` · ${inspected.asset_name}` : ""}</strong><small>{inspected ? `Expected ${inspected.expected_quantity} · Counted ${inspected.counted_quantity} · ${signedQuantity(inspected.difference)}` : `${count} ${count === 1 ? "asset" : "assets"} inspected`}{inspected?.condition ? ` · ${conditionLabels[inspected.condition] || inspected.condition}` : ""}</small><em>{formatDateTime(item.at)} · by {item.checked_by || "Crew"}</em></span><CrewStatusBadge tone="success">Inspection</CrewStatusBadge></article>;
}

function InspectionFlow({ token, data, initial, onBack, onSaved }) {
  const draft = initial.draft; const [scope, setScope] = useState(draft?.category_scope?.type || initial.scope || "all"); const [category, setCategory] = useState(draft?.category_scope?.category_ids?.[0] || "");
  const initialAssets = draft ? (draft.draft_data?.rows || []).map((row) => ({ ...data.assets.find((asset) => asset.id === row.asset_id), saved: row })) : initial.assets; const scoped = useMemo(() => (initialAssets || data.assets || []).filter((item) => scope !== "category" || item.category_id === category), [initialAssets, data.assets, scope, category]);
  const [started, setStarted] = useState(Boolean(draft || initial.scope === "specific")); const [index, setIndex] = useState(draft?.current_step ? Math.max(0, draft.current_step - 1) : 0); const [rows, setRows] = useState(() => Object.fromEntries((initialAssets || []).map((item) => [item.id, item.saved || { asset_id: item.id, counted_quantity: item.current_quantity, condition_status: item.condition || "healthy", remark: "", evidence: [] }]))); const initialRows = useRef(JSON.stringify(Object.fromEntries((initialAssets || []).map((item) => [item.id, item.saved || { asset_id: item.id, counted_quantity: item.current_quantity, condition_status: item.condition || "healthy", remark: "", evidence: [] }])))); const touchStart = useRef(null); const [pendingPhotos, setPendingPhotos] = useState({}); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  const current = scoped[index]; const row = current && rows[current.id]; const categoryOptions = [{ value: "", label: "Choose category" }, ...(data.categories || []).map((item) => ({ value: item.id, label: item.name }))];
  function patch(values) { setRows((previous) => ({ ...previous, [current.id]: { ...previous[current.id], ...values } })); }
  function choosePhoto(file) { if (!file || !current) return; setError(""); const previewUrl = URL.createObjectURL(file); setPendingPhotos((previous) => { if (previous[current.id]?.previewUrl) URL.revokeObjectURL?.(previous[current.id].previewUrl); return { ...previous, [current.id]: { file, previewUrl } }; }); }
  function removePhoto() { if (!current) return; setPendingPhotos((previous) => { if (previous[current.id]?.previewUrl) URL.revokeObjectURL?.(previous[current.id].previewUrl); const next = { ...previous }; delete next[current.id]; return next; }); }
  const payload = (status, evidenceByAsset = {}) => ({ draft_id: draft?.id || null, status, category_scope: { type: scope, category_ids: category ? [category] : [] }, current_step: index + 1, completion_percentage: scoped.length ? Math.round((index / scoped.length) * 100) : 0, draft_data: { rows: scoped.map((item) => rows[item.id]) }, rows: scoped.map((item) => { const value = rows[item.id]; const template = data.condition_templates?.find((candidate) => candidate.category_id === item.category_id && candidate.name.toLowerCase() === (conditionLabels[value.condition_status] || value.condition_status).toLowerCase()); return { ...value, evidence: [...(value.evidence || []), ...(evidenceByAsset[item.id] ? [evidenceByAsset[item.id]] : [])], condition_template_id: template?.id || null, evidence_required: Boolean(template?.requires_photo) }; }) });
  const hasChanges = JSON.stringify(rows) !== initialRows.current || Object.keys(pendingPhotos).length > 0;
  async function save(status) { setSaving(true); setError(""); try { const evidenceByAsset = {}; for (const [assetId, pending] of Object.entries(pendingPhotos)) { const evidence = await crewService.uploadAssetInspectionEvidence(token, assetId, pending.file); evidenceByAsset[assetId] = { image_url: evidence.image_url }; } const result = await crewService.submitAssetInspection(token, { requestId: requestId(), ...payload(status, evidenceByAsset) }); Object.values(pendingPhotos).forEach((photo) => URL.revokeObjectURL?.(photo.previewUrl)); await onSaved(result, status); } catch (cause) { setError(cause.message || "Unable to save inspection."); } finally { setSaving(false); } }
  function isSwipeExcluded(target) { return target instanceof Element && Boolean(target.closest("button, input, textarea, label, [role='slider'], .crew-ui-quantity-stepper, .crew-ui-evidence-photo-picker")); }
  function handleTouchStart(event) { if (event.touches.length !== 1 || isSwipeExcluded(event.target)) { touchStart.current = null; return; } const touch = event.touches[0]; touchStart.current = { x: touch.clientX, y: touch.clientY }; }
  function handleTouchEnd(event) { const start = touchStart.current; touchStart.current = null; if (!start || saving || isSwipeExcluded(event.target) || event.changedTouches.length !== 1) return; const touch = event.changedTouches[0]; const horizontal = touch.clientX - start.x; const vertical = touch.clientY - start.y; if (Math.abs(horizontal) < 56 || Math.abs(horizontal) < Math.abs(vertical) * 1.4) return; if (horizontal < 0 && index < scoped.length - 1) setIndex((currentIndex) => currentIndex + 1); if (horizontal > 0 && index > 0) setIndex((currentIndex) => currentIndex - 1); }
  if (!started) return <section className="crew-assets-page"><CrewMobileDetailHeader title="Start Inspection" onBack={onBack} /><div className="crew-inspection-setup"><ClipboardCheck size={30} /><h1>Choose inspection scope</h1><button type="button" className={scope === "all" ? "active" : ""} onClick={() => setScope("all")}><strong>Full outlet</strong><small>Inspect every active outlet asset</small></button><button type="button" className={scope === "category" ? "active" : ""} onClick={() => setScope("category")}><strong>Category</strong><small>Inspect one asset category</small></button>{scope === "category" ? <CrewChoicePicker label="Category" value={category} options={categoryOptions} onChange={setCategory} /> : null}<button className="crew-mobile-primary" disabled={scope === "category" && !category} onClick={() => setStarted(true)}>Start Inspection</button></div></section>;
  const expected = Number(current?.current_quantity ?? 0); const counted = Number(row?.counted_quantity ?? expected); const difference = Number.isFinite(counted) ? counted - expected : 0;
  const differenceCopy = difference === 0 ? "No difference" : `${signedQuantity(difference)} ${current.unit}`;
  const progress = scoped.length ? Math.round(((index + 1) / scoped.length) * 100) : 0;
  return <section className="crew-assets-page"><CrewMobileDetailHeader title="Asset Inspection" onBack={onBack} />{current ? <article className="crew-inspection-step" onTouchStart={handleTouchStart} onTouchEnd={handleTouchEnd}><header><div className="crew-inspection-progress-heading"><strong>{index + 1} of {scoped.length}</strong><span>{progress}%</span></div><strong className="crew-inspection-asset-name">{current.name}</strong><small>{current.location || current.category_name}</small></header><div className="crew-inspection-progress" aria-label={`${progress}% complete`}><span style={{ width: `${progress}%` }} /></div><div className="crew-inspection-count-context"><span><small>Expected</small><strong>{pluralize(expected, current.unit)}</strong></span><span><small>Difference</small><strong className={difference ? `is-difference ${difference > 0 ? "is-positive" : "is-negative"}` : ""}>{differenceCopy}</strong></span></div><CrewQuantityStepper label="Counted" unit={current.unit} value={row.counted_quantity} onChange={(value) => patch({ counted_quantity: value })} /><fieldset className="crew-inspection-condition"><legend>Condition</legend>{conditions.map((item) => <button type="button" key={item} aria-pressed={row.condition_status === item} className={`${row.condition_status === item ? "active " : ""}is-${item.replaceAll("_", "-")}`} onClick={() => patch({ condition_status: item })}>{conditionLabels[item]}</button>)}</fieldset><label>Note<textarea enterKeyHint="done" value={row.remark} onChange={(event) => patch({ remark: event.target.value })} placeholder="Add details when attention is needed" /></label><CrewEvidencePhotoPicker previewUrl={pendingPhotos[current.id]?.previewUrl} onChoose={choosePhoto} onRemove={removePhoto} />{row.evidence?.length ? <small>{row.evidence.length} saved photo{row.evidence.length === 1 ? "" : "s"}</small> : null}{error ? <p className="crew-v2-error" role="alert">{error}</p> : null}<div className="crew-inspection-draft-action"><button className="crew-mobile-ghost" disabled={saving || !hasChanges} onClick={() => void save("in_progress")}>{saving ? "Saving…" : "Save Draft"}</button>{hasChanges ? <small>Save a draft before leaving the inspection.</small> : null}</div><footer className="crew-assets-inspection-actions"><button className="crew-mobile-secondary" disabled={saving || index === 0} onClick={() => setIndex((currentIndex) => currentIndex - 1)}><ArrowLeft size={17} />Previous</button>{index < scoped.length - 1 ? <button className="crew-mobile-primary" disabled={saving} onClick={() => setIndex((currentIndex) => currentIndex + 1)}>Next<ArrowRight size={17} /></button> : <button className="crew-mobile-primary" disabled={saving} onClick={() => void save("completed")}>{saving ? "Saving…" : "Complete Inspection"}</button>}</footer></article> : <CrewEmptyState title="No assets in this scope" body="Choose another inspection scope." />}</section>;
}
