import { useEffect, useMemo, useRef, useState } from "react";
import { Camera, ChevronRight, ClipboardCheck, History, ImagePlus, MapPin, PackagePlus, PackageSearch, SlidersHorizontal, Trash2 } from "lucide-react";
import { crewService } from "../../../services/crewService.js";
import { ASSET_CREATE_UNIT_OPTIONS, assetCreateErrorMessage, buildCrewAssetCreatePayload, validateAssetCreateValues } from "../../sales-purchase/utils/assetCreationContract.js";
import CrewBottomSheet from "./CrewBottomSheet.jsx";
import CrewChoicePicker from "./CrewChoicePicker.jsx";
import CrewMobileDetailHeader from "./CrewMobileDetailHeader.jsx";
import { CrewEmptyState, CrewSearchBar, CrewStatusBadge } from "./CrewMobileUI.jsx";
import "./CrewAssetsMobile.css";

const conditions = ["healthy", "needs_attention", "low_quantity", "damaged", "missing"];
const conditionLabels = { healthy: "Healthy", needs_attention: "Needs attention", low_quantity: "Low quantity", damaged: "Damaged", missing: "Missing" };
const adjustmentOptions = [{ value: "correction", label: "Set exact quantity" }, { value: "add", label: "Add quantity" }, { value: "reduce", label: "Reduce quantity" }];
const reasonOptions = [{ value: "stock_count", label: "Stock count" }, { value: "received", label: "Received" }, { value: "used", label: "Used / consumed" }, { value: "damaged", label: "Damaged" }, { value: "missing", label: "Missing" }, { value: "other", label: "Other" }];
const tone = (value) => value === "healthy" ? "success" : value === "low_quantity" || value === "needs_attention" ? "warning" : "danger";
const requestId = () => globalThis.crypto?.randomUUID?.() || `${Date.now()}-${Math.random()}`;
const pluralize = (quantity, unit) => `${quantity} ${Number(quantity) === 1 ? unit : `${unit}s`}`;
const formatDate = (value, options = { day: "numeric", month: "short", year: "numeric" }) => value ? new Intl.DateTimeFormat(undefined, options).format(new Date(value)) : "Not recorded";
const formatDateTime = (value) => formatDate(value, { day: "numeric", month: "short", hour: "numeric", minute: "2-digit" });
const signedQuantity = (value) => `${Number(value) > 0 ? "+" : ""}${value}`;

function State({ loading, error, retry, children }) {
  if (loading) return <section className="crew-v2-state" role="status"><span className="crew-v2-spinner" /><strong>Loading Assets…</strong></section>;
  if (error) return <section className="crew-v2-state"><strong>Assets unavailable</strong><p>{error}</p><button className="crew-mobile-primary" onClick={retry}>Try again</button></section>;
  return children;
}

function activityProjection(data, assetId) {
  // Inspection corrections are represented by the richer inspection evidence below.
  const movements = (data?.movement_history || []).filter((item) => item.reason !== "inspection" && (!assetId || item.asset_id === assetId)).map((item) => ({ ...item, kind: "adjustment", at: item.created_at || item.movement_date }));
  const inspections = (data?.inspection_history || []).filter((item) => !assetId || item.asset_ids?.includes(assetId)).map((item) => ({ ...item, kind: "inspection", at: item.created_at || item.inspection_date }));
  return [...movements, ...inspections].sort((a, b) => new Date(b.at) - new Date(a.at));
}

function AssetMasterImage({ asset, alt = "", className = "" }) {
  const sources = [...new Set([asset.thumbnail_url, asset.image_url, asset.original_image_url].filter(Boolean))];
  const [sourceIndex, setSourceIndex] = useState(0);
  useEffect(() => setSourceIndex(0), [asset.id, sources.join("|")]);
  const source = sources[sourceIndex];
  return source ? <img className={className} src={source} alt={alt} onError={() => setSourceIndex((current) => current + 1)} /> : null;
}

export default function CrewAssetsMobile({ token, onBack }) {
  const [data, setData] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const [query, setQuery] = useState(""); const [category, setCategory] = useState("all"); const [asset, setAsset] = useState(null);
  const [adjusting, setAdjusting] = useState(false); const [adding, setAdding] = useState(false); const [inspection, setInspection] = useState(null); const [activity, setActivity] = useState(false); const [notice, setNotice] = useState("");
  async function load(assetId) { setLoading(true); setError(""); try { const next = await crewService.assetsMobile(token, assetId); setData(next); return next; } catch (cause) { setError(cause.message || "Unable to load Assets."); return null; } finally { setLoading(false); } }
  useEffect(() => { void load(); }, [token]);
  const visible = useMemo(() => (data?.assets || []).filter((item) => (category === "all" || item.category_id === category) && `${item.name} ${item.asset_code || ""} ${item.location || ""}`.toLowerCase().includes(query.toLowerCase())), [data, query, category]);
  const categories = useMemo(() => [{ value: "all", label: "All categories" }, ...(data?.categories || []).map((item) => ({ value: item.id, label: item.name }))], [data]);
  if (inspection) return <InspectionFlow token={token} data={data} initial={inspection} onBack={() => setInspection(null)} onSaved={async (result, status) => { const refreshed = await load(); const updates = new Map((result?.asset_updates || []).map((item) => [item.id, item])); if (updates.size) setData((previous) => previous ? { ...previous, assets: previous.assets.map((item) => ({ ...item, ...(updates.get(item.id) || {}) })) } : previous); if (asset) { const latest = refreshed?.assets?.find((item) => item.id === asset.id) || asset; setAsset({ ...latest, ...(updates.get(asset.id) || {}) }); } setNotice(status === "in_progress" ? "Draft saved" : "Inspection completed"); setInspection(null); }} />;
  if (asset) return <><AssetDetail asset={asset} data={data} onBack={() => setAsset(null)} onAdjust={() => setAdjusting(true)} onInspect={() => setInspection({ scope: "specific", assets: [asset] })} onActivity={() => setActivity({ assetId: asset.id, title: asset.name })} />
    {adjusting ? <AdjustSheet token={token} asset={asset} onClose={() => setAdjusting(false)} onSaved={async () => { const refreshed = await load(); setAsset(refreshed?.assets?.find((item) => item.id === asset.id) || null); setAdjusting(false); }} /> : null}
    {activity ? <ActivitySheet data={data} assetId={activity.assetId} title={activity.title} onClose={() => setActivity(false)} /> : null}
  </>;
  return <section className="crew-assets-page"><CrewMobileDetailHeader title="Assets" onBack={onBack} /><State loading={loading} error={error} retry={load}><>
    <header className="crew-assets-intro"><div><strong>{data?.outlet?.name}</strong><span>{data?.assets?.length || 0} active assets</span></div><span className="crew-assets-header-actions"><button type="button" onClick={() => setActivity({ title: "Asset activity" })}><History size={19} /><span>Activity</span></button></span></header>
    <CrewSearchBar value={query} onChange={setQuery} placeholder="Search assets" />
    {notice ? <p className="crew-assets-notice" role="status">{notice}</p> : null}
    {data?.inspection_drafts?.map((draft) => <button className="crew-assets-resume" type="button" key={draft.id} onClick={() => setInspection({ draft })}><span><strong>Resume inspection</strong><small>{draft.completion_percentage || 0}% complete · saved {formatDateTime(draft.updated_at)}</small></span><ChevronRight size={18} /></button>)}
    {(data?.can_add_assets || data?.can_perform_asset_inspections) ? <div className={`crew-assets-operational-actions${data?.can_add_assets && data?.can_perform_asset_inspections ? "" : " is-single"}`}>{data?.can_add_assets ? <button className="crew-mobile-secondary" type="button" onClick={() => setAdding(true)}><PackagePlus size={18} />Add Asset</button> : null}{data?.can_perform_asset_inspections ? <button className="crew-mobile-primary" type="button" onClick={() => setInspection({ scope: "all", assets: data.assets })}><ClipboardCheck size={18} />Start inspection</button> : null}</div> : null}
    <div className="crew-assets-filters"><CrewChoicePicker label="Category" value={category} options={categories} onChange={setCategory} /></div>
    <div className="crew-assets-list">{visible.map((item) => <button type="button" key={item.id} onClick={() => setAsset(item)}><span className="crew-assets-thumb">{item.thumbnail_url || item.image_url || item.original_image_url ? <AssetMasterImage asset={item} /> : <PackageSearch size={22} />}</span><span><strong>{item.name}</strong><small>{item.category_name}{item.location ? ` · ${item.location}` : ""}</small><em>{pluralize(item.current_quantity, item.unit)}</em></span><CrewStatusBadge tone={tone(item.condition)}>{conditionLabels[item.condition] || item.condition}</CrewStatusBadge><ChevronRight size={18} /></button>)}{!visible.length ? <CrewEmptyState title="No assets found" body="Try another search or category." /> : null}</div>
    {adding ? <AddAssetSheet token={token} categories={data?.categories || []} onClose={() => setAdding(false)} onSaved={async (assetId) => { const refreshed = await load(assetId); setAdding(false); setAsset(refreshed?.assets?.find((item) => item.id === assetId) || null); }} /> : null}{activity ? <ActivitySheet data={data} title={activity.title} onClose={() => setActivity(false)} /> : null}
  </></State></section>;
}

function AssetDetail({ asset, data, onBack, onAdjust, onInspect, onActivity }) {
  const activity = activityProjection(data, asset.id).slice(0, 4); const movement = activity.find((item) => item.kind === "adjustment"); const inspection = activity.find((item) => item.kind === "inspection");
  return <section className="crew-assets-page"><CrewMobileDetailHeader title="Asset Detail" onBack={onBack} /><article className="crew-asset-detail">
    <div className="crew-asset-detail-lead"><div className="crew-asset-detail-image">{asset.image_url || asset.original_image_url ? <AssetMasterImage asset={{ ...asset, thumbnail_url: "" }} /> : <PackageSearch size={30} />}</div><header><span><small>{asset.asset_code || asset.category_name}</small><h1>{asset.name}</h1>{asset.location ? <em><MapPin size={14} />{asset.location}</em> : null}</span><CrewStatusBadge tone={tone(asset.condition)}>{conditionLabels[asset.condition] || asset.condition}</CrewStatusBadge></header></div>
    {asset.description ? <p>{asset.description}</p> : null}<dl><div><dt>Quantity</dt><dd>{pluralize(asset.current_quantity, asset.unit)}</dd></div>{asset.location ? <div><dt>Location</dt><dd>{asset.location}</dd></div> : null}<div><dt>Last movement</dt><dd>{movement ? formatDateTime(movement.at) : "No movements"}</dd></div><div><dt>Last inspection</dt><dd>{inspection ? formatDate(inspection.inspection_date) : formatDate(asset.last_inspection_at)}</dd></div></dl>
    {asset.maintenance?.length ? <section className="crew-asset-maintenance"><strong>Maintenance</strong>{asset.maintenance.map((item, index) => <p key={index}>{item.status === "in_progress" ? "In progress" : "Scheduled"}{item.issue ? ` · ${item.issue}` : ""}{item.scheduled_date ? ` · ${formatDate(item.scheduled_date)}` : ""}</p>)}</section> : null}
    <section className="crew-asset-activity"><header><strong>Recent activity</strong>{activity.length ? <button type="button" onClick={onActivity}>View all activity</button> : null}</header>{activity.length ? activity.map((item) => <ActivityRow key={`${item.kind}-${item.id}`} item={item} />) : <p>No recent activity for this asset.</p>}</section>
    <footer>{data?.can_adjust_assets ? <button className="crew-mobile-secondary" onClick={onAdjust}><SlidersHorizontal size={18} />Adjust Quantity</button> : null}{data?.can_perform_asset_inspections ? <button className="crew-mobile-primary" onClick={onInspect}><ClipboardCheck size={18} />Inspect Asset</button> : null}</footer>
  </article></section>;
}

function AdjustSheet({ token, asset, onClose, onSaved }) {
  const [type, setType] = useState("correction"); const [quantity, setQuantity] = useState(String(asset.current_quantity)); const [reason, setReason] = useState("stock_count"); const [note, setNote] = useState("");
  const [confirming, setConfirming] = useState(false); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  const entered = Number(quantity); const current = Number(asset.current_quantity); const next = Number.isFinite(entered) ? type === "add" ? current + entered : type === "reduce" ? current - entered : entered : current; const difference = next - current; const requiresConfirmation = Math.abs(difference) >= Math.max(10, current * 0.25);
  async function save() { setSaving(true); setError(""); try { await crewService.adjustAsset(token, { requestId: requestId(), assetId: asset.id, adjustmentType: type, quantity, reason, note }); await onSaved(); } catch (cause) { setError(cause.message || "Unable to adjust quantity."); } finally { setSaving(false); } }
  const footer = <><button className="crew-mobile-ghost" onClick={confirming ? () => setConfirming(false) : onClose} disabled={saving}>{confirming ? "Back" : "Cancel"}</button><button className="crew-mobile-primary" disabled={saving || !quantity || !reason || next < 0} onClick={() => confirming ? void save() : requiresConfirmation ? setConfirming(true) : void save()}>{saving ? "Saving…" : confirming ? "Confirm adjustment" : "Save adjustment"}</button></>;
  return <CrewBottomSheet title={confirming ? "Confirm large adjustment" : "Adjust Quantity"} description={asset.name} onClose={onClose} closeDisabled={saving} footer={footer}>{confirming ? <div className="crew-assets-confirm"><p>This changes stock by <strong>{signedQuantity(difference)} {asset.unit}</strong>.</p><div className="crew-assets-impact"><span><small>Current</small><strong>{pluralize(current, asset.unit)}</strong></span><ChevronRight size={18} /><span><small>New quantity</small><strong>{pluralize(next, asset.unit)}</strong></span></div><p>Confirm only after checking the physical count.</p></div> : <div className="crew-assets-form">
    <CrewChoicePicker label="Adjustment" value={type} options={adjustmentOptions} onChange={setType} /><label>Quantity<input inputMode="decimal" enterKeyHint="next" type="number" min="0" step="any" value={quantity} onChange={(event) => setQuantity(event.target.value)} /></label><div className="crew-assets-impact"><span><small>Current quantity</small><strong>{pluralize(current, asset.unit)}</strong></span><ChevronRight size={18} /><span><small>New quantity</small><strong>{pluralize(next, asset.unit)}</strong></span><em>{signedQuantity(difference)} {asset.unit}</em></div><CrewChoicePicker label="Reason" value={reason} options={reasonOptions} onChange={setReason} /><label>Note {reason !== "other" ? <small>Optional</small> : null}<textarea enterKeyHint="done" value={note} onChange={(event) => setNote(event.target.value)} placeholder="Add operational context" /></label>{error ? <p className="crew-v2-error" role="alert">{error}</p> : null}
  </div>}</CrewBottomSheet>;
}

function AddAssetSheet({ token, categories, onClose, onSaved }) {
  const [name, setName] = useState(""); const [category, setCategory] = useState(""); const [quantity, setQuantity] = useState(""); const [unit, setUnit] = useState("unit"); const [code, setCode] = useState(""); const [location, setLocation] = useState(""); const [description, setDescription] = useState(""); const [photo, setPhoto] = useState(null); const [preparingPhoto, setPreparingPhoto] = useState(false); const [createdAssetId, setCreatedAssetId] = useState(""); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  const createRequestId = useRef(requestId()); const photoRequestId = useRef(requestId());
  const categoryOptions = [{ value: "", label: "Choose category" }, ...categories.map((item) => ({ value: item.id, label: item.name }))];
  const draft = { name, category_id: category, initial_quantity: quantity, unit, asset_code: code, location, description };
  const validationError = validateAssetCreateValues(draft, categories.map((item) => item.id));
  useEffect(() => () => { if (photo?.previewUrl) URL.revokeObjectURL?.(photo.previewUrl); }, [photo?.previewUrl]);
  async function choosePhoto(file) {
    if (!file) return;
    setPreparingPhoto(true); setError("");
    try { setPhoto(await crewService.prepareAssetMasterPhoto(file)); } catch (cause) { setError(cause.message || "That photo could not be prepared. Try another image."); } finally { setPreparingPhoto(false); }
  }
  function removePhoto() { setPhoto(null); photoRequestId.current = requestId(); }
  async function save() {
    setSaving(true); setError(""); let stage = "create";
    try {
      let assetId = createdAssetId;
      if (!assetId) {
        const result = await crewService.createAsset(token, { requestId: createRequestId.current, asset: buildCrewAssetCreatePayload(draft) });
        assetId = result?.asset?.id || "";
        if (!assetId) throw new Error("Asset creation returned no identifier.");
        setCreatedAssetId(assetId);
      }
      if (photo) { stage = "photo"; await crewService.uploadInitialAssetPhoto(token, assetId, photo, photoRequestId.current); }
      await onSaved(assetId);
    } catch (cause) { setError(assetCreateErrorMessage(stage, cause)); } finally { setSaving(false); }
  }
  const locked = Boolean(createdAssetId);
  return <CrewBottomSheet title="Add Asset" description={locked ? "Asset created. Retry the photo attachment to finish." : "Creates a new active asset for this outlet."} onClose={onClose} closeDisabled={saving} footer={<><button className="crew-mobile-ghost" type="button" onClick={onClose} disabled={saving}>Cancel</button><button className="crew-mobile-primary" type="button" disabled={Boolean(validationError) || saving || preparingPhoto} onClick={() => void save()}>{saving ? "Adding…" : locked ? "Retry photo" : "Add Asset"}</button></>}><div className="crew-assets-form"><label>Asset name<input enterKeyHint="next" value={name} onChange={(event) => setName(event.target.value)} autoComplete="off" disabled={locked} /></label><CrewChoicePicker label="Category" value={category} options={categoryOptions} onChange={setCategory} disabled={locked} /><div className="crew-assets-inline-fields"><label>Initial quantity<input type="number" inputMode="decimal" enterKeyHint="next" min="0" step="any" value={quantity} onChange={(event) => setQuantity(event.target.value)} disabled={locked} /></label><CrewChoicePicker label="Unit" value={unit} options={ASSET_CREATE_UNIT_OPTIONS} onChange={setUnit} disabled={locked} /></div><label>Asset code <small>Optional</small><input enterKeyHint="next" value={code} onChange={(event) => setCode(event.target.value)} autoComplete="off" disabled={locked} /></label><label>Location <small>Optional</small><input enterKeyHint="next" value={location} onChange={(event) => setLocation(event.target.value)} disabled={locked} /></label><fieldset className="crew-assets-photo-field"><legend>Photo <small>Optional</small></legend>{photo ? <div className="crew-assets-photo-preview"><img src={photo.previewUrl} alt="Normalized Asset preview" /><div><label><Camera size={17} />Replace<input type="file" accept="image/jpeg,image/png,image/webp" capture="environment" onChange={(event) => void choosePhoto(event.target.files?.[0])} /></label><button type="button" onClick={removePhoto}><Trash2 size={17} />Remove</button></div></div> : <div className="crew-assets-photo-actions"><label><Camera size={18} />Take Photo<input type="file" accept="image/jpeg,image/png,image/webp" capture="environment" onChange={(event) => void choosePhoto(event.target.files?.[0])} /></label><label><ImagePlus size={18} />Choose from Library<input type="file" accept="image/jpeg,image/png,image/webp" onChange={(event) => void choosePhoto(event.target.files?.[0])} /></label></div>}{preparingPhoto ? <small role="status">Preparing 4:3 preview…</small> : null}</fieldset><label>Description <small>Optional</small><textarea enterKeyHint="done" value={description} onChange={(event) => setDescription(event.target.value)} disabled={locked} /></label>{error ? <p className="crew-v2-error" role="alert">{error}</p> : null}</div></CrewBottomSheet>;
}

function ActivitySheet({ data, assetId, title, onClose }) {
  const [filter, setFilter] = useState("all"); const events = activityProjection(data, assetId).filter((item) => filter === "all" || item.kind === filter);
  return <CrewBottomSheet title={title || "Asset activity"} description={assetId ? "Latest activity for this asset" : "Quantity movements and completed inspections"} onClose={onClose}><div className="crew-assets-activity-filter" role="group" aria-label="Activity filter">{[{ value: "all", label: "All" }, { value: "adjustment", label: "Adjustments" }, { value: "inspection", label: "Inspections" }].map((item) => <button type="button" key={item.value} className={filter === item.value ? "active" : ""} onClick={() => setFilter(item.value)}>{item.label}</button>)}</div><div className="crew-assets-history">{events.map((item) => <ActivityRow key={`${item.kind}-${item.id}`} item={item} />)}{!events.length ? <CrewEmptyState title="No activity yet" body="Asset movements and completed inspections appear here." /> : null}</div></CrewBottomSheet>;
}

function ActivityRow({ item }) {
  if (item.kind === "adjustment") return <article className="crew-assets-activity-row"><span><strong>Quantity adjusted · {item.asset_name}</strong><small>{item.quantity_before} → {item.quantity_after} units · {signedQuantity(item.quantity_change)}</small><em>{item.reason?.replaceAll("_", " ")} · {formatDateTime(item.at)} · by {item.actor_name || "Admin"}</em></span><CrewStatusBadge tone="neutral">Adjustment</CrewStatusBadge></article>;
  const count = item.summary?.checked_assets || item.asset_ids?.length || 0; const inspected = item.items?.[0];
  return <article className="crew-assets-activity-row"><span><strong>Inspection completed{inspected?.asset_name ? ` · ${inspected.asset_name}` : ""}</strong><small>{inspected ? `Expected ${inspected.expected_quantity} · Counted ${inspected.counted_quantity} · ${signedQuantity(inspected.difference)}` : `${count} ${count === 1 ? "asset" : "assets"} inspected`}{inspected?.condition ? ` · ${conditionLabels[inspected.condition] || inspected.condition}` : ""}</small><em>{formatDateTime(item.at)} · by {item.checked_by || "Crew"}</em></span><CrewStatusBadge tone="success">Inspection</CrewStatusBadge></article>;
}

function InspectionFlow({ token, data, initial, onBack, onSaved }) {
  const draft = initial.draft; const [scope, setScope] = useState(draft?.category_scope?.type || initial.scope || "all"); const [category, setCategory] = useState(draft?.category_scope?.category_ids?.[0] || "");
  const initialAssets = draft ? (draft.draft_data?.rows || []).map((row) => ({ ...data.assets.find((asset) => asset.id === row.asset_id), saved: row })) : initial.assets; const scoped = useMemo(() => (initialAssets || data.assets || []).filter((item) => scope !== "category" || item.category_id === category), [initialAssets, data.assets, scope, category]);
  const [started, setStarted] = useState(Boolean(draft || initial.scope === "specific")); const [index, setIndex] = useState(draft?.current_step ? Math.max(0, draft.current_step - 1) : 0); const [rows, setRows] = useState(() => Object.fromEntries((initialAssets || []).map((item) => [item.id, item.saved || { asset_id: item.id, counted_quantity: item.current_quantity, condition_status: item.condition || "healthy", remark: "", evidence: [] }]))); const initialRows = useRef(JSON.stringify(Object.fromEntries((initialAssets || []).map((item) => [item.id, item.saved || { asset_id: item.id, counted_quantity: item.current_quantity, condition_status: item.condition || "healthy", remark: "", evidence: [] }])))); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  const current = scoped[index]; const row = current && rows[current.id]; const categoryOptions = [{ value: "", label: "Choose category" }, ...(data.categories || []).map((item) => ({ value: item.id, label: item.name }))];
  function patch(values) { setRows((previous) => ({ ...previous, [current.id]: { ...previous[current.id], ...values } })); }
  async function upload(file) { if (!file) return; setSaving(true); setError(""); try { const evidence = await crewService.uploadAssetInspectionEvidence(token, current.id, file); patch({ evidence: [...(row.evidence || []), { image_url: evidence.image_url }] }); } catch (cause) { setError(cause.message || "Unable to upload photo."); } finally { setSaving(false); } }
  const payload = (status) => ({ draft_id: draft?.id || null, status, category_scope: { type: scope, category_ids: category ? [category] : [] }, current_step: index + 1, completion_percentage: scoped.length ? Math.round((index / scoped.length) * 100) : 0, draft_data: { rows: scoped.map((item) => rows[item.id]) }, rows: scoped.map((item) => { const value = rows[item.id]; const template = data.condition_templates?.find((candidate) => candidate.category_id === item.category_id && candidate.name.toLowerCase() === (conditionLabels[value.condition_status] || value.condition_status).toLowerCase()); return { ...value, condition_template_id: template?.id || null, evidence_required: Boolean(template?.requires_photo) }; }) });
  const hasChanges = JSON.stringify(rows) !== initialRows.current;
  async function save(status) { setSaving(true); setError(""); try { const result = await crewService.submitAssetInspection(token, { requestId: requestId(), ...payload(status) }); await onSaved(result, status); } catch (cause) { setError(cause.message || "Unable to save inspection."); } finally { setSaving(false); } }
  if (!started) return <section className="crew-assets-page"><CrewMobileDetailHeader title="Start Inspection" onBack={onBack} /><div className="crew-inspection-setup"><ClipboardCheck size={30} /><h1>Choose inspection scope</h1><button type="button" className={scope === "all" ? "active" : ""} onClick={() => setScope("all")}><strong>Full outlet</strong><small>Inspect every active outlet asset</small></button><button type="button" className={scope === "category" ? "active" : ""} onClick={() => setScope("category")}><strong>Category</strong><small>Inspect one asset category</small></button>{scope === "category" ? <CrewChoicePicker label="Category" value={category} options={categoryOptions} onChange={setCategory} /> : null}<button className="crew-mobile-primary" disabled={scope === "category" && !category} onClick={() => setStarted(true)}>Begin inspection</button></div></section>;
  const expected = Number(current?.current_quantity ?? 0); const counted = Number(row?.counted_quantity ?? expected); const difference = Number.isFinite(counted) ? counted - expected : 0;
  return <section className="crew-assets-page"><CrewMobileDetailHeader title="Asset Inspection" onBack={onBack} />{current ? <article className="crew-inspection-step"><header><span>Asset {index + 1} of {scoped.length}</span><strong>{current.name}</strong><small>{current.location || current.category_name}</small></header><div className="crew-inspection-progress"><span style={{ width: `${((index + 1) / scoped.length) * 100}%` }} /></div><div className="crew-inspection-count-context"><span><small>Expected quantity</small><strong>{pluralize(expected, current.unit)}</strong></span><span><small>Difference</small><strong className={difference ? "is-difference" : ""}>{signedQuantity(difference)} {current.unit}</strong></span></div><label>Counted quantity<input type="number" min="0" step="any" inputMode="decimal" enterKeyHint="next" value={row.counted_quantity} onChange={(event) => patch({ counted_quantity: event.target.value })} /></label><fieldset><legend>Condition</legend>{conditions.map((item) => <button type="button" key={item} className={row.condition_status === item ? "active" : ""} onClick={() => patch({ condition_status: item })}>{conditionLabels[item]}</button>)}</fieldset><label>Note<textarea enterKeyHint="done" value={row.remark} onChange={(event) => patch({ remark: event.target.value })} placeholder="Add details when attention is needed" /></label><label className="crew-assets-photo"><Camera size={18} />Add photo<input type="file" accept="image/jpeg,image/png,image/webp" capture="environment" onChange={(event) => void upload(event.target.files?.[0])} /></label>{row.evidence?.length ? <small>{row.evidence.length} photo attached</small> : null}{error ? <p className="crew-v2-error" role="alert">{error}</p> : null}<footer><button className="crew-mobile-secondary" disabled={saving || !hasChanges} onClick={() => void save("in_progress")}>{saving ? "Saving…" : "Save draft"}</button>{index > 0 ? <button className="crew-mobile-ghost" onClick={() => setIndex(index - 1)}>Previous</button> : null}{index < scoped.length - 1 ? <button className="crew-mobile-primary" onClick={() => setIndex(index + 1)}>Next</button> : <button className="crew-mobile-primary" disabled={saving} onClick={() => void save("completed")}>{saving ? "Saving…" : "Complete inspection"}</button>}</footer></article> : <CrewEmptyState title="No assets in this scope" body="Choose another inspection scope." />}</section>;
}
