import { useEffect, useMemo, useState } from "react";
import { Camera, ChevronRight, ClipboardCheck, History, MapPin, PackageSearch, SlidersHorizontal } from "lucide-react";
import { crewService } from "../../../services/crewService.js";
import CrewBottomSheet from "./CrewBottomSheet.jsx";
import CrewChoicePicker from "./CrewChoicePicker.jsx";
import CrewMobileDetailHeader from "./CrewMobileDetailHeader.jsx";
import { CrewEmptyState, CrewSearchBar, CrewStatusBadge } from "./CrewMobileUI.jsx";
import "./CrewAssetsMobile.css";

const conditions = ["healthy", "needs_attention", "low_quantity", "damaged", "missing"];
const conditionLabels = { healthy: "Healthy", needs_attention: "Needs attention", low_quantity: "Low quantity", damaged: "Damaged", missing: "Missing" };
const adjustmentOptions = [{ value: "correction", label: "Set exact quantity" }, { value: "add", label: "Add quantity" }, { value: "reduce", label: "Reduce quantity" }];
const reasonOptions = [{ value: "stock_count", label: "Stock count" }, { value: "received", label: "Received" }, { value: "used", label: "Used / consumed" }, { value: "damaged", label: "Damaged" }, { value: "missing", label: "Missing" }, { value: "other", label: "Other" }];
const tone = (value) => value === "healthy" ? "success" : value === "low_quantity" || value === "needs_attention" ? "warning" : "danger";
const requestId = () => globalThis.crypto?.randomUUID?.() || `${Date.now()}-${Math.random()}`;
const pluralize = (quantity, unit) => `${quantity} ${Number(quantity) === 1 ? unit : `${unit}s`}`;
const formatDate = (value, options = { day: "numeric", month: "short", year: "numeric" }) => value ? new Intl.DateTimeFormat(undefined, options).format(new Date(value)) : "Not recorded";
const formatDateTime = (value) => formatDate(value, { day: "numeric", month: "short", hour: "numeric", minute: "2-digit" });
const signedQuantity = (value) => `${Number(value) > 0 ? "+" : ""}${value}`;

function State({ loading, error, retry, children }) {
  if (loading) return <section className="crew-v2-state" role="status"><span className="crew-v2-spinner" /><strong>Loading Assets…</strong></section>;
  if (error) return <section className="crew-v2-state"><strong>Assets unavailable</strong><p>{error}</p><button className="crew-mobile-primary" onClick={retry}>Try again</button></section>;
  return children;
}

function activityProjection(data, assetId) {
  const movements = (data?.movement_history || []).filter((item) => !assetId || item.asset_id === assetId).map((item) => ({ ...item, kind: "adjustment", at: item.created_at || item.movement_date }));
  const inspections = (data?.inspection_history || []).filter((item) => !assetId || item.asset_ids?.includes(assetId)).map((item) => ({ ...item, kind: "inspection", at: item.created_at || item.inspection_date }));
  return [...movements, ...inspections].sort((a, b) => new Date(b.at) - new Date(a.at));
}

export default function CrewAssetsMobile({ token, onBack }) {
  const [data, setData] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const [query, setQuery] = useState(""); const [category, setCategory] = useState("all"); const [asset, setAsset] = useState(null);
  const [adjusting, setAdjusting] = useState(false); const [inspection, setInspection] = useState(null); const [activity, setActivity] = useState(false);
  async function load(assetId) { setLoading(true); setError(""); try { const next = await crewService.assetsMobile(token, assetId); setData(next); return next; } catch (cause) { setError(cause.message || "Unable to load Assets."); return null; } finally { setLoading(false); } }
  useEffect(() => { void load(); }, [token]);
  const visible = useMemo(() => (data?.assets || []).filter((item) => (category === "all" || item.category_id === category) && `${item.name} ${item.asset_code || ""} ${item.location || ""}`.toLowerCase().includes(query.toLowerCase())), [data, query, category]);
  const categories = useMemo(() => [{ value: "all", label: "All categories" }, ...(data?.categories || []).map((item) => ({ value: item.id, label: item.name }))], [data]);
  if (inspection) return <InspectionFlow token={token} data={data} initial={inspection} onBack={() => setInspection(null)} onSaved={async () => { await load(); setInspection(null); }} />;
  if (asset) return <><AssetDetail asset={asset} data={data} onBack={() => setAsset(null)} onAdjust={() => setAdjusting(true)} onInspect={() => setInspection({ scope: "specific", assets: [asset] })} onActivity={() => setActivity({ assetId: asset.id, title: asset.name })} />
    {adjusting ? <AdjustSheet token={token} asset={asset} onClose={() => setAdjusting(false)} onSaved={async () => { const refreshed = await load(); setAsset(refreshed?.assets?.find((item) => item.id === asset.id) || null); setAdjusting(false); }} /> : null}
    {activity ? <ActivitySheet data={data} assetId={activity.assetId} title={activity.title} onClose={() => setActivity(false)} /> : null}
  </>;
  return <section className="crew-assets-page"><CrewMobileDetailHeader title="Assets" onBack={onBack} /><State loading={loading} error={error} retry={load}><>
    <header className="crew-assets-intro"><div><strong>{data?.outlet?.name}</strong><span>{data?.assets?.length || 0} active assets</span></div><button type="button" onClick={() => setActivity({ title: "Asset activity" })}><History size={19} /><span>Activity</span></button></header>
    <CrewSearchBar value={query} onChange={setQuery} placeholder="Search assets" />
    {data?.inspection_drafts?.map((draft) => <button className="crew-assets-resume" type="button" key={draft.id} onClick={() => setInspection({ draft })}><span><strong>Resume inspection</strong><small>{draft.completion_percentage || 0}% complete · saved {formatDateTime(draft.updated_at)}</small></span><ChevronRight size={18} /></button>)}
    <div className="crew-assets-filters"><CrewChoicePicker label="Category" value={category} options={categories} onChange={setCategory} />{data?.can_perform_asset_inspections ? <button className="crew-assets-inspect" type="button" onClick={() => setInspection({ scope: "all", assets: data.assets })}><ClipboardCheck size={18} />Start inspection</button> : null}</div>
    <div className="crew-assets-list">{visible.map((item) => <button type="button" key={item.id} onClick={() => setAsset(item)}><span className="crew-assets-thumb">{item.thumbnail_url || item.image_url ? <img src={item.thumbnail_url || item.image_url} alt="" /> : <PackageSearch size={22} />}</span><span><strong>{item.name}</strong><small>{item.category_name}{item.location ? ` · ${item.location}` : ""}</small><em>{pluralize(item.current_quantity, item.unit)}</em></span><CrewStatusBadge tone={tone(item.condition)}>{conditionLabels[item.condition] || item.condition}</CrewStatusBadge><ChevronRight size={18} /></button>)}{!visible.length ? <CrewEmptyState title="No assets found" body="Try another search or category." /> : null}</div>
    {activity ? <ActivitySheet data={data} title={activity.title} onClose={() => setActivity(false)} /> : null}
  </></State></section>;
}

function AssetDetail({ asset, data, onBack, onAdjust, onInspect, onActivity }) {
  const activity = activityProjection(data, asset.id).slice(0, 4); const movement = activity.find((item) => item.kind === "adjustment"); const inspection = activity.find((item) => item.kind === "inspection");
  return <section className="crew-assets-page"><CrewMobileDetailHeader title="Asset Detail" onBack={onBack} /><article className="crew-asset-detail">
    <div className="crew-asset-detail-lead"><div className="crew-asset-detail-image">{asset.image_url ? <img src={asset.image_url} alt="" /> : <PackageSearch size={30} />}</div><header><span><small>{asset.asset_code || asset.category_name}</small><h1>{asset.name}</h1>{asset.location ? <em><MapPin size={14} />{asset.location}</em> : null}</span><CrewStatusBadge tone={tone(asset.condition)}>{conditionLabels[asset.condition] || asset.condition}</CrewStatusBadge></header></div>
    {asset.description ? <p>{asset.description}</p> : null}<dl><div><dt>Quantity</dt><dd>{pluralize(asset.current_quantity, asset.unit)}</dd></div>{asset.location ? <div><dt>Location</dt><dd>{asset.location}</dd></div> : null}<div><dt>Last movement</dt><dd>{movement ? formatDateTime(movement.at) : "No movements"}</dd></div><div><dt>Last inspection</dt><dd>{inspection ? formatDate(inspection.inspection_date) : formatDate(asset.last_inspection_at)}</dd></div></dl>
    {asset.maintenance?.length ? <section className="crew-asset-maintenance"><strong>Maintenance</strong>{asset.maintenance.map((item, index) => <p key={index}>{item.status === "in_progress" ? "In progress" : "Scheduled"}{item.issue ? ` · ${item.issue}` : ""}{item.scheduled_date ? ` · ${formatDate(item.scheduled_date)}` : ""}</p>)}</section> : null}
    <section className="crew-asset-activity"><header><strong>Recent activity</strong>{activity.length ? <button type="button" onClick={onActivity}>View all activity</button> : null}</header>{activity.length ? activity.map((item) => <ActivityRow key={`${item.kind}-${item.id}`} item={item} />) : <p>No recent activity for this asset.</p>}</section>
    <footer>{data?.can_adjust_assets ? <button className="crew-mobile-ghost" onClick={onAdjust}><SlidersHorizontal size={18} />Adjust Asset</button> : null}{data?.can_perform_asset_inspections ? <button className="crew-mobile-primary" onClick={onInspect}><ClipboardCheck size={18} />Inspect Asset</button> : null}</footer>
  </article></section>;
}

function AdjustSheet({ token, asset, onClose, onSaved }) {
  const [type, setType] = useState("correction"); const [quantity, setQuantity] = useState(String(asset.current_quantity)); const [condition, setCondition] = useState(asset.condition || "healthy"); const [reason, setReason] = useState("stock_count"); const [note, setNote] = useState("");
  const [confirming, setConfirming] = useState(false); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  const entered = Number(quantity); const current = Number(asset.current_quantity); const next = Number.isFinite(entered) ? type === "add" ? current + entered : type === "reduce" ? current - entered : entered : current; const difference = next - current; const requiresConfirmation = Math.abs(difference) >= Math.max(10, current * 0.25);
  async function save() { setSaving(true); setError(""); try { await crewService.adjustAsset(token, { requestId: requestId(), assetId: asset.id, adjustmentType: type, quantity, condition, reason, note }); await onSaved(); } catch (cause) { setError(cause.message || "Unable to adjust asset."); } finally { setSaving(false); } }
  const footer = <><button className="crew-mobile-ghost" onClick={confirming ? () => setConfirming(false) : onClose} disabled={saving}>{confirming ? "Back" : "Cancel"}</button><button className="crew-mobile-primary" disabled={saving || !quantity || !reason || next < 0} onClick={() => confirming ? void save() : requiresConfirmation ? setConfirming(true) : void save()}>{saving ? "Saving…" : confirming ? "Confirm adjustment" : "Save adjustment"}</button></>;
  return <CrewBottomSheet title={confirming ? "Confirm large adjustment" : "Adjust Asset"} description={asset.name} onClose={onClose} closeDisabled={saving} footer={footer}>{confirming ? <div className="crew-assets-confirm"><p>This changes stock by <strong>{signedQuantity(difference)} {asset.unit}</strong>.</p><div className="crew-assets-impact"><span><small>Current</small><strong>{pluralize(current, asset.unit)}</strong></span><ChevronRight size={18} /><span><small>New quantity</small><strong>{pluralize(next, asset.unit)}</strong></span></div><p>Confirm only after checking the physical count.</p></div> : <div className="crew-assets-form">
    <CrewChoicePicker label="Adjustment" value={type} options={adjustmentOptions} onChange={setType} /><label>Quantity<input inputMode="decimal" type="number" min="0" step="any" value={quantity} onChange={(event) => setQuantity(event.target.value)} /></label><div className="crew-assets-impact"><span><small>Current quantity</small><strong>{pluralize(current, asset.unit)}</strong></span><ChevronRight size={18} /><span><small>New quantity</small><strong>{pluralize(next, asset.unit)}</strong></span><em>{signedQuantity(difference)} {asset.unit}</em></div><fieldset><legend>Condition</legend>{conditions.map((item) => <button type="button" key={item} className={condition === item ? "active" : ""} onClick={() => setCondition(item)}>{conditionLabels[item]}</button>)}</fieldset><CrewChoicePicker label="Reason" value={reason} options={reasonOptions} onChange={setReason} /><label>Note {reason !== "other" ? <small>Optional</small> : null}<textarea value={note} onChange={(event) => setNote(event.target.value)} placeholder="Add operational context" /></label>{error ? <p className="crew-v2-error" role="alert">{error}</p> : null}
  </div>}</CrewBottomSheet>;
}

function ActivitySheet({ data, assetId, title, onClose }) {
  const [filter, setFilter] = useState("all"); const events = activityProjection(data, assetId).filter((item) => filter === "all" || item.kind === filter);
  return <CrewBottomSheet title={title || "Asset activity"} description={assetId ? "Latest activity for this asset" : "Quantity movements and completed inspections"} onClose={onClose}><div className="crew-assets-activity-filter" role="group" aria-label="Activity filter">{[{ value: "all", label: "All" }, { value: "adjustment", label: "Adjustments" }, { value: "inspection", label: "Inspections" }].map((item) => <button type="button" key={item.value} className={filter === item.value ? "active" : ""} onClick={() => setFilter(item.value)}>{item.label}</button>)}</div><div className="crew-assets-history">{events.map((item) => <ActivityRow key={`${item.kind}-${item.id}`} item={item} />)}{!events.length ? <CrewEmptyState title="No activity yet" body="Asset movements and completed inspections appear here." /> : null}</div></CrewBottomSheet>;
}

function ActivityRow({ item }) {
  if (item.kind === "adjustment") return <article className="crew-assets-activity-row"><span><strong>Quantity adjusted · {item.asset_name}</strong><small>{item.quantity_before} → {item.quantity_after} units · {signedQuantity(item.quantity_change)}</small><em>{item.reason?.replaceAll("_", " ")} · {formatDateTime(item.at)} · by {item.actor_name || "Admin"}</em></span><CrewStatusBadge tone="neutral">Adjustment</CrewStatusBadge></article>;
  const count = item.summary?.checked_assets || item.asset_ids?.length || 0;
  return <article className="crew-assets-activity-row"><span><strong>Inspection completed</strong><small>{count} {count === 1 ? "asset" : "assets"} inspected</small><em>{formatDateTime(item.at)} · by {item.checked_by || "Crew"}</em></span><CrewStatusBadge tone="success">Inspection</CrewStatusBadge></article>;
}

function InspectionFlow({ token, data, initial, onBack, onSaved }) {
  const draft = initial.draft; const [scope, setScope] = useState(draft?.category_scope?.type || initial.scope || "all"); const [category, setCategory] = useState(draft?.category_scope?.category_ids?.[0] || "");
  const initialAssets = draft ? (draft.draft_data?.rows || []).map((row) => ({ ...data.assets.find((asset) => asset.id === row.asset_id), saved: row })) : initial.assets; const scoped = useMemo(() => (initialAssets || data.assets || []).filter((item) => scope !== "category" || item.category_id === category), [initialAssets, data.assets, scope, category]);
  const [started, setStarted] = useState(Boolean(draft || initial.scope === "specific")); const [index, setIndex] = useState(draft?.current_step ? Math.max(0, draft.current_step - 1) : 0); const [rows, setRows] = useState(() => Object.fromEntries((initialAssets || []).map((item) => [item.id, item.saved || { asset_id: item.id, counted_quantity: item.current_quantity, condition_status: item.condition || "healthy", remark: "", evidence: [] }]))); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  const current = scoped[index]; const row = current && rows[current.id]; const categoryOptions = [{ value: "", label: "Choose category" }, ...(data.categories || []).map((item) => ({ value: item.id, label: item.name }))];
  function patch(values) { setRows((previous) => ({ ...previous, [current.id]: { ...previous[current.id], ...values } })); }
  async function upload(file) { if (!file) return; setSaving(true); setError(""); try { const evidence = await crewService.uploadAssetInspectionEvidence(token, current.id, file); patch({ evidence: [...(row.evidence || []), { image_url: evidence.image_url }] }); } catch (cause) { setError(cause.message || "Unable to upload photo."); } finally { setSaving(false); } }
  const payload = (status) => ({ draft_id: draft?.id || null, status, category_scope: { type: scope, category_ids: category ? [category] : [] }, current_step: index + 1, completion_percentage: scoped.length ? Math.round((index / scoped.length) * 100) : 0, draft_data: { rows: scoped.map((item) => rows[item.id]) }, rows: scoped.map((item) => { const value = rows[item.id]; const template = data.condition_templates?.find((candidate) => candidate.category_id === item.category_id && candidate.name.toLowerCase() === (conditionLabels[value.condition_status] || value.condition_status).toLowerCase()); return { ...value, condition_template_id: template?.id || null, evidence_required: Boolean(template?.requires_photo) }; }) });
  async function save(status) { setSaving(true); setError(""); try { await crewService.submitAssetInspection(token, { requestId: requestId(), ...payload(status) }); await onSaved(); } catch (cause) { setError(cause.message || "Unable to save inspection."); } finally { setSaving(false); } }
  if (!started) return <section className="crew-assets-page"><CrewMobileDetailHeader title="Start Inspection" onBack={onBack} /><div className="crew-inspection-setup"><ClipboardCheck size={30} /><h1>Choose inspection scope</h1><button type="button" className={scope === "all" ? "active" : ""} onClick={() => setScope("all")}><strong>Full outlet</strong><small>Inspect every active outlet asset</small></button><button type="button" className={scope === "category" ? "active" : ""} onClick={() => setScope("category")}><strong>Category</strong><small>Inspect one asset category</small></button>{scope === "category" ? <CrewChoicePicker label="Category" value={category} options={categoryOptions} onChange={setCategory} /> : null}<button className="crew-mobile-primary" disabled={scope === "category" && !category} onClick={() => setStarted(true)}>Begin inspection</button></div></section>;
  return <section className="crew-assets-page"><CrewMobileDetailHeader title="Asset Inspection" onBack={onBack} />{current ? <article className="crew-inspection-step"><header><span>Asset {index + 1} of {scoped.length}</span><strong>{current.name}</strong><small>{current.location || current.category_name}</small></header><div className="crew-inspection-progress"><span style={{ width: `${((index + 1) / scoped.length) * 100}%` }} /></div><label>Counted quantity<input type="number" min="0" step="any" inputMode="decimal" value={row.counted_quantity} onChange={(event) => patch({ counted_quantity: event.target.value })} /></label><fieldset><legend>Condition</legend>{conditions.map((item) => <button type="button" key={item} className={row.condition_status === item ? "active" : ""} onClick={() => patch({ condition_status: item })}>{conditionLabels[item]}</button>)}</fieldset><label>Note<textarea value={row.remark} onChange={(event) => patch({ remark: event.target.value })} placeholder="Add details when attention is needed" /></label><label className="crew-assets-photo"><Camera size={18} />Add photo<input type="file" accept="image/jpeg,image/png,image/webp" capture="environment" onChange={(event) => void upload(event.target.files?.[0])} /></label>{row.evidence?.length ? <small>{row.evidence.length} photo attached</small> : null}{error ? <p className="crew-v2-error" role="alert">{error}</p> : null}<footer><button className="crew-mobile-ghost" disabled={saving} onClick={() => void save("in_progress")}>Save draft</button>{index > 0 ? <button className="crew-mobile-ghost" onClick={() => setIndex(index - 1)}>Previous</button> : null}{index < scoped.length - 1 ? <button className="crew-mobile-primary" onClick={() => setIndex(index + 1)}>Next</button> : <button className="crew-mobile-primary" disabled={saving} onClick={() => void save("completed")}>Complete inspection</button>}</footer></article> : <CrewEmptyState title="No assets in this scope" body="Choose another inspection scope." />}</section>;
}
