import { useEffect, useState } from "react";
import { AlertTriangle, ArrowLeft, Check, ChevronRight, ClipboardCheck, Clock3, FileText, HeartPulse, ListChecks, Store } from "lucide-react";
import { crewService } from "../../../services/crewService.js";
import CrewRichContent from "./CrewRichContent.jsx";
import CrewSopImage from "./CrewSopImage.jsx";
import { plainTextToSopHtml } from "../utils/sopDocumentContent.js";

const REASONS = [
  ["equipment_issue", "Equipment issue"], ["stock_unavailable", "Stock unavailable"], ["area_unavailable", "Area unavailable"],
  ["manager_instruction", "Manager instruction"], ["other", "Other"],
];
const title = (value) => ({ opening: "Opening Checklist", closing: "Closing Checklist", daily: "Daily Checklist", health: "Store Health Check" }[value] || "Checklist");
const label = (value) => ({ not_started: "Not Started", in_progress: "In Progress", completed: "Completed", completed_with_exceptions: "Completed · Exceptions", overdue: "Overdue", pending: "Pending", exception: "Unable", good: "Good", needs_attention: "Needs Attention", not_checked: "Not Checked" }[value] || value);
const icon = (type) => type === "health" ? HeartPulse : type === "opening" || type === "closing" ? Store : ClipboardCheck;

export default function CrewOperationsMobile({ token, data, loading, initialTarget, onRefresh, onBack }) {
  const [detail, setDetail] = useState(null); const [selected, setSelected] = useState(null); const [reason, setReason] = useState(""); const [note, setNote] = useState("");
  const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [sop, setSop] = useState(null);
  useEffect(() => { setDetail(null); setSelected(null); setSop(null); }, [token]);
  useEffect(() => {
    if (!initialTarget) return;
    if (initialTarget.kind === "checklist") openChecklist(initialTarget.row);
    if (initialTarget.kind === "task") {
      setSelected({ ...initialTarget.row, kind: "task" });
      setReason("");
      setNote("");
    }
  }, [initialTarget]);
  async function openChecklist(row) { setSaving(true); setError(""); try { setDetail(await crewService.operationDetail(token, row.id)); } catch (cause) { setError(cause.message); } finally { setSaving(false); } }
  async function refreshDetail() { if (!detail) return; const next = await crewService.operationDetail(token, detail.id); setDetail(next); await onRefresh?.(); }
  async function submit(action) { if (!selected) return; setSaving(true); setError(""); try { if (selected.kind === "task") await crewService.updateDailyTask(token, selected.id, action, reason || null, note || null); else await crewService.updateOperationItem(token, selected.id, action, reason || null, note || null); setSelected(null); setReason(""); setNote(""); if (detail) await refreshDetail(); else await onRefresh?.(); } catch (cause) { setError(cause.message); } finally { setSaving(false); } }
  async function finish() { setSaving(true); setError(""); try { await crewService.completeOperationChecklist(token, detail.id); await refreshDetail(); } catch (cause) { setError(cause.message); } finally { setSaving(false); } }
  async function openSop(reference) { setSaving(true); setError(""); try { setSop(await crewService.sopVersion(token, reference.sop_version_id)); } catch (cause) { setError(cause.message); } finally { setSaving(false); } }

  if (sop) return <section className="crew-ops-mobile"><MobileHeader title={sop.title} onBack={() => setSop(null)} /><div className="crew-ops-sop-meta">Published v{sop.version}</div><div className="crew-ops-document">{(sop.sections || []).map((section, index) => <article key={section.id}><small>{String(index + 1).padStart(2, "0")}</small><h2>{section.title}</h2><CrewRichContent html={plainTextToSopHtml(section.body || "")} /><CrewSopImage media={section.media} token={token} sopVersionId={sop.id} />{section.key_point ? <div className="crew-ops-key"><strong>Key Point</strong><p>{section.body}</p></div> : null}</article>)}</div></section>;
  if (detail) return <section className="crew-ops-mobile"><MobileHeader title={detail.name} onBack={() => setDetail(null)} /><div className="crew-ops-detail-head"><span>{title(detail.type)}</span><strong>{label(detail.status)}</strong><small>{detail.items.filter((item) => !["pending", "not_checked"].includes(item.status)).length} of {detail.items.length} checked</small></div><div className="crew-ops-items">{detail.items.map((item, index) => <button type="button" key={item.id} className={`crew-ops-item is-${item.status}`} onClick={() => { setSelected({ ...item, kind: "item", operationType: detail.type }); setReason(item.exception_reason || ""); setNote(item.note || ""); }}><span className="crew-ops-item-state">{["completed", "good"].includes(item.status) ? <Check size={18} /> : ["exception", "needs_attention"].includes(item.status) ? <AlertTriangle size={17} /> : index + 1}</span><span><strong>{item.title}{item.required ? " *" : ""}</strong><small>{item.description || (item.required ? "Required" : "Optional")}</small>{item.sop_reference ? <em onClick={(event) => { event.stopPropagation(); openSop(item.sop_reference); }}><FileText size={13} /> {item.sop_reference.title} · v{item.sop_reference.version}</em> : null}</span><span><b>{label(item.status)}</b><ChevronRight size={16} /></span></button>)}</div>{error ? <div className="crew-v2-error">{error}</div> : null}<div className="crew-ops-sticky"><button className="crew-v2-primary" disabled={saving || ["completed", "completed_with_exceptions"].includes(detail.status)} onClick={finish}>{saving ? "Saving…" : ["completed", "completed_with_exceptions"].includes(detail.status) ? "Checklist Completed" : "Complete Checklist"}</button></div>{selected ? <ActionSheet item={selected} reason={reason} note={note} setReason={setReason} setNote={setNote} saving={saving} onClose={() => setSelected(null)} onSubmit={submit} /> : null}</section>;

  return <section className="crew-ops-mobile"><MobileHeader title="Today’s Tasks" onBack={onBack} /><div className="crew-ops-context"><span><Store size={17} /><strong>{data?.outlet?.name || "Your outlet"}</strong></span><small>{data?.attendance_context?.on_shift ? "On Shift" : "Attendance is not required to review today’s tasks"}</small></div>{loading ? <div className="crew-ops-loading">Loading today’s operations…</div> : <><section className="crew-ops-group"><div className="crew-v2-section-title"><h2>Checklists</h2><span>{data?.checklists?.length || 0}</span></div>{data?.checklists?.length ? data.checklists.map((row) => { const Icon = icon(row.type); return <button key={row.id} type="button" className="crew-ops-card" onClick={() => openChecklist(row)}><span><Icon size={19} /></span><span><strong>{row.name}</strong><small>{title(row.type)} · {row.completed_count}/{row.item_count}</small><i><b style={{ width: `${row.item_count ? row.completed_count / row.item_count * 100 : 0}%` }} /></i></span><em>{label(row.status)}<ChevronRight size={16} /></em></button>; }) : <Empty text="No checklists apply to your role today." />}</section><section className="crew-ops-group"><div className="crew-v2-section-title"><h2>Daily Tasks</h2><span>{data?.daily_tasks?.length || 0}</span></div>{data?.daily_tasks?.length ? data.daily_tasks.map((task) => <button key={task.id} type="button" className={`crew-ops-task is-${task.status}`} onClick={() => { setSelected({ ...task, kind: "task" }); setReason(""); setNote(""); }}><span><ListChecks size={17} /></span><span><strong>{task.title}</strong><small>{task.description || `${task.priority} priority`}</small></span><em>{label(task.status)}<ChevronRight size={16} /></em></button>) : <Empty text="No one-time tasks assigned today." />}</section></>}{error ? <div className="crew-v2-error">{error}</div> : null}{selected ? <ActionSheet item={selected} reason={reason} note={note} setReason={setReason} setNote={setNote} saving={saving} onClose={() => setSelected(null)} onSubmit={submit} /> : null}</section>;
}

function ActionSheet({ item, reason, note, setReason, setNote, saving, onClose, onSubmit }) {
  const health = item.operationType === "health";
  return <div className="crew-ops-sheet-backdrop"><section className="crew-ops-sheet"><div><h2>{item.title}</h2><button onClick={onClose}>×</button></div><p>{health ? "Record the current condition. This is operational evidence, not a Performance deduction." : "Complete this item, or record why it cannot be completed."}</p>{health ? <><button className="crew-ops-choice is-good" onClick={() => onSubmit("good")}><Check size={18} /> Good</button><button className="crew-ops-choice is-warning" onClick={() => setReason("needs_attention")}><AlertTriangle size={18} /> Needs Attention</button><button className="crew-ops-choice" onClick={() => onSubmit("not_checked")}>Not Checked</button>{reason === "needs_attention" ? <><label>What needs attention?<textarea value={note} onChange={(event) => setNote(event.target.value)} placeholder="Required note" /></label><button className="crew-v2-primary" disabled={saving || note.trim().length < 3} onClick={() => onSubmit("needs_attention")}>Submit Result</button></> : null}</> : <><button className="crew-ops-choice is-good" onClick={() => onSubmit("completed")}><Check size={18} /> Complete</button><button className="crew-ops-choice is-warning" onClick={() => setReason(reason || "equipment_issue")}><AlertTriangle size={18} /> Unable to Complete</button>{reason ? <><label>Reason<select value={reason} onChange={(event) => setReason(event.target.value)}>{REASONS.map(([value, text]) => <option key={value} value={value}>{text}</option>)}</select></label><label>Note<textarea value={note} onChange={(event) => setNote(event.target.value)} placeholder="Add helpful context" /></label><button className="crew-v2-primary" disabled={saving} onClick={() => onSubmit("exception")}>Record Exception</button></> : null}</>}</section></div>;
}
function MobileHeader({ title: text, onBack }) { return <header className="crew-v2-page-header"><div><button type="button" onClick={onBack} aria-label="Back"><ArrowLeft size={19} /></button><h1>{text}</h1></div></header>; }
function Empty({ text }) { return <div className="crew-ops-empty"><ClipboardCheck size={22} /><p>{text}</p></div>; }
