import { useEffect, useState } from "react";
import { AlertTriangle, ArrowLeft, Check, ChevronRight, ClipboardCheck, FileText, HeartPulse, ListChecks, Store } from "lucide-react";
import { crewService } from "../../../services/crewService.js";

const REASONS = [["equipment_issue", "Equipment issue"], ["stock_unavailable", "Stock unavailable"], ["area_unavailable", "Area unavailable"], ["manager_instruction", "Manager instruction"], ["other", "Other"]];
const label = (value) => ({ not_started: "Not Started", in_progress: "In Progress", completed: "Completed", completed_with_exceptions: "Completed · Exceptions", review_required: "Review Required", overdue: "Overdue", pending: "Pending", exception: "Exception", good: "Good", needs_attention: "Needs Attention", not_checked: "Not Checked" }[value] || value);

export default function CrewOperationsMobile({ token, data, loading, initialTarget, onRefresh, onBack }) {
  const [detail, setDetail] = useState(null); const [selected, setSelected] = useState(null); const [reason, setReason] = useState(""); const [note, setNote] = useState(""); const [response, setResponse] = useState({}); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  useEffect(() => { setDetail(null); setSelected(null); }, [token]);
  useEffect(() => { if (!initialTarget) return; if (initialTarget.kind === "legacy_task") setSelected({ ...initialTarget.row, kind: "legacy_task" }); else openTask(initialTarget.row); }, [initialTarget]);
  async function openTask(row) { setSaving(true); setError(""); try { setDetail(await crewService.operationDetail(token, row.id)); } catch (cause) { setError(cause.message); } finally { setSaving(false); } }
  async function refreshDetail() { if (!detail) return; setDetail(await crewService.operationDetail(token, detail.id)); await onRefresh?.(); }
  async function submit(action) { if (!selected) return; setSaving(true); setError(""); try { if (selected.kind === "legacy_task") await crewService.updateDailyTask(token, selected.id, action, reason || null, note || null); else await crewService.updateTaskBlock(token, selected.id, action, response, reason || null, note || null); setSelected(null); setResponse({}); setReason(""); setNote(""); if (detail) await refreshDetail(); else await onRefresh?.(); } catch (cause) { setError(cause.message); } finally { setSaving(false); } }
  async function finish() { setSaving(true); setError(""); try { await crewService.completeOperationChecklist(token, detail.id); await refreshDetail(); } catch (cause) { setError(cause.message); } finally { setSaving(false); } }

  if (detail) return <section className="crew-ops-mobile"><MobileHeader title={detail.name} onBack={() => setDetail(null)} /><div className="crew-ops-detail-head"><span>{String(detail.task_type || "task").replaceAll("_", " ")}</span><strong>{label(detail.status)}</strong><small>{detail.blocks.filter((item) => !["pending", "not_checked"].includes(item.status)).length} of {detail.blocks.filter((item) => !["text", "key_point", "image", "sop_reference"].includes(item.block_type)).length} completed</small></div><div className="crew-ops-items">{detail.blocks.map((block, index) => <TaskBlock key={block.id} block={block} index={index} onOpen={() => { if (["text", "key_point", "image", "sop_reference"].includes(block.block_type)) return; setSelected({ ...block, kind: "block", allow_exception: detail.allow_exception }); setResponse(block.response || {}); setReason(block.exception_reason || ""); setNote(block.note || ""); }} />)}</div>{error ? <div className="crew-v2-error">{error}</div> : null}<div className="crew-ops-sticky"><button className="crew-v2-primary" disabled={saving || ["completed", "completed_with_exceptions"].includes(detail.status)} onClick={finish}>{saving ? "Saving…" : ["completed", "completed_with_exceptions"].includes(detail.status) ? "Task Completed" : "Complete Task"}</button></div>{selected ? <TaskResponseModal item={selected} response={response} setResponse={setResponse} reason={reason} setReason={setReason} note={note} setNote={setNote} saving={saving} onClose={() => setSelected(null)} onSubmit={submit} /> : null}</section>;

  const tasks = data?.tasks || [];
  return <section className="crew-ops-mobile"><MobileHeader title="Today’s Tasks" onBack={onBack} /><div className="crew-ops-context"><span><Store size={17} /><strong>{data?.outlet?.name || "Your outlet"}</strong></span><small>{data?.attendance_context?.on_shift ? "On Shift" : "Tasks remain available for review outside your shift"}</small></div>{loading ? <div className="crew-ops-loading">Loading today’s tasks…</div> : <section className="crew-ops-group"><div className="crew-v2-section-title"><h2>Tasks</h2><span>{tasks.length}</span></div>{tasks.length ? tasks.map((task) => <button key={`${task.source}-${task.id}`} type="button" className={`crew-ops-task is-${task.status}`} onClick={() => task.source === "legacy_daily" ? setSelected({ ...task, kind: "legacy_task" }) : openTask(task)}><span>{task.task_type === "health_check" ? <HeartPulse size={17} /> : task.task_type === "checklist" ? <ClipboardCheck size={17} /> : <ListChecks size={17} />}</span><span><strong>{task.name}</strong><small>{task.block_count ? `${task.completed_count || 0} / ${task.block_count} completed` : task.description || String(task.task_type).replaceAll("_", " ")}</small></span><em>{label(task.status)}<ChevronRight size={16} /></em></button>) : <Empty text="No Tasks apply to you today." />}</section>}{error ? <div className="crew-v2-error">{error}</div> : null}{selected ? <TaskResponseModal item={selected} response={response} setResponse={setResponse} reason={reason} setReason={setReason} note={note} setNote={setNote} saving={saving} onClose={() => setSelected(null)} onSubmit={submit} /> : null}</section>;
}

function TaskBlock({ block, index, onOpen }) { const informational = ["text", "key_point", "image", "sop_reference"].includes(block.block_type); const Component = onOpen ? "button" : "div"; return <Component {...(onOpen ? { type: "button", onClick: onOpen } : {})} className={`crew-ops-item is-${block.status || "pending"}${informational ? " is-information" : ""}`}><span className="crew-ops-item-state">{["completed", "good"].includes(block.status) ? <Check size={18} /> : ["exception", "needs_attention"].includes(block.status) ? <AlertTriangle size={17} /> : index + 1}</span><span><strong>{block.title}{block.required ? " *" : ""}</strong><small>{block.description || String(block.block_type).replaceAll("_", " ")}</small>{block.sop_reference ? <em><FileText size={13} /> {block.sop_reference.title} · v{block.sop_reference.version}</em> : null}</span><span>{!informational && onOpen ? <><b>{label(block.status)}</b><ChevronRight size={16} /></> : null}</span></Component>; }

export function CrewTaskPreview({ task }) {
  const blocks = (task.blocks || []).map((block) => ({
    ...block,
    required: block.required ?? block.is_required,
    status: block.status || "pending",
    sop_reference: block.sop_reference || (block.sop_version_id ? { title: block.sop_title || "Published SOP", version: block.sop_version || "pinned" } : null),
  }));
  const actionable = blocks.filter((item) => !["text", "key_point", "image", "sop_reference"].includes(item.block_type));
  return <section className="crew-ops-mobile crew-task-preview" aria-label="Crew Task preview"><div className="crew-ops-detail-head"><span>{String(task.task_type || "task").replaceAll("_", " ")}</span><strong>Preview</strong><small>0 of {actionable.length} completed</small></div><div className="crew-ops-items">{blocks.map((block, index) => <TaskBlock key={block.id || index} block={block} index={index} />)}</div></section>;
}
function TaskResponseModal({ item, response, setResponse, reason, setReason, note, setNote, saving, onClose, onSubmit }) { const type = item.block_type; return <div className="crew-ops-sheet-backdrop"><section className="crew-ops-sheet"><div><h2>{item.name || item.title}</h2><button onClick={onClose}>×</button></div><p>{item.description || "Complete this Task, or record an exception when permitted."}</p>{type === "health_rating" ? <><button className="crew-ops-choice is-good" onClick={() => onSubmit("good")}><Check size={18} /> Good</button><button className="crew-ops-choice is-warning" onClick={() => setReason("needs_attention")}><AlertTriangle size={18} /> Needs Attention</button><button className="crew-ops-choice" onClick={() => onSubmit("not_checked")}>Not Checked</button></> : type === "yes_no" ? <div className="grid grid-cols-2 gap-2"><button className={`crew-ops-choice${response.value === "yes" ? " is-good" : ""}`} onClick={() => setResponse({ value: "yes" })}>Yes</button><button className={`crew-ops-choice${response.value === "no" ? " is-warning" : ""}`} onClick={() => setResponse({ value: "no" })}>No</button></div> : type === "single_choice" ? <label>Choose one<select value={response.value || ""} onChange={(event) => setResponse({ value: event.target.value })}><option value="">Select</option>{(item.config?.options || []).map((option) => <option key={option}>{option}</option>)}</select></label> : ["number", "temperature"].includes(type) ? <label>{type === "temperature" ? "Temperature" : "Measurement"}<input type="number" value={response.value ?? ""} onChange={(event) => setResponse({ value: event.target.value })} /></label> : type === "short_text" ? <label>Response<textarea value={response.value || ""} onChange={(event) => setResponse({ value: event.target.value })} /></label> : null}{reason === "needs_attention" ? <label>What needs attention?<textarea value={note} onChange={(event) => setNote(event.target.value)} /></label> : null}{type !== "health_rating" ? <button className="crew-v2-primary" disabled={saving || (["yes_no", "single_choice", "number", "temperature", "short_text"].includes(type) && !String(response.value ?? "").trim())} onClick={() => onSubmit("completed")}>Complete</button> : null}{item.allow_exception || item.kind === "legacy_task" ? <><button className="crew-ops-choice is-warning" onClick={() => setReason(reason || "equipment_issue")}><AlertTriangle size={18} /> Record Exception</button>{reason && reason !== "needs_attention" ? <><label>Reason<select value={reason} onChange={(event) => setReason(event.target.value)}>{REASONS.map(([value, text]) => <option key={value} value={value}>{text}</option>)}</select></label><label>Note<textarea value={note} onChange={(event) => setNote(event.target.value)} /></label><button className="crew-v2-primary" disabled={saving} onClick={() => onSubmit("exception")}>Submit Exception</button></> : null}</> : null}</section></div>; }
function MobileHeader({ title, onBack }) { return <header className="crew-v2-page-header"><div><button type="button" onClick={onBack} aria-label="Back"><ArrowLeft size={19} /></button><h1>{title}</h1></div></header>; }
function Empty({ text }) { return <div className="crew-ops-empty"><ClipboardCheck size={22} /><p>{text}</p></div>; }
