import { beforeEach, describe, expect, it, vi } from "vitest";
const mocks=vi.hoisted(()=>({rpc:vi.fn(),audit:vi.fn(),from:vi.fn()}));
vi.mock("../../lib/supabase",()=>({supabase:{rpc:mocks.rpc,from:mocks.from}}));
vi.mock("../auditLogService.js",()=>({auditLogService:{createAuditLog:mocks.audit}}));
import { roleService } from "../roleService.js";
const role={id:"00000000-0000-4000-8000-000000000001",name:"Operations Lead",description:"Current",is_active:true,outletAccess:"selected",permissions:["dashboard.view"],selectedOutletIds:["00000000-0000-4000-8000-000000000101"]};
const result={role:{id:role.id,name:"operations_lead",description:"Current",is_active:true,is_system_role:false,outlet_access_type:"selected"},permissions:["dashboard.view"],outlet_ids:role.selectedOutletIds};
beforeEach(()=>{mocks.rpc.mockReset().mockResolvedValue({data:result,error:null});mocks.audit.mockReset().mockResolvedValue();mocks.from.mockReset();});
describe("Role trusted configuration service contracts",()=>{
 it("maps one complete update snapshot to the trusted RPC without browser relation DML",async()=>{await roleService.saveRole({...role,requestId:"00000000-0000-4000-8000-000000000010"});expect(mocks.rpc).toHaveBeenCalledWith("save_role_configuration",{p_request_id:"00000000-0000-4000-8000-000000000010",p_role:{id:role.id,name:"operations_lead",description:"Current",is_active:true,outlet_access_type:"selected"},p_permission_codes:["dashboard.view"],p_outlet_ids:role.selectedOutletIds});expect(mocks.audit).toHaveBeenCalledTimes(1);});
 it("maps create to the same authority and preserves a supplied retry request ID",async()=>{const create={...role,id:undefined,requestId:"00000000-0000-4000-8000-000000000011"};await roleService.saveRole(create);await roleService.saveRole(create);expect(mocks.rpc.mock.calls.map(([,p])=>p.p_request_id)).toEqual([create.requestId,create.requestId]);});
 it("saves a Factory-only role with no Restaurant Outlet Access",async()=>{const factoryRole={...role,permissions:["factory_dashboard.view"],outletAccess:"all",selectedOutletIds:["00000000-0000-4000-8000-000000000101"]};const saved=await roleService.saveRole(factoryRole);expect(mocks.rpc).toHaveBeenCalledWith("save_role_configuration",expect.objectContaining({p_role:expect.objectContaining({outlet_access_type:"none"}),p_permission_codes:["factory_dashboard.view"],p_outlet_ids:[]}));expect(saved.outletScopeApplicable).toBe(false);expect(saved.outletAccess).toBe("none");});
 it("surfaces trusted rejection with no audit success",async()=>{mocks.rpc.mockResolvedValueOnce({data:null,error:new Error("rejected")});await expect(roleService.saveRole(role)).rejects.toThrow("rejected");expect(mocks.audit).not.toHaveBeenCalled();});
 it("reads assigned employees only through the canonical employee role relation",async()=>{const order=vi.fn().mockResolvedValue({data:[{id:"employee-1",full_name:"Ari Chen",nickname:"Ari",employee_code:"EMP-001",position:"Supervisor",workplace:"Factory",enable_system_login:true,access_state:"invited",employment_status:"active",employment_type:"full_time"}],error:null});const eq=vi.fn(()=>({order}));const select=vi.fn(()=>({eq}));mocks.from.mockReturnValue({select});await expect(roleService.listAssignedEmployees(role.id)).resolves.toEqual([{id:"employee-1",fullName:"Ari Chen",preferredName:"Ari",employeeCode:"EMP-001",position:"Supervisor",workplace:"Factory",accountState:"invited",employmentStatus:"active",employmentType:"full_time"}]);expect(mocks.from).toHaveBeenCalledWith("employees");expect(select).toHaveBeenCalledWith("id,full_name,nickname,employee_code,position,workplace,enable_system_login,access_state,employment_status,employment_type");expect(eq).toHaveBeenCalledWith("role_id",role.id);expect(order).toHaveBeenCalledWith("full_name",{ascending:true});});
 it("does not substitute a noncanonical role identifier with another employee set",async()=>{await expect(roleService.listAssignedEmployees("role-1")).resolves.toEqual([]);expect(mocks.from).not.toHaveBeenCalled();});
});
