import { FinanceReadiness } from './FinanceVisualSystem.jsx';
import { metricRegistry } from './metrics.js';
import { costRatio } from './costs.js';
import { financialValue, movementValue } from './presentation.js';

// Scales below are display geometry only. Amounts, shares and movements come from canonical projections.
export function ProfitArchitecture({ dataset, selectedId, onSelect }) {
  const ids = ['revenue', 'cogs', 'gross_profit', 'labour', 'opex', 'ebitda'];
  const missing = ids.every(id => dataset.metrics[id].value === null);
  return <div className="finance-architecture"><ol>{ids.map(id => {
    const metric = dataset.metrics[id];
    const share = id === 'revenue' ? null : costRatio(dataset, id);
    const width = metric.value === null ? null : id === 'revenue' ? 100 : share?.value === null ? null : Math.min(100, Math.abs(share.value));
    return <li key={id}><button type="button" aria-label={`Explore ${metricRegistry[id].label} flow`} aria-pressed={selectedId === id} onClick={() => onSelect(id)} className={`${['cogs', 'labour', 'opex'].includes(id) ? 'is-cost' : 'is-retained'} ${metric.value === null ? 'is-pending' : ''} ${metric.value < 0 ? 'is-negative' : ''}`}><span className="finance-architecture-label">{metricRegistry[id].label}<strong>{financialValue(metric)}</strong></span><span className="finance-architecture-track" aria-hidden="true">{width !== null ? <i style={{width:`${width}%`}} /> : null}</span><span className="finance-architecture-share">{id === 'revenue' && metric.value !== null ? 'Revenue base' : share?.value !== null && share?.value !== undefined ? financialValue(share) : '—'}</span></button></li>;
  })}</ol>{missing ? <FinanceReadiness title="Profit Architecture evidence not ready">Revenue and supplied cost evidence are required. Muted layers describe the financial structure only.</FinanceReadiness> : null}</div>;
}
export function DriverContribution({ movement, selectedId, onSelect }) {
  const bound = Math.max(1, ...movement.rows.map(row => Math.abs(row.contribution ?? 0)));
  return <div className="finance-contribution" aria-label="Driver Contribution"><div className="finance-contribution-inputs">{movement.rows.map(row => <button type="button" key={row.id} aria-label={`Explore ${metricRegistry[row.id].label} driver`} aria-pressed={selectedId === row.id} onClick={() => onSelect(row.id)} className={row.contribution === null ? 'is-pending' : row.contribution < 0 ? 'is-pressure' : 'is-support'}><span className="finance-contribution-bar" aria-hidden="true">{row.contribution !== null ? <i style={{height:`${Math.max(3,Math.abs(row.contribution)/bound*100)}%`}} /> : null}</span><strong>{row.contribution === null ? '—' : movementValue({value:row.contribution})}</strong><span>{metricRegistry[row.id].label}</span><small>{!row.included ? 'Outside this basis' : row.contribution === null ? '' : row.contribution < 0 ? 'Reduces EBITDA' : 'Supports EBITDA'}</small></button>)}</div><button type="button" className="finance-contribution-result" aria-pressed={selectedId === 'ebitda'} onClick={() => onSelect('ebitda')}><span>EBITDA movement</span><strong>{movement.total.value === null ? '—' : movementValue(movement.total)}</strong></button></div>;
}
export function MarginPressureMap({ rows, selectedId, onSelect }) {
  const ready = rows.filter(row => row.growth.value !== null && row.revenueGrowth.value !== null && row.ratioMovement.value !== null);
  const xb = Math.max(.01,...ready.map(row=>Math.abs(row.growth.value-row.revenueGrowth.value)))*1.15;
  const yb = Math.max(.01,...ready.map(row=>Math.abs(row.ratioMovement.value)))*1.15;
  const x=row=>300+(row.growth.value-row.revenueGrowth.value)/xb*230;
  const y=row=>190-row.ratioMovement.value/yb*145;
  return <section className="finance-margin-map" aria-labelledby="finance-margin-map-title"><div className="finance-analysis-heading"><div><h2 id="finance-margin-map-title">Margin Pressure Map</h2><p>Cost growth relative to Revenue meets cost-share pressure on margin.</p></div></div><svg viewBox="0 0 620 410" role="group" aria-label="Cost growth relative to Revenue and margin impact"><rect x="70" y="45" width="460" height="290" className="finance-map-base"/><rect x="300" y="45" width="230" height="145" className="finance-map-pressure"/><rect x="70" y="190" width="230" height="145" className="finance-map-support"/><path d="M300 45V335M70 190H530" className="finance-field-axis"/><text x="78" y="32">Share rises</text><text x="525" y="32" textAnchor="end">Margin pressure</text><text x="78" y="356">Slower than Revenue</text><text x="525" y="356" textAnchor="end">Faster than Revenue</text><text x="300" y="356" textAnchor="middle">0</text><text x="300" y="390" textAnchor="middle">Cost growth relative to Revenue · pp</text><text x="20" y="190" textAnchor="middle" transform="rotate(-90 20 190)">Margin impact · cost share change (pp)</text><text x="58" y="52" textAnchor="end">{ready.length ? `+${yb.toFixed(yb < .1 ? 2 : 1)}` : '—'}</text><text x="58" y="195" textAnchor="end">0</text><text x="58" y="335" textAnchor="end">{ready.length ? `−${yb.toFixed(yb < .1 ? 2 : 1)}` : '—'}</text>{ready.map((row,index)=><g key={row.id} role="button" tabIndex="0" aria-label={`Investigate ${row.label ?? metricRegistry[row.id].label} pressure`} aria-pressed={row.id===selectedId} onClick={()=>onSelect(row.id)} onKeyDown={event=>{if(['Enter',' '].includes(event.key)){event.preventDefault();onSelect(row.id);}}} className={`finance-pressure-point ${row.direction === 'pressure' ? 'is-pressure' : row.direction === 'stable' ? 'is-stable' : 'is-support'} ${row.id===selectedId ? 'is-selected' : ''}`}><title>{row.label ?? metricRegistry[row.id].label}: cost growth {row.growth.value.toFixed(1)}%; Revenue growth {row.revenueGrowth.value.toFixed(1)}%; cost share {movementValue(row.ratioMovement,'percent')}</title><circle cx={x(row)} cy={y(row)} r="22" fill="transparent"/><circle cx={x(row)} cy={y(row)} r="6"/>{(row.id===selectedId || !ready.some(other=>other.id!==row.id && Math.hypot(x(other)-x(row),y(other)-y(row))<34)) ? <text x={x(row)+(x(row)>440?-12:12)} y={y(row)+(index%2?16:-8)} textAnchor={x(row)>440?'end':'start'}>{row.label ?? metricRegistry[row.id].label}</text> : null}</g>)}</svg>{!ready.length ? <FinanceReadiness title="Margin pressure evidence not ready">Comparable costs and positive Revenue are required. No cost items have been positioned.</FinanceReadiness> : <p className="finance-analysis-muted">Zero compares growth and share, not a target. Higher cost share presses margin; points describe arithmetic relationships, not business causes. Coincident points retain their coordinates; every item remains selectable in Cost Movements.</p>}</section>;
}
