import { FinanceReadiness, FinanceDisclosure, FinanceMissing } from './FinanceVisualSystem.jsx';
import { useState } from 'react';
import { ArrowRight } from 'lucide-react';
import { navigateAdminRoute } from '../../app/routeOwnership.js';
import FinanceComparisonWorkspace from './FinanceComparisonWorkspace.jsx';
import AnalysisContext from './AnalysisContext.jsx';
import LiquidityTimeline from './LiquidityTimeline.jsx';
import { cashDiagnosticIds, cashMovements, cashPair, cashPositionIds, liquidityTimeline } from './cash.js';
import { metricMovement, metricRegistry } from './metrics.js';
import { financialPeriod, financialSemantics, financialValue, movementValue } from './presentation.js';
import './cash.css';

const cycle = [['inventory', 'ar', 'cash'], ['ap', 'cash']];
const dayMetric = { inventory: 'inventory_days', ar: 'ar_days', ap: 'ap_days', cash: 'cash_coverage' };
const related = { cash: ['ar', 'ap', 'cash_coverage'], ar: ['ar_days', 'average_ar', 'credit_sales'], inventory: ['inventory_days', 'average_inventory', 'cogs'], ap: ['ap_days', 'average_ap', 'credit_purchases'], debt: ['financing_cash_flow'], working_capital: ['ar', 'inventory', 'ap', 'current_assets', 'current_liabilities'] };
const gaps = { cash: 'Book cash does not establish bank availability. Only validated dated events can explain expected inflows and outflows.', ar: 'Aggregate receivables do not establish customer risk, collection dates or aging. Those details require validated customer and settlement evidence.', ap: 'Aggregate payables do not establish supplier aging or overdue commitments. Only supplied dated payment evidence can explain the timeline.', inventory: 'Accounting valuation is required. Operational stock quantities and purchase-based COGS do not establish accounting inventory or cash released.', working_capital: 'Current Assets less Current Liabilities is a broader balance than Cash, AR, Inventory and AP. Components are investigation paths, not a complete bridge or attributed causes.', debt: 'Outstanding debt is a position. Financing cash movement and dated repayments require separate authoritative evidence.' };
function eventPair(pair, event) {
  const eventPeriod = { start: event.date, end: event.date };
  const metric = { ...pair.current.metrics.cash, period: eventPeriod, id: 'cash_event', value: event.amount, completeness: event.completeness, provenance: event.provenance, reason: event.reason };
  return { current: { ...pair.current, period: eventPeriod, metrics: { ...pair.current.metrics, cash_event: metric } }, previous: { ...pair.previous, metrics: { ...pair.previous.metrics, cash_event: { ...metric, period: pair.previous.period, value: null, completeness: 'unavailable', provenance: [], reason: 'No matched historical event comparison supplied.' } } } };
}
export function FinanceCash({ analysis }) {
  const pair = cashPair(analysis), timeline = liquidityTimeline(pair.current);
  const [selectedId, setSelectedId] = useState('cash'), [event, setEvent] = useState(null), [action, setAction] = useState('Explain');
  const select = (id) => { setSelectedId(id); setEvent(null); };
  const selectedPair = event ? eventPair(pair, event) : pair;
  const metricId = event ? 'cash_event' : selectedId;
  const definition = event ? { label: event.label, definition: `Expected ${event.direction} on ${event.date}. Forecast event from the supplied schedule; not recognized expense or historical cash.`, dependencies: [] } : metricRegistry[selectedId];
  const current = selectedPair.current.metrics[metricId], movement = event ? null : metricMovement(current, selectedPair.previous.metrics[metricId]);
  const explanation = <><p><strong>{financialValue(current)}</strong> · {event ? `Expected ${event.direction} on ${event.date} · Forecast` : `${financialSemantics(current)} · ${financialPeriod(pair.current.period)}`}. {movement ? `Movement: ${movementValue(movement, current.unit)}${movement.reason ? ` · ${movement.reason}` : ''}` : ''}</p><p>{current.reason || definition.definition}</p><p>{event ? timeline.reason : gaps[selectedId] || definition.definition}</p><p className="finance-analysis-muted">Next investigation: {event ? 'review the event source and schedule coverage below, then examine the related balance.' : current.value === null ? 'review Data Sources for balances, accounting valuation and dated commitment coverage.' : 'compare this measure, then select related evidence in Break down. A balance movement alone does not establish cash generation or its causes.'}</p></>;
  const linked = event ? [event.kind === 'receivable' ? 'ar' : event.kind === 'supplier' ? 'ap' : event.kind === 'debt' ? 'debt' : 'cash'] : related[selectedId] ?? definition.dependencies;
  const relevantEvents = timeline.rows.flatMap((row) => row.events).filter((entry) => selectedId === 'cash' || (selectedId === 'ar' && entry.kind === 'receivable') || (selectedId === 'ap' && entry.kind === 'supplier') || (selectedId === 'debt' && entry.kind === 'debt'));
  const breakdown = <><p>{event ? 'The validated schedule supplies this dated amount. Transaction lines and matched historical events are unavailable.' : gaps[selectedId] || 'These supplied inputs support the selected diagnostic. Missing or incompatible inputs remain unavailable.'}</p><div className="finance-analysis-inputs">{linked.map((id) => <button type="button" className="btn-secondary" key={id} onClick={() => select(id)}>{metricRegistry[id].label}<span>{financialValue(pair.current.metrics[id])}</span></button>)}</div>{!event && relevantEvents.length ? <ul className="finance-cash-related-events">{relevantEvents.map((entry) => <li key={entry.id}><button type="button" onClick={() => setEvent(entry)}>{entry.date} · {entry.label} <ArrowRight size={14} /></button></li>)}</ul> : null}{!event && !relevantEvents.length ? <p className="finance-analysis-muted">No validated finer source detail or relevant dated events are supplied. No customer, supplier or inventory causes are inferred.</p> : null}</>;
  return <div className="finance-analysis-body finance-cash-body">
    {pair.current.demo ? <p className="finance-demo" role="status">Development demo · All balances, cash movements and dated events are illustrative. No business records are used.</p> : null}
    <div className="finance-analysis-heading"><div><p className="finance-analysis-muted">Closing position · {pair.current.period.end}</p><h2>Cash & capital position</h2><p>Understand available balances, then trace the evidence behind cash conversion.</p></div><span className="finance-cash-basis">Compared with {financialPeriod(pair.previous.period)}</span></div>
    {cashPositionIds.every((id) => pair.current.metrics[id].value === null) ? <><div className="finance-position-skeleton" aria-label="Current financial position"><div>Cash<strong>—</strong></div><div>Working Capital<strong>—</strong></div><span>AR · Inventory · AP · Debt</span></div><FinanceReadiness title="Cash position not ready">Authoritative cash, receivable, payable, inventory and debt balances are required. Operational profit does not establish cash availability.</FinanceReadiness></> : <>    <dl className="finance-performance-strip finance-cash-position" aria-label="Current financial position">{['cash', 'working_capital', 'ar', 'inventory', 'ap', 'debt'].filter((id) => pair.current.metrics[id].value !== null).map((id) => <div key={id} className={["cash","working_capital"].includes(id) ? "is-primary" : ""}><dt><button type="button" aria-pressed={!event && selectedId === id} onClick={() => select(id)}>{metricRegistry[id].label}</button></dt><dd><strong>{financialValue(pair.current.metrics[id])}</strong><span>{movementValue(metricMovement(pair.current.metrics[id], pair.previous.metrics[id]))} movement</span><small>{financialSemantics(pair.current.metrics[id])} · {pair.current.metrics[id].completeness}</small></dd></div>)}</dl>
<FinanceMissing ids={cashPositionIds} metrics={pair.current.metrics} registry={metricRegistry} /></>}
    <FinanceDisclosure label="Liquidity diagnostics">    <dl className="finance-cash-diagnostics" aria-label="Liquidity diagnostics">{cashDiagnosticIds.filter((id) => pair.current.metrics[id].value !== null).map((id) => <div key={id}><dt><button type="button" aria-pressed={!event && selectedId === id} onClick={() => select(id)}>{metricRegistry[id].label}</button></dt><dd>{financialValue(pair.current.metrics[id])}<small>{financialSemantics(pair.current.metrics[id])} · {pair.current.metrics[id].completeness}</small></dd></div>)}</dl>
<FinanceMissing ids={cashDiagnosticIds} metrics={pair.current.metrics} registry={metricRegistry} /></FinanceDisclosure>
    <FinanceDisclosure label="Cash source & readiness"><p>{pair.current.sourceLabel}. Account balances: {pair.current.capabilities.account_balances}. Inventory valuation: {pair.current.capabilities.inventory_valuation}. Dated schedule: {timeline.schedule?.completeness ?? 'unavailable'}. Historical accounting inputs are required for derived conversion days and coverage. Cash Coverage uses historical operating payments and is not future runway.</p><p>Book cash is not live bank availability. AR/AP balances are not aging; operational inventory is not accounting valuation. Read time does not establish source freshness.</p><button type="button" className="btn-secondary" onClick={() => navigateAdminRoute('finance_data_sources')}>Review Data Sources <ArrowRight size={14} /></button></FinanceDisclosure>
    <div className="finance-cash-investigation"><LiquidityTimeline model={timeline} selectedEventId={event?.id} onEvent={setEvent} onCash={() => select('cash')} />
    <section className="finance-cash-section" aria-labelledby="finance-cycle-title"><div className="finance-analysis-heading"><div><h2 id="finance-cycle-title">Working Capital Flow</h2><p>Select a stage to examine its balance, conversion evidence and movement.</p></div><button type="button" className="finance-cash-wc" onClick={() => select('working_capital')}>Working Capital {pair.current.metrics.working_capital.value !== null ? <><strong>{financialValue(pair.current.metrics.working_capital)}</strong><span>{movementValue(metricMovement(pair.current.metrics.working_capital, pair.previous.metrics.working_capital))} movement</span></> : <span>Explore required evidence</span>}</button></div>
      <div className="finance-working-flow">      {cycle.map((ids, index) => <ol className="finance-capital-cycle" key={index} aria-label={index === 0 ? 'Inventory to cash cycle' : 'Supplier to cash out cycle'}>{ids.map((id) => <li key={id}><button type="button" aria-label={`Explore ${index === 1 && id === 'cash' ? 'Cash Out' : metricRegistry[id].label} stage`} aria-pressed={!event && selectedId === id} onClick={() => select(id)}><span>{index === 1 && id === 'cash' ? 'Cash Out' : id === 'ar' ? 'Receivables' : id === 'ap' ? 'Supplier / Payable' : metricRegistry[id].label}</span><strong>{index === 1 && id === 'cash' ? 'Dated payment evidence' : financialValue(pair.current.metrics[id])}</strong><small>{index === 1 && id === 'cash' ? `${timeline.schedule?.completeness ?? 'Unavailable'} schedule` : `${metricRegistry[dayMetric[id]].label} · ${financialValue(pair.current.metrics[dayMetric[id]])}`}</small></button></li>)}</ol>)}<p className="finance-analysis-muted">Days are historical conversion measures, not invoice aging. Stage balances do not exhaust Working Capital or establish a cash-conversion bridge.</p></div>{['inventory','ar','cash','ap'].every(id=>pair.current.metrics[id].value===null) ? <FinanceReadiness title="Capital conversion evidence not ready">Accounting inventory, receivables, payables and historical conversion evidence are required. Muted stages are relationships, not a cash bridge.</FinanceReadiness> : null}</section></div>
    <FinanceDisclosure label="Explore cash evidence" open={Boolean(event) || selectedId !== 'cash' || cashPositionIds.some((id) => pair.current.metrics[id].value !== null)}>    <section className="finance-cash-exploration" aria-label="Cash driver exploration"><nav aria-label="Cash drill path"><button type="button" onClick={() => select('cash')}>Cash</button><span aria-hidden="true">/</span><span aria-current="page">{definition.label}</span></nav><AnalysisContext pair={selectedPair} metricId={metricId} definition={definition} action={action} onAction={setAction} onMetric={select} explanation={explanation} breakdown={breakdown} comparison={event ? <p>No matched historical comparison is supplied for this expected event. The comparison period does not establish a previous commitment or a zero amount.</p> : undefined} /></section>
</FinanceDisclosure>
    <section className="finance-cash-section" aria-labelledby="finance-cash-movement-title"><div className="finance-analysis-heading"><div><h2 id="finance-cash-movement-title">Profit, cash & period movement</h2><p>Separate profit performance, closing balance change and supplied cash flows.</p></div></div><FinanceDisclosure label="Compare supplied profit, balances & cash flows"><div className="finance-analysis-table-wrap"><table className="finance-analysis-table"><caption>{financialPeriod(pair.previous.period)} → {financialPeriod(pair.current.period)} · same selected scope</caption><thead><tr><th>Measure</th><th>Comparison</th><th>Current</th><th>Movement</th><th>Evidence</th></tr></thead><tbody>{cashMovements(pair).map((row) => <tr key={row.id}><th scope="row"><button type="button" onClick={() => select(row.id)}>{metricRegistry[row.id].label}<small>{row.isFlow ? 'Period flow' : 'Closing balance'}</small></button></th><td>{financialValue(row.previous)}</td><td>{financialValue(row.current)}</td><td>{movementValue(row.movement)}</td><td>{financialSemantics(row.current)} · {row.current.completeness}</td></tr>)}</tbody></table></div></FinanceDisclosure><p className="finance-analysis-muted">EBITDA is not cash generation. Closing cash changes are not an operating cash-flow reconciliation. Working Capital movements cannot be attributed to AR, Inventory or AP without a complete validated bridge. Financing and investing movements remain separate supplied evidence.</p></section>
  </div>;
}
export default function FinanceCashPage(props) { return <FinanceComparisonWorkspace {...props} title="Cash" description="Understand liquidity, trace working capital, and investigate dated cash pressure.">{(analysis) => <FinanceCash analysis={analysis} />}</FinanceComparisonWorkspace>; }
