import { financialValue } from './presentation.js';

const eventMetric = (event) => ({ value: event.amount, unit: 'money' });
export default function LiquidityTimeline({ model, selectedEventId, onEvent, onCash }) {
  const { cash, schedule, rows, lowest, constrained, largestCollection, largestCommitment } = model;
  return <section className="finance-cash-section finance-liquidity" aria-labelledby="finance-liquidity-title">
    <div className="finance-analysis-heading"><div><h2 id="finance-liquidity-title">Liquidity timeline</h2><p>{schedule ? `${schedule.horizon.start} to ${schedule.horizon.end} · ${schedule.completeness} schedule coverage` : 'Opening position → dated collections & commitments → expected cash'}</p></div><span className="finance-cash-basis">{model.projected ? 'Forecast · end-of-day checkpoints' : 'Expected positions unavailable'}</span></div>
    <p className="finance-analysis-muted">{model.reason}</p>
    <div className="finance-liquidity-opening"><button type="button" onClick={onCash}>Opening book cash <strong>{financialValue(cash)}</strong></button><span>As at {cash.period.end} · {cash.completeness}</span></div>
    {rows.length ? <ol className="finance-liquidity-dates" aria-label="Dated liquidity checkpoints">{rows.map((row) => <li key={row.date}><time dateTime={row.date}>{row.date}</time><div className="finance-liquidity-events">{row.events.map((event) => <button type="button" key={event.id} aria-pressed={selectedEventId === event.id} aria-label={`Investigate ${event.label}`} onClick={() => onEvent(event)}><span>{event.label}<small>{event.kind} · Forecast · {event.completeness}</small></span><strong>{event.direction === 'inflow' ? '+' : '−'}{financialValue(eventMetric(event))}<small>{event.direction === 'inflow' ? 'Expected in' : 'Expected out'}</small></strong></button>)}</div><div className="finance-liquidity-position"><span>Expected book cash</span><strong>{financialValue(row.position)}</strong><small>{row.position ? 'Forecast' : 'Incomplete coverage / opening evidence'}</small></div></li>)}</ol> : <ol className="finance-liquidity-empty" aria-label="Liquidity evidence required"><li><strong>Dated collections</strong><span>{schedule?.completeness === 'complete' ? 'No inflows in the supplied complete horizon.' : 'Unavailable · receivable balances do not establish collection dates.'}</span></li><li><strong>Dated commitments</strong><span>{schedule?.completeness === 'complete' ? 'No outflows in the supplied complete horizon.' : 'Unavailable · supplier, payroll, rent, tax and debt payment evidence is required.'}</span></li><li><strong>Expected position</strong><span>{model.projected ? 'Book cash remains at the opening position under the supplied schedule.' : 'Unavailable · no complete projection or lowest point can be established.'}</span></li></ol>}
    <dl className="finance-liquidity-summary"><div><dt>Expected lowest point</dt><dd>{lowest ? <><strong>{financialValue(lowest.position)}</strong><span>{lowest.date} · supplied-schedule model</span></> : 'Unavailable'}</dd></div><div><dt>Largest known collection</dt><dd>{largestCollection ? <button type="button" onClick={() => onEvent(largestCollection)}>{financialValue(eventMetric(largestCollection))}<span>{largestCollection.date} · Forecast · {largestCollection.completeness} · {largestCollection.label}</span></button> : 'Unavailable / no supplied events'}</dd></div><div><dt>Largest known commitment</dt><dd>{largestCommitment ? <button type="button" onClick={() => onEvent(largestCommitment)}>{financialValue(eventMetric(largestCommitment))}<span>{largestCommitment.date} · Forecast · {largestCommitment.completeness} · {largestCommitment.label}</span></button> : 'Unavailable / no supplied events'}</dd></div></dl>
    {model.projected ? <p className="finance-analysis-muted">{constrained.length ? `At or below zero at checkpoints: ${constrained.map((period) => `${period.start} until ${period.end}`).join('; ')}. Between-checkpoint changes and intraday availability are unknown.` : 'No at-or-below-zero checkpoint in the supplied horizon. This does not establish available bank funds or cover unrecorded events.'}</p> : null}
  </section>;
}
