import { FinanceReadiness, FinanceDisclosure } from './FinanceVisualSystem.jsx';
import { financialValue } from './presentation.js';

const eventMetric = (event) => ({ value: event.amount, unit: 'money' });
export default function LiquidityTimeline({ model, selectedEventId, onEvent, onCash }) {
  const { cash, schedule, rows, lowest, constrained, largestCollection, largestCommitment } = model;
  // Coordinate projection of validated checkpoints; no additional financial forecast is calculated here.
  const points = model.projected ? [{date:schedule.asOf, position:cash}, ...rows, ...(rows.at(-1)?.date !== schedule.horizon.end ? [{date:schedule.horizon.end,position:rows.at(-1)?.position ?? cash}] : [])] : [];
  const values = points.map(point=>point.position.value), low = Math.min(0,...values), high = Math.max(1,...values);
  const start = schedule ? Date.parse(schedule.asOf) : 0, end = schedule ? Date.parse(schedule.horizon.end) : 1;
  const x = date => 65+(Date.parse(date)-start)/(end-start)*710;
  const y = value => 245-(value-low)/(high-low)*185;
  const path = points.map((point,index)=>`${index ? 'H'+x(point.date)+'V' : 'M'+x(point.date)+','}${y(point.position.value)}`).join(' ');
  return <section className="finance-cash-section finance-liquidity" aria-labelledby="finance-liquidity-title">
    <div className="finance-analysis-heading"><div><h2 id="finance-liquidity-title">Liquidity timeline</h2><p>{schedule ? `${schedule.horizon.start} to ${schedule.horizon.end} · ${schedule.completeness} schedule coverage` : 'Opening position → dated collections & commitments → expected cash'}</p></div><span className="finance-cash-basis">{model.projected ? 'Forecast · end-of-day checkpoints' : 'Expected positions unavailable'}</span></div>
    <div className="finance-timeline-canvas"><svg viewBox="0 0 840 320" role="group" aria-label="Horizontal Liquidity Timeline"><path d="M65 60V245H775" className="finance-field-axis"/><path d="M65 150H775" className="finance-timeline-guide"/>{model.projected ? <><text x="55" y="66" textAnchor="end">{financialValue({value:high,unit:'money'})}</text><text x="55" y="249" textAnchor="end">{financialValue({value:low,unit:'money'})}</text><path d={path} className="finance-timeline-path"/>{points.map(point=><g key={point.date}><circle cx={x(point.date)} cy={y(point.position.value)} r="4" className="finance-timeline-dot"/><text x={x(point.date)} y="270" textAnchor="middle">{point.date.slice(5)}</text></g>)}<text x="775" y="305" textAnchor="end">Closing expected book cash · {financialValue(points.at(-1).position)}</text></> : <><text x="65" y="270">Opening cash</text><text x="420" y="270" textAnchor="middle">Collections &amp; commitments</text><text x="775" y="270" textAnchor="end">Expected cash</text></>}{rows.flatMap(row=>row.events).map((event,index)=><g key={event.id} role="button" tabIndex="0" aria-label={`Select ${event.label} on timeline`} aria-pressed={selectedEventId===event.id} onClick={()=>onEvent(event)} onKeyDown={e=>{if(['Enter',' '].includes(e.key)){e.preventDefault();onEvent(event);}}} className={`finance-timeline-event ${event.direction==='inflow'?'is-inflow':'is-outflow'}`}><title>{event.date} · {event.label} · {financialValue(eventMetric(event))} · Forecast</title><circle cx={x(event.date)} cy={model.projected ? y(rows.find(row=>row.date===event.date).position.value) : 150} r="20" fill="transparent"/><circle cx={x(event.date)} cy={model.projected ? y(rows.find(row=>row.date===event.date).position.value) : 150} r="6"/><text x={x(event.date)} y={model.projected ? Math.max(24,y(rows.find(row=>row.date===event.date).position.value)-18-(index%2)*20) : 110-(index%2)*25} textAnchor="middle">{event.kind}</text></g>)}</svg></div>
    {model.projected ? <dl className="finance-timeline-readout"><div><dt>Expected lowest point</dt><dd>{financialValue(lowest.position)}<small>{lowest.date} · Forecast</small></dd></div><div><dt>Closing expected cash</dt><dd>{financialValue(points.at(-1).position)}<small>{schedule.horizon.end} · Forecast</small></dd></div></dl> : null}
    <div className="finance-timeline-selectors" aria-label="Select dated cash evidence">{rows.flatMap(row=>row.events).map(event=><button type="button" key={event.id} aria-pressed={selectedEventId===event.id} onClick={()=>onEvent(event)}><span>{event.date.slice(5)} · {event.kind}</span><strong>{event.direction==='inflow'?'+':'−'}{financialValue(eventMetric(event))}</strong></button>)}</div>
    {!rows.length && !model.projected ? <FinanceReadiness title="Dated liquidity evidence not ready">Opening book cash and validated collection / payment dates are required. The muted timeline does not imply a cash projection.</FinanceReadiness> : null}
    <FinanceDisclosure label="Dated checkpoints & schedule evidence">
    <p className="finance-analysis-muted">{model.reason}</p>
    <div className="finance-liquidity-opening"><button type="button" onClick={onCash}>Opening book cash <strong>{financialValue(cash)}</strong></button><span>As at {cash.period.end} · {cash.completeness}</span></div>
    {rows.length ? <ol className="finance-liquidity-dates" aria-label="Dated liquidity checkpoints">{rows.map((row) => <li key={row.date}><time dateTime={row.date}>{row.date}</time><div className="finance-liquidity-events">{row.events.map((event) => <button type="button" key={event.id} aria-pressed={selectedEventId === event.id} aria-label={`Investigate ${event.label}`} onClick={() => onEvent(event)}><span>{event.label}<small>{event.kind} · Forecast · {event.completeness}</small></span><strong>{event.direction === 'inflow' ? '+' : '−'}{financialValue(eventMetric(event))}<small>{event.direction === 'inflow' ? 'Expected in' : 'Expected out'}</small></strong></button>)}</div><div className="finance-liquidity-position"><span>Expected book cash</span><strong>{financialValue(row.position)}</strong><small>{row.position ? 'Forecast' : 'Incomplete coverage / opening evidence'}</small></div></li>)}</ol> : model.projected ? <p>No dated events in the supplied complete horizon. Expected book cash remains at the opening position.</p> : null}
    <dl className="finance-liquidity-summary"><div><dt>Lowest checkpoint evidence</dt><dd>{lowest ? <><strong>{financialValue(lowest.position)}</strong><span>{lowest.date} · supplied-schedule model</span></> : 'Unavailable'}</dd></div><div><dt>Largest known collection</dt><dd>{largestCollection ? <button type="button" onClick={() => onEvent(largestCollection)}>{financialValue(eventMetric(largestCollection))}<span>{largestCollection.date} · Forecast · {largestCollection.completeness} · {largestCollection.label}</span></button> : 'Unavailable / no supplied events'}</dd></div><div><dt>Largest known commitment</dt><dd>{largestCommitment ? <button type="button" onClick={() => onEvent(largestCommitment)}>{financialValue(eventMetric(largestCommitment))}<span>{largestCommitment.date} · Forecast · {largestCommitment.completeness} · {largestCommitment.label}</span></button> : 'Unavailable / no supplied events'}</dd></div></dl>
    </FinanceDisclosure>
    {model.projected ? <p className="finance-analysis-muted">{constrained.length ? `At or below zero at checkpoints: ${constrained.map((period) => `${period.start} until ${period.end}`).join('; ')}. Between-checkpoint changes and intraday availability are unknown.` : 'No at-or-below-zero checkpoint in the supplied horizon. This does not establish available bank funds or cover unrecorded events.'}</p> : null}
  </section>;
}
