import { useState } from "react";
import Modal from "../../../components/feedback/Modal.jsx";
import { Field, inputClass } from "../components/FactoryBulkSelectionModal.jsx";
import SearchableSelect from "../components/SearchableSelect.jsx";

export function FactoryEquipmentCategoryModal({ categories = [], onClose, onSave }) {
  const [draft, setDraft] = useState({ name: "", category_code: "", status: "active" });
  const [saving, setSaving] = useState(false);
  async function submit(event) { event.preventDefault(); setSaving(true); try { await onSave(draft); setDraft({ name: "", category_code: "", status: "active" }); } finally { setSaving(false); } }
  return <Modal title="Manage Equipment Categories" description="Categories in use are retained for historical equipment records." size="lg" onClose={saving ? undefined : onClose} footer={<button className="btn-secondary" type="button" onClick={onClose}>Close</button>}><form className="space-y-3" onSubmit={submit}><div className="grid gap-3 sm:grid-cols-3"><Field label="Name *"><input className={inputClass()} value={draft.name} onChange={(e) => setDraft((x) => ({ ...x, name: e.target.value }))} /></Field><Field label="Code"><input className={inputClass()} value={draft.category_code} onChange={(e) => setDraft((x) => ({ ...x, category_code: e.target.value }))} /></Field><div className="flex items-end"><button className="btn-primary w-full" disabled={saving}>Add Category</button></div></div><div className="divide-y rounded-lg border border-border">{categories.map((category) => <div key={category.id} className="flex items-center justify-between gap-3 px-3 py-2"><div><div className="font-bold text-text-primary">{category.name}</div><div className="text-xs text-text-secondary">{category.category_code || "No code"}</div></div><button className="btn-secondary px-3 py-1.5 text-xs" type="button" onClick={() => onSave({ ...category, status: category.status === "active" ? "inactive" : "active" })}>{category.status === "active" ? "Deactivate" : "Reactivate"}</button></div>)}</div></form></Modal>;
}

export default function FactoryEquipmentModal({ initialValue, categories = [], locations = [], onClose, onSave }) {
  const [form, setForm] = useState(() => ({ equipment_code: "", name: "", category_id: "", current_location_id: "", status: "active", notes: "", ...initialValue }));
  const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  async function submit(event) { event.preventDefault(); if (!form.equipment_code || !form.name || !form.current_location_id) { setError("Code, name and Location are required."); return; } setSaving(true); try { await onSave(form); } finally { setSaving(false); } }
  return <Modal title={initialValue?.id ? "Edit Equipment" : "Create Equipment"} description="Equipment uses the canonical Factory Location and remains traceable after later changes." size="lg" onClose={saving ? undefined : onClose} footer={<><button className="btn-secondary" type="button" onClick={onClose}>Cancel</button><button className="btn-primary" form="factory-equipment-form" disabled={saving}>{saving ? "Saving..." : "Save Equipment"}</button></>}><form id="factory-equipment-form" className="space-y-4" onSubmit={submit}>{error ? <div role="alert" className="text-sm font-semibold text-rose-700">{error}</div> : null}<div className="grid gap-3 sm:grid-cols-2"><Field label="Equipment Code *"><input className={inputClass()} value={form.equipment_code} onChange={(e) => setForm((x) => ({ ...x, equipment_code: e.target.value }))} /></Field><Field label="Equipment Name *"><input className={inputClass()} value={form.name} onChange={(e) => setForm((x) => ({ ...x, name: e.target.value }))} /></Field><Field label="Category"><SearchableSelect value={form.category_id || ""} options={[{ value: "", label: "Uncategorised" }, ...categories.map((x) => ({ value: x.id, label: x.name }))]} onChange={(category_id) => setForm((x) => ({ ...x, category_id }))} /></Field><Field label="Location *"><SearchableSelect value={form.current_location_id || ""} options={locations.filter((x) => x.status === "active" || x.id === form.current_location_id).map((x) => ({ value: x.id, label: x.location_name }))} onChange={(current_location_id) => setForm((x) => ({ ...x, current_location_id }))} /></Field><Field label="Status"><SearchableSelect value={form.status} options={[{ value: "active", label: "Active" }, { value: "inactive", label: "Inactive" }, { value: "maintenance", label: "Maintenance" }, { value: "out_of_service", label: "Out of Service" }]} onChange={(status) => setForm((x) => ({ ...x, status }))} /></Field></div><Field label="Notes"><textarea className={inputClass()} rows={3} value={form.notes || ""} onChange={(e) => setForm((x) => ({ ...x, notes: e.target.value }))} /></Field></form></Modal>;
}
