import { useEffect, useMemo, useState } from "react";
import { Bell, BookOpen, BriefcaseBusiness, ChevronDown, Clock3, GraduationCap, Home, LogOut, MapPin, Navigation, Settings, Trophy, UserRound } from "lucide-react";
import { crewService } from "../../services/crewService.js";

const storageKey = "feedx.crew.session";
const clockInOptions = ["Outlet GPS location seems inaccurate", "Working off-site", "Assigned to another location", "Location accuracy issue", "Location permission unavailable", "Device location unavailable", "Other"];
const clockOutOptions = ["Working off-site", "Assigned to another location", "Outlet GPS location seems inaccurate", "Location accuracy issue", "Forgot to clock out before leaving", "Location permission unavailable", "Device location unavailable", "Other"];
const readSession = () => { try { const value = JSON.parse(localStorage.getItem(storageKey) || "null"); return value?.token && new Date(value.expires_at) > new Date() ? value : null; } catch { return null; } };
const formatTime = (value) => value ? new Date(value).toLocaleTimeString("en-MY", { hour: "2-digit", minute: "2-digit" }) : "—";
const formatDate = (value) => value ? new Date(value).toLocaleDateString("en-MY", { day: "numeric", month: "short", year: "numeric" }) : "—";
const distanceMeters = (a, b, c, d) => { const r = (value) => value * Math.PI / 180; const p = r(c - a); const q = r(d - b); return 6371000 * 2 * Math.atan2(Math.sqrt(Math.sin(p / 2) ** 2 + Math.cos(r(a)) * Math.cos(r(c)) * Math.sin(q / 2) ** 2), Math.sqrt(1 - (Math.sin(p / 2) ** 2 + Math.cos(r(a)) * Math.cos(r(c)) * Math.sin(q / 2) ** 2))); };
const getLocation = () => new Promise((resolve, reject) => { if (!navigator.geolocation) return reject(new Error("Device location unavailable")); navigator.geolocation.getCurrentPosition((p) => resolve({ latitude: p.coords.latitude, longitude: p.coords.longitude, accuracy_meters: p.coords.accuracy }), (e) => reject(new Error(e.code === 1 ? "Location permission unavailable" : "Device location unavailable")), { enableHighAccuracy: true, timeout: 12000, maximumAge: 30000 }); });

function ShiftRing({ openShift }) { return <div className={`crew-shift-ring ${openShift ? "is-live" : ""}`} aria-label={openShift ? "On shift" : "Not clocked in"}><svg viewBox="0 0 120 120" aria-hidden="true"><circle cx="60" cy="60" r="48" className="crew-ring-track" /><circle cx="60" cy="60" r="48" className="crew-ring-value" /></svg><div><small>{openShift ? "You are" : "Ready to"}</small><strong>{openShift ? "On Shift" : "start"}</strong></div></div>; }

export default function CrewMobileApp() {
  const [session, setSession] = useState(readSession); const [screen, setScreen] = useState("home"); const [mobile, setMobile] = useState(""); const [passcode, setPasscode] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(false); const [attendance, setAttendance] = useState([]); const [context, setContext] = useState(null); const [clockDraft, setClockDraft] = useState(null); const [exception, setException] = useState(""); const [otherReason, setOtherReason] = useState(""); const [passcodeChangeOpen, setPasscodeChangeOpen] = useState(false); const [currentPasscode, setCurrentPasscode] = useState(""); const [newPasscode, setNewPasscode] = useState("");
  const openShift = useMemo(() => attendance.find((item) => item.status === "open"), [attendance]);
  const hour = new Date().getHours(); const greeting = hour < 12 ? "Good morning" : hour < 18 ? "Good afternoon" : "Good evening";
  async function refresh(token = session?.token) { if (!token) return; try { const [history, nextContext] = await Promise.all([crewService.myAttendance(token), crewService.attendanceContext(token)]); setAttendance(history); setContext(nextContext); } catch (e) { localStorage.removeItem(storageKey); setSession(null); setError(e.message || "Your session ended. Please sign in again."); } }
  useEffect(() => { refresh(); }, [session?.token]);
  async function login(event) { event.preventDefault(); setError(""); if (!/^\d{4}$/.test(passcode)) return setError("Enter your four-digit passcode."); setLoading(true); try { const next = await crewService.signIn(mobile, passcode); localStorage.setItem(storageKey, JSON.stringify(next)); setSession(next); setPasscode(""); } catch (e) { setError(e.message || "Unable to sign in."); } finally { setLoading(false); } }
  async function prepareClock(action) { setError(""); setLoading(true); setClockDraft(null); setException(""); setOtherReason(""); try { const location = await getLocation(); const distance = context?.location_enabled ? distanceMeters(location.latitude, location.longitude, Number(context.latitude), Number(context.longitude)) : null; setClockDraft({ action, location, distance }); } catch (e) { setClockDraft({ action, location: null, locationError: e.message }); } finally { setLoading(false); } }
  async function submitClock() { const reason = exception === "Other" ? otherReason.trim() : exception; const requiresException = context?.location_enabled && (!clockDraft?.location || clockDraft?.distance > Number(context.radius_meters)); if (requiresException && !reason) return setError(`Choose an exception reason to clock ${clockDraft.action === "out" ? "out" : "in"}.`); setLoading(true); setError(""); try { await crewService.clock(session.token, clockDraft.action, clockDraft.location || null, reason); setClockDraft(null); await refresh(); } catch (e) { setError(e.message || "Unable to update attendance."); } finally { setLoading(false); } }
  async function changePasscode(event) { event.preventDefault(); setError(""); if (!/^\d{4}$/.test(currentPasscode) || !/^\d{4}$/.test(newPasscode)) return setError("Enter both four-digit passcodes."); setLoading(true); try { const next = await crewService.changePasscode(session.token, currentPasscode, newPasscode); const updated = { ...session, token: next.token, expires_at: next.expires_at }; localStorage.setItem(storageKey, JSON.stringify(updated)); setSession(updated); setCurrentPasscode(""); setNewPasscode(""); setPasscodeChangeOpen(false); } catch (e) { setError(e.message || "Unable to change passcode."); } finally { setLoading(false); } }
  function logout() { localStorage.removeItem(storageKey); setSession(null); setAttendance([]); setScreen("home"); }
  if (!session) return <main className="crew-mobile-shell"><section className="crew-mobile-login"><div className="crew-mobile-brand"><span>FeedX</span><small>Crew</small></div><h1>Your shift starts here.</h1><p>Sign in with the mobile number and Crew passcode from your manager.</p><form onSubmit={login}><label>Mobile number<input inputMode="tel" autoComplete="tel" value={mobile} onChange={(e) => setMobile(e.target.value)} placeholder="+60 12 345 6789" required /></label><label>Passcode<input inputMode="numeric" autoComplete="current-password" maxLength="4" value={passcode} onChange={(e) => setPasscode(e.target.value.replace(/\D/g, ""))} placeholder="••••" required /></label>{error && <div className="crew-mobile-error">{error}</div>}<button className="crew-mobile-primary" disabled={loading}>{loading ? "Signing in…" : "Sign in to Crew"}</button></form><a href="#dashboard" className="crew-mobile-admin-link">FeedX Admin sign in</a></section></main>;
  const employee = session.employee || {}; const exceptionRequired = Boolean(context?.location_enabled && (!clockDraft?.location || clockDraft?.distance > Number(context.radius_meters))); const outside = Boolean(clockDraft?.location && clockDraft?.distance > Number(context?.radius_meters)); const options = clockDraft?.action === "out" ? clockOutOptions : clockInOptions;
  const nav = [{ id: "home", label: "Home", icon: Home }, { id: "learn", label: "Learn", icon: GraduationCap }, { id: "work", label: "Work", icon: BriefcaseBusiness }, { id: "performance", label: "Performance", icon: Trophy }, { id: "me", label: "Me", icon: UserRound }];
  return <main className="crew-mobile-shell"><section className="crew-mobile-app"><header className="crew-mobile-top"><div><p>{greeting},</p><h1>{employee.nickname || employee.full_name?.split(" ")[0] || "Crew"} <span>👋</span></h1><small className={`crew-status-pill ${openShift ? "is-on" : ""}`}>{openShift ? "● On Shift" : "○ Not clocked in"}</small><p>{context?.outlet_name || employee.workplace || "Your outlet"}</p></div><div className="crew-top-actions"><button className="crew-icon-button" aria-label="Notifications"><Bell size={17} /></button><div className="crew-mobile-avatar">{(employee.nickname || employee.full_name || "C").slice(0, 1)}</div></div></header>
    {screen === "home" && <><section className={`crew-home-attendance ${openShift ? "is-on-shift" : ""}`}><div><small>{openShift ? "Clocked in" : "Ready to start"}</small><strong>{openShift ? formatTime(openShift.clock_in_at) : "Clock In required"}</strong><span>{openShift ? "Your current shift is active" : "Your next shift is waiting"}</span></div><div className="crew-checkmark">{openShift ? "✓" : <Clock3 size={21} />}</div></section><section className="crew-mobile-section crew-focus"><div className="crew-mobile-section-head"><h2>Today’s focus</h2><button type="button" onClick={() => setScreen("learn")}>See all</button></div><div className="crew-focus-list"><div><BookOpen size={17} /><span><strong>Continue onboarding</strong><small>Coming soon · no assignment yet</small></span><em>›</em></div><div><BriefcaseBusiness size={17} /><span><strong>Daily operations</strong><small>Coming soon · no checklist due</small></span><em>›</em></div><div><Navigation size={17} /><span><strong>SOP update</strong><small>Coming soon · no new update</small></span><em>›</em></div></div></section><section className="crew-progress-card"><div className="crew-progress-empty"><span>—</span></div><div><h2>Your progress</h2><p>Your learning journey will appear here when assignments are available.</p></div></section></>}
    {screen === "work" && <><div className="crew-work-header"><h1>Attendance</h1><button>Today <ChevronDown size={14} /></button></div><section className="crew-work-hero"><ShiftRing openShift={openShift} /><div className="crew-work-time"><strong>{openShift ? formatTime(openShift.clock_in_at) : "—"}</strong><small>{openShift ? "Current Shift" : "No active shift"}</small></div><div className="crew-work-meta"><span><small>Clock In</small><strong>{openShift ? formatTime(openShift.clock_in_at) : "—"}</strong></span><span><small>Schedule</small><strong>Not assigned</strong></span><span><small>Outlet</small><strong>{context?.outlet_name || "—"}</strong></span></div></section>{openShift ? <button className="crew-mobile-primary" onClick={() => prepareClock("out")} disabled={loading}>{loading ? "Checking location…" : "Clock Out"}</button> : <button className="crew-mobile-primary" onClick={() => prepareClock("in")} disabled={loading}>{loading ? "Checking location…" : "Clock In"}</button>}<section className="crew-location-panel"><MapPin size={19} /><div><strong>{context?.location_enabled ? "Location verification" : "Location not configured"}</strong><small>{context?.location_enabled ? `Within ${context.radius_meters}m of ${context.outlet_name}` : "Your manager has not enabled a geofence."}</small></div></section></>}
    {clockDraft && <section className="crew-location-check" aria-live="polite"><div className="crew-draft-heading"><Navigation size={18} /><div><strong>{clockDraft.action === "out" ? "Clock out location" : "Clock in location"}</strong><small>{context?.outlet_name || "Outlet"}</small></div></div>{!exceptionRequired && <p className="crew-verified-copy">✓ Location Verified · within outlet area</p>}{outside && <><p className="crew-warning-copy">You’re outside the outlet area</p><div className="crew-location-metrics"><span>Current distance<strong>{Math.round(clockDraft.distance)} m</strong></span><span>Allowed radius<strong>{context.radius_meters} m</strong></span></div></>}{!clockDraft.location && <p className="crew-warning-copy">Location couldn’t be verified</p>}{exceptionRequired && <label className="crew-select-label">Why are you clocking {clockDraft.action === "out" ? "out" : "in"} here?<select value={exception} onChange={(e) => setException(e.target.value)}><option value="">Select a reason</option>{options.map((option) => <option key={option}>{option}</option>)}</select></label>}{exception === "Other" && <input className="crew-exception-input" value={otherReason} maxLength="280" onChange={(e) => setOtherReason(e.target.value)} placeholder="Brief reason" />}{error && <div className="crew-mobile-error">{error}</div>}<div className="crew-draft-actions"><button className="btn-secondary" type="button" onClick={() => { setClockDraft(null); setError(""); }} disabled={loading}>Cancel</button><button className="crew-mobile-primary" type="button" onClick={submitClock} disabled={loading}>{exceptionRequired ? `Clock ${clockDraft.action === "out" ? "Out" : "In"} with Exception` : `Confirm Clock ${clockDraft.action === "out" ? "Out" : "In"}`}</button></div></section>}
    {screen === "learn" && <section className="crew-coming-soon"><GraduationCap size={25} /><h2>Learning Journey</h2><p>Learning modules will appear when your manager assigns them.</p></section>}{screen === "performance" && <section className="crew-coming-soon"><Trophy size={25} /><h2>Performance</h2><p>Your performance summary will appear when it is available.</p></section>}
    {screen === "me" && <><section className="crew-profile-card"><div className="crew-mobile-avatar">{(employee.nickname || employee.full_name || "C").slice(0, 1)}</div><div><h2>{employee.full_name}</h2><p>{employee.position || "Crew member"}</p><small>{context?.outlet_name || employee.workplace || "Workplace"}</small></div></section><section className="crew-profile-list"><div><UserRound size={17} /><span>Profile Information</span><em>›</em></div><div><BookOpen size={17} /><span>Employment Documents</span><em>›</em></div><button onClick={() => setScreen("work")}><Clock3 size={17} /><span>Attendance</span><em>›</em></button><button onClick={() => setPasscodeChangeOpen(true)}><Settings size={17} /><span>Change Passcode</span><em>›</em></button><div><Settings size={17} /><span>Settings</span><em>›</em></div><div><Bell size={17} /><span>Help & Support</span><em>›</em></div></section>{passcodeChangeOpen && <form className="crew-location-check" onSubmit={changePasscode}><strong>Change passcode</strong><input className="crew-exception-input" inputMode="numeric" maxLength="4" value={currentPasscode} onChange={(e) => setCurrentPasscode(e.target.value.replace(/\D/g, ""))} placeholder="Current passcode" /><input className="crew-exception-input" inputMode="numeric" maxLength="4" value={newPasscode} onChange={(e) => setNewPasscode(e.target.value.replace(/\D/g, ""))} placeholder="New four-digit passcode" /><div className="crew-draft-actions"><button className="btn-secondary" type="button" onClick={() => setPasscodeChangeOpen(false)}>Cancel</button><button className="crew-mobile-primary" disabled={loading}>Save</button></div></form>}<button className="crew-logout" onClick={logout}><LogOut size={17} /> Log Out</button></>}
    {screen === "work" && <section className="crew-history-section"><div className="crew-mobile-section-head"><h2>Attendance history</h2><span>{attendance.length} shifts</span></div><div className="crew-mobile-history">{attendance.length ? attendance.map((row) => <div key={row.id}><div><strong>{formatDate(row.clock_in_at)}</strong><small>{row.clock_in_location_verified ? "Location Verified" : row.clock_in_location_exception ? "Location Exception" : "Location unavailable"}</small></div><div><strong>{formatTime(row.clock_in_at)} — {row.clock_out_at ? formatTime(row.clock_out_at) : "Now"}</strong><small>{row.status === "open" ? "On shift" : "Completed"}</small></div></div>) : <p>No attendance records yet.</p>}</div></section>}
    <nav className="crew-mobile-nav">{nav.map(({ id, label, icon: Icon }) => <button key={id} className={screen === id ? "active" : ""} onClick={() => setScreen(id)}><Icon size={18} /><span>{label}</span></button>)}</nav></section></main>;
}
