import { afterEach, expect, it } from 'vitest';
import { cleanup, render, screen } from '@testing-library/react';
import { FinanceOverview } from '../FinanceWorkspacePage.jsx';
import { FinanceAnalysis } from '../FinanceAnalysisPage.jsx';
import { FinanceCosts } from '../FinanceCostsPage.jsx';
import { FinanceCash } from '../FinanceCashPage.jsx';
import { createFixtureProvider } from '../providers/fixtureProvider.js';
import { readFinanceAnalysis } from '../analysis.js';
import { monthlyPeriod } from '../foundation.js';
afterEach(cleanup);
it('retains muted analytical structures without fabricating points, bars or projected cash',async()=>{
  const pair=await readFinanceAnalysis(createFixtureProvider({development:true}),{scope:{kind:'group',id:'demo-group'},period:monthlyPeriod('2026-10'),currency:'MYR'},{allowDemo:true});
  for(const dataset of [pair.current,pair.previous]){for(const metric of Object.values(dataset.metrics)){metric.value=null;metric.completeness='unavailable';metric.provenance=[];}delete dataset.classifications;delete dataset.liquiditySchedule;}
  const before=JSON.stringify(pair);
  let view=render(<FinanceOverview dataset={pair.current}/>);
  expect(screen.getByRole('region',{name:'Profit Architecture'})).toBeTruthy();
  expect(document.querySelectorAll('.finance-architecture-track i')).toHaveLength(0);
  view.unmount();view=render(<FinanceAnalysis analysis={pair}/>);
  expect(document.querySelectorAll('.finance-contribution-inputs button')).toHaveLength(4);
  expect(document.querySelectorAll('.finance-contribution-bar i')).toHaveLength(0);
  expect(screen.getByRole('group',{name:'Outlet revenue growth and EBITDA margin field'})).toBeTruthy();
  expect(document.querySelectorAll('.finance-field-point')).toHaveLength(0);
  view.unmount();view=render(<FinanceCosts analysis={pair}/>);
  expect(screen.getByRole('group',{name:'Cost growth relative to Revenue and margin impact'})).toBeTruthy();
  expect(document.querySelectorAll('.finance-pressure-point')).toHaveLength(0);
  view.unmount();render(<FinanceCash analysis={pair}/>);
  expect(screen.getByRole('group',{name:'Horizontal Liquidity Timeline'})).toBeTruthy();
  expect(document.querySelectorAll('.finance-timeline-path')).toHaveLength(0);
  expect(screen.getByRole('list',{name:'Inventory to cash cycle'})).toBeTruthy();
  expect(JSON.stringify(pair)).toBe(before);
});
