import { afterEach, expect, it } from 'vitest';
import { cleanup, fireEvent, render, screen, within } from '@testing-library/react';
import { FinanceAnalysis } from '../FinanceAnalysisPage.jsx';
import { FinanceCosts } from '../FinanceCostsPage.jsx';
import { FinanceCash } from '../FinanceCashPage.jsx';
import { FinanceOverview } from '../FinanceWorkspacePage.jsx';
import { readFinanceAnalysis } from '../analysis.js';
import { readFinanceOverview } from '../financeService.js';
import { createFixtureProvider } from '../providers/fixtureProvider.js';
import { monthlyPeriod } from '../foundation.js';
afterEach(cleanup);
const request = { scope: { kind: 'group', id: 'demo-group' }, period: monthlyPeriod('2026-10'), currency: 'MYR' };
const fixture = () => readFinanceAnalysis(createFixtureProvider({development:true}), request, {allowDemo:true});
it('keeps one analytical mode mounted and discloses context only after selection', async () => {
  const pair = await fixture();
  const view = render(<FinanceAnalysis analysis={pair}/>);
  expect(screen.queryByRole('region',{name:'Selected analysis context'})).toBeNull();
  expect(screen.queryByRole('group',{name:'Outlet revenue growth and EBITDA margin field'})).toBeNull();
  fireEvent.keyDown(screen.getByRole('tab',{name:'Profit Drivers'}),{key:'ArrowRight'});
  expect(screen.queryByRole('group',{name:'Driver Contribution'})).toBeNull();
  expect(screen.getByRole('tabpanel',{name:'Outlets'})).toBeTruthy();
  view.unmount();render(<FinanceCash analysis={pair}/>);
  expect(screen.queryByRole('region',{name:'Selected analysis context'})).toBeNull();
  expect(screen.queryByRole('group',{name:'Working Capital Flow relationships'})).toBeNull();
  fireEvent.click(screen.getByRole('tab',{name:'Working Capital'}));
  expect(screen.queryByRole('group',{name:'Horizontal Liquidity Timeline'})).toBeNull();
  fireEvent.keyDown(screen.getByRole('button',{name:'Explore Accounts Receivable stage'}),{key:'Enter'});
  expect(within(screen.getByRole('tabpanel',{name:'Working Capital'})).getByRole('region',{name:'Selected analysis context'})).toBeTruthy();
});
it('switches cost evidence geometry without adding reads or financial values', async () => {
  const pair = await fixture(), before = JSON.stringify(pair);
  render(<FinanceCosts analysis={pair}/>);
  expect(screen.queryByRole('region',{name:'Selected analysis context'})).toBeNull();
  expect(screen.getByRole('button',{name:'Explore COGS layer'})).toBeTruthy();
  const pressure = screen.getByRole('group',{name:'Cost growth relative to Revenue and margin impact'});
  expect(pressure.textContent).toContain('-0.06');
  fireEvent.click(screen.getByRole('tab',{name:'Structure'}));
  expect(screen.queryByRole('group',{name:'Cost growth relative to Revenue and margin impact'})).toBeNull();
  fireEvent.keyDown(screen.getByRole('button',{name:'Investigate COGS structure'}),{key:'Enter'});
  expect(within(screen.getByRole('tabpanel',{name:'Structure'})).getByRole('region',{name:'Selected analysis context'})).toBeTruthy();
  fireEvent.click(screen.getByRole('tab',{name:'Trend'}));
  expect(screen.queryByRole('region',{name:'Selected analysis context'})).toBeNull();
  expect(screen.queryByRole('group',{name:'Cost structure evidence'})).toBeNull();
  expect(screen.getByRole('group',{name:'Cost trend evidence'})).toBeTruthy();
  expect(JSON.stringify(pair)).toBe(before);
});
it('summarizes existing validated attribution and suppresses unsupported attention issues', async () => {
  const dataset = await readFinanceOverview(createFixtureProvider({development:true}), request, {allowDemo:true});
  const before = JSON.stringify(dataset);
  render(<FinanceOverview dataset={dataset}/>);
  expect(screen.queryByRole('group',{name:'Revenue consumption and retained profit structure'})).toBeNull();
  expect(screen.getByRole('group',{name:'Driver Contribution'}).textContent).toContain('3,747');
  expect(screen.queryByRole('region',{name:'Needs attention'})).toBeNull();
  expect(screen.queryByRole('region',{name:'Selected movement context'})).toBeNull();
  expect(JSON.stringify(dataset)).toBe(before);
});
