import { afterEach, expect, it } from 'vitest';
import { cleanup, fireEvent, render, screen, within } from '@testing-library/react';
import FinanceCostTrend from '../FinanceCostTrend.jsx';
import { FinanceCash } from '../FinanceCashPage.jsx';
import { readFinanceAnalysis } from '../analysis.js';
import { createFixtureProvider } from '../providers/fixtureProvider.js';
import { monthlyPeriod } from '../foundation.js';
import { overviewHistory } from '../overviewDashboard.js';
import { financeDashboardSummaryItems } from '../summaryItems.js';
afterEach(cleanup);
const fixture = () => readFinanceAnalysis(createFixtureProvider({development:true}), {scope:{kind:'group',id:'demo-group'},period:monthlyPeriod('2026-10'),currency:'MYR'}, {allowDemo:true,includeHistory:true});
it('uses validated monthly costs, retains month nodes across range changes and compares selected month evidence', async () => {
  const analysis = await fixture(), before = JSON.stringify(analysis);
  render(<FinanceCostTrend analysis={analysis}/>);
  const chart = screen.getByRole('group',{name:'Monthly cost history'});
  const july = within(chart).getByRole('button',{name:'July 2026 COGS and Labour Cost and OPEX'});
  fireEvent.focus(july); expect(screen.getByRole('tooltip').textContent).toContain('COGS');
  fireEvent.keyDown(july,{key:'Enter'});
  fireEvent.click(screen.getByRole('tab',{name:'12M'}));
  expect(within(chart).getAllByRole('button')).toHaveLength(12);
  expect(within(chart).getByRole('button',{name:'July 2026 COGS and Labour Cost and OPEX'})).toBe(july);
  fireEvent.click(screen.getByRole('tab',{name:'Compare',exact:true}));
  const context = screen.getByRole('region',{name:'Selected analysis context'});
  expect(context.textContent).toContain('July 2026'); expect(context.textContent).toContain('June 2026'); expect(context.textContent).not.toContain('October 2026');
  expect(chart.textContent).not.toContain('Prime Cost');
  expect(JSON.stringify(analysis)).toBe(before);
});
it('leaves absent, partial and incompatible monthly cost evidence as gaps', async () => {
  const analysis = await fixture();
  const june = analysis.history.find(entry => entry.period.start === '2026-06-01');
  june.dataset.metrics.cogs = {...june.dataset.metrics.cogs,completeness:'partial'};
  const july = analysis.history.find(entry => entry.period.start === '2026-07-01');
  july.dataset = null;
  const rows = overviewHistory({...analysis.current,history:analysis.history},6,['cogs','labour','opex']);
  expect(rows.find(row => row.period.start === '2026-06-01').cogs).toBeNull();
  expect(rows.find(row => row.period.start === '2026-07-01').opex).toBeNull();
  render(<FinanceCostTrend analysis={analysis}/>);
  expect(screen.getByText('Partial monthly cost evidence')).toBeTruthy();
  expect(screen.queryByRole('button',{name:'July 2026 COGS and Labour Cost and OPEX'})).toBeNull();
});
it('retains neutral balance movements in shared Cash cards and independently selectable capital stages', async () => {
  const pair = await fixture();
  const ids = ['cash','working_capital','ar','inventory','ap','debt'];
  expect(financeDashboardSummaryItems(pair,ids).every(item => item.deltaTone === 'neutral')).toBe(true);
  render(<FinanceCash analysis={pair}/>);
  expect(screen.queryByRole('tab',{name:'Liquidity',exact:true})).toBeNull();
  fireEvent.keyDown(screen.getByRole('button',{name:'Explore Accounts Receivable stage'}),{key:'Enter'});
  expect(screen.getByRole('group',{name:'Horizontal Liquidity Timeline'})).toBeTruthy();
  expect(screen.getByRole('region',{name:'Selected analysis context'}).textContent).toContain('Accounts Receivable');
});
