import { afterEach, expect, it } from 'vitest';
import { cleanup, fireEvent, render, screen, within } from '@testing-library/react';
import { FinanceAnalysis } from '../FinanceAnalysisPage.jsx';
import { FinanceCosts } from '../FinanceCostsPage.jsx';
import { FinanceCash } from '../FinanceCashPage.jsx';
import { FinanceOverview } from '../FinanceWorkspacePage.jsx';
import { readFinanceAnalysis } from '../analysis.js';
import { readFinanceOverview } from '../financeService.js';
import { createFixtureProvider } from '../providers/fixtureProvider.js';
import { monthlyPeriod } from '../foundation.js';
afterEach(cleanup);
const request = { scope: { kind: 'group', id: 'demo-group' }, period: monthlyPeriod('2026-10'), currency: 'MYR' };
const fixture = () => readFinanceAnalysis(createFixtureProvider({development:true}), request, {allowDemo:true});
it('keeps Analysis sections mounted independently and Cash analyses independent', async () => {
  const pair = await fixture();
  const view = render(<FinanceAnalysis analysis={pair}/>);
  expect(screen.queryByRole('region',{name:'Selected analysis context'})).toBeNull();
  expect(screen.getByRole('group',{name:'Outlet revenue growth and EBITDA margin field'})).toBeTruthy();
  expect(screen.getByRole('group',{name:'Driver Contribution'})).toBeTruthy();
  expect(screen.getByRole('group',{name:'Monthly EBITDA Margin history'})).toBeTruthy();
  expect(screen.queryByRole('tab',{name:'Profit Drivers'})).toBeNull();
  view.unmount();render(<FinanceCash analysis={pair}/>);
  expect(screen.queryByRole('region',{name:'Selected analysis context'})).toBeNull();
  expect(screen.getByRole('group',{name:'Working Capital Flow relationships'})).toBeTruthy();
  expect(screen.getByRole('group',{name:'Horizontal Liquidity Timeline'})).toBeTruthy();
  fireEvent.keyDown(screen.getByRole('button',{name:'Explore Accounts Receivable stage'}),{key:'Enter'});
  expect(within(document.querySelector('[data-admin-analytical-surface][aria-label="Working Capital Flow"]')).getByRole('region',{name:'Selected analysis context'})).toBeTruthy();
});
it('keeps cost analyses and selected contexts independent without mutating evidence', async () => {
  const pair = await fixture(), before = JSON.stringify(pair);
  render(<FinanceCosts analysis={pair}/>);
  expect(screen.queryByRole('region',{name:'Selected analysis context'})).toBeNull();
  expect(screen.queryByRole('tab',{name:'Structure'})).toBeNull();
  expect(screen.getByRole('group',{name:'Cost growth relative to Revenue and margin impact'})).toBeTruthy();
  expect(screen.getByRole('group',{name:'100 percent Revenue composition'})).toBeTruthy();
  expect(screen.queryByText('Partial composition evidence')).toBeNull();
  expect(screen.getByRole('group',{name:'100 percent Revenue composition'}).querySelectorAll('.chart-pending')).toHaveLength(0);
  expect(screen.getByRole('group',{name:'Monthly cost history'})).toBeTruthy();
  const pressure = document.querySelector('[data-admin-analytical-surface][aria-label="Margin Pressure Map"]');
  const structure = document.querySelector('[data-admin-analytical-surface][aria-label="Cost Structure"]');
  fireEvent.click(within(pressure).getByRole('button',{name:'Explore COGS layer'}));
  fireEvent.keyDown(within(structure).getByRole('button',{name:'Inspect Labour Cost conversion'}),{key:'Enter'});
  expect(within(pressure).getByRole('region',{name:'Selected analysis context'}).textContent).toContain('COGS');
  expect(within(structure).getByRole('region',{name:'Selected analysis context'}).textContent).toContain('Labour Cost');
  expect(JSON.stringify(pair)).toBe(before);
});
it('summarizes existing validated attribution and suppresses unsupported attention issues', async () => {
  const dataset = await readFinanceOverview(createFixtureProvider({development:true}), request, {allowDemo:true});
  const before = JSON.stringify(dataset);
  render(<FinanceOverview dataset={dataset}/>);
  expect(screen.queryByRole('group',{name:'Revenue consumption and retained profit structure'})).toBeNull();
  expect(screen.getByRole('heading',{name:'What changed this month?'})).toBeTruthy();
  expect(screen.getByRole('group',{name:'Driver Contribution'}).textContent).toContain('3,747');
  expect(screen.queryByRole('region',{name:'Needs attention'})).toBeNull();
  expect(screen.queryByRole('region',{name:'Selected movement context'})).toBeNull();
  expect(JSON.stringify(dataset)).toBe(before);
});
