import {test} from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import {transformSync} from 'esbuild';
const source=transformSync(fs.readFileSync(new URL('../../../supabase/functions/recruitment-generated-voice-lab/index.ts',import.meta.url),'utf8'),{loader:'ts'}).code.replace(/^import .*;$/m,'').replace(/export /g,'');
function harness({url='https://ujkzdaaadnvcfayuldmh.supabase.co',permission=true,user=true}={}){
 let handler,stored=null,calls=[];
 const storage={download:async()=>stored?{data:new Blob([stored])}:{error:{statusCode:'404'}},upload:async(_p,value,{upsert})=>{if(stored&&!upsert)return {error:{}};stored=value;return {error:null};}};
 vm.runInNewContext(source,{Deno:{env:{get:name=>name==='SUPABASE_URL'?url:'private-test-key'},serve:h=>handler=h},createClient:()=>({auth:{getUser:async()=>({data:{user:user?{}:null}})},rpc:async()=>({data:permission}),storage:{from:()=>storage}}),fetch:async(url,options)=>{calls.push({url,body:options.body});return url.includes('/models/')?new Response('{}',{status:404}):new Response(JSON.stringify({error:{message:'Project lacks api.voices.write',code:'missing_scope',type:'permission_error'}}),{status:403});},Response,Blob,AbortSignal,Date,JSON,Error});
 return {run:(action,auth=true,origin='https://fnb-system-staging.vercel.app')=>handler(new Request('https://edge',{method:'POST',headers:{origin,...(auth?{authorization:'Bearer test'}:{})},body:JSON.stringify({action})})),calls};
}
test('protected staging probe caches exact provider denial and never retries on reload',async()=>{const h=harness();assert.equal((await (await h.run('status')).json()).status,'not_checked');assert.equal(h.calls.length,0);const r=await(await h.run('probe')).json();assert.equal(r.provider_status,403);assert.equal(r.provider_code,'missing_scope');await h.run('probe');await h.run('status');assert.equal(h.calls.length,2);assert.equal(JSON.parse(h.calls[1].body).type,'prompt');assert.equal(JSON.parse(h.calls[1].body).audio_sample,undefined);});
test('wrong environment, unauthorized, denied permission and wrong origin cannot call provider',async()=>{for(const [opts,auth,origin,status] of [[{url:'production'},true,undefined,403],[{},false,undefined,401],[{user:false},true,undefined,401],[{permission:false},true,undefined,403],[{},true,'https://evil.test',403]]){const h=harness(opts);assert.equal((await h.run('probe',auth,origin)).status,status);assert.equal(h.calls.length,0);}});
