import Modal from "../../../../components/feedback/Modal.jsx";
import Badge from "../../../../components/ui/Badge.jsx";
import Card from "../../../../components/ui/Card.jsx";
import { FactoryTable } from "../../components/FactoryDataDisplay.jsx";
import { formatFactoryDate } from "../../utils/factoryDates.js";
import { costDisplay, recipeCostInfo, unitCostDisplay } from "../../utils/factoryCosting.js";
import { percent, quantity } from "../../utils/factoryFormatters.js";
import { jobStatusLabel } from "../../utils/factoryStatus.js";

export default function ProductRecipeDetailModal({ recipe, receivings = [], onClose }) {
  const finishedGoodName = recipe.product_name_en || recipe.product_name || "Finished Good";
  const finishedGoodCn = recipe.product_name_cn || "";
  const recipeCost = recipeCostInfo(recipe, receivings);
  return <Modal title={finishedGoodName} description={`Product Recipe / BOM · ${recipe.version || "v1"}`} size="2xl" onClose={onClose} footer={<button className="btn-secondary" type="button" onClick={onClose}>Close</button>}>
    <div className="space-y-5"><Card title="Recipe Summary"><div className="grid gap-x-8 gap-y-3 px-2 py-1 sm:px-4 md:grid-cols-3 lg:px-6"><div><div className="text-[10.5px] font-semibold text-[rgb(107,114,128)]">Finished Good</div><div className="mt-1 text-sm font-bold text-text-primary">{finishedGoodName}</div>{finishedGoodCn ? <div className="text-xs font-semibold text-text-secondary">{finishedGoodCn}</div> : null}</div><div><div className="text-[10.5px] font-semibold text-[rgb(107,114,128)]">Version</div><div className="mt-1"><Badge tone="info">{recipe.version || "v1"}</Badge></div></div><div><div className="text-[10.5px] font-semibold text-[rgb(107,114,128)]">Status</div><div className="mt-1"><Badge tone={recipe.status === "active" ? "success" : recipe.status === "draft" ? "info" : "neutral"}>{jobStatusLabel(recipe.status)}</Badge></div></div><div><div className="text-[10.5px] font-semibold text-[rgb(107,114,128)]">Standard Output</div><div className="mt-1 text-sm font-bold text-text-primary">{quantity(recipe.yield_quantity, recipe.uom)}</div></div><div><div className="text-[10.5px] font-semibold text-[rgb(107,114,128)]">Updated</div><div className="mt-1 text-sm font-bold text-text-primary">{formatFactoryDate(recipe.updated_at)}</div></div><div><div className="text-[10.5px] font-semibold text-[rgb(107,114,128)]">Recipe Total Cost</div><div className="mt-1 text-sm font-bold text-text-primary">{costDisplay(recipeCost.standardCost, recipeCost.missingCostRows, recipeCost.unsupportedCostRows)}</div></div><div><div className="text-[10.5px] font-semibold text-[rgb(107,114,128)]">Cost / {recipe.uom || "UOM"}</div><div className="mt-1 text-sm font-bold text-text-primary">{costDisplay(recipeCost.costPerUnit, recipeCost.missingCostRows, recipeCost.unsupportedCostRows)}</div></div></div></Card>
      <Card title="BOM Materials"><FactoryTable columns={[{ key: "raw_material", label: "Raw Material", render: (row) => <div className="font-semibold text-text-primary">{row.raw_material_name || "Raw Material"}</div> }, { key: "required_qty", label: "Qty", render: (row) => quantity(row.quantity_used, row.recipe_usage_uom || row.uom) }, { key: "uom", label: "Usage UOM", render: (row) => row.recipe_usage_uom || row.uom || "—" }, { key: "unit_cost", label: "Unit Cost", render: (row) => row.missing_cost ? "Missing Cost" : unitCostDisplay({ unitCost: row.unit_cost, uom: row.cost_uom }) }, { key: "line_cost", label: "Material Cost", render: (row) => <div>{costDisplay(row.standard_cost, row.missing_cost ? 1 : 0, row.unsupported_cost ? 1 : 0)}{row.conversion_reason ? <div className="mt-1 text-xs font-semibold text-amber-700">{row.conversion_reason}</div> : null}</div> }, { key: "wastage_percent", label: "Wastage", render: (row) => percent(row.wastage_percent) }, { key: "remarks", label: "Remarks", render: (row) => row.remarks || row.notes || "—" }]} rows={recipeCost.itemRows} emptyTitle="No BOM materials" emptyDescription="Add raw material rows before activating this production standard." /><div className="mt-4 flex flex-col gap-2 rounded-xl border border-border bg-slate-50 px-4 py-3 sm:flex-row sm:items-center sm:justify-between"><div><div className="text-sm font-bold text-text-primary">Recipe Total Cost</div><div className="text-xs font-semibold text-text-secondary">Costed from the saved BOM material quantities.</div></div><div className="grid gap-2 text-right sm:grid-cols-3"><div><div className="text-[10.5px] font-semibold text-[rgb(107,114,128)]">Total Cost</div><div className="text-lg font-black text-text-primary">{costDisplay(recipeCost.standardCost, recipeCost.missingCostRows, recipeCost.unsupportedCostRows)}</div></div><div><div className="text-[10.5px] font-semibold text-[rgb(107,114,128)]">Output Qty</div><div className="text-lg font-black text-text-primary">{quantity(recipe.yield_quantity, recipe.uom)}</div></div><div><div className="text-[10.5px] font-semibold text-[rgb(107,114,128)]">Cost / {recipe.uom || "UOM"}</div><div className="text-lg font-black text-text-primary">{costDisplay(recipeCost.costPerUnit, recipeCost.missingCostRows, recipeCost.unsupportedCostRows)}</div></div></div></div></Card>
      {recipe.remarks || recipe.notes ? <Card title="Remarks"><p className="whitespace-pre-wrap text-sm font-medium leading-6 text-text-secondary">{recipe.remarks || recipe.notes}</p></Card> : null}</div>
  </Modal>;
}
