import { cleanup, fireEvent, render, screen, waitFor, within } from "@testing-library/react";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";

const mocks = vi.hoisted(() => ({ tables: {}, notifications: [], saveWaste: vi.fn(), from: vi.fn() }));
vi.mock("../../../../lib/supabase.ts", () => ({ supabase: { from: mocks.from } }));
vi.mock("../../../../services/inventoryLifecycleService.js", () => ({ inventoryLifecycleService: { saveInventoryWaste: mocks.saveWaste } }));
vi.mock("../../../../services/productAnalyticsService.js", () => ({ productAnalyticsService: { listReports: vi.fn().mockResolvedValue([]), listItemsByReportIds: vi.fn().mockResolvedValue([]) } }));
import InventoryControlPage from "../InventoryControlPage.jsx";

const ids = { outlet: "00000000-0000-4000-8000-000000000001", category: "00000000-0000-4000-8000-000000000002", item: "00000000-0000-4000-8000-000000000003", waste: "00000000-0000-4000-8000-000000000004" };
function tables() { return { inventory_items: [{ id: ids.item, item_name: "Dried Chilli", sku_code: "RM-CHILLI", category_id: ids.category, unit: "kg", status: "active" }], inventory_categories: [{ id: ids.category, name: "Raw Materials", status: "active", sort_order: 1 }], inventory_uoms: [], inventory_item_outlets: [{ id: "link", inventory_item_id: ids.item, outlet_id: ids.outlet, is_active: true, outlets: { id: ids.outlet, name: "KL Central", code: "KLC" } }], inventory_item_outlet_suppliers: [], inventory_stock_check_groups: [], inventory_stock_check_group_categories: [], inventory_stock_checks: [], inventory_stock_check_items: [], inventory_purchase_orders: [], inventory_purchase_order_items: [], inventory_purchase_receipts: [], inventory_purchase_receipt_items: [], inventory_movements: [{ id: "move", reference_type: "waste", reference_id: ids.waste, reference_no: "WST-0001" }], inventory_waste_records: [{ id: ids.waste, outlet_id: ids.outlet, inventory_item_id: ids.item, waste_type: "Spoilage", quantity: 2, unit: "kg", waste_date: "2026-08-10", notes: "Damaged delivery", photo_url: "https://example.test/waste.jpg", created_by: "user-1", created_at: "2026-08-10T08:00:00Z" }], inventory_menu_categories: [], inventory_recipes: [], inventory_recipe_items: [], employees: [] }; }
function query(table) { const builder = {}; const result = () => ({ data: mocks.tables[table] || [], error: null }); ["select", "order", "ilike", "limit", "eq"].forEach((key) => { builder[key] = vi.fn(() => builder); }); builder.then = (resolve, reject) => Promise.resolve(result()).then(resolve, reject); return builder; }
function readCount() { return mocks.from.mock.calls.filter(([table]) => table === "inventory_items").length; }
function mount(permissions = ["inventory_waste.view", "inventory_waste.create"]) { const ui = { notify: vi.fn((notice) => mocks.notifications.push(notice)) }; render(<InventoryControlPage initialTab="waste" store={{ outlets: [{ id: ids.outlet, name: "KL Central", code: "KLC" }], suppliers: [] }} auth={{ user: { id: "user-1" }, profile: { id: "user-1", role_outlet_access_type: "selected", role_outlet_ids: [ids.outlet] }, hasPermission: (key) => permissions.includes(key) }} ui={ui} />); return ui; }
async function ready() { await screen.findAllByText("Dried Chilli"); }
function changeByLabel(label, value) { const labelNode = screen.getAllByText(label, { selector: "div" }).find((node) => node.parentElement?.querySelector("input")); fireEvent.change(labelNode.parentElement.querySelector("input"), { target: { value } }); }
beforeEach(() => { mocks.tables = tables(); mocks.notifications.length = 0; mocks.from.mockImplementation(query); mocks.from.mockClear(); mocks.saveWaste.mockReset(); mocks.saveWaste.mockResolvedValue({ waste_id: ids.waste }); });
afterEach(cleanup);

describe("InventoryControlPage Waste lifecycle", () => {
  it("mounts a non-empty Waste list and its extracted detail presentation", async () => { mount(); await ready(); expect(screen.getByText("Damaged delivery")).toBeTruthy(); fireEvent.click(screen.getByRole("button", { name: "View" })); await screen.findByRole("heading", { name: "Waste Record Detail" }); expect(screen.getByText("WST-0001")).toBeTruthy(); expect(screen.getByAltText("Waste evidence")).toBeTruthy(); });
  it("uses one trusted Waste mutation, refresh, notification, and closes on success", async () => { mount(); await ready(); const before = readCount(); fireEvent.click(screen.getByRole("button", { name: "Record Waste" })); await screen.findByRole("heading", { name: "Record Waste" }); changeByLabel("Quantity", "3"); fireEvent.click(screen.getByRole("button", { name: "Save Waste" })); await waitFor(() => expect(mocks.saveWaste).toHaveBeenCalledTimes(1)); await waitFor(() => expect(screen.queryByRole("heading", { name: "Record Waste" })).toBeNull()); expect(mocks.saveWaste).toHaveBeenCalledWith({ waste: expect.objectContaining({ outletId: ids.outlet, itemId: ids.item, wasteType: "Spoilage", quantity: 3, unit: "kg", notes: "" }) }); expect(readCount()).toBe(before + 1); expect(mocks.notifications).toContainEqual(expect.objectContaining({ title: "Waste record created" })); });
  it("keeps the modal usable on rejection without false success or duplicate refresh", async () => { mocks.saveWaste.mockRejectedValueOnce(new Error("rejected")); mount(); await ready(); const before = readCount(); fireEvent.click(screen.getByRole("button", { name: "Record Waste" })); await screen.findByRole("heading", { name: "Record Waste" }); changeByLabel("Quantity", "3"); fireEvent.click(screen.getByRole("button", { name: "Save Waste" })); await waitFor(() => expect(mocks.saveWaste).toHaveBeenCalledTimes(1)); expect(screen.getByRole("heading", { name: "Record Waste" })).toBeTruthy(); await waitFor(() => expect(screen.getByRole("button", { name: "Save Waste" }).disabled).toBe(false)); expect(readCount()).toBe(before + 1); expect(mocks.notifications).toContainEqual(expect.objectContaining({ title: "Failed to create Waste Record", tone: "error" })); expect(mocks.notifications.some((entry) => entry.title === "Waste record created")).toBe(false); });
  it("prevents a repeat submit while the trusted mutation is pending", async () => { let resolveSave; mocks.saveWaste.mockImplementation(() => new Promise((resolve) => { resolveSave = resolve; })); mount(); await ready(); fireEvent.click(screen.getByRole("button", { name: "Record Waste" })); await screen.findByRole("heading", { name: "Record Waste" }); changeByLabel("Quantity", "3"); const save = screen.getByRole("button", { name: "Save Waste" }); fireEvent.click(save); fireEvent.click(save); expect(mocks.saveWaste).toHaveBeenCalledTimes(1); resolveSave({ waste_id: ids.waste }); await waitFor(() => expect(screen.queryByRole("heading", { name: "Record Waste" })).toBeNull()); });
  it("does not render an enabled Waste mutation control for view-only permissions", async () => { mount(["inventory_waste.view"]); await ready(); expect(screen.queryByRole("button", { name: "Record Waste" })).toBeNull(); expect(mocks.saveWaste).not.toHaveBeenCalled(); });
});
