import { createContext, useMemo } from "react";

export const FactoryNavigationContext = createContext(null);

export function FactoryNavigationProvider({ auditReferenceLoading, openAuditReference, rawMovementReferenceLoading, openRawMaterialMovementReference, openingBatchTraceabilityDispatchId, openBatchTraceabilityDispatch, openCreateSupplier, openEditSupplier, archiveSupplier, openCreateCustomer, openEditCustomer, archiveCustomer, openCreateStorageLocation, openEditStorageLocation, archiveStorageLocation, openCreateFinishedGood, openEditFinishedGood, archiveFinishedGood, openFinishedGoodPackagingSku, archiveFinishedGoodPackagingSku, openFinishedGoodCategory, openCreateRawMaterial, openEditRawMaterial, openRawMaterialCost, openRawMaterialImage, openRawMaterialCategory, openPlanningJobOrderDraft, openProductionPlanningPar, saveProductRecipe, activateProductRecipe, archiveProductRecipe, restoreProductRecipe, createProductRecipeNewVersion, deleteProductRecipe, children }) {
  const value = useMemo(
    () => ({ auditReferenceLoading, openAuditReference, rawMovementReferenceLoading, openRawMaterialMovementReference, openingBatchTraceabilityDispatchId, openBatchTraceabilityDispatch, openCreateSupplier, openEditSupplier, archiveSupplier, openCreateCustomer, openEditCustomer, archiveCustomer, openCreateStorageLocation, openEditStorageLocation, archiveStorageLocation, openCreateFinishedGood, openEditFinishedGood, archiveFinishedGood, openFinishedGoodPackagingSku, archiveFinishedGoodPackagingSku, openFinishedGoodCategory, openCreateRawMaterial, openEditRawMaterial, openRawMaterialCost, openRawMaterialImage, openRawMaterialCategory, openPlanningJobOrderDraft, openProductionPlanningPar, saveProductRecipe, activateProductRecipe, archiveProductRecipe, restoreProductRecipe, createProductRecipeNewVersion, deleteProductRecipe }),
    [auditReferenceLoading, openAuditReference, rawMovementReferenceLoading, openRawMaterialMovementReference, openingBatchTraceabilityDispatchId, openBatchTraceabilityDispatch, openCreateSupplier, openEditSupplier, archiveSupplier, openCreateCustomer, openEditCustomer, archiveCustomer, openCreateStorageLocation, openEditStorageLocation, archiveStorageLocation, openCreateFinishedGood, openEditFinishedGood, archiveFinishedGood, openFinishedGoodPackagingSku, archiveFinishedGoodPackagingSku, openFinishedGoodCategory, openCreateRawMaterial, openEditRawMaterial, openRawMaterialCost, openRawMaterialImage, openRawMaterialCategory, openPlanningJobOrderDraft, openProductionPlanningPar, saveProductRecipe, activateProductRecipe, archiveProductRecipe, restoreProductRecipe, createProductRecipeNewVersion, deleteProductRecipe],
  );

  return <FactoryNavigationContext.Provider value={value}>{children}</FactoryNavigationContext.Provider>;
}
