-- FeedX Crew Growth QA dataset. STAGING ONLY; never a migration.
-- Master data is created through crew_growth_save_skill and certification state
-- is created through the same controlled assessment/certify authorities as Admin UI.
begin;

do $$
declare
  qa_admin constant uuid := '266912cf-0e84-4074-82b5-0fc483080741';
  qa_role uuid;
  outlet uuid;
  completed_employee uuid;
  progress_employee uuid;
  module_greeting uuid; module_orders uuid; lesson_table uuid; lesson_handover uuid; lesson_grooming uuid; lesson_clean uuid; lesson_open uuid; lesson_close uuid;
  quiz_greeting uuid; quiz_orders uuid; sop_welcome uuid; sop_grooming uuid; sop_clean uuid;
  v_skill_id uuid;
begin
  select e.role_id into qa_role from public.employees e where e.auth_user_id=qa_admin and e.is_active;
  if qa_role is null or not exists(select 1 from public.roles where id=qa_role and lower(name)='crew_admin_qa') then raise exception 'Staging Crew Admin QA identity is unavailable.'; end if;
  insert into public.role_permissions(role_id,permission_id) select qa_role,p.id from public.permissions p where p.code in ('crew_growth.view','crew_growth.manage','crew_growth.assess','crew_growth.certify') on conflict do nothing;
  select id into outlet from public.outlets where name='Friends Corner';
  if outlet is null or not exists(select 1 from public.role_outlets where role_id=qa_role and outlet_id=outlet) then raise exception 'Crew Admin QA does not have Friends Corner scope.'; end if;
  select e.id into completed_employee from public.employees e join public.crew_access ca on ca.employee_id=e.id where ca.primary_outlet_id=outlet and e.employee_code='QA-CREW-CO-01';
  select e.id into progress_employee from public.employees e join public.crew_access ca on ca.employee_id=e.id where ca.primary_outlet_id=outlet and e.employee_code='QA-CREW-IP-01';
  if completed_employee is null or progress_employee is null then raise exception 'Required QA Crew fixtures are unavailable.'; end if;

  -- Pin Growth requirements to evidence IDs from the QA employee's immutable
  -- assignment snapshot. A newer live Onboarding version must not retroactively
  -- replace evidence already earned by an existing employee.
  select mp.module_id into module_greeting from public.crew_module_progress mp join public.crew_journey_assignments a on a.id=mp.assignment_id join public.crew_journey_modules m on m.id=mp.module_id where a.employee_id=completed_employee and mp.status='completed' and m.title='Customer Arrival & Greeting' order by mp.completed_at desc nulls last limit 1;
  select mp.module_id into module_orders from public.crew_module_progress mp join public.crew_journey_assignments a on a.id=mp.assignment_id join public.crew_journey_modules m on m.id=mp.module_id where a.employee_id=completed_employee and mp.status='completed' and m.title='Taking Orders' order by mp.completed_at desc nulls last limit 1;
  select lp.lesson_id into lesson_table from public.crew_lesson_progress lp join public.crew_journey_assignments a on a.id=lp.assignment_id join public.crew_lessons l on l.id=lp.lesson_id where a.employee_id=completed_employee and lp.status='completed' and l.title='Table Awareness' order by lp.completed_at desc nulls last limit 1;
  select lp.lesson_id into lesson_handover from public.crew_lesson_progress lp join public.crew_journey_assignments a on a.id=lp.assignment_id join public.crew_lessons l on l.id=lp.lesson_id where a.employee_id=completed_employee and lp.status='completed' and l.title='Handover' order by lp.completed_at desc nulls last limit 1;
  select lp.lesson_id into lesson_grooming from public.crew_lesson_progress lp join public.crew_journey_assignments a on a.id=lp.assignment_id join public.crew_lessons l on l.id=lp.lesson_id where a.employee_id=completed_employee and lp.status='completed' and l.title='Personal Grooming' order by lp.completed_at desc nulls last limit 1;
  select lp.lesson_id into lesson_clean from public.crew_lesson_progress lp join public.crew_journey_assignments a on a.id=lp.assignment_id join public.crew_lessons l on l.id=lp.lesson_id where a.employee_id=completed_employee and lp.status='completed' and l.title='Workstation Cleanliness' order by lp.completed_at desc nulls last limit 1;
  select lp.lesson_id into lesson_open from public.crew_lesson_progress lp join public.crew_journey_assignments a on a.id=lp.assignment_id join public.crew_lessons l on l.id=lp.lesson_id where a.employee_id=completed_employee and lp.status='completed' and l.title='Opening Readiness' order by lp.completed_at desc nulls last limit 1;
  select lp.lesson_id into lesson_close from public.crew_lesson_progress lp join public.crew_journey_assignments a on a.id=lp.assignment_id join public.crew_lessons l on l.id=lp.lesson_id where a.employee_id=completed_employee and lp.status='completed' and l.title='Closing Responsibilities' order by lp.completed_at desc nulls last limit 1;
  select q.id into quiz_greeting from public.crew_quizzes q join public.crew_lessons l on l.id=q.lesson_id where l.title='First 5 Seconds' and q.status='published' limit 1;
  select q.id into quiz_orders from public.crew_quizzes q join public.crew_lessons l on l.id=q.lesson_id where l.title='Taking an Accurate Order' and q.status='published' limit 1;
  select sa.sop_version_id into sop_welcome from public.crew_sop_acknowledgements sa join public.crew_sop_versions v on v.id=sa.sop_version_id join public.crew_sops s on s.id=v.sop_id where sa.employee_id=completed_employee and s.outlet_id=outlet and s.title='Welcome & Goodbye Standard' and v.status='published' order by sa.acknowledged_at desc limit 1;
  select sa.sop_version_id into sop_grooming from public.crew_sop_acknowledgements sa join public.crew_sop_versions v on v.id=sa.sop_version_id join public.crew_sops s on s.id=v.sop_id where sa.employee_id=completed_employee and s.outlet_id=outlet and s.title='Personal Grooming Standard' and v.status='published' order by sa.acknowledged_at desc limit 1;
  select sa.sop_version_id into sop_clean from public.crew_sop_acknowledgements sa join public.crew_sop_versions v on v.id=sa.sop_version_id join public.crew_sops s on s.id=v.sop_id where sa.employee_id=completed_employee and s.outlet_id=outlet and s.title='Workstation Cleanliness' and v.status='published' order by sa.acknowledged_at desc limit 1;
  if module_greeting is null or module_orders is null or lesson_table is null or sop_welcome is null then raise exception 'Published QA Learning evidence is incomplete.'; end if;

  perform set_config('request.jwt.claims',jsonb_build_object('sub',qa_admin,'role','authenticated')::text,true);
  execute 'set local role authenticated';

  if not exists(select 1 from public.crew_skills where outlet_id=outlet and name='Customer Greeting') then
    v_skill_id:=public.crew_growth_save_skill(jsonb_build_object('outlet_id',outlet,'name','Customer Greeting','category','Service','description','Create a warm first impression and a consistent farewell.','status','active','certification_method','learning_and_review','positions',jsonb_build_array('Service Crew'),'outlets',jsonb_build_array(outlet),'requirements',jsonb_build_array(jsonb_build_object('type','module','reference_id',module_greeting,'label','Customer Arrival & Greeting completed','required',true),jsonb_build_object('type','sop','reference_id',sop_welcome,'label','Welcome & Goodbye Standard acknowledged','required',true),jsonb_build_object('type','quiz','reference_id',quiz_greeting,'label','Greeting Basics passed','required',true),jsonb_build_object('type','practical','label','Customer Greeting Practical Review','required',true,'config',jsonb_build_object('items',jsonb_build_array('Welcome within 5 seconds','Proper greeting','Eye contact & smile','Offer assistance','Thank You / Goodbye'))))));
  else select id into v_skill_id from public.crew_skills where outlet_id=outlet and name='Customer Greeting'; end if;
  if not exists(select 1 from public.crew_practical_assessments where employee_id=completed_employee and crew_practical_assessments.skill_id=v_skill_id) then perform public.crew_growth_submit_assessment(completed_employee,v_skill_id,'pass','[{"label":"Greeting standard","rating":"meets_standard"}]'::jsonb,'Growth QA evidence'); end if;
  if not exists(select 1 from public.crew_skill_certifications where employee_id=completed_employee and crew_skill_certifications.skill_id=v_skill_id and status='certified') then perform public.crew_growth_certify(completed_employee,v_skill_id,'Growth QA certification'); end if;

  if not exists(select 1 from public.crew_skills where outlet_id=outlet and name='Taking Orders') then
    perform public.crew_growth_save_skill(jsonb_build_object('outlet_id',outlet,'name','Taking Orders','category','Service','description','Take and confirm guest orders accurately.','status','active','certification_method','learning_and_review','positions',jsonb_build_array('Service Crew'),'outlets',jsonb_build_array(outlet),'requirements',jsonb_build_array(jsonb_build_object('type','module','reference_id',module_orders,'label','Taking Orders module completed','required',true),jsonb_build_object('type','quiz','reference_id',quiz_orders,'label','Accurate Order Check passed','required',true),jsonb_build_object('type','practical','label','Taking Orders Practical Review','required',true))));
  end if;
  select id into v_skill_id from public.crew_skills where outlet_id=outlet and name='Table Service';
  if v_skill_id is null then
    v_skill_id:=public.crew_growth_save_skill(jsonb_build_object('outlet_id',outlet,'name','Table Service','category','Service','description','Serve safely and maintain table awareness.','status','active','certification_method','learning_and_review','positions',jsonb_build_array('Service Crew'),'outlets',jsonb_build_array(outlet),'requirements',jsonb_build_array(jsonb_build_object('type','lesson','reference_id',lesson_table,'label','Table Awareness lesson completed','required',true),jsonb_build_object('type','lesson','reference_id',lesson_handover,'label','Handover lesson completed','required',true),jsonb_build_object('type','practical','label','Table Service Practical Review','required',true))));
  elsif not exists(select 1 from public.crew_skill_requirements where skill_id=v_skill_id and reference_id=lesson_handover) then
    v_skill_id:=public.crew_growth_save_skill(jsonb_build_object('id',v_skill_id,'outlet_id',outlet,'name','Table Service','category','Service','description','Serve safely and maintain table awareness.','status','active','certification_method','learning_and_review','positions',jsonb_build_array('Service Crew'),'outlets',jsonb_build_array(outlet),'requirements',jsonb_build_array(jsonb_build_object('type','lesson','reference_id',lesson_table,'label','Table Awareness lesson completed','required',true),jsonb_build_object('type','lesson','reference_id',lesson_handover,'label','Handover lesson completed','required',true),jsonb_build_object('type','practical','label','Table Service Practical Review','required',true))));
  end if;
  if not exists(select 1 from public.crew_practical_assessments where employee_id=progress_employee and crew_practical_assessments.skill_id=v_skill_id) then perform public.crew_growth_submit_assessment(progress_employee,v_skill_id,'pass','[{"label":"Table service sequence","rating":"meets_standard"}]'::jsonb,'Growth QA in-progress evidence'); end if;

  if not exists(select 1 from public.crew_skills where outlet_id=outlet and name='Personal Grooming') then
    v_skill_id:=public.crew_growth_save_skill(jsonb_build_object('outlet_id',outlet,'name','Personal Grooming','category','Service','description','Maintain the approved personal presentation standard.','status','active','certification_method','learning_and_review','positions',jsonb_build_array('Service Crew'),'outlets',jsonb_build_array(outlet),'requirements',jsonb_build_array(jsonb_build_object('type','lesson','reference_id',lesson_grooming,'label','Personal Grooming lesson completed','required',true),jsonb_build_object('type','sop','reference_id',sop_grooming,'label','Personal Grooming Standard acknowledged','required',true),jsonb_build_object('type','practical','label','Grooming Review','required',true))));
  else select id into v_skill_id from public.crew_skills where outlet_id=outlet and name='Personal Grooming'; end if;
  if not exists(select 1 from public.crew_practical_assessments where employee_id=completed_employee and crew_practical_assessments.skill_id=v_skill_id) then perform public.crew_growth_submit_assessment(completed_employee,v_skill_id,'pass','[{"label":"Grooming standard","rating":"meets_standard"}]'::jsonb,'Growth QA evidence'); end if;
  if not exists(select 1 from public.crew_skill_certifications where employee_id=completed_employee and crew_skill_certifications.skill_id=v_skill_id and status='certified') then perform public.crew_growth_certify(completed_employee,v_skill_id,'Growth QA certification'); end if;

  if not exists(select 1 from public.crew_skills where outlet_id=outlet and name='Workstation Cleanliness') then perform public.crew_growth_save_skill(jsonb_build_object('outlet_id',outlet,'name','Workstation Cleanliness','category','Cleaning','description','Keep the assigned area clean and service-ready.','status','active','certification_method','learning_and_review','positions',jsonb_build_array('Service Crew'),'outlets',jsonb_build_array(outlet),'requirements',jsonb_build_array(jsonb_build_object('type','lesson','reference_id',lesson_clean,'label','Workstation Cleanliness lesson completed','required',true),jsonb_build_object('type','sop','reference_id',sop_clean,'label','Workstation Cleanliness SOP acknowledged','required',true),jsonb_build_object('type','practical','label','Cleanliness Practical Review','required',true)))); end if;
  if not exists(select 1 from public.crew_skills where outlet_id=outlet and name='Opening Readiness') then perform public.crew_growth_save_skill(jsonb_build_object('outlet_id',outlet,'name','Opening Readiness','category','Opening & Closing','description','Prepare the outlet safely before service.','status','active','certification_method','learning_and_review','positions',jsonb_build_array('Service Crew'),'outlets',jsonb_build_array(outlet),'requirements',jsonb_build_array(jsonb_build_object('type','lesson','reference_id',lesson_open,'label','Opening Readiness lesson completed','required',true),jsonb_build_object('type','practical','label','Opening Practical Review','required',true)))); end if;
  if not exists(select 1 from public.crew_skills where outlet_id=outlet and name='Closing Responsibilities') then perform public.crew_growth_save_skill(jsonb_build_object('outlet_id',outlet,'name','Closing Responsibilities','category','Opening & Closing','description','Close and hand over assigned areas responsibly.','status','active','certification_method','learning_and_review','positions',jsonb_build_array('Service Crew'),'outlets',jsonb_build_array(outlet),'requirements',jsonb_build_array(jsonb_build_object('type','lesson','reference_id',lesson_close,'label','Closing Responsibilities lesson completed','required',true),jsonb_build_object('type','practical','label','Closing Practical Review','required',true)))); end if;
  if not exists(select 1 from public.crew_skills where outlet_id=outlet and name='Cash Handling') then perform public.crew_growth_save_skill(jsonb_build_object('outlet_id',outlet,'name','Cash Handling','category','Cashier','description','Handle payments and cash securely.','status','active','certification_method','manual','validity_months',12,'positions',jsonb_build_array('Cashier'),'outlets',jsonb_build_array(outlet),'requirements',jsonb_build_array(jsonb_build_object('type','manual','label','Manager Cash Handling Certification','required',true)))); end if;

  execute 'reset role';
end $$;

commit;
