import { useEffect, useState } from "react";
import PageHeader from "../../components/layout/PageHeader.jsx";
import Card from "../../components/ui/Card.jsx";
import Badge from "../../components/ui/Badge.jsx";
import Modal from "../../components/feedback/Modal.jsx";
import AdminSegmentedControl from "../../components/forms/AdminSegmentedControl.jsx";
import AdminFormField from "../../components/forms/AdminFormField.jsx";
import { recruitmentService } from "./recruitmentService.js";

const initialOpening = { title: "", position_id: "", outlet_id: "", workplace: "", legal_entity_id: "", description: "", status: "draft", config: { required_topics: ["Relevant experience", "Availability"], scenario_briefs: [], language_guidance: "Use the candidate's preferred EN, BM or Chinese naturally, including code-switching.", target_minutes: 20, max_minutes: 30, candidate_instructions: "Please find a quiet place with a stable connection.", interview_instructions: "Ask natural follow-ups and cover each required topic with concrete examples." } };
const fieldClass = "control w-full";
const titleFor = (opening) => opening?.title || "Opening";

function OpeningForm({ opening, data, busy, onSave, onClose }) {
  const [draft, setDraft] = useState(() => structuredClone(opening || initialOpening));
  const [error, setError] = useState("");
  const patch = (key, value) => setDraft((current) => ({ ...current, [key]: value }));
  const patchConfig = (key, value) => setDraft((current) => ({ ...current, config: { ...current.config, [key]: value } }));
  const workplaceValue = draft.outlet_id || draft.workplace;
  async function submit() {
    setError("");
    try { await onSave({ ...draft, outlet_id: data.outlets.some((row) => row.id === workplaceValue) ? workplaceValue : null, workplace: data.outlets.some((row) => row.id === workplaceValue) ? "" : workplaceValue }); onClose(); }
    catch (cause) { setError(cause.message || "Unable to save opening."); }
  }
  return <Modal title={opening ? "Edit opening" : "New opening"} description="Interview topics describe evidence to collect; the AI will choose its questions conversationally." size="xl" onClose={onClose} footer={<><button type="button" className="btn-secondary" onClick={onClose}>Cancel</button><button type="button" className="btn-primary" disabled={busy} onClick={submit}>Save opening</button></>}>
    <div className="grid gap-4 md:grid-cols-2">
      <AdminFormField label="Job-facing title" required><input className={fieldClass} value={draft.title} onChange={(e) => patch("title", e.target.value)} /></AdminFormField>
      <AdminFormField label="Canonical position" required><select className={fieldClass} value={draft.position_id} onChange={(e) => patch("position_id", e.target.value)}><option value="">Select position</option>{data.positions.map((row) => <option key={row.id} value={row.id}>{row.name}</option>)}</select></AdminFormField>
      <AdminFormField label="Workplace" required><select className={fieldClass} value={workplaceValue} onChange={(e) => { patch("outlet_id", e.target.value); patch("workplace", e.target.value); }}><option value="">Select workplace</option>{data.outlets.map((row) => <option key={row.id} value={row.id}>{row.name}</option>)}<option value="Factory">Factory</option><option value="Management">Management</option></select></AdminFormField>
      <AdminFormField label="Legal employer" required><select className={fieldClass} value={draft.legal_entity_id} onChange={(e) => patch("legal_entity_id", e.target.value)}><option value="">Select legal entity</option>{data.legal_entities.map((row) => <option key={row.id} value={row.id}>{row.name}</option>)}</select></AdminFormField>
      <AdminFormField label="Status"><select className={fieldClass} value={draft.status} onChange={(e) => patch("status", e.target.value)}><option value="draft">Draft</option><option value="open">Open</option><option value="closed">Closed</option></select></AdminFormField>
      <AdminFormField label="Description"><input className={fieldClass} value={draft.description} onChange={(e) => patch("description", e.target.value)} /></AdminFormField>
      <AdminFormField label="Required topics" helper="One evidence target per line. Not a question script." className="md:col-span-2"><textarea className={`${fieldClass} min-h-28`} value={(draft.config.required_topics || []).join("\n")} onChange={(e) => patchConfig("required_topics", e.target.value.split("\n").map((x) => x.trim()).filter(Boolean))} /></AdminFormField>
      <AdminFormField label="Scenario briefs" helper="One scenario brief per line." className="md:col-span-2"><textarea className={`${fieldClass} min-h-24`} value={(draft.config.scenario_briefs || []).join("\n")} onChange={(e) => patchConfig("scenario_briefs", e.target.value.split("\n").map((x) => x.trim()).filter(Boolean))} /></AdminFormField>
      <AdminFormField label="Language guidance" className="md:col-span-2"><textarea className={fieldClass} value={draft.config.language_guidance} onChange={(e) => patchConfig("language_guidance", e.target.value)} /></AdminFormField>
      <AdminFormField label="Target minutes"><input type="number" min="5" max="90" className={fieldClass} value={draft.config.target_minutes} onChange={(e) => patchConfig("target_minutes", Number(e.target.value))} /></AdminFormField>
      <AdminFormField label="Maximum minutes"><input type="number" min="5" max="120" className={fieldClass} value={draft.config.max_minutes} onChange={(e) => patchConfig("max_minutes", Number(e.target.value))} /></AdminFormField>
      <AdminFormField label="Candidate instructions" className="md:col-span-2"><textarea className={fieldClass} value={draft.config.candidate_instructions} onChange={(e) => patchConfig("candidate_instructions", e.target.value)} /></AdminFormField>
      <AdminFormField label="Interview instructions" className="md:col-span-2"><textarea className={`${fieldClass} min-h-24`} value={draft.config.interview_instructions} onChange={(e) => patchConfig("interview_instructions", e.target.value)} /></AdminFormField>
    </div>{error ? <p role="alert" className="mt-4 text-red-700">{error}</p> : null}
  </Modal>;
}

export default function RecruitmentPage({ auth }) {
  const [data, setData] = useState(null);
  const [tab, setTab] = useState("openings");
  const [formOpening, setFormOpening] = useState(undefined);
  const [applicationForm, setApplicationForm] = useState(false);
  const [selectedOpening, setSelectedOpening] = useState("");
  const [selectedApplicant, setSelectedApplicant] = useState("");
  const [applicantQuery, setApplicantQuery] = useState("");
  const [applicantResults, setApplicantResults] = useState([]);
  const [page, setPage] = useState(1);
  const [applicant, setApplicant] = useState({ full_name: "", contact: "", email: "" });
  const [invitation, setInvitation] = useState("");
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const canManage = auth?.hasPermission?.("recruitment.manage") || auth?.permissions?.includes?.("recruitment.manage");
  async function load(targetPage = page) { setError(""); try { setData(await recruitmentService.adminData(targetPage)); } catch (cause) { setError(cause.message || "Unable to load Recruitment."); } }
  useEffect(() => { load(page); }, [page]);
  useEffect(() => { if (!applicationForm || applicantQuery.trim().length < 2) { setApplicantResults([]); return; } let active = true; const timer = setTimeout(() => recruitmentService.findApplicants(applicantQuery.trim()).then((rows) => { if (active) setApplicantResults(rows); }).catch(() => { if (active) setApplicantResults([]); }), 250); return () => { active = false; clearTimeout(timer); }; }, [applicationForm, applicantQuery]);
  async function mutate(action) { setBusy(true); setError(""); try { const result = await action(); await load(); return result; } catch (cause) { setError(cause.message || "Action failed."); throw cause; } finally { setBusy(false); } }
  async function register(e) { e.preventDefault(); try { await mutate(() => recruitmentService.registerApplication(selectedOpening, applicant, selectedApplicant || null)); setApplicationForm(false); setPage(1); setTab("applications"); } catch { /* shown above */ } }
  async function issue(row) { try { const token = await mutate(() => recruitmentService.issueInvitation(row.id, new Date(Date.now() + 7 * 86400000).toISOString())); const origin = import.meta.env.VITE_INTERVIEW_WEB_APP_HOSTNAME ? `https://${import.meta.env.VITE_INTERVIEW_WEB_APP_HOSTNAME}` : ["os.feedx.my", "feedx-os.vercel.app"].includes(window.location.hostname) ? "https://interview.feedx.my" : window.location.origin; setInvitation(`${origin}/i/${token}`); } catch { /* shown above */ } }
  return <div className="space-y-5"><PageHeader section="People" title="Recruitment" description="Manage job openings, applicants and interview invitations." primaryActions={canManage ? <><button className="btn-secondary" type="button" onClick={() => setApplicationForm(true)}>Register application</button><button className="btn-primary" type="button" onClick={() => setFormOpening(null)}>New opening</button></> : null} />
    <AdminSegmentedControl value={tab} onChange={setTab} label="Recruitment view" options={[{ value: "openings", label: "Openings" }, { value: "applications", label: "Applicants / Applications" }, { value: "interviews", label: "Interviews" }]} />
    {error ? <p role="alert" className="rounded-xl border border-red-200 bg-red-50 p-3 text-red-800">{error}</p> : null}
    {!data ? <Card title="Loading Recruitment"><p className="p-4">Loading…</p></Card> : tab === "openings" ? <Card title="Job openings"><div className="divide-y divide-border">{data.openings.length ? data.openings.map((row) => <div key={row.id} className="flex flex-wrap items-center justify-between gap-3 p-4"><div><strong>{titleFor(row)}</strong><p className="text-sm text-text-secondary">{row.workplace} · {data.legal_entities.find((x) => x.id === row.legal_entity_id)?.name || "Legal entity"} · Interview config v{row.config_version}</p></div><div className="flex items-center gap-2"><Badge tone={row.status === "open" ? "success" : "neutral"}>{row.status}</Badge>{canManage ? <button className="btn-secondary" type="button" onClick={() => setFormOpening(row)}>Edit</button> : null}</div></div>) : <p className="p-4 text-text-secondary">No job openings yet.</p>}</div></Card> : <Card title={tab === "applications" ? "Applicants and applications" : "Interview invitations and readiness"}><div className="divide-y divide-border">{data.applications.length ? data.applications.map((row) => <div key={row.id} className="flex flex-wrap items-center justify-between gap-3 p-4"><div><strong>{row.name}</strong><p className="text-sm text-text-secondary">{row.opening_title} · {tab === "applications" ? row.contact : row.attempt_status || "Not invited"}</p>{tab === "interviews" && row.expires_at ? <p className="text-xs text-text-muted">Expires {new Date(row.expires_at).toLocaleString()} {row.revoked_at ? "· Revoked" : ""}</p> : null}</div><div className="flex items-center gap-2"><Badge tone={row.attempt_status === "ready" ? "success" : "neutral"}>{row.status}</Badge>{canManage ? <><button type="button" className="btn-secondary" disabled={busy} onClick={() => issue(row)}>Issue link</button>{row.issued_at && !row.revoked_at ? <button type="button" className="btn-secondary" disabled={busy} onClick={() => mutate(() => recruitmentService.revokeInvitation(row.id)).catch(() => {})}>Revoke</button> : null}</> : null}</div></div>) : <p className="p-4 text-text-secondary">No applications on this page.</p>}</div><div className="flex items-center justify-between border-t border-border p-4 text-sm"><span>Page {data.page} · {data.applications_total} applications</span><div className="flex gap-2"><button className="btn-secondary" type="button" disabled={page <= 1} onClick={() => setPage((value) => value - 1)}>Previous</button><button className="btn-secondary" type="button" disabled={page * data.page_size >= data.applications_total} onClick={() => setPage((value) => value + 1)}>Next</button></div></div></Card>}
    {formOpening !== undefined && data ? <OpeningForm opening={formOpening} data={data} busy={busy} onSave={(opening) => mutate(() => recruitmentService.saveOpening(opening))} onClose={() => setFormOpening(undefined)} /> : null}
    {applicationForm && data ? <Modal title="Register application" onClose={() => setApplicationForm(false)} size="md" footer={<><button type="button" className="btn-secondary" onClick={() => setApplicationForm(false)}>Cancel</button><button type="submit" form="recruitment-application-form" className="btn-primary" disabled={busy}>Register</button></>}><form id="recruitment-application-form" onSubmit={register} className="grid gap-4"><AdminFormField label="Open opening" required><select required className={fieldClass} value={selectedOpening} onChange={(e) => setSelectedOpening(e.target.value)}><option value="">Select opening</option>{data.openings.filter((x) => x.status === "open").map((x) => <option key={x.id} value={x.id}>{x.title}</option>)}</select></AdminFormField><AdminFormField label="Find existing applicant" helper="Search by name or contact number; leave empty to register a new applicant."><input className={fieldClass} value={applicantQuery} onChange={(e) => { setApplicantQuery(e.target.value); setSelectedApplicant(""); }} /></AdminFormField>{applicantResults.length ? <AdminFormField label="Matching applicant"><select className={fieldClass} value={selectedApplicant} onChange={(e) => setSelectedApplicant(e.target.value)}><option value="">Register new applicant</option>{applicantResults.map((x) => <option key={x.id} value={x.id}>{x.name} · {x.contact}</option>)}</select></AdminFormField> : null}{!selectedApplicant ? <><AdminFormField label="Full name" required><input required className={fieldClass} value={applicant.full_name} onChange={(e) => setApplicant({ ...applicant, full_name: e.target.value })} /></AdminFormField><AdminFormField label="Contact number" required><input required className={fieldClass} value={applicant.contact} onChange={(e) => setApplicant({ ...applicant, contact: e.target.value })} /></AdminFormField><AdminFormField label="Email (optional)"><input type="email" className={fieldClass} value={applicant.email} onChange={(e) => setApplicant({ ...applicant, email: e.target.value })} /></AdminFormField></> : null}</form></Modal> : null}
    {invitation ? <Modal title="Interview invitation" description="Copy this link now. For security, the full token is not stored and cannot be retrieved later." onClose={() => setInvitation("")} footer={<button className="btn-primary" type="button" onClick={() => navigator.clipboard.writeText(invitation)}>Copy link</button>}><p className="break-all rounded-lg bg-surface-muted p-3 text-sm">{invitation}</p></Modal> : null}
  </div>;
}
