import { describe, it, expect, vi, afterEach } from "vitest";
import { render, screen, waitFor, fireEvent, cleanup } from "@testing-library/react";
import { validateReport, explicitRequirements } from "../../../supabase/functions/recruitment-report/report.ts";
import { reviewAreas } from "./reviewIntelligence.js";
import Review from "./RecruitmentEvidenceReview.jsx";
const service = vi.hoisted(() => ({ managerEvidence: vi.fn(), decide: vi.fn() }));
vi.mock("./recruitmentService.js", () => ({ recruitmentService: service }));
const turns = [
  { id: 330, turn_number: 14, speaker: "candidate", transcript: "平日只能上午至下午工作，周末整天都可以。", elapsed_end_ms: 90000 },
  { id: 334, turn_number: 18, speaker: "candidate", transcript: "我不能上平日晚上十点半的关店班。", elapsed_end_ms: 120000 },
  { id: 333, turn_number: 17, speaker: "ai", transcript: "10点半收工", elapsed_end_ms: 110000 },
];
const claim = (text, ids) => ({ text, kind: ids.length ? "candidate_stated" : "unresolved", turn_ids: ids });
const source = { attempt: { status: "partial", recording_state: "partial" }, config: { required_topics: ["Shift Flexibility"], scenario_briefs: [], opening_requirements: { weekend_required: true, closing_shift: "Closing shifts required around 10:30 PM", preferred_start: "Immediate start preferred" } }, turns, topics: [{ topic_index: 0, topic: "Shift Flexibility", state: "covered", evidence_turn_id: 334 }], units: [], annotations: [], gaps: [] };
const raw = () => ({ candidate_snapshot: [claim("Weekdays: morning/afternoon; weekends: all day.", [330,334])], topics: [{ index: 0, state: "covered", finding: claim("Weekday morning/afternoon availability and weekend all-day availability are established.", [330,334]) }], scenarios: [], follow_up: [claim("Confirm preferred start date.", [])], opening_requirements: [{ key: "weekend_required", state: "meets", finding: claim("Available all day on Saturday and Sunday.", [330]) }, { key: "closing_shift", state: "does_not_meet", finding: claim("Cannot work weekday late closing shifts; availability is morning to afternoon.", [330,334]) }, { key: "preferred_start", state: "unclear", finding: claim("Start date not established.", []) }] });
const report = () => ({ id: "report", status: "ready", version: 3, created_at: "2026-10-05T07:00:00Z", source_snapshot: source, body: validateReport(raw(), source, "recruitment-report-v3") });
const data = () => ({ attempt: { id: "attempt", status: "partial", recording_state: "partial" }, application: { decision_state: "review", opening_title_snapshot: "Service Crew", workplace_snapshot: "Happiness Kopitiam" }, candidate: { full_name: "Acceptance tester" }, attempts: [], reports: [report()], topics: source.topics, turns, scenarios: [], units: [], events: [], annotations: [], decisions: [], can_manage: true, can_hire: true, launch_ready: true, opening_requirements: source.config.opening_requirements, interview_profile: { name: "Service Crew", version: 1 }, coverage_findings: [ { id: "a", topic_index: 0, state: "partial", evidence_turn_id: 330, reason: "Historical partial", created_at: "2026-10-05T06:00:00Z" }, { id: "b", topic_index: 0, state: "covered", evidence_turn_id: 334, reason: "Latest coverage", created_at: "2026-10-05T06:05:00Z" } ] });
afterEach(cleanup);
describe("Requirement fit remains separate from evidence coverage", () => {
  it("preserves Covered while closing fit Does not meet with Chinese citations", () => { const result=report().body; expect(result.topics[0].state).toBe("covered"); expect(result.opening_requirements[1]).toMatchObject({state:"does_not_meet",finding:{evidence:[{turn_id:330},{turn_id:334}]}}); expect(result.opening_requirements[2].state).toBe("unclear"); });
  it.each([{ids:[333]}, {ids:[999]}, {ids:[]}])("rejects missing/AI/foreign citations for fit %j", ({ids}) => { const body=raw(); body.opening_requirements[1].finding=claim("Cannot close",ids); expect(()=>validateReport(body,source,"recruitment-report-v3")).toThrow(); });
  it("rejects omitted or invented requirements",()=>{const body=raw();body.opening_requirements.pop();expect(()=>validateReport(body,source,"recruitment-report-v3")).toThrow("requirements incomplete");body.opening_requirements.push({key:"salary",state:"meets",finding:claim("Salary",[330])});expect(()=>validateReport(body,source,"recruitment-report-v3")).toThrow();});
  it("does not infer requirements from coverage or false/empty configuration",()=>expect(explicitRequirements({opening_requirements:{weekend_required:false,closing_shift:" "}})).toEqual([]));
  it("uses canonical coverage even if report model returns another state",()=>{const body=raw();body.topics[0].state="partial";expect(validateReport(body,source,"recruitment-report-v3").topics[0].state).toBe("covered");});
  it("consolidates each area while retaining history and unique supporting turns",()=>{const d=data();const rows=reviewAreas(d,d.reports[0]);expect(rows).toHaveLength(1);expect(rows[0].history).toHaveLength(2);expect(rows[0].evidenceIds).toEqual([330,334]);expect(d.coverage_findings).toHaveLength(2);});
  it("counts current support separately from superseded citations without a report",()=>{const d=data();expect(reviewAreas(d,null)[0].evidenceIds).toEqual([334]);expect(reviewAreas(d,null)[0].history).toHaveLength(2);});
  it("does not mix future evidence into an older report snapshot",()=>{const d=data();d.coverage_findings.push({...d.coverage_findings[1],id:"future",created_at:"2026-10-06T00:00:00Z"});expect(reviewAreas(d,d.reports[0])[0].history).toHaveLength(2);});
});
describe("Manager review progressive disclosure",()=>{
  it("shows compact fit/coverage, expands Chinese citation into transcript, never decides automatically",async()=>{const d=data(); service.managerEvidence.mockResolvedValue(d);const scroll=vi.fn();Element.prototype.scrollIntoView=scroll;render(<Review application={{id:"application",name:"Tester"}} onClose={()=>{}}/>);await waitFor(()=>expect(screen.getByText("Opening Requirements")).toBeTruthy());fireEvent.click(screen.getByRole("tab",{name:"Job Fit"}));expect(screen.getByText("Does not meet")).toBeTruthy();fireEvent.click(screen.getByRole("tab",{name:"Interview Evidence"}));expect(screen.getByText("Covered")).toBeTruthy();const transcript=screen.getByText("Transcript · 3 turns").closest("details");expect(transcript.open).toBe(false);expect(screen.getByText("Historical partial").closest("details").open).toBe(false);fireEvent.click(screen.getByRole("button",{name:"View transcript · Turn 18"}));expect(transcript.open).toBe(true);await waitFor(()=>expect(scroll).toHaveBeenCalled());expect(service.decide).not.toHaveBeenCalled();expect(screen.queryByText(/candidate score|recommended hire/i)).toBeNull();});
});

it("shows unscored historical areas separately from fit and evidence",async()=>{service.managerEvidence.mockResolvedValue(data());render(<Review application={{id:"application",name:"Tester"}} onClose={()=>{}}/>);await screen.findByRole("tab",{name:"Assessment"});fireEvent.click(screen.getByRole("tab",{name:"Assessment"}));expect(screen.getByText(/Historical evidence has not been scored/)).toBeTruthy();expect(screen.getByText("No rubric in this version")).toBeTruthy();expect(screen.getByRole("tab",{name:"Assessment"}).getAttribute("aria-selected")).toBe("true");expect(screen.getByText("Opening Requirements").closest("section").hidden).toBe(true);});
it("renders trusted rubric results with criterion/source drilldown, never calculates a total",async()=>{const d=data();d.reports[0].source_snapshot={...source,assessment_plan:{profile_id:"future",version:3,areas:[{index:0,name:"Shift Flexibility",rubric:{levels:[1,2,3,4].map(level=>({level,criteria:`Role-specific criterion ${level}`}))}}]}};d.reports[0].body.assessments=[{index:0,area:"Shift Flexibility",status:"assessed",level:2,criterion:"Role-specific criterion 2",finding:{text:"States concrete shift constraints.",kind:"interpretation",evidence:[{turn_id:330,turn_number:18,recordings:[]}]}}];service.managerEvidence.mockResolvedValue(d);render(<Review application={{id:"application",name:"Tester"}} onClose={()=>{}}/>);await screen.findByRole("tab",{name:"Assessment"});fireEvent.click(screen.getByRole("tab",{name:"Assessment"}));expect(screen.getByText("Criterion: Role-specific criterion 2")).toBeTruthy();expect(screen.queryByText(/overall candidate score|recommended hire/i)).toBeNull();fireEvent.click(screen.getAllByRole("button",{name:"Turn 18"})[0]);expect(screen.getByRole("tab",{name:"Interview Evidence"}).getAttribute("aria-selected")).toBe("true");expect(service.decide).not.toHaveBeenCalled();});
