import { useCallback, useEffect, useMemo, useState } from "react";
import { Plus } from "lucide-react";
import PageHeader from "../../../components/layout/PageHeader.jsx";
import Modal from "../../../components/feedback/Modal.jsx";
import { FactoryDataSurface, FactoryTable } from "../components/FactoryDataDisplay.jsx";
import FactoryFilterBar from "../components/FactoryFilterBar.jsx";
import FactoryRowActions from "../components/FactoryRowActions.jsx";
import FactoryStatusBadge from "../components/FactoryStatusBadge.jsx";
import FactoryViewTabs from "../components/FactoryViewTabs.jsx";
import { Field, inputClass } from "../components/FactoryBulkSelectionModal.jsx";
import FeedXDatePicker from "../components/FeedXDatePicker.jsx";
import SearchableSelect from "../components/SearchableSelect.jsx";
import useFactoryMasterData from "../hooks/useFactoryMasterData.js";
import useFactoryPermissions from "../hooks/useFactoryPermissions.js";
import { factoryService } from "../../../services/factoryService.js";
import { formatFactoryDate, malaysiaBusinessDateInput } from "../utils/factoryDates.js";

const frequencies = [1, 3, 6, 12];
const tones = { current: "success", due_soon: "warning", due: "warning", overdue: "danger", failed: "danger", inactive: "neutral", awaiting_verification: "info", verified: "success" };
const tabs = [{ value: "schedule", label: "Schedule" }, { value: "records", label: "Records" }, { value: "setup", label: "Setup" }];
const label = (value) => String(value || "").replaceAll("_", " ").replace(/\b\w/g, (char) => char.toUpperCase());
const emptyRequirement = () => ({ equipment_id: "", calibration_type: "Temperature", interval_months: 1, effective_from: malaysiaBusinessDateInput(), status: "active" });
const emptyRecord = (row) => ({ scheduled_due_date: row.next_due, calibrated_date: malaysiaBusinessDateInput(), result: "pass", provider_name: "", reference_no: "", notes: "" });

function matches(row, filters) {
  const text = `${row.equipment_name || row.equipment_snapshot?.equipment_name || ""} ${row.equipment_code || row.equipment_snapshot?.equipment_code || ""} ${row.calibration_type || ""}`.toLowerCase();
  return (!filters.query || text.includes(filters.query.toLowerCase())) && (!filters.status || row.status === filters.status) && (!filters.location || (row.location_name || row.equipment_snapshot?.location_name) === filters.location);
}

function CalibrationFilters({ filters, locations, setFilters }) {
  const active = [filters.query && { key: "search", label: "Search", value: filters.query, onRemove: () => setFilters((current) => ({ ...current, query: "" })) }, filters.status && { key: "status", label: "Status", value: label(filters.status), onRemove: () => setFilters((current) => ({ ...current, status: "" })) }, filters.location && { key: "location", label: "Location", value: filters.location, onRemove: () => setFilters((current) => ({ ...current, location: "" })) }].filter(Boolean);
  return <FactoryFilterBar activeFilters={active} onClear={() => setFilters({ query: "", status: "", location: "" })} moreFilters={<Field label="Location"><SearchableSelect value={filters.location} options={[{ value: "", label: "All" }, ...locations.map((value) => ({ value, label: value }))]} placeholder="All" onChange={(location) => setFilters((current) => ({ ...current, location }))} /></Field>}>
    <Field label="Search"><input className={inputClass()} value={filters.query} placeholder="Equipment or calibration type" onChange={(event) => setFilters((current) => ({ ...current, query: event.target.value }))} /></Field>
    <Field label="Status"><SearchableSelect value={filters.status} options={[{ value: "", label: "All" }, ...Object.keys(tones).map((value) => ({ value, label: label(value) }))]} placeholder="All" onChange={(status) => setFilters((current) => ({ ...current, status }))} /></Field>
  </FactoryFilterBar>;
}

export default function FactoryMestiCalibrationPage({ onNotify, onRefreshFactoryData }) {
  const master = useFactoryMasterData();
  const { can } = useFactoryPermissions();
  const [tab, setTab] = useState("schedule");
  const [schedule, setSchedule] = useState([]);
  const [records, setRecords] = useState([]);
  const [requirement, setRequirement] = useState(null);
  const [recording, setRecording] = useState(null);
  const [recordForm, setRecordForm] = useState(null);
  const [filters, setFilters] = useState({ query: "", status: "", location: "" });
  const [error, setError] = useState("");
  const requirements = master.mestiCalibrationRequirements || [];
  const equipment = master.equipment || [];
  const canManage = can("factory_mesti_calibration.manage");
  const locations = useMemo(() => [...new Set([...schedule.map((row) => row.location_name), ...records.map((row) => row.equipment_snapshot?.location_name)].filter(Boolean))].sort(), [records, schedule]);
  const visibleSchedule = useMemo(() => schedule.filter((row) => matches(row, filters)), [filters, schedule]);
  const visibleRecords = useMemo(() => records.filter((row) => matches(row, filters)), [filters, records]);
  const load = useCallback(async () => { try { setError(""); const [nextSchedule, nextRecords] = await Promise.all([factoryService.listMestiCalibrationSchedule(), factoryService.listMestiCalibrationRecords()]); setSchedule(nextSchedule); setRecords(nextRecords); } catch (reason) { setError(reason.message || "Unable to load Calibration."); } }, []);
  useEffect(() => { load(); }, [load]);
  async function saveRequirement(event) { event.preventDefault(); try { const saved = await factoryService.saveMestiCalibrationRequirement(requirement); setRequirement(null); await onRefreshFactoryData?.({ silent: true }); await load(); onNotify?.({ title: saved?.version_created ? "Calibration requirement version created" : "Calibration requirement unchanged", tone: "success" }); } catch (reason) { setError(reason.message); } }
  async function record(event) { event.preventDefault(); try { await factoryService.recordMestiCalibration(recording.id, recordForm); setRecording(null); await load(); onNotify?.({ title: "Calibration recorded", tone: "success" }); } catch (reason) { setError(reason.message); } }
  async function verify(id) { try { await factoryService.verifyMestiCalibration(id); await load(); onNotify?.({ title: "Calibration verified", tone: "success" }); } catch (reason) { setError(reason.message); } }
  const scheduleColumns = [{ key: "equipment", label: "Equipment", render: (row) => <div><div className="font-semibold text-text-primary">{row.equipment_name}</div><div className="text-xs text-text-secondary">{row.equipment_code}</div></div> }, { key: "category", label: "Category", render: (row) => row.category_name || "—" }, { key: "location", label: "Location", render: (row) => row.location_name || "—" }, { key: "type", label: "Calibration Type", render: (row) => row.calibration_type }, { key: "frequency", label: "Frequency", render: (row) => `${row.interval_months} month${row.interval_months === 1 ? "" : "s"}` }, { key: "last", label: "Last Valid Calibration", render: (row) => formatFactoryDate(row.last_calibration) }, { key: "next", label: "Next Due", render: (row) => formatFactoryDate(row.next_due) }, { key: "status", label: "Status", render: (row) => <FactoryStatusBadge tone={tones[row.status] || "neutral"}>{label(row.status)}</FactoryStatusBadge> }, { key: "actions", label: "Actions", align: "right", render: (row) => <FactoryRowActions primaryAction={{ label: "Record Calibration", disabled: row.status === "inactive" || (!can("factory_mesti_calibration.complete") && !canManage), onClick: () => { setRecording(row); setRecordForm(emptyRecord(row)); } }} /> }];
  const recordColumns = [{ key: "date", label: "Calibrated Date", render: (row) => formatFactoryDate(row.calibrated_date) }, { key: "equipment", label: "Equipment", render: (row) => row.equipment_snapshot?.equipment_name || "—" }, { key: "type", label: "Calibration Type", render: (row) => requirements.find((item) => item.id === row.requirement_id)?.calibration_type || "Historical requirement" }, { key: "due", label: "Scheduled Due", render: (row) => formatFactoryDate(row.scheduled_due_date) }, { key: "result", label: "Result", render: (row) => <FactoryStatusBadge tone={row.result === "pass" ? "success" : "danger"}>{label(row.result)}</FactoryStatusBadge> }, { key: "performed", label: "Recorded By", render: (row) => row.recorded_by_name || "—" }, { key: "provider", label: "Provider", render: (row) => row.provider_name || "—" }, { key: "verification", label: "Verification", render: (row) => <FactoryStatusBadge tone={tones[row.status]}>{label(row.status)}</FactoryStatusBadge> }, { key: "actions", label: "Actions", align: "right", render: (row) => <FactoryRowActions primaryAction={row.status === "awaiting_verification" ? { label: "Verify", disabled: !can("factory_mesti_calibration.review") && !canManage, onClick: () => verify(row.id) } : null} /> }];
  const setupColumns = [{ key: "equipment", label: "Equipment", render: (row) => row.equipment?.name || "—" }, { key: "type", label: "Calibration Type", render: (row) => row.calibration_type }, { key: "frequency", label: "Frequency", render: (row) => `${row.interval_months} months` }, { key: "effective", label: "Effective From", render: (row) => formatFactoryDate(row.effective_from) }, { key: "version", label: "Version", render: (row) => `Version ${row.version_no}` }, { key: "status", label: "Status", render: (row) => <FactoryStatusBadge tone={row.status === "active" ? "success" : "neutral"}>{label(row.status)}</FactoryStatusBadge> }, { key: "actions", label: "Actions", align: "right", render: (row) => <FactoryRowActions directSingleSecondary secondaryActions={canManage ? [{ label: "Edit", onClick: () => setRequirement({ ...row }) }] : []} /> }];
  return <div className="space-y-5"><PageHeader section="MeSTI" title="Calibration Schedule & Record" description="Periodic equipment calibration, verification, and immutable history." />
    <FactoryViewTabs value={tab} onChange={setTab} tabs={tabs} />
    {error ? <div role="alert" className="rounded-lg border border-rose-200 bg-rose-50 p-3 text-sm font-semibold text-rose-700">{error}</div> : null}
    {tab !== "setup" ? <CalibrationFilters filters={filters} locations={locations} setFilters={setFilters} /> : null}
    {tab === "schedule" ? <FactoryDataSurface><FactoryTable rows={visibleSchedule} columns={scheduleColumns} emptyTitle="No Calibration Requirements" emptyDescription="Create an active requirement in Setup." /></FactoryDataSurface> : null}
    {tab === "records" ? <FactoryDataSurface><FactoryTable rows={visibleRecords} columns={recordColumns} emptyTitle="No Calibration Records" emptyDescription="Recorded calibration evidence remains after requirement changes." /></FactoryDataSurface> : null}
    {tab === "setup" ? <><div className="flex justify-end">{canManage ? <button className="btn-primary" type="button" onClick={() => setRequirement(emptyRequirement())}><Plus size={15} /> Create Requirement</button> : null}</div><FactoryDataSurface><FactoryTable rows={requirements} columns={setupColumns} emptyTitle="No Calibration Requirements" /></FactoryDataSurface></> : null}
    {requirement ? <Modal title={requirement.id ? "Edit Calibration Requirement" : "Create Calibration Requirement"} onClose={() => setRequirement(null)} footer={<><button className="btn-secondary" type="button" onClick={() => setRequirement(null)}>Cancel</button><button className="btn-primary" type="submit" form="calibration-requirement">Save Requirement</button></>}><form id="calibration-requirement" className="grid gap-3" onSubmit={saveRequirement}><Field label="Equipment"><SearchableSelect value={requirement.equipment_id} options={equipment.filter((item) => item.status === "active" || item.id === requirement.equipment_id).map((item) => ({ value: item.id, label: `${item.name} · ${item.location?.location_name || "No location"}` }))} onChange={(equipment_id) => setRequirement((current) => ({ ...current, equipment_id }))} /></Field><Field label="Calibration Type"><input className={inputClass()} value={requirement.calibration_type} onChange={(event) => setRequirement((current) => ({ ...current, calibration_type: event.target.value }))} /></Field><Field label="Interval"><SearchableSelect value={String(requirement.interval_months)} options={frequencies.map((value) => ({ value: String(value), label: `${value} month${value === 1 ? "" : "s"}` }))} onChange={(value) => setRequirement((current) => ({ ...current, interval_months: Number(value) }))} /></Field><Field label="Effective From"><FeedXDatePicker value={requirement.effective_from} onChange={(effective_from) => setRequirement((current) => ({ ...current, effective_from }))} /></Field><Field label="Status"><SearchableSelect value={requirement.status} options={[{ value: "active", label: "Active" }, { value: "inactive", label: "Inactive" }]} onChange={(status) => setRequirement((current) => ({ ...current, status }))} /></Field></form></Modal> : null}
    {recording ? <Modal title="Record Calibration" description={`${recording.equipment_name} · ${recording.calibration_type}`} onClose={() => setRecording(null)} footer={<><button className="btn-secondary" type="button" onClick={() => setRecording(null)}>Cancel</button><button className="btn-primary" type="submit" form="calibration-record">Submit Record</button></>}><form id="calibration-record" className="grid gap-3" onSubmit={record}><Field label="Scheduled Due"><input className={inputClass()} readOnly value={recordForm.scheduled_due_date} /></Field><Field label="Calibrated Date"><FeedXDatePicker value={recordForm.calibrated_date} onChange={(calibrated_date) => setRecordForm((current) => ({ ...current, calibrated_date }))} /></Field><Field label="Result"><SearchableSelect value={recordForm.result} options={[{ value: "pass", label: "Pass" }, { value: "fail", label: "Fail" }]} onChange={(result) => setRecordForm((current) => ({ ...current, result }))} /></Field><Field label="Provider"><input className={inputClass()} value={recordForm.provider_name} onChange={(event) => setRecordForm((current) => ({ ...current, provider_name: event.target.value }))} /></Field><Field label="Reference No"><input className={inputClass()} value={recordForm.reference_no} onChange={(event) => setRecordForm((current) => ({ ...current, reference_no: event.target.value }))} /></Field><Field label="Notes"><textarea className={inputClass()} value={recordForm.notes} onChange={(event) => setRecordForm((current) => ({ ...current, notes: event.target.value }))} /></Field></form></Modal> : null}
  </div>;
}
