import { useCallback, useEffect, useMemo, useState } from "react";
import { Plus, RefreshCw } from "lucide-react";
import Badge from "../../../components/ui/Badge.jsx";
import Modal from "../../../components/feedback/Modal.jsx";
import PageHeader from "../../../components/layout/PageHeader.jsx";
import { factoryService } from "../../../services/factoryService.js";
import { FactoryTable } from "../components/FactoryDataDisplay.jsx";
import FactoryFilterBar from "../components/FactoryFilterBar.jsx";
import FactoryRowAction from "../components/FactoryRowAction.jsx";
import { Field, inputClass } from "../components/FactoryBulkSelectionModal.jsx";
import FeedXDatePicker from "../components/FeedXDatePicker.jsx";
import SearchableSelect from "../components/SearchableSelect.jsx";
import useFactoryPermissions from "../hooks/useFactoryPermissions.js";
import { formatFactoryDateTime } from "../utils/factoryDates.js";

const symptoms = [
  ["diarrhea", "Diarrhea"], ["fever", "Fever"], ["jaundice", "Jaundice"], ["visible_skin_infection", "Visible skin infection"], ["ear_nose_eye_infection", "Ear / nose / eye infection"], ["other", "Other"],
];
const label = (value) => String(value || "").replaceAll("_", " ").replace(/\b\w/g, (character) => character.toUpperCase());
const healthTone = (value) => value === "fit_for_work" || value === "cleared" ? "success" : "warning";
const emptyForm = (type) => ({ declaration_type: type, employee_id: "", symptoms: [], notes: "", visitor_name: "", company: "", purpose: "", host: "", contact: "", entry_decision: "allowed", request_id: crypto.randomUUID() });

function SymptomPicker({ value, onChange }) {
  const selected = Array.isArray(value) ? value : [];
  return <div className="flex flex-wrap gap-2"><button className={`rounded-md border px-3 py-2 text-sm font-semibold ${selected.length === 0 ? "border-primary bg-primary text-white" : "border-border text-text-secondary"}`} type="button" onClick={() => onChange([])}>No symptoms</button>{symptoms.map(([key, name]) => <label key={key} className={`flex cursor-pointer items-center gap-2 rounded-md border px-3 py-2 text-sm font-semibold ${selected.includes(key) ? "border-amber-400 bg-amber-50 text-amber-900" : "border-border text-text-secondary"}`}><input type="checkbox" checked={selected.includes(key)} onChange={() => onChange(selected.includes(key) ? selected.filter((item) => item !== key) : [...selected, key])} />{name}</label>)}</div>;
}

function detailRow(labelText, value) { return <div key={labelText} className="border-b border-border py-2.5 last:border-0"><div className="text-[11px] font-semibold uppercase tracking-[0.08em] text-text-muted">{labelText}</div><div className="mt-0.5 text-sm font-semibold text-text-primary">{value || "—"}</div></div>; }

export default function FactoryMestiHealthDeclarationPage({ onNotify }) {
  const { can } = useFactoryPermissions();
  const [tab, setTab] = useState("employee");
  const [records, setRecords] = useState([]);
  const [employees, setEmployees] = useState([]);
  const [form, setForm] = useState(null);
  const [detail, setDetail] = useState(null);
  const [action, setAction] = useState(null);
  const [filters, setFilters] = useState({ dateFrom: "", dateTo: "", type: "", healthStatus: "", symptom: "", search: "" });
  const [error, setError] = useState("");
  const canRecord = can("factory_mesti_health_declaration.create") || can("factory_mesti_health_declaration.manage");
  const canManage = can("factory_mesti_health_declaration.manage");
  const load = useCallback(async () => {
    try {
      setError("");
      const [nextRecords, options] = await Promise.all([factoryService.listMestiHealthDeclarations(filters), factoryService.listMestiHealthDeclarationOptions()]);
      setRecords(nextRecords); setEmployees(options.employees || []);
    } catch (loadError) { setError(loadError.message || "Unable to load Health Declarations."); }
  }, [filters]);
  useEffect(() => { load(); }, [load]);
  const employeeOptions = useMemo(() => employees.map((employee) => ({ value: employee.id, label: [employee.name, employee.position].filter(Boolean).join(" · ") })), [employees]);
  async function submit(event) { event.preventDefault(); try { await factoryService.submitMestiHealthDeclaration(form); setForm(null); await load(); onNotify?.({ title: "Health declaration recorded", tone: "success" }); } catch (submitError) { setError(submitError.message); } }
  async function saveAction(event) { event.preventDefault(); try { await factoryService.actionMestiHealthDeclaration(action.id, action.work_action, action.action_notes); setAction(null); await load(); onNotify?.({ title: "Employee action recorded", tone: "success" }); } catch (actionError) { setError(actionError.message); } }
  const columns = [{ key: "declared_at", label: "Date / Time", render: (row) => formatFactoryDateTime(row.declared_at) }, { key: "person", label: "Person", render: (row) => <div><div className="font-semibold">{row.declaration_type === "employee" ? row.employee_snapshot?.employee_name : row.visitor_name}</div><div className="text-xs text-text-secondary">{row.declaration_type === "employee" ? row.employee_snapshot?.position : row.visitor_company}</div></div> }, { key: "type", label: "Type", render: (row) => label(row.declaration_type) }, { key: "health", label: "Health Status", render: (row) => <Badge tone={healthTone(row.health_status)}>{label(row.health_status)}</Badge> }, { key: "symptoms", label: "Symptoms", render: (row) => row.symptoms?.length ? row.symptoms.map(label).join(", ") : "No symptoms" }, { key: "decision", label: "Action / Entry Decision", render: (row) => row.work_action ? label(row.work_action) : row.entry_decision ? label(row.entry_decision) : "—" }, { key: "recorded", label: "Recorded By", render: (row) => row.recorded_by_name || "—" }, { key: "actions", label: "Actions", align: "right", render: (row) => <div className="flex justify-end gap-2"><FactoryRowAction onClick={(event) => { event.stopPropagation(); setDetail(row); }} />{row.declaration_type === "employee" && row.health_status === "health_issue_declared" && !row.work_action ? <button className="btn-primary px-3 py-1.5 text-xs" type="button" disabled={!canManage} onClick={(event) => { event.stopPropagation(); setAction({ ...row, work_action: "not_allowed_to_work", action_notes: "" }); }}>Action</button> : null}</div> }];
  const formIsEmployee = form?.declaration_type === "employee";
  return <div className="space-y-4"><PageHeader section="MeSTI" title="Health Declaration" description="Employee and visitor health declaration evidence." actions={<button className="btn-secondary" type="button" onClick={load}><RefreshCw size={15} /> Refresh</button>} />
    <div className="flex gap-2 rounded-lg border border-border bg-white p-2">{["employee", "visitor", "records"].map((item) => <button key={item} className={`rounded-md px-4 py-2 text-sm font-bold ${tab === item ? "bg-primary text-white" : "text-text-secondary"}`} type="button" onClick={() => setTab(item)}>{label(item)}</button>)}</div>
    {error ? <div role="alert" className="rounded-lg border border-rose-200 bg-rose-50 p-3 text-sm font-semibold text-rose-700">{error}</div> : null}
    {tab !== "records" ? <div className="rounded-lg border border-border bg-white p-5"><div className="flex items-center justify-between"><div><div className="text-base font-bold text-text-primary">{tab === "employee" ? "Employee Health Report" : "Visitor Health Declaration"}</div><div className="mt-1 text-sm text-text-secondary">{tab === "employee" ? "Record the employee's original declaration before any supervisor action." : "Record visitor health status and entry decision."}</div></div><button className="btn-primary" disabled={!canRecord} type="button" onClick={() => setForm(emptyForm(tab))}><Plus size={15} /> New Declaration</button></div></div> : null}
    {tab === "records" ? <><FactoryFilterBar
      activeFilters={[
        filters.dateFrom && { key: "date-from", label: "Date", value: filters.dateFrom, onRemove: () => setFilters((current) => ({ ...current, dateFrom: "" })) },
        filters.dateTo && { key: "date-to", label: "To", value: filters.dateTo, onRemove: () => setFilters((current) => ({ ...current, dateTo: "" })) },
        filters.type && { key: "type", label: "Type", value: label(filters.type), onRemove: () => setFilters((current) => ({ ...current, type: "" })) },
        filters.healthStatus && { key: "health", label: "Health", value: label(filters.healthStatus), onRemove: () => setFilters((current) => ({ ...current, healthStatus: "" })) },
        filters.symptom && { key: "symptom", label: "Symptom", value: label(filters.symptom), onRemove: () => setFilters((current) => ({ ...current, symptom: "" })) },
        filters.search && { key: "search", label: "Search", value: filters.search, onRemove: () => setFilters((current) => ({ ...current, search: "" })) },
      ].filter(Boolean)}
      onClear={() => setFilters({ dateFrom: "", dateTo: "", type: "", healthStatus: "", symptom: "", search: "" })}
      moreFilters={<><Field label="Health Status"><SearchableSelect value={filters.healthStatus} options={[{value:"",label:"All"},{value:"fit_for_work",label:"Fit for Work"},{value:"cleared",label:"Cleared"},{value:"health_issue_declared",label:"Health Issue Declared"}]} onChange={(healthStatus) => setFilters((current) => ({ ...current, healthStatus }))} /></Field><Field label="Symptom"><SearchableSelect value={filters.symptom} options={[{value:"",label:"All"},...symptoms.map(([value,labelText]) => ({value,label:labelText}))]} onChange={(symptom) => setFilters((current) => ({ ...current, symptom }))} /></Field></>}
    ><Field label="Date"><FeedXDatePicker value={filters.dateFrom} placeholder="From" onChange={(dateFrom) => setFilters((current) => ({ ...current, dateFrom }))} /></Field><Field label="To"><FeedXDatePicker value={filters.dateTo} placeholder="To" onChange={(dateTo) => setFilters((current) => ({ ...current, dateTo }))} /></Field><Field label="Type"><SearchableSelect value={filters.type} options={[{ value:"",label:"All" },{value:"employee",label:"Employee"},{value:"visitor",label:"Visitor"}]} onChange={(type) => setFilters((current) => ({ ...current, type }))} /></Field><Field label="Search"><input className={inputClass()} placeholder="Employee, visitor or company" value={filters.search} onChange={(event) => setFilters((current) => ({...current,search:event.target.value}))} /></Field></FactoryFilterBar><div className="overflow-hidden rounded-lg border border-border bg-white"><FactoryTable rows={records} columns={columns} onRowClick={setDetail} emptyTitle="No Health Declarations" emptyDescription="Submitted employee and visitor declarations appear here." /></div></> : null}
    {form ? <Modal title={formIsEmployee ? "Employee Health Declaration" : "Visitor Health Declaration"} onClose={() => setForm(null)} footer={<><button className="btn-secondary" type="button" onClick={() => setForm(null)}>Cancel</button><button className="btn-primary" type="submit" form="health-declaration">Submit Declaration</button></>}><form id="health-declaration" className="grid gap-4" onSubmit={submit}>{formIsEmployee ? <Field label="Employee"><SearchableSelect value={form.employee_id} options={employeeOptions} placeholder="Select employee" onChange={(employee_id) => setForm((current) => ({ ...current, employee_id }))} /></Field> : <><Field label="Visitor Name"><input required className={inputClass()} value={form.visitor_name} onChange={(event) => setForm((current) => ({...current,visitor_name:event.target.value}))} /></Field><div className="grid gap-3 md:grid-cols-2"><Field label="Company"><input className={inputClass()} value={form.company} onChange={(event) => setForm((current) => ({...current,company:event.target.value}))} /></Field><Field label="Purpose"><input className={inputClass()} value={form.purpose} onChange={(event) => setForm((current) => ({...current,purpose:event.target.value}))} /></Field><Field label="Host / Person Visited"><input className={inputClass()} value={form.host} onChange={(event) => setForm((current) => ({...current,host:event.target.value}))} /></Field><Field label="Contact"><input className={inputClass()} value={form.contact} onChange={(event) => setForm((current) => ({...current,contact:event.target.value}))} /></Field></div></>}<Field label="Symptoms"><SymptomPicker value={form.symptoms} onChange={(selected) => setForm((current) => ({...current,symptoms:selected,entry_decision:selected.length ? "entry_restricted" : "allowed"}))} /></Field>{!formIsEmployee ? <Field label="Entry Decision"><SearchableSelect value={form.entry_decision} options={[{value:"allowed",label:"Allowed"},{value:"entry_restricted",label:"Entry Restricted"}]} onChange={(entry_decision) => setForm((current) => ({...current,entry_decision}))} /></Field> : null}<Field label="Notes"><textarea className={inputClass()} value={form.notes} onChange={(event) => setForm((current) => ({...current,notes:event.target.value}))} /></Field></form></Modal> : null}
    {action ? <Modal title="Employee Preventive Action" onClose={() => setAction(null)} footer={<><button className="btn-secondary" type="button" onClick={() => setAction(null)}>Cancel</button><button className="btn-primary" type="submit" form="health-action">Record Action</button></>}><form id="health-action" className="grid gap-3" onSubmit={saveAction}><Field label="Work Action"><SearchableSelect value={action.work_action} options={[{value:"not_allowed_to_work",label:"Not Allowed to Work"},{value:"leave_granted",label:"Leave Granted"},{value:"other_preventive_action",label:"Other Preventive Action"}]} onChange={(work_action) => setAction((current) => ({...current,work_action}))} /></Field><Field label="Action Notes"><textarea className={inputClass()} value={action.action_notes} onChange={(event) => setAction((current) => ({...current,action_notes:event.target.value}))} /></Field></form></Modal> : null}
    {detail ? <Modal title="Health Declaration Record" description="Immutable declaration evidence and any subsequent action." onClose={() => setDetail(null)}><div className="grid gap-x-6 md:grid-cols-2">{detailRow("Declaration Type",label(detail.declaration_type))}{detailRow("Person",detail.declaration_type === "employee" ? detail.employee_snapshot?.employee_name : detail.visitor_name)}{detailRow("Employee / Company",detail.declaration_type === "employee" ? detail.employee_snapshot?.position : detail.visitor_company)}{detailRow("Declared",formatFactoryDateTime(detail.declared_at))}{detailRow("Symptoms",detail.symptoms?.length ? detail.symptoms.map(label).join(", ") : "No symptoms")}{detailRow("Health Status",label(detail.health_status))}{detailRow("Notes",detail.notes)}{detailRow(detail.declaration_type === "employee" ? "Work Action" : "Entry Decision",label(detail.work_action || detail.entry_decision))}{detailRow("Action Notes",detail.action_notes)}{detailRow("Recorded By",detail.recorded_by_name)}{detailRow("Reviewed / Actioned By",detail.reviewed_by_name)}{detailRow("Reviewed / Actioned At",formatFactoryDateTime(detail.reviewed_at))}</div></Modal> : null}
  </div>;
}
