import { useMemo, useState } from "react";
import { CheckCircle2, Clock3, Tag, Truck } from "lucide-react";
import PageHeader from "../../../components/layout/PageHeader.jsx";
import Card from "../../../components/ui/Card.jsx";
import MetricCard from "../../../components/ui/MetricCard.jsx";
import FactoryPagination, { useFactoryClientPagination } from "../components/FactoryPagination.jsx";
import { FactoryTable } from "../components/FactoryDataDisplay.jsx";
import useFactoryMasterData from "../hooks/useFactoryMasterData.js";
import useFactoryNavigation from "../hooks/useFactoryNavigation.js";
import useFactoryPermissions from "../hooks/useFactoryPermissions.js";

export default function FactoryCustomersPage() {
  const { customers } = useFactoryMasterData(); const { can } = useFactoryPermissions(); const nav = useFactoryNavigation(); const [search, setSearch] = useState("");
  const rows = useMemo(() => customers.filter((customer) => `${customer.customer_name || ""} ${customer.customer_code || ""}`.toLowerCase().includes(search.toLowerCase())), [customers, search]);
  const pager = useFactoryClientPagination("customers", rows.length, 20, search); const active = customers.filter((customer) => customer.status === "active").length;
  return <div className="space-y-5"><PageHeader section="System" title="Customers" description="Manage Factory customers and destinations used by finished goods dispatch documents." actions={can("factory_customers.create") ? <button className="btn-primary" type="button" onClick={nav.openCreateCustomer}><Truck size={15} /> Create Customer</button> : null} /><div className="grid gap-3 md:grid-cols-4"><MetricCard icon={Truck} label="Total Customers" value={customers.length} helper="Active and archived" /><MetricCard icon={CheckCircle2} label="Active" value={active} helper="Available for dispatch" tone="success" /><MetricCard icon={Clock3} label="Archived" value={customers.length - active} helper="Historical customers" /><MetricCard icon={Tag} label="Customer Types" value={new Set(customers.map((customer) => customer.customer_type).filter(Boolean)).size} helper={`${customers.filter((customer) => customer.contact_person || customer.phone || customer.email).length} with contact details`} /></div><Card title="Factory Customer Master"><input className="field-input mb-4" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search customers" /><FactoryTable rows={rows.slice(pager.from, pager.to)} columns={[{ key: "customer", label: "Customer", render: (row) => <div><div className="font-bold">{row.customer_name || "—"}</div><div className="text-xs text-text-secondary">{row.customer_code || "—"}</div></div> }, { key: "type", label: "Type", render: (row) => row.customer_type || "—" }, { key: "status", label: "Status", render: (row) => row.status || "—" }, { key: "actions", label: "Actions", align: "right", render: (row) => <div className="flex justify-end gap-2">{can("factory_customers.edit") ? <button className="btn-secondary text-xs" type="button" onClick={() => nav.openEditCustomer(row)}>Edit</button> : null}{can("factory_customers.delete") && row.status !== "archived" ? <button className="btn-secondary text-xs" type="button" onClick={() => nav.archiveCustomer(row)}>Archive</button> : null}</div> }]} emptyTitle="No Factory customers" /><FactoryPagination page={pager.page} pageSize={pager.pageSize} total={rows.length} onPageChange={pager.setPage} onPageSizeChange={pager.setPageSize} /></Card></div>;
}
