import { useCallback, useEffect, useMemo, useState } from "react";
import { Check, Plus } from "lucide-react";
import PageHeader from "../../../components/layout/PageHeader.jsx";
import Modal from "../../../components/feedback/Modal.jsx";
import { factoryService } from "../../../services/factoryService.js";
import FactoryComplianceMatrix from "../components/FactoryComplianceMatrix.jsx";
import FactoryDailyToolbar, { FactoryDailyDateField } from "../components/FactoryDailyToolbar.jsx";
import { FactoryDataSurface, FactoryTable } from "../components/FactoryDataDisplay.jsx";
import FactoryOperationalGroup, { FactoryOperationalEvidence, FactoryOperationalRow } from "../components/FactoryOperationalGroup.jsx";
import FactoryRowAction from "../components/FactoryRowAction.jsx";
import FactoryRowActions from "../components/FactoryRowActions.jsx";
import FactoryStatusBadge from "../components/FactoryStatusBadge.jsx";
import FactoryMonthPicker from "../components/FactoryMonthPicker.jsx";
import FactoryViewTabs from "../components/FactoryViewTabs.jsx";
import FeedXDatePicker from "../components/FeedXDatePicker.jsx";
import { Field, inputClass } from "../components/FactoryBulkSelectionModal.jsx";
import SearchableSelect from "../components/SearchableSelect.jsx";
import useFactoryPermissions from "../hooks/useFactoryPermissions.js";
import { formatFactoryDate, formatFactoryDateTime, malaysiaBusinessDateInput } from "../utils/factoryDates.js";

const statusTone = { draft: "neutral", submitted: "warning", verified: "success" };
const label = (value) => String(value || "").replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase());
const currentMonth = () => malaysiaBusinessDateInput().slice(0, 7);
const monthDays = (month) => { const [year, zeroMonth] = month.split("-").map(Number); return Array.from({ length: new Date(year, zeroMonth, 0).getDate() }, (_, index) => `${month}-${String(index + 1).padStart(2, "0")}`); };
const detailRow = (name, value) => <div key={name} className="border-b border-border py-2.5 last:border-0"><div className="text-[11px] font-semibold uppercase tracking-[0.08em] text-text-muted">{name}</div><div className="mt-0.5 text-sm font-semibold text-text-primary">{value || "-"}</div></div>;

function EventDetail({ detail, onClose }) {
  if (!detail) return null;
  const events = detail.events || [];
  return <Modal title={`${detail.location_name || "Location"} disposal evidence`} description="Daily disposal events and session verification evidence." onClose={onClose} size="lg"><div className="grid gap-x-6 md:grid-cols-2">{detailRow("Required Count", detail.required_count)}{detailRow("Completed Count", detail.completed_count)}{detailRow("Session Status", label(detail.session_status || "draft"))}{detailRow("Submitted By", detail.submitted_by_name)}{detailRow("Submitted At", formatFactoryDateTime(detail.submitted_at))}{detailRow("Verified By", detail.verified_by_name)}{detailRow("Verified At", formatFactoryDateTime(detail.verified_at))}</div><div className="mt-4 border-t border-border pt-3"><div className="mb-2 text-xs font-bold uppercase tracking-[0.08em] text-text-muted">Disposal Events</div>{events.length ? events.map((event) => <div key={event.id} className="border-b border-border py-2 text-sm last:border-0"><span className="font-semibold">{formatFactoryDateTime(event.disposed_at)}</span><span className="text-text-secondary"> · {event.completed_by_name || "-"}</span>{event.remarks ? <div className="mt-1 text-text-secondary">{event.remarks}</div> : null}</div>) : <div className="text-sm text-text-secondary">No disposal events recorded.</div>}</div></Modal>;
}

function RequirementModal({ value, locations, onClose, onSave }) {
  const [form, setForm] = useState(value || { location_id: "", required_count: 1, effective_from: malaysiaBusinessDateInput(), status: "active" });
  return <Modal title={value ? "Edit Waste Disposal Requirement" : "New Waste Disposal Requirement"} onClose={onClose} footer={<><button type="button" className="btn-secondary" onClick={onClose}>Cancel</button><button form="waste-requirement" type="submit" className="btn-primary">Save Requirement</button></>}><form id="waste-requirement" className="grid gap-4" onSubmit={(event) => { event.preventDefault(); onSave(form); }}><Field label="Location"><SearchableSelect value={form.location_id} options={locations.map((location) => ({ value: location.id, label: location.location_name }))} placeholder="Select canonical Location" onChange={(location_id) => setForm((current) => ({ ...current, location_id }))} /></Field><Field label="Frequency"><div className="rounded-md border border-border bg-slate-50 px-3 py-2 text-sm font-semibold">Daily</div></Field><Field label="Required Times / Day"><input className={inputClass()} required min="1" type="number" value={form.required_count} onChange={(event) => setForm((current) => ({ ...current, required_count: event.target.value }))} /></Field><Field label="Effective From"><FeedXDatePicker value={form.effective_from} onChange={(effective_from) => setForm((current) => ({ ...current, effective_from }))} /></Field><Field label="Status"><SearchableSelect value={form.status} options={[{ value: "active", label: "Active" }, { value: "inactive", label: "Inactive" }]} onChange={(status) => setForm((current) => ({ ...current, status }))} /></Field></form></Modal>;
}

export default function FactoryMestiWasteDisposalPage({ auth, onNotify }) {
  const { can } = useFactoryPermissions();
  const [tab, setTab] = useState("daily"); const [date, setDate] = useState(malaysiaBusinessDateInput()); const [month, setMonth] = useState(currentMonth());
  const [daily, setDaily] = useState({ locations: [] }); const [monthly, setMonthly] = useState([]); const [requirements, setRequirements] = useState([]); const [locations, setLocations] = useState([]);
  const [detail, setDetail] = useState(null); const [eventForm, setEventForm] = useState(null); const [requirementForm, setRequirementForm] = useState(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  const session = daily.session; const draft = !session || session.status === "draft";
  const loadDaily = useCallback(async () => { setLoading(true); setError(""); try { setDaily(await factoryService.getMestiWasteDisposalDaily(date)); } catch (reason) { setError(reason.message || "Unable to load Waste Disposal Record."); } finally { setLoading(false); } }, [date]);
  const loadSetup = useCallback(async () => { setLoading(true); setError(""); try { const [nextRequirements, options] = await Promise.all([factoryService.listMestiWasteDisposalRequirements(), factoryService.listMestiWasteDisposalLocations()]); setRequirements(nextRequirements); setLocations(options); } catch (reason) { setError(reason.message || "Unable to load Waste Disposal setup."); } finally { setLoading(false); } }, []);
  const loadMonthly = useCallback(async () => { setLoading(true); setError(""); try { setMonthly(await factoryService.listMestiWasteDisposalMonthly(month)); } catch (reason) { setError(reason.message || "Unable to load monthly Waste Disposal Record."); } finally { setLoading(false); } }, [month]);
  useEffect(() => { if (tab === "daily") loadDaily(); if (tab === "monthly") loadMonthly(); if (tab === "setup") loadSetup(); }, [tab, loadDaily, loadMonthly, loadSetup]);
  const summary = useMemo(() => (daily.locations || []).reduce((total, location) => ({ locations: total.locations + 1, required: total.required + Number(location.required_count || 0), completed: total.completed + Number(location.completed_count || 0) }), { locations: 0, required: 0, completed: 0 }), [daily]);
  async function record(event) { try { await factoryService.recordMestiWasteDisposal(date, event); setEventForm(null); await loadDaily(); onNotify?.({ title: "Waste disposal recorded", tone: "success" }); } catch (reason) { setError(reason.message || "Unable to record disposal."); } }
  async function saveRequirement(value) { try { await factoryService.saveMestiWasteDisposalRequirement(value); setRequirementForm(null); await loadSetup(); onNotify?.({ title: "Waste disposal requirement saved", tone: "success" }); } catch (reason) { setError(reason.message || "Unable to save requirement."); } }
  async function submit() { try { await factoryService.submitMestiWasteDisposal(date); await loadDaily(); } catch (reason) { setError(reason.message || "Unable to submit daily disposal record."); } }
  async function verify() { try { await factoryService.verifyMestiWasteDisposal(date); await loadDaily(); } catch (reason) { setError(reason.message || "Unable to verify daily disposal record."); } }
  const setupColumns = [{ key: "location", label: "Location", render: (row) => row.location_name }, { key: "frequency", label: "Frequency", render: () => "Daily" }, { key: "required", label: "Required / Day", render: (row) => row.required_count }, { key: "effective", label: "Effective From", render: (row) => formatFactoryDate(row.effective_from) }, { key: "status", label: "Status", render: (row) => <FactoryStatusBadge tone={row.status === "active" ? "success" : "neutral"}>{label(row.status)}</FactoryStatusBadge> }, { key: "actions", label: "Actions", align: "right", render: (row) => <FactoryRowActions directSingleSecondary secondaryActions={[{ label: "Edit", onClick: () => setRequirementForm(row) }]} /> }];
  return <div className="space-y-5"><PageHeader section="MeSTI" title="Waste Disposal Record" description="Daily Factory Location waste disposal frequency evidence." />
    <FactoryViewTabs value={tab} onChange={setTab} tabs={[{ value: "daily", label: "Daily" }, { value: "monthly", label: "Monthly" }, { value: "setup", label: "Setup" }]} />
    {error ? <div role="alert" className="rounded-lg border border-rose-200 bg-rose-50 p-3 text-sm font-semibold text-rose-700">{error}</div> : null}
    {tab === "daily" ? <><div className="flex flex-wrap items-center gap-3 text-sm"><span className="font-bold">{summary.locations} Locations</span><span>{summary.required} Required</span><span className="text-emerald-700">{summary.completed} Completed</span><span className={summary.completed < summary.required ? "text-rose-700" : "text-text-secondary"}>{Math.max(summary.required - summary.completed, 0)} Pending</span><FactoryStatusBadge tone={statusTone[session?.status] || "neutral"}>{label(session?.status || "draft")}</FactoryStatusBadge>{draft ? <button className="btn-primary ml-auto" disabled={!summary.completed || !can("factory_mesti_waste_disposal.submit")} onClick={submit} type="button">Submit Daily Record</button> : null}{session?.status === "submitted" ? <button className="btn-primary ml-auto" disabled={!can("factory_mesti_waste_disposal.verify")} onClick={verify} type="button"><Check size={15} />Verify</button> : null}</div><FactoryDailyToolbar><FactoryDailyDateField><FeedXDatePicker value={date} onChange={setDate} /></FactoryDailyDateField></FactoryDailyToolbar>
      <FactoryDataSurface>{(daily.locations || []).map((location) => <FactoryOperationalGroup key={location.location_id} title={location.location_name} count={`${location.completed_count} / ${location.required_count} completed`}><FactoryOperationalRow primary={`Required ${location.required_count} time${location.required_count === 1 ? "" : "s"}`} evidence={<FactoryOperationalEvidence items={(location.events || []).map((event) => ({ key: event.id, label: `${formatFactoryDateTime(event.disposed_at)} · ${event.completed_by_name || "—"}` }))} />} status={<FactoryStatusBadge variant="emphasized" tone={location.completed_count >= location.required_count ? "success" : "warning"}>{location.completed_count >= location.required_count ? "Compliant" : "Pending"}</FactoryStatusBadge>} actions={<><FactoryRowAction label={`View ${location.location_name} details`} onClick={() => setDetail({ ...location, session_status: session?.status, submitted_by_name: session?.submitted_by_name, submitted_at: session?.submitted_at, verified_by_name: session?.verified_by_name, verified_at: session?.verified_at })} />{draft ? <button type="button" className="btn-secondary" disabled={!can("factory_mesti_waste_disposal.record")} onClick={() => setEventForm({ location_id: location.location_id, disposed_at: new Date().toISOString().slice(0, 16), remarks: "" })}>Record Disposal</button> : null}</>} /></FactoryOperationalGroup>)}</FactoryDataSurface></> : null}
    {tab === "monthly" ? <><FactoryDailyToolbar><div className="w-full sm:w-[170px]"><Field label="Month"><FactoryMonthPicker value={month} onChange={setMonth} /></Field></div></FactoryDailyToolbar><FactoryDataSurface><FactoryComplianceMatrix rows={monthly} days={monthDays(month)} rowKey={(row) => row.location_id} entityLabel="Location" frequencyLabel="Required / Day" renderEntity={(row) => row.location_name} renderFrequency={() => "Daily"} getCell={(row, day) => { const cell = row.days?.[day]; return cell ? { ...cell, status: cell.state === "verified_compliant" ? "verified" : cell.state === "incomplete" ? "missed" : "completed" } : null; }} cellLabel={(cell) => `${cell.completed_count}/${cell.required_count}`} cellTitle={(cell, row) => `${row.location_name}: ${cell.completed_count}/${cell.required_count}`} onCellClick={(cell, row) => setDetail({ ...cell, location_name: row.location_name })} empty={<div className="py-10 text-center text-sm font-semibold text-text-secondary">No active Location requirements for this month.</div>} /></FactoryDataSurface></> : null}
    {tab === "setup" ? <><div className="flex justify-end"><button type="button" className="btn-primary" disabled={!can("factory_mesti_waste_disposal.manage")} onClick={() => setRequirementForm({})}><Plus size={15} />Create Requirement</button></div><FactoryDataSurface><FactoryTable rows={requirements} columns={setupColumns} emptyTitle="No Waste Disposal Requirements" emptyDescription="Create an active Factory Location requirement." /></FactoryDataSurface></> : null}
    {loading ? <div className="py-6 text-center text-sm font-semibold text-text-secondary">Loading Waste Disposal Record...</div> : null}
    {eventForm ? <Modal title="Record Disposal" onClose={() => setEventForm(null)} footer={<><button className="btn-secondary" type="button" onClick={() => setEventForm(null)}>Cancel</button><button className="btn-primary" type="submit" form="waste-event">Record Disposal</button></>}><form id="waste-event" className="grid gap-4" onSubmit={(event) => { event.preventDefault(); record(eventForm); }}><Field label="Disposed At"><input className={inputClass()} type="datetime-local" value={eventForm.disposed_at} onChange={(event) => setEventForm((current) => ({ ...current, disposed_at: event.target.value }))} /></Field><Field label="Remarks"><textarea className={inputClass()} value={eventForm.remarks} onChange={(event) => setEventForm((current) => ({ ...current, remarks: event.target.value }))} /></Field></form></Modal> : null}
    {requirementForm ? <RequirementModal value={requirementForm.id ? requirementForm : null} locations={locations} onClose={() => setRequirementForm(null)} onSave={saveRequirement} /> : null}<EventDetail detail={detail} onClose={() => setDetail(null)} />
  </div>;
}
