create or replace function public.crew_tasks_today(p_token text,p_business_date date default timezone('Asia/Kuala_Lumpur',now())::date)
returns jsonb language plpgsql volatile security definer set search_path=public as $$
declare ctx jsonb; v_employee uuid; v_outlet uuid; v_role uuid; v_position text; tasks jsonb; legacy jsonb; attendance jsonb;
begin
 ctx:=public.crew_operations_employee_context(p_token); v_employee:=(ctx->>'employee_id')::uuid; v_outlet:=(ctx->>'outlet_id')::uuid; v_role:=nullif(ctx->>'role_id','')::uuid; v_position:=ctx->>'position';
 perform public.crew_operations_ensure_instances(v_outlet,p_business_date);
 select coalesce(jsonb_agg(jsonb_build_object('id',i.id,'source','instance','name',i.name,'task_type',i.task_type,'schedule_type',i.schedule_type,'priority',i.priority,'status',case when a.status='not_started' and i.available_until<now() then 'overdue' else a.status end,'available_from',i.available_from,'due_at',i.available_until,'completed_at',a.completed_at,'block_count',(select count(*) from public.crew_operation_instance_items x where x.instance_id=i.id),'completed_count',(select count(*) from public.crew_task_item_responses r join public.crew_operation_instance_items x on x.id=r.instance_item_id where x.instance_id=i.id and r.employee_id=v_employee and r.status not in ('not_checked')),'exception_count',(select count(*) from public.crew_task_item_responses r join public.crew_operation_instance_items x on x.id=r.instance_item_id where x.instance_id=i.id and r.employee_id=v_employee and r.status in ('exception','needs_attention'))) order by case i.priority when 'critical' then 1 when 'important' then 2 else 3 end,i.available_until,i.name),'[]'::jsonb) into tasks
 from public.crew_operation_instances i join public.crew_task_instance_assignees a on a.instance_id=i.id and a.employee_id=v_employee where i.outlet_id=v_outlet and i.business_date=p_business_date;
 select coalesce(jsonb_agg(jsonb_build_object('id',t.id,'source','legacy_daily','name',t.title,'description',t.description,'task_type','instruction','schedule_type','one_time','priority',case t.priority when 'high' then 'critical' else 'normal' end,'status',case when t.status='pending' and t.due_at<now() then 'overdue' else t.status end,'due_at',t.due_at,'sop_reference',t.sop_snapshot,'completed_at',t.completed_at) order by t.due_at nulls last,t.title),'[]'::jsonb) into legacy from public.crew_daily_tasks t where t.outlet_id=v_outlet and t.task_date=p_business_date and public.crew_operations_applicable(v_role,v_position,t.applicable_role_ids,t.applicable_positions);
 select jsonb_build_object('on_shift',exists(select 1 from public.crew_attendance_records a where a.employee_id=v_employee and a.outlet_id=v_outlet and a.status='open'),'clock_in_at',(select max(a.clock_in_at) from public.crew_attendance_records a where a.employee_id=v_employee and a.outlet_id=v_outlet and a.status='open')) into attendance;
 return jsonb_build_object('date',p_business_date,'outlet',jsonb_build_object('id',v_outlet,'name',(select name from public.outlets where id=v_outlet)),'employee',jsonb_build_object('id',v_employee,'name',ctx->>'employee_name','position',v_position),'attendance_context',attendance,'tasks',tasks||legacy);
end; $$;
revoke all on function public.crew_tasks_today(text,date) from public,anon,authenticated;
grant execute on function public.crew_tasks_today(text,date) to anon,authenticated;
