alter table public.crew_operation_template_items drop constraint crew_operation_template_items_block_type_check;
alter table public.crew_operation_template_items add constraint crew_operation_template_items_block_type_check
  check(block_type in ('text','checklist_item','key_point','image','sop_reference','yes_no','single_choice','number','temperature','short_text','health_rating','confirmation'));

create or replace function public.crew_tasks_save(p_outlet_id uuid,p_task jsonb)
returns uuid language plpgsql volatile security definer set search_path=public as $$
declare mapped jsonb; item jsonb; mapped_items jsonb:='[]'::jsonb; task_id uuid; v_operation text; employee_ids uuid[]; group_names text[];
begin
 if not public.current_user_has_permission('crew_operations.manage') or not public.current_user_can_access_outlet(p_outlet_id) then raise exception using errcode='42501',message='Task management is unavailable for this outlet.'; end if;
 if jsonb_typeof(p_task)<>'object' or char_length(btrim(coalesce(p_task->>'name','')))<2 or jsonb_typeof(p_task->'blocks')<>'array' or jsonb_array_length(p_task->'blocks')=0 then raise exception using errcode='22023',message='Task name and at least one content block are required.'; end if;
 if coalesce(p_task->>'task_type','') not in ('checklist','instruction','health_check','confirmation','sop_review') or coalesce(p_task->>'schedule_type','') not in ('one_time','recurring','shift_based') then raise exception using errcode='22023',message='Task type or schedule is invalid.'; end if;
 if coalesce(p_task->>'assignment_type','') not in ('all_crew','position','specific_crew','group') or coalesce(p_task->>'priority','') not in ('normal','important','critical') or coalesce(p_task->>'completion_rule','') not in ('any_assigned','every_assigned','one_for_team') then raise exception using errcode='22023',message='Task assignment, priority or completion rule is invalid.'; end if;
 if p_task->>'assignment_type'='position' and jsonb_array_length(coalesce(p_task->'applicable_positions','[]'::jsonb))=0 then raise exception using errcode='22023',message='Choose at least one position.'; end if;
 if p_task->>'assignment_type'='specific_crew' and jsonb_array_length(coalesce(p_task->'applicable_employee_ids','[]'::jsonb))=0 then raise exception using errcode='22023',message='Choose at least one Crew employee.'; end if;
 if p_task->>'assignment_type'='group' and jsonb_array_length(coalesce(p_task->'applicable_group_names','[]'::jsonb))=0 then raise exception using errcode='22023',message='Choose at least one Crew group.'; end if;
 if p_task->>'schedule_type'='recurring' and coalesce(p_task#>>'{schedule_config,frequency}','') not in ('every_day','specific_weekdays','weekly','monthly','custom_interval') then raise exception using errcode='22023',message='Recurring schedule is invalid.'; end if;
 if p_task#>>'{schedule_config,frequency}'='specific_weekdays' and jsonb_array_length(coalesce(p_task#>'{schedule_config,weekdays}','[]'::jsonb))=0 then raise exception using errcode='22023',message='Choose at least one weekday.'; end if;
 for item in select value from jsonb_array_elements(p_task->'blocks') loop
   if coalesce(item->>'block_type','') not in ('text','checklist_item','key_point','image','sop_reference','yes_no','single_choice','number','temperature','short_text','health_rating','confirmation') then raise exception using errcode='22023',message='Task content block type is invalid.'; end if;
   if item->>'block_type'='image' then raise exception using errcode='0A000',message='Photo content remains disabled until the Operations media store is available.'; end if;
   if item->>'block_type'='sop_reference' and nullif(item->>'sop_version_id','') is null then raise exception using errcode='22023',message='Choose a published SOP for every SOP Reference block.'; end if;
   if item->>'block_type'='single_choice' and jsonb_array_length(coalesce(item#>'{config,options}','[]'::jsonb))<2 then raise exception using errcode='22023',message='Single Choice needs at least two options.'; end if;
   if item->>'block_type' in ('number','temperature') and nullif(item#>>'{config,min}','') is not null and nullif(item#>>'{config,max}','') is not null and (item#>>'{config,min}')::numeric>(item#>>'{config,max}')::numeric then raise exception using errcode='22023',message='Measurement minimum cannot exceed maximum.'; end if;
   mapped_items:=mapped_items||jsonb_build_array(jsonb_build_object('title',coalesce(nullif(btrim(item->>'title'),''),initcap(replace(item->>'block_type','_',' '))),'description',item->>'description','is_required',coalesce((item->>'is_required')::boolean,item->>'block_type' not in ('text','key_point','sop_reference')),'evidence_requirement',coalesce(item->>'evidence_requirement','none'),'health_category',case when item->>'block_type'='health_rating' then coalesce(item->>'health_category','front_of_house') end,'sop_version_id',coalesce(item->>'sop_version_id',''),'block_type',item->>'block_type','block_config',coalesce(item->'config','{}'::jsonb)));
 end loop;
 v_operation:=case p_task->>'task_type' when 'health_check' then 'health' else 'daily' end;
 mapped:=jsonb_build_object('id',p_task->>'id','series_id',p_task->>'series_id','name',p_task->>'name','operation_type',v_operation,'effective_date',coalesce(p_task->>'effective_date',timezone('Asia/Kuala_Lumpur',now())::date::text),'available_from',coalesce(p_task->>'start_time',''),'available_until',coalesce(p_task->>'due_time',''),'applicable_positions',coalesce(p_task->'applicable_positions','[]'::jsonb),'applicable_role_ids','[]'::jsonb,'items',mapped_items);
 task_id:=public.crew_operations_save_template(p_outlet_id,mapped);
 select coalesce(array_agg(value::uuid),'{}') into employee_ids from jsonb_array_elements_text(coalesce(p_task->'applicable_employee_ids','[]'::jsonb));
 select coalesce(array_agg(value),'{}') into group_names from jsonb_array_elements_text(coalesce(p_task->'applicable_group_names','[]'::jsonb));
 if p_task->>'assignment_type'='specific_crew' and exists(select 1 from unnest(employee_ids) employee_id where not exists(select 1 from public.crew_access ca join public.employees e on e.id=ca.employee_id where ca.employee_id=employee_id and ca.primary_outlet_id=p_outlet_id and ca.access_state='active' and e.is_active and coalesce(e.employment_status,'active') not in ('resigned','terminated'))) then raise exception using errcode='22023',message='Specific Crew must belong to this outlet.'; end if;
 if p_task->>'assignment_type'='group' and exists(select 1 from unnest(group_names) group_name where lower(group_name) not in ('floor','kitchen','other')) then raise exception using errcode='22023',message='Crew group is invalid.'; end if;
 update public.crew_operation_templates set task_type=p_task->>'task_type',schedule_type=p_task->>'schedule_type',schedule_config=coalesce(p_task->'schedule_config','{}'::jsonb),assignment_type=coalesce(p_task->>'assignment_type','all_crew'),applicable_employee_ids=employee_ids,applicable_group_names=group_names,on_duty_only=coalesce((p_task->>'on_duty_only')::boolean,false),priority=coalesce(p_task->>'priority','normal'),completion_rule=coalesce(p_task->>'completion_rule','one_for_team'),allow_exception=coalesce((p_task->>'allow_exception')::boolean,true),exception_requires_reason=coalesce((p_task->>'exception_requires_reason')::boolean,true),manager_review_required=coalesce((p_task->>'manager_review_required')::boolean,false),allow_late_completion=coalesce((p_task->>'allow_late_completion')::boolean,true),updated_at=now() where id=task_id;
 update public.crew_operation_template_items i set block_type=x.block_type,block_config=x.config from (select (value->>'block_type') block_type,coalesce(value->'config','{}'::jsonb) config,(ordinality-1)::int sort_order from jsonb_array_elements(p_task->'blocks') with ordinality)x where i.template_id=task_id and i.sort_order=x.sort_order;
 return task_id;
end; $$;
revoke all on function public.crew_tasks_save(uuid,jsonb) from public,anon,authenticated;
grant execute on function public.crew_tasks_save(uuid,jsonb) to authenticated;
