-- Crew Journey Phase B: Learning Core. Uses employees.id as the sole Crew identity.

create table public.crew_journeys (
  id uuid primary key default gen_random_uuid(), name text not null, description text, journey_type text not null default 'onboarding' check (journey_type in ('onboarding','learning','refresher')),
  status text not null default 'draft' check (status in ('draft','published','archived')), version integer not null default 1 check (version > 0), estimated_minutes integer, sequential_modules boolean not null default false,
  outlet_id uuid references public.outlets(id), position text, created_by uuid references auth.users(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), published_at timestamptz
);
create table public.crew_journey_modules (id uuid primary key default gen_random_uuid(), journey_id uuid not null references public.crew_journeys(id) on delete cascade, title text not null, description text, sort_order integer not null, estimated_minutes integer, required boolean not null default true, status text not null default 'draft' check(status in ('draft','published','archived')), unique(journey_id, sort_order));
create table public.crew_lessons (id uuid primary key default gen_random_uuid(), module_id uuid not null references public.crew_journey_modules(id) on delete cascade, title text not null, sort_order integer not null, content_type text not null default 'lesson', required boolean not null default true, estimated_minutes integer, unique(module_id, sort_order));
create table public.crew_lesson_blocks (id uuid primary key default gen_random_uuid(), lesson_id uuid not null references public.crew_lessons(id) on delete cascade, block_type text not null check(block_type in ('intro','text','key_point','image','sop_reference','steps','scenario','quiz','acknowledgement','video')), payload jsonb not null default '{}'::jsonb, sort_order integer not null, unique(lesson_id, sort_order));
create table public.crew_journey_assignments (id uuid primary key default gen_random_uuid(), employee_id uuid not null references public.employees(id), journey_id uuid not null references public.crew_journeys(id), journey_version_assigned integer not null, assigned_at timestamptz not null default now(), assigned_by uuid references auth.users(id), due_at timestamptz, status text not null default 'not_started' check(status in ('not_started','in_progress','completed')), started_at timestamptz, completed_at timestamptz, unique(employee_id, journey_id, journey_version_assigned));
create table public.crew_lesson_progress (id uuid primary key default gen_random_uuid(), assignment_id uuid not null references public.crew_journey_assignments(id) on delete cascade, lesson_id uuid not null references public.crew_lessons(id), status text not null default 'not_started' check(status in ('not_started','in_progress','completed')), first_started_at timestamptz, last_activity_at timestamptz, completed_at timestamptz, unique(assignment_id, lesson_id));
create table public.crew_sops (id uuid primary key default gen_random_uuid(), title text not null, category text not null default 'Other', summary text, status text not null default 'draft' check(status in ('draft','published','archived')), current_version integer, outlet_id uuid references public.outlets(id), position text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.crew_sop_versions (id uuid primary key default gen_random_uuid(), sop_id uuid not null references public.crew_sops(id) on delete cascade, version integer not null, effective_date date, change_summary text, status text not null default 'draft' check(status in ('draft','published','archived')), require_acknowledgement boolean not null default false, published_at timestamptz, published_by uuid references auth.users(id), unique(sop_id, version));
create table public.crew_sop_sections (id uuid primary key default gen_random_uuid(), sop_version_id uuid not null references public.crew_sop_versions(id) on delete cascade, title text not null, body text, sort_order integer not null, key_point boolean not null default false, media_url text, unique(sop_version_id, sort_order));
create table public.crew_sop_acknowledgements (id uuid primary key default gen_random_uuid(), employee_id uuid not null references public.employees(id), sop_version_id uuid not null references public.crew_sop_versions(id), acknowledged_at timestamptz not null default now(), source text not null check(source in ('direct_library','journey','required_update')), unique(employee_id, sop_version_id));

alter table public.crew_journeys enable row level security; alter table public.crew_journey_modules enable row level security; alter table public.crew_lessons enable row level security; alter table public.crew_lesson_blocks enable row level security; alter table public.crew_journey_assignments enable row level security; alter table public.crew_lesson_progress enable row level security; alter table public.crew_sops enable row level security; alter table public.crew_sop_versions enable row level security; alter table public.crew_sop_sections enable row level security; alter table public.crew_sop_acknowledgements enable row level security;
create policy crew_learning_admin_journeys on public.crew_journeys for all to authenticated using (public.current_user_has_permission('crew_learning.manage')) with check (public.current_user_has_permission('crew_learning.manage'));
create policy crew_learning_admin_modules on public.crew_journey_modules for all to authenticated using (public.current_user_has_permission('crew_learning.manage')) with check (public.current_user_has_permission('crew_learning.manage'));
create policy crew_learning_admin_lessons on public.crew_lessons for all to authenticated using (public.current_user_has_permission('crew_learning.manage')) with check (public.current_user_has_permission('crew_learning.manage'));
create policy crew_learning_admin_blocks on public.crew_lesson_blocks for all to authenticated using (public.current_user_has_permission('crew_learning.manage')) with check (public.current_user_has_permission('crew_learning.manage'));
create policy crew_learning_admin_assignments on public.crew_journey_assignments for all to authenticated using (public.current_user_has_permission('crew_learning.manage')) with check (public.current_user_has_permission('crew_learning.manage'));
create policy crew_learning_admin_progress on public.crew_lesson_progress for select to authenticated using (public.current_user_has_permission('crew_learning.view'));
create policy crew_sop_admin on public.crew_sops for all to authenticated using (public.current_user_has_permission('crew_sop.manage')) with check (public.current_user_has_permission('crew_sop.manage'));
create policy crew_sop_versions_admin on public.crew_sop_versions for all to authenticated using (public.current_user_has_permission('crew_sop.manage')) with check (public.current_user_has_permission('crew_sop.manage'));
create policy crew_sop_sections_admin on public.crew_sop_sections for all to authenticated using (public.current_user_has_permission('crew_sop.manage')) with check (public.current_user_has_permission('crew_sop.manage'));
create policy crew_sop_ack_admin on public.crew_sop_acknowledgements for select to authenticated using (public.current_user_has_permission('crew_sop.view'));

create or replace function public.crew_learning_home(p_token text) returns jsonb language plpgsql security definer set search_path = public as $$
declare v_employee uuid; v_assignment public.crew_journey_assignments%rowtype; v_total integer; v_done integer;
begin
 v_employee := public.crew_session_employee(p_token);
 select * into v_assignment from public.crew_journey_assignments where employee_id=v_employee and status <> 'completed' order by assigned_at limit 1;
 if not found then return jsonb_build_object('assignment', null, 'required_sops', '[]'::jsonb); end if;
 select count(*) into v_total from public.crew_lessons l join public.crew_journey_modules m on m.id=l.module_id where m.journey_id=v_assignment.journey_id and l.required;
 select count(*) into v_done from public.crew_lesson_progress p where p.assignment_id=v_assignment.id and p.status='completed';
 return jsonb_build_object('assignment', jsonb_build_object('id',v_assignment.id,'journey_id',v_assignment.journey_id,'status',v_assignment.status,'journey_version_assigned',v_assignment.journey_version_assigned,'lessons_completed',v_done,'lessons_total',v_total), 'required_sops','[]'::jsonb);
end; $$;
revoke all on function public.crew_learning_home(text) from public, anon, authenticated; grant execute on function public.crew_learning_home(text) to anon, authenticated;
