-- Forward fix for 014's PL/pgSQL variable/column ambiguity.
create or replace function public.crew_submit_quiz(p_token text,p_assignment_id uuid,p_quiz_id uuid,p_answers jsonb) returns jsonb language plpgsql security definer set search_path=public as $$
declare e uuid; a public.crew_journey_assignments%rowtype; m jsonb; l jsonb; q jsonb; question jsonb; answer jsonb; selected text[]; correct text[]; expected int; seen int; n int:=0; v_score int; v_passed boolean; attempt_no int; attempt_id uuid;
begin
 if p_answers is null or jsonb_typeof(p_answers)<>'array' or jsonb_array_length(p_answers)=0 then raise exception using errcode='22023',message='Quiz answers must be a non-empty array.'; end if;
 e:=public.crew_session_employee(p_token); select * into a from public.crew_journey_assignments where id=p_assignment_id and employee_id=e for update; if not found then raise exception using errcode='42501',message='Learning assignment is unavailable.'; end if;
 select mm,ll into m,l from jsonb_array_elements(a.journey_snapshot->'modules') mm cross join lateral jsonb_array_elements(mm->'lessons') ll where (ll->'quiz'->>'id')::uuid=p_quiz_id limit 1; if l is null then raise exception using errcode='42501',message='Quiz is unavailable.'; end if; q:=l->'quiz'; expected:=jsonb_array_length(q->'questions'); if expected=0 then raise exception using errcode='22023',message='Quiz has no questions.'; end if;
 if exists(select 1 from jsonb_array_elements(p_answers) x where jsonb_typeof(x)<>'object' or not(x ? 'question_id') or not(x ? 'option_ids') or jsonb_typeof(x->'option_ids')<>'array' or x ? 'score' or x ? 'passed' or x ? 'is_correct' or x ? 'correct') then raise exception using errcode='22023',message='Quiz answer payload is invalid.'; end if;
 select count(*),count(distinct x->>'question_id') into seen,n from jsonb_array_elements(p_answers) x; if seen<>expected or n<>expected then raise exception using errcode='22023',message='Every quiz question must be answered exactly once.'; end if;
 if exists(select 1 from jsonb_array_elements(p_answers) x where not exists(select 1 from jsonb_array_elements(q->'questions') y where y->>'id'=x->>'question_id')) then raise exception using errcode='22023',message='Quiz answer contains an unexpected question.'; end if;
 select coalesce(max(attempt_number),0)+1 into attempt_no from public.crew_quiz_attempts where employee_id=e and quiz_id=p_quiz_id; insert into public.crew_quiz_attempts(employee_id,quiz_id,attempt_number,score,passed) values(e,p_quiz_id,attempt_no,0,false) returning id into attempt_id;
 n:=0; for question in select value from jsonb_array_elements(q->'questions') loop select value into answer from jsonb_array_elements(p_answers) where value->>'question_id'=question->>'id'; select array_agg(value order by value),count(*) into selected,seen from jsonb_array_elements_text(answer->'option_ids'); if seen<>cardinality(array(select distinct unnest(selected))) then raise exception using errcode='22023',message='Duplicate quiz option.'; end if; if (question->>'question_type')='single_choice' and seen<>1 then raise exception using errcode='22023',message='Single-choice question requires one option.'; end if; if exists(select 1 from unnest(selected) z where not exists(select 1 from jsonb_array_elements(question->'options') o where o->>'id'=z)) then raise exception using errcode='22023',message='Quiz option does not belong to its question.'; end if; select array_agg(o->>'id' order by o->>'id') into correct from jsonb_array_elements(question->'options') o where coalesce((o->>'is_correct')::boolean,false); if selected=correct then n:=n+1; end if; insert into public.crew_quiz_answers(attempt_id,question_id,selected_option_ids,correct) values(attempt_id,(question->>'id')::uuid,selected::uuid[],selected=correct); end loop;
 v_score:=round(n::numeric*100/expected); v_passed:=v_score>=(q->>'passing_score')::int; update public.crew_quiz_attempts set score=v_score,passed=v_passed,completed_at=now() where id=attempt_id; return jsonb_build_object('attempt_id',attempt_id,'attempt_number',attempt_no,'score',v_score,'passed',v_passed,'completed_at',now());
end; $$;
revoke all on function public.crew_submit_quiz(text,uuid,uuid,jsonb) from public,anon,authenticated; grant execute on function public.crew_submit_quiz(text,uuid,uuid,jsonb) to anon,authenticated;
