-- Keep the paged Task projection on the template composite while calculating
-- next_run. A CTE row is a generic record and cannot satisfy that function's
-- composite-type argument.
create or replace function public.crew_tasks_admin_page(p_outlet_id uuid,p_from date,p_to date,p_listing text default 'definitions',p_filters jsonb default '{}'::jsonb,p_page integer default 1,p_page_size integer default 20)
returns jsonb language plpgsql volatile security definer set search_path=public as $$
declare v_page integer:=greatest(coalesce(p_page,1),1); v_size integer:=case when p_page_size in(20,50,100) then p_page_size else 20 end; v_total integer; v_rows jsonb; v_sops jsonb; v_employees jsonb; v_summary jsonb;
begin
 if not public.current_user_has_permission('crew_operations.view') or not public.current_user_can_access_outlet(p_outlet_id) then raise exception using errcode='42501',message='Tasks are unavailable for this outlet.'; end if;
 if p_from is null or p_to is null or p_from>p_to or p_to-p_from>92 then raise exception using errcode='22023',message='Choose a valid Task period of 93 days or fewer.'; end if;
 if p_listing not in ('definitions','review_queue') then raise exception using errcode='22023',message='Unsupported Tasks listing.'; end if;
 perform public.crew_tasks_refresh_lifecycle(p_outlet_id); perform public.crew_operations_ensure_instances(p_outlet_id,d::date) from generate_series(p_from,p_to,interval '1 day') g(d);
 select coalesce(jsonb_agg(jsonb_build_object('sop_id',s.id,'title',s.title,'version_id',v.id,'version',v.version) order by s.title),'[]'::jsonb) into v_sops from public.crew_sops s join lateral(select * from public.crew_sop_versions v where v.sop_id=s.id and v.status='published' order by v.version desc limit 1)v on true where s.outlet_id is null or s.outlet_id=p_outlet_id;
 select coalesce(jsonb_agg(jsonb_build_object('id',e.id,'name',e.full_name,'position',e.position) order by e.full_name),'[]'::jsonb) into v_employees from public.employees e join public.crew_access ca on ca.employee_id=e.id and ca.primary_outlet_id=p_outlet_id and ca.access_state='active' where e.is_active and coalesce(e.employment_status,'active') not in ('resigned','terminated');
 if p_listing='review_queue' then
  select count(*) into v_total from public.crew_task_instance_assignees a join public.crew_operation_instances i on i.id=a.instance_id where i.outlet_id=p_outlet_id and i.business_date between p_from and p_to and a.status='review_required';
  select coalesce(jsonb_agg(to_jsonb(x) order by x.business_date,x.employee_name),'[]'::jsonb) into v_rows from (select i.id instance_id,e.id employee_id,i.name task_name,e.full_name employee_name,i.business_date,a.status from public.crew_task_instance_assignees a join public.crew_operation_instances i on i.id=a.instance_id join public.employees e on e.id=a.employee_id where i.outlet_id=p_outlet_id and i.business_date between p_from and p_to and a.status='review_required' order by i.business_date,e.full_name offset (v_page-1)*v_size limit v_size)x;
 else
  with series as (select t.series_id,max(t.updated_at) updated_at from public.crew_operation_templates t where t.outlet_id=p_outlet_id group by t.series_id), canonical as (select s.*,coalesce((select t.id from public.crew_operation_templates t where t.series_id=s.series_id and t.status<>'draft' order by case t.status when 'active' then 1 when 'paused' then 2 when 'ended' then 3 else 4 end,t.revision desc limit 1),(select t.id from public.crew_operation_templates t where t.series_id=s.series_id and t.status='draft' order by t.revision desc limit 1)) template_id from series s), filtered as (select t.* from canonical c join public.crew_operation_templates t on t.id=c.template_id where (coalesce(p_filters->>'status','all')='all' or t.status=p_filters->>'status') and (coalesce(p_filters->>'assignment','all')='all' or t.assignment_type=p_filters->>'assignment') and (coalesce(p_filters->>'query','')='' or concat_ws(' ',t.name,t.task_type,t.assignment_type) ilike '%'||p_filters->>'query'||'%')) select count(*) into v_total from filtered;
  with series as (select t.series_id,max(t.updated_at) updated_at from public.crew_operation_templates t where t.outlet_id=p_outlet_id group by t.series_id), canonical as (select s.*,coalesce((select t.id from public.crew_operation_templates t where t.series_id=s.series_id and t.status<>'draft' order by case t.status when 'active' then 1 when 'paused' then 2 when 'ended' then 3 else 4 end,t.revision desc limit 1),(select t.id from public.crew_operation_templates t where t.series_id=s.series_id and t.status='draft' order by t.revision desc limit 1)) template_id from series s), filtered as (select t.*,c.updated_at series_updated_at,public.crew_tasks_next_run(t) next_run from canonical c join public.crew_operation_templates t on t.id=c.template_id where (coalesce(p_filters->>'status','all')='all' or t.status=p_filters->>'status') and (coalesce(p_filters->>'assignment','all')='all' or t.assignment_type=p_filters->>'assignment') and (coalesce(p_filters->>'query','')='' or concat_ws(' ',t.name,t.task_type,t.assignment_type) ilike '%'||p_filters->>'query'||'%')) select coalesce(jsonb_agg((to_jsonb(x)-'created_by'-'next_run')||jsonb_build_object('definition_status',x.status,'next_run',x.next_run,'has_draft',exists(select 1 from public.crew_operation_templates d where d.series_id=x.series_id and d.status='draft'),'blocks',coalesce((select jsonb_agg((to_jsonb(i)-'sop_snapshot')||jsonb_build_object('sop_reference',i.sop_snapshot,'config',i.block_config) order by i.sort_order) from public.crew_operation_template_items i where i.template_id=x.id),'[]'::jsonb)) order by x.series_updated_at desc),'[]'::jsonb) into v_rows from (select * from filtered order by series_updated_at desc,id desc offset (v_page-1)*v_size limit v_size)x;
 end if;
 select jsonb_build_object('published_sops',v_sops,'employees',v_employees,'from',p_from,'to',p_to) into v_summary;
 return jsonb_build_object('rows',v_rows,'total_count',v_total,'page',v_page,'page_size',v_size,'summary',v_summary);
end; $$;
revoke all on function public.crew_tasks_admin_page(uuid,date,date,text,jsonb,integer,integer) from public,anon,authenticated;
grant execute on function public.crew_tasks_admin_page(uuid,date,date,text,jsonb,integer,integer) to authenticated;
