import { useEffect, useMemo, useRef, useState } from "react";
import FloatingLayer from "../../../components/ui/FloatingLayer.jsx";
import { inputClass } from "./FactoryBulkSelectionModal.jsx";
import { formatDateDisplay, isoDate, monthStart, todayInput } from "../utils/factoryDates.js";

export default function FeedXDatePicker({ value, onChange, placeholder = "Select date", error, buttonRef, required = false, disabled = false }) {
  const [open, setOpen] = useState(false);
  const [visibleMonth, setVisibleMonth] = useState(() => monthStart(value));
  const [pickerMode, setPickerMode] = useState("days");
  const [yearRangeStart, setYearRangeStart] = useState(() => { const startYear = value ? monthStart(value).getFullYear() : new Date().getFullYear(); return startYear - (startYear % 12); });
  const buttonNode = useRef(null);
  const anchorRef = buttonNode;
  const todayIso = todayInput();
  const selectedIso = value || "";
  const monthOptions = Array.from({ length: 12 }, (_, index) => ({ value: index, label: new Date(2026, index, 1).toLocaleDateString("en-MY", { month: "short" }) }));
  const yearOptions = Array.from({ length: 12 }, (_, index) => yearRangeStart + index);
  const days = useMemo(() => { const first = new Date(visibleMonth.getFullYear(), visibleMonth.getMonth(), 1); const start = new Date(first); start.setDate(first.getDate() - first.getDay()); return Array.from({ length: 42 }, (_, index) => { const date = new Date(start); date.setDate(start.getDate() + index); return date; }); }, [visibleMonth]);
  function selectDate(nextDate) { onChange(isoDate(nextDate)); setOpen(false); }
  function shiftMonth(delta) { setVisibleMonth((current) => new Date(current.getFullYear(), current.getMonth() + delta, 1)); }
  function setMonth(month) { setVisibleMonth((current) => new Date(current.getFullYear(), Number(month), 1)); setPickerMode("days"); }
  function setYear(year) { setVisibleMonth((current) => new Date(Number(year), current.getMonth(), 1)); setPickerMode("months"); }
  useEffect(() => { if (value) { const selectedDate = monthStart(value); setVisibleMonth(selectedDate); setYearRangeStart(selectedDate.getFullYear() - (selectedDate.getFullYear() % 12)); } }, [value]);
  useEffect(() => { if (open) setPickerMode("days"); }, [open]);
  return <div>
    <button ref={(node) => { buttonNode.current = node; if (buttonRef) buttonRef(node); }} className={`${inputClass(error)} flex items-center justify-between text-left disabled:cursor-not-allowed disabled:opacity-70 ${value ? "text-text-primary" : "text-text-muted"}`} type="button" disabled={disabled} onClick={() => setOpen((current) => !current)}><span>{formatDateDisplay(value, placeholder)}</span><span className="text-xs font-semibold text-text-muted">{required ? "Required" : "Optional"}</span></button>
    <FloatingLayer open={open} onOpenChange={setOpen} anchorRef={anchorRef} align="start" minWidth={300} estimatedHeight={360} maxHeight={420} layer="popover" className="p-3 shadow-2xl" contentClassName="">
      <div className="flex items-center gap-2"><button className="btn-secondary px-2 py-1 text-xs" type="button" onClick={() => shiftMonth(-1)}>Prev</button><button className={`min-w-0 flex-1 rounded-lg border px-2 py-1.5 text-sm font-bold outline-none transition ${pickerMode === "months" ? "border-primary bg-primary/10 text-primary" : "border-border bg-surface text-text-primary hover:border-primary/50"}`} type="button" onClick={() => setPickerMode((current) => current === "months" ? "days" : "months")}>{monthOptions[visibleMonth.getMonth()]?.label}</button><button className={`w-24 rounded-lg border px-2 py-1.5 text-sm font-bold outline-none transition ${pickerMode === "years" ? "border-primary bg-primary/10 text-primary" : "border-border bg-surface text-text-primary hover:border-primary/50"}`} type="button" onClick={() => { setYearRangeStart(visibleMonth.getFullYear() - (visibleMonth.getFullYear() % 12)); setPickerMode((current) => current === "years" ? "days" : "years"); }}>{visibleMonth.getFullYear()}</button><button className="btn-secondary px-2 py-1 text-xs" type="button" onClick={() => shiftMonth(1)}>Next</button></div>
      {pickerMode === "years" ? <div className="mt-3"><div className="mb-2 flex items-center justify-between text-xs font-semibold text-text-secondary"><button className="rounded-lg px-2 py-1 hover:bg-slate-100" type="button" onClick={() => setYearRangeStart((current) => current - 12)}>Prev 12</button><span>{yearRangeStart} - {yearRangeStart + 11}</span><button className="rounded-lg px-2 py-1 hover:bg-slate-100" type="button" onClick={() => setYearRangeStart((current) => current + 12)}>Next 12</button></div><div className="grid grid-cols-3 gap-2">{yearOptions.map((year) => <button key={year} className={`rounded-xl px-3 py-2 text-sm font-bold transition ${year === visibleMonth.getFullYear() ? "bg-primary text-white shadow-sm" : "bg-surface text-text-primary hover:bg-primary/10 hover:text-primary"}`} type="button" onClick={() => setYear(year)}>{year}</button>)}</div></div> : pickerMode === "months" ? <div className="mt-3 grid grid-cols-3 gap-2">{monthOptions.map((month) => <button key={month.value} className={`rounded-xl px-3 py-2 text-sm font-bold transition ${month.value === visibleMonth.getMonth() ? "bg-primary text-white shadow-sm" : "bg-surface text-text-primary hover:bg-primary/10 hover:text-primary"}`} type="button" onClick={() => setMonth(month.value)}>{month.label}</button>)}</div> : <><div className="mt-3 grid grid-cols-7 gap-1 text-center text-[11px] font-semibold text-text-muted">{["S", "M", "T", "W", "T", "F", "S"].map((day, index) => <div key={`${day}-${index}`}>{day}</div>)}</div><div className="mt-1 grid grid-cols-7 gap-1">{days.map((date) => { const currentIso = isoDate(date); const inMonth = date.getMonth() === visibleMonth.getMonth(); const selected = currentIso === selectedIso; const today = currentIso === todayIso; return <button key={currentIso} className={`h-9 rounded-lg text-sm font-semibold transition ${selected ? "bg-primary text-white shadow-sm" : today ? "bg-primary/10 text-primary" : inMonth ? "text-text-primary hover:bg-slate-100" : "text-text-muted/50 hover:bg-slate-50"}`} type="button" onClick={() => selectDate(date)}>{date.getDate()}</button>; })}</div></>}
      <div className="mt-3 flex items-center justify-between border-t border-border pt-3"><button className="btn-secondary px-3 py-1.5 text-xs" type="button" onClick={() => selectDate(new Date())}>Today</button><button className="btn-secondary px-3 py-1.5 text-xs" type="button" onClick={() => { onChange(""); setOpen(false); }}>Clear</button></div>
    </FloatingLayer>
  </div>;
}
