import en from "../en/crew.js";
const resources = { ...en,
  common: { ...en.common, back:"返回",close:"关闭",closeNamed:"关闭{{title}}",aboutNamed:"关于{{title}}",cancel:"取消",continue:"继续",confirm:"确认",save:"保存",saving:"保存中…",submit:"提交",retry:"重试",viewAll:"查看全部",loading:"加载中…",optional:"可选",required:"必需",today:"今天",now:"现在",outlet:"门店",role:"职位",other:"其他",noLimit:"不限",days:"天",shifts:"班次" },
  nav:{home:"首页",learn:"学习",reward:"奖励",growth:"成长",me:"我的",label:"员工导航"},
  auth:{...en.auth,welcomeTo:"欢迎使用",crew:"Crew",workday:"从这里开始今天的工作。",signInPrompt:"请使用已登记的手机号码登录。",mobile:"手机号码",countryCode:"国家代码",invalidMobile:"请输入有效的手机号码。",welcomeBack:"欢迎回来",enterPasscode:"请输入 4 位 Crew 密码",digitsEntered:"已输入 {{count}}/4 位",backspace:"退格",signingIn:"登录中…",secure:"您的密码会被安全保护。",unable:"无法登录。"},
  status:{completed:"已完成",completed_with_exceptions:"已完成 · 有异常",in_progress:"进行中",pending:"待处理",ready_for_review:"待审核",review_required:"需要审核",certified:"已认证",finalized:"已确认",paid:"已支付",qualified:"符合资格",approved:"已批准",rejected:"已拒绝",cancelled:"已取消",overdue:"已逾期",exception:"异常",active:"启用",paused:"已暂停",ended:"已结束",not_started:"未开始",on_shift:"工作中",good:"良好",needs_attention:"需要关注",not_checked:"未检查"},
  home:{...en.home,morning:"早上好",afternoon:"下午好",evening:"晚上好",crewMember:"员工",yourOutlet:"您的门店",ready:"准备就绪",onShift:"工作中",shiftCompleted:"班次已完成",readyClockIn:"可以打卡上班",clockedInAt:"{{time}} 已打卡",worked:"已工作 {{duration}}",dateOutlet:"{{date}} · {{outlet}}",withinArea:"位于范围内 · GPS 已验证",verifyAtClock:"打卡时验证位置",tapTo:"点击",tapToFinish:"点击结束",attendanceSecured:"考勤已记录",confirmed:"已确认",locating:"定位中…",clockIn:"打卡上班",clockOut:"打卡下班",todayShift:"今日班次",viewAttendance:"查看考勤",todaysTasks:"今日任务",allClear:"今天没有待办",noTasks:"今天没有分配任务。",showFewer:"收起任务",showRemaining:"显示其余 {{count}} 项任务",mySchedule:"我的排班",noPublishedShift:"今天没有已发布班次",scheduleWillAppear:"已发布的排班会显示在这里。",notPublished:"未发布",clockedInSuccess:"打卡上班成功",clockInTime:"打卡时间",goHome:"返回首页"},
  attendance:{...en.attendance,title:"考勤",readyShift:"准备开始班次",noShift:"没有已发布班次",todayShift:"今日班次",scheduleNotPublished:"排班未发布",started:"{{time}} 开始",checkingLocation:"正在检查位置…",locationVerification:"位置验证",locationNotConfigured:"尚未设置位置",withinMeters:"距离 {{outlet}} {{meters}} 米以内",noGeofence:"管理员尚未启用定位范围。",history:"考勤记录",locationVerified:"位置已验证",locationException:"位置异常",locationUnavailable:"无法取得位置",noShifts:"暂无班次",completedAppear:"完成的班次会显示在这里。",confirmClock:"确认打卡{{action}}",selectReason:"选择原因",reason:"原因",briefReason:"简要说明",unableUpdate:"无法更新考勤。"},
  schedule:{...en.schedule,title:"我的排班",upcoming:"接下来排班",nextDays:"未来 14 天",viewMonth:"查看整月",fullSchedule:"排班随时可查",tapShift:"点击班次查看详情。",off:"休息",annualLeave:"年假",medicalLeave:"病假",unpaidLeave:"无薪假",otherLeave:"其他假期",working:"上班",upcomingStatus:"即将开始",noSchedule:"暂无已发布排班",noScheduleBody:"已发布的排班会显示在这里。",hours:"{{count}} 小时"},
  learn:{...en.learn,title:"学习",loading:"正在加载学习内容…",unable:"无法加载学习内容。",tagline:"学习、实践、共同成长。",search:"搜索 SOP、主题或关键词",filters:"浏览 SOP 筛选",onboarding:"入职培训",onboardingComplete:"入职培训已完成！",onboardingPending:"入职培训尚未发布。",onboardingPendingBody:"门店经理正在准备入职培训。",mandatory:"必修入职培训",completedReview:"已完成 · 可随时复习",greatJob:"做得好！您已完成全部模块。",continueJourney:"继续完成必修学习。",modulesTitle:"模块",modules:"个模块",lessons:"节课程",lesson:"课程",moduleLesson:"模块课程",minutes:"{{count}} 分钟",ownPace:"按自己的节奏完成",reviewAnytime:"随时复习",percentComplete:"已完成 {{count}}%",completeEarlier:"请先完成前面的必修学习",lessonQuiz:"课程 + 知识测验",readyLearn:"可以开始学习",browseCategory:"按类别浏览",all:"全部",sops:"SOP",latest:"最新",titleSort:"标题",noSops:"没有符合条件的 SOP。",openSop:"打开 {{title}}",estimatedMinutes:"约 {{count}} 分钟",acknowledged:"已确认阅读",acknowledgementRequired:"需要确认阅读",noAcknowledgement:"无需确认阅读",acknowledgedTitle:"已确认 SOP",acknowledgedBody:"您已确认版本 {{version}}，可随时回来复习。",acknowledge:"我已阅读并确认此 SOP",readerFallback:"SOP",requiredSop:"必读 SOP",metadata:"SOP 信息",version:"版本 {{version}}",referencedTask:"此任务引用的 SOP",knowledgeCheck:"知识测验",passScore:"及格分数：{{score}}%",selectAll:"选择所有适用答案",selectOne:"选择一个答案",passed:"已通过",attempt:"第 {{number}} 次尝试",checking:"检查中…",submitQuiz:"提交测验",completeLesson:"完成课程",noContent:"暂无内容",noContentBody:"此版本尚未添加内容。"},
  tasks:{...en.tasks,title:"今日任务",task:"任务",outsideShift:"非工作时段仍可查看任务",noTasks:"今天没有适用任务。",preview:"预览",crewPreview:"员工任务预览",untitled:"未命名任务",previewOnly:"仅预览 · 不会保存执行记录或证据。",completed:"任务已完成",submittedReview:"任务已提交审核",completedCount:"已完成 {{completed}}/{{total}}",completedAt:"完成于 {{time}}",pending:"待处理",hide:"收起",view:"查看",issueReported:"已报告问题",done:"已完成",confirmed:"已确认",reportIssue:"报告问题",recordException:"记录异常",chooseReason:"选择原因",note:"备注",explainIssue:"说明无法完成的原因",submitException:"提交异常",evidenceUnavailable:"仅在安全任务媒体可用时显示证据上传。",evidence:"证据：{{type}}",markDone:"标记完成",confirmAction:"确认",saveAnswer:"保存答案",saveChoice:"保存选项",saveValue:"保存数值",saveResponse:"保存回复",saveRating:"保存评级",yes:"是",no:"否",good:"良好",needsAttention:"需要关注",notChecked:"未检查",addTitle:"添加标题后即可预览。",addInstruction:"添加说明内容后即可预览。",addKeyPoint:"添加重点内容后即可预览。",imageUnavailable:"安全任务图片预览暂不可用。",choosePublishedSop:"请选择已发布的 SOP 进行预览。",addOption:"至少添加一个选项后即可预览。",expectedRange:"预期 {{min}}–{{max}}{{unit}}",any:"不限",publishedSop:"已发布 SOP",sopReadOnly:"{{title}} 将以员工只读方式打开。",legacyInstruction:"完成此任务，或在允许时记录异常。",openSop:"打开 SOP",openPreview:"打开预览",reasons:{equipment_issue:"设备问题",stock_unavailable:"库存不足",area_unavailable:"区域不可用",manager_instruction:"经理指示",other:"其他"},types:{text:"说明",checklist_item:"检查项",key_point:"重点",image:"图片",sop_reference:"SOP 引用",yes_no:"是 / 否",single_choice:"单选",number:"数值输入",temperature:"温度",short_text:"简短回复",health_rating:"健康评级",confirmation:"确认"}},
  leave:{...en.leave,title:"我的假期",apply:"申请假期",step:"第 {{step}} 步，共 4 步",progress:"申请进度",leaveType:"假期类型",annual:"年假",medical:"病假 / MC",unpaid:"无薪假",other:"其他假期",dates:"日期",startDate:"开始日期",endDate:"结束日期",fullDay:"全天",halfDay:"半天",reason:"原因",reasonNote:"原因 / 备注",reasonPlaceholder:"简要说明请假原因",review:"确认申请",duration:"时长",availableBefore:"申请前可用",afterRequest:"申请后剩余",submitRequest:"提交申请",submitting:"提交中…",balances:"假期余额",pendingUsed:"{{pending}} 待审批 · {{used}} 已使用",noBalanceLimit:"无余额限制",upcoming:"即将开始",history:"历史",loading:"正在加载假期…",submitted:"提交于 {{date}}",cancelRequest:"取消申请",noLeave:"没有{{tab}}假期",noUpcoming:"已批准的未来假期会显示在这里。",noPending:"等待审核的申请会显示在这里。",noHistory:"已拒绝或取消的申请会显示在这里。",available:"可用",requested:"申请",after:"剩余",medicalDocumentFuture:"后续版本将支持添加证明文件。",documentNotUploaded:"尚未上传证明文件",documentOptionalV1:"当前版本允许不附文件提交病假申请。",approvedChangeHelp:"如需更改已批准的假期，请联系经理。",insufficient:"假期余额不足，请减少天数或联系经理。"},
  reward:{...en.reward,title:"奖励",help:"奖励说明",estimatedReward:"预计奖励",finalReward:"最终奖励",paidReward:"已支付奖励",qualified:"符合资格",thisMonth:"本月",contribution:"您的贡献",eligibleHours:"{{eligible}} 小时 / {{total}} 小时合资格工时",rewardPool:"奖励池",sharedPool:"由符合资格的员工共享",maximum:"最高可获得",maximumCaption:"最高份额的 100%",scoreBasis:"根据当前绩效分数 {{score}} 计算。",performanceOverview:"绩效概览",performanceCaption:"绩效决定您可获得最高份额的比例。",viewPerformance:"查看我的绩效",currentRate:"当前奖励比例",onTrack:"进度正常",projection:"预计奖励变化",projectionCaption:"查看绩效提高后奖励可能如何增长。",howWorks:"运作方式",calculated:"如何计算？",history:"奖励记录",historyCaption:"查看过往奖励发放。",noHistory:"已确认的奖励记录会显示在这里。",loading:"正在加载奖励…",unavailable:"暂时无法查看奖励",unavailableBody:"无法加载本月奖励资料。",notAvailable:"暂无奖励",notAvailableYet:"本月奖励尚未开放。",retry:"重试",finalized:"奖励已确认",finalizedCaption:"本月金额已确定，不再显示预测。",performanceScore:"绩效分数 {{score}}",earnRateWorks:"了解奖励比例",viewAll:"查看全部",score:"分数 {{score}}",rateEarned:"获得 {{rate}}",projectionAssumption:"预测假设当前贡献比例（{{contribution}}）和奖励池保持相近。",motivation:"增加合资格工时并提升绩效，可更接近您的最高奖励份额！",about:"关于您的奖励",maximumShare:"最高份额",maximumShareHelp:"您在奖励池中的份额取决于合资格工时贡献。",performanceEarnRate:"绩效奖励比例",performanceEarnRateHelp:"最终绩效分数决定您可获得最高份额的百分比。",helpCallout:"更多合资格工时可能提高贡献比例；更好的绩效可解锁更高奖励比例。",yourMaximumShare:"您的最高份额",maximumDetail:"您的最高份额是 {{amount}}，按合资格工时计算自门店奖励池。",contributionDetail:"您贡献了 {{eligible}} / {{total}} 小时，占 {{rate}}。",poolDetail:"本月 {{amount}} 奖励池由符合资格的员工共享。",performanceRates:"绩效奖励比例",performanceRatesHelp:"最终月度绩效分数会对应一个透明的奖励比例。",aboutProjections:"关于预测",projectionDetail:"预测固定当前奖励池与工时贡献，只改变绩效等级；金额仅供参考。",formulaTitle:"奖励计算方式",contributionShare:"贡献比例",rateTable:"绩效奖励比例表",scoreRange:"分数范围",level:"等级",earnRate:"奖励比例",levels:{outstanding:"卓越",excellent:"优秀",strong:"强劲",meetsStandard:"达到标准",developing:"发展中",belowStandard:"低于标准"}},
  growth:{...en.growth,title:"成长",help:"成长说明",about:"关于成长",helpSkills:"查看正在发展的营运技能。",helpReview:"您已完成所需证据，正在等待经理审核。",helpPerformance:"月度绩效分数反映已验证的工作证据。",nextMilestone:"下一个里程碑",allCaughtUp:"全部完成",skillsCurrent:"当前技能已是最新状态。",viewSkill:"查看技能",yourSkills:"您的技能",skillsCaption:"查看技能与认证进度。",viewAllSkills:"查看全部技能",readyForReview:"待审核",skillCount:"{{count}} 项技能",myProgress:"我的进度",skills:"技能",skillDetail:"技能详情",skillCategories:"技能类别",requirementsComplete:"学习要求已完成",managerReview:"经理审核",nextAction:"下一步",waitingReview:"等待经理审核",certifiedOn:"认证于 {{date}}",validUntil:"有效至 {{date}}",noExpiry:"无到期日",myPath:"我的路径",requirementCount:"已完成 {{completed}}/{{total}} 项要求",allMilestones:"当前里程碑已全部完成",certifications:"我的认证",noStageSkills:"此阶段暂无技能。",performance:"绩效",performanceCaption:"本月绩效表现。",viewPerformance:"查看我的绩效",thisMonth:"本月",noTrend:"暂无趋势",recentTrend:"近期绩效趋势",loading:"正在加载成长资料…",unavailable:"暂时无法查看成长资料",searchSkills:"搜索技能",skillCategories:"技能类别",all:"全部",noMatch:"没有符合条件的技能。",keepGoing:"继续加油！",timeline:"成长记录",updates:"{{count}} 条更新",noTimeline:"完成的学习与认证会显示在这里。"},
  performance:{...en.performance,title:"我的绩效",help:"绩效说明",scoreBreakdown:"分数明细",strengthsTitle:"我的优势",trend:"绩效趋势",lastMonths:"最近 4 个月",finalizedTrend:"已确认的月度绩效趋势",trendMore:"更多月度结果确认后会显示趋势。",rewardImpact:"奖励影响",earnRate:"奖励比例",viewReward:"查看奖励",unavailable:"暂时没有绩效结果",unavailableBody:"门店具备足够的已验证资料后会显示月度分数。",verifiedEvidence:"分数来自 FeedX 已验证资料。",learnCalculation:"了解绩效计算方式",awaitingData:"等待资料",awaitingEvidence:"等待证据",draft:"草稿",inReview:"审核中",reviewProgress:"审核进行中",evidenceReview:"已验证证据仍在审核中。",vsPeriod:"{{delta}}，对比 {{period}}",current:"当前绩效",whyScore:"分数原因",keepItUp:"继续保持",howImprove:"如何改善",whatCounts:"计分依据",viewEvidence:"查看{{label}}证据",weight:"权重 {{weight}}%",finalizedPerformance:"已确认绩效",estimatedPerformance:"预计 · 尚未确认",calculationTitle:"绩效计算方式",componentCalculation:"根据此项目的 FeedX 已验证证据计算。",about:"关于我的绩效",monthlyScore:"月度分数",monthlyScoreHelp:"最终月度分数根据 FeedX 已验证证据计算。",breakdownHelp:"每个项目按固定权重计入总分 100 分。",rewardHelp:"最终绩效分数决定您可获得最高奖励份额的百分比。",messages:{excellent:"本月表现卓越！",strong:"本月表现强劲。",meets:"您已达到标准。",progress:"继续保持进步。",improve:"专注下一个改善步骤。"},components:{attendance:"考勤",service:"服务标准",customer:"顾客体验",knowledge:"知识与 SOP",conduct:"行为规范"},strengths:{attendance:"本月考勤证据满分。",service:"服务标准审核满分。",customer:"顾客体验证据满分。",knowledge:"学习证据满分。",conduct:"行为规范证据满分。"}},
  me:{...en.me,title:"我的",settings:"设置",notifications:"通知",language:"语言",passcode:"密码",privacy:"隐私",terms:"条款",about:"关于 FeedX",profile:"个人资料",employmentStatus:"雇佣状态",notAssigned:"未分配",viewProfile:"查看资料",workSummary:"工作状态概览",attendance:"考勤",leaveBalance:"假期余额",noBalance:"暂无余额",daysAvailable:"天可用 · 年假",noHistory:"暂无考勤记录",noActivity:"暂无记录",work:"工作",leave:"假期",employmentDocuments:"雇佣文件",account:"账户",changePasscode:"更改密码",support:"支持",help:"帮助与支持",logout:"退出登录",currentPasscode:"当前密码",newPasscode:"新密码",savePasscode:"保存密码",logoutTitle:"退出 FeedX？",logoutBody:"再次登录时需要手机号码和密码。",languageTitle:"选择语言",languageHint:"系统界面会立即更新；SOP 和任务内容仍使用发布时的语言。"},
  locationEvidence:{attendanceStatus:"考勤状态",verified:"范围内 · GPS 已验证",verifiedHelp:"您打卡时已由考勤服务器验证位置。",exception:"已记录位置例外",exceptionHelp:"您打卡时已记录位置例外。",unavailable:"打卡时无法取得位置",unavailableHelp:"此次打卡没有已验证的 GPS 证据。",checkAtClockIn:"打卡时检查 GPS",checkAtClockInHelp:"点击上班打卡时系统会检查您的位置。",notConfigured:"未配置位置检查",notConfiguredHelp:"此门店目前不要求地理围栏验证。"},
  performanceGuidance:{...en.performanceGuidance,evidenceUnavailable:"暂无证据",verifiedEvidencePeriod:"使用本评分周期内经验证的 FeedX 证据。",reviewStatus:"审核状态",reviewRecorded:"已记录并验证审核",viewSkills:"查看相关技能",viewGrowth:"查看成长",upToDate:"已是最新",goLearn:"前往学习",verifiedEvidence:"已验证证据",calculating:"证据计算中",criteria:{welcome_greeting:"欢迎 / 问候",thank_you_goodbye:"感谢 / 道别",grooming:"仪容",work_area_cleanliness:"工作区域清洁",initiative:"主动性",guest_interaction:"顾客互动",professional_conduct:"职业操守",teamwork:"团队合作",responsibility:"责任感",communication:"沟通",policy_compliance:"遵守政策"},ratings:{meets_standard:"达到标准",needs_improvement:"需要改进",not_observed:"未观察"},attendance:{records:"考勤记录",completed:"已完成 {{completed}} / {{records}}",incomplete:"不完整记录",approvedLeave:"已批准假期",daysExcluded:"已排除 {{count}} 天",locationExceptions:"位置例外",evidenceFlags:"{{count}} · 仅作证据标记",maintainComplete:"每个已排班班次都保持完整的上下班打卡记录。",completeClock:"每个已排班班次都完成上下班打卡。",keepComplete:"保持每条已排班考勤记录完整。",completePeriod:"完成已排定的工作时段。",resolveExceptions:"经理要求补充资料时及时处理考勤例外。",whatCounts:"仅计入本评分周期中与工作记录关联的已验证考勤。位置例外不会自动扣分。"},service:{keep:"每个班次都持续保持这些服务标准。",welcome_greeting:"及时欢迎并问候顾客。",thank_you_goodbye:"感谢顾客并温暖地结束每次互动。",grooming:"每班前遵循最新仪容 SOP。",work_area_cleanliness:"整个班次保持所负责区域清洁。",initiative:"主动寻找下一项可协助的工作。",guest_interaction:"保持专注并与顾客清楚沟通。",nextReview:"完成下一次服务观察审核，并保持必需实务技能有效。",whatCounts:"分数依据本周期经验证、按标准评估的服务审核。"},conduct:{keep:"持续保持这些工作场所标准。",professional_conduct:"始终遵守工作流程。",teamwork:"繁忙时支持同事。",responsibility:"对分配的任务负责。",communication:"清楚且尊重地沟通。",policy_compliance:"每个班次都遵守当前工作政策。",nextReview:"在下一次工作审核中持续展现这些标准。",whatCounts:"分数依据本周期经验证、按标准评估的工作场所审核。"},customer:{feedback:"已验证反馈",responses:"{{count}} 条反馈",positive:"正面体验",improvement:"改善信号",confidence:"可信度",insufficient:"数据不足",lowSample:"样本量较少",positiveSignals:"正面信号",needsAttention:"需要关注",needMore:"需要更多经验证的顾客反馈才能计算可靠分数。",keep:"持续提供友善、细心的服务。",improve:"保持友善、细心的服务，并及时回应顾客需要。",whatCounts:"仅计入本周期内有效且经审核的顾客反馈。样本较少会被视为低可信度，而不是表现差。",tags:{greeting:"及时问候顾客。",response_time:"迅速回应顾客请求。",accuracy:"完成前确认订单和请求。",cleanliness:"保持顾客区域清洁并随时可用。",product_knowledge:"复习当前产品与 SOP 知识。"}},knowledge:{requiredSop:"必需 SOP",acknowledged:"已确认 {{percent}}",checks:"知识测验",allPassed:"所有必需测验已通过",passed:"已通过 {{percent}}",requiredLearning:"必需学习",complete:"已完成 {{percent}}",keep:"您已是最新状态，请继续复习 SOP 更新和必需学习。",lessons:"完成尚未完成的必修课程。",sops:"完成尚未确认的 SOP。",retry:"重试符合条件的知识测验。",learning:"保持必需学习与技能为最新状态。",whatCounts:"持续有效的 Onboarding 完成记录、精确 SOP 确认、已通过知识测验和适用成长学习会作为已验证证据复用。"}},
  attendanceReasons:{outlet_gps:"门店 GPS 位置似乎不准确",off_site:"在外工作",another_location:"被安排到其他地点",accuracy:"定位精度问题",permission:"未授予定位权限",unavailable:"设备位置不可用",forgot_clock_out:"离开前忘记打卡下班",other:"其他"},
  errors:{...en.errors,acknowledgeSop:"无法确认此 SOP。",chooseExceptionReason:"请选择例外原因后再{{action}}。"},
  languages:en.languages
};
Object.assign(resources.home, { workedDuration:"工作时长", clockInAt:"上班打卡", clockOutAt:"下班打卡" });
Object.assign(resources.attendance, { outsideRange:"您距离门店 {{distance}} 米（允许范围 {{meters}} 米）。" });
Object.assign(resources.schedule, { jumpToday:"跳到今天" });
Object.assign(resources.tasks, { reportIssueFor:"报告 {{title}} 的问题", completeBlock:"完成 {{title}}" });
Object.assign(resources.growth, { skillCount_one:"{{count}} 项技能", skillCount_other:"{{count}} 项技能" });
Object.assign(resources.me, { shiftsThisMonth_one:"本月 {{count}} 个班次", shiftsThisMonth_other:"本月 {{count}} 个班次", pendingCount:"{{count}} 项待处理", enterPasscodes:"请输入当前和新的四位数密码。", unablePasscode:"无法更改密码。" });
Object.assign(resources.reward, { currentProjection:"当前", greatProjection:"表现优秀", maxPotential:"最高潜力" });
export default resources;
